var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u2800", "n" : "BRAILLE PATTERN BLANK", "h" : "2800" },
{"g" : "\u2801", "n" : "BRAILLE PATTERN DOTS-1", "h" : "2801" },
{"g" : "\u2802", "n" : "BRAILLE PATTERN DOTS-2", "h" : "2802" },
{"g" : "\u2803", "n" : "BRAILLE PATTERN DOTS-12", "h" : "2803" },
{"g" : "\u2804", "n" : "BRAILLE PATTERN DOTS-3", "h" : "2804" },
{"g" : "\u2805", "n" : "BRAILLE PATTERN DOTS-13", "h" : "2805" },
{"g" : "\u2806", "n" : "BRAILLE PATTERN DOTS-23", "h" : "2806" },
{"g" : "\u2807", "n" : "BRAILLE PATTERN DOTS-123", "h" : "2807" },
{"g" : "\u2808", "n" : "BRAILLE PATTERN DOTS-4", "h" : "2808" },
{"g" : "\u2809", "n" : "BRAILLE PATTERN DOTS-14", "h" : "2809" },
{"g" : "\u280A", "n" : "BRAILLE PATTERN DOTS-24", "h" : "280A" },
{"g" : "\u280B", "n" : "BRAILLE PATTERN DOTS-124", "h" : "280B" },
{"g" : "\u280C", "n" : "BRAILLE PATTERN DOTS-34", "h" : "280C" },
{"g" : "\u280D", "n" : "BRAILLE PATTERN DOTS-134", "h" : "280D" },
{"g" : "\u280E", "n" : "BRAILLE PATTERN DOTS-234", "h" : "280E" },
{"g" : "\u280F", "n" : "BRAILLE PATTERN DOTS-1234", "h" : "280F" },
{"g" : "\u2810", "n" : "BRAILLE PATTERN DOTS-5", "h" : "2810" },
{"g" : "\u2811", "n" : "BRAILLE PATTERN DOTS-15", "h" : "2811" },
{"g" : "\u2812", "n" : "BRAILLE PATTERN DOTS-25", "h" : "2812" },
{"g" : "\u2813", "n" : "BRAILLE PATTERN DOTS-125", "h" : "2813" },
{"g" : "\u2814", "n" : "BRAILLE PATTERN DOTS-35", "h" : "2814" },
{"g" : "\u2815", "n" : "BRAILLE PATTERN DOTS-135", "h" : "2815" },
{"g" : "\u2816", "n" : "BRAILLE PATTERN DOTS-235", "h" : "2816" },
{"g" : "\u2817", "n" : "BRAILLE PATTERN DOTS-1235", "h" : "2817" },
{"g" : "\u2818", "n" : "BRAILLE PATTERN DOTS-45", "h" : "2818" },
{"g" : "\u2819", "n" : "BRAILLE PATTERN DOTS-145", "h" : "2819" },
{"g" : "\u281A", "n" : "BRAILLE PATTERN DOTS-245", "h" : "281A" },
{"g" : "\u281B", "n" : "BRAILLE PATTERN DOTS-1245", "h" : "281B" },
{"g" : "\u281C", "n" : "BRAILLE PATTERN DOTS-345", "h" : "281C" },
{"g" : "\u281D", "n" : "BRAILLE PATTERN DOTS-1345", "h" : "281D" },
{"g" : "\u281E", "n" : "BRAILLE PATTERN DOTS-2345", "h" : "281E" },
{"g" : "\u281F", "n" : "BRAILLE PATTERN DOTS-12345", "h" : "281F" },
{"g" : "\u2820", "n" : "BRAILLE PATTERN DOTS-6", "h" : "2820" },
{"g" : "\u2821", "n" : "BRAILLE PATTERN DOTS-16", "h" : "2821" },
{"g" : "\u2822", "n" : "BRAILLE PATTERN DOTS-26", "h" : "2822" },
{"g" : "\u2823", "n" : "BRAILLE PATTERN DOTS-126", "h" : "2823" },
{"g" : "\u2824", "n" : "BRAILLE PATTERN DOTS-36", "h" : "2824" },
{"g" : "\u2825", "n" : "BRAILLE PATTERN DOTS-136", "h" : "2825" },
{"g" : "\u2826", "n" : "BRAILLE PATTERN DOTS-236", "h" : "2826" },
{"g" : "\u2827", "n" : "BRAILLE PATTERN DOTS-1236", "h" : "2827" },
{"g" : "\u2828", "n" : "BRAILLE PATTERN DOTS-46", "h" : "2828" },
{"g" : "\u2829", "n" : "BRAILLE PATTERN DOTS-146", "h" : "2829" },
{"g" : "\u282A", "n" : "BRAILLE PATTERN DOTS-246", "h" : "282A" },
{"g" : "\u282B", "n" : "BRAILLE PATTERN DOTS-1246", "h" : "282B" },
{"g" : "\u282C", "n" : "BRAILLE PATTERN DOTS-346", "h" : "282C" },
{"g" : "\u282D", "n" : "BRAILLE PATTERN DOTS-1346", "h" : "282D" },
{"g" : "\u282E", "n" : "BRAILLE PATTERN DOTS-2346", "h" : "282E" },
{"g" : "\u282F", "n" : "BRAILLE PATTERN DOTS-12346", "h" : "282F" },
{"g" : "\u2830", "n" : "BRAILLE PATTERN DOTS-56", "h" : "2830" },
{"g" : "\u2831", "n" : "BRAILLE PATTERN DOTS-156", "h" : "2831" },
{"g" : "\u2832", "n" : "BRAILLE PATTERN DOTS-256", "h" : "2832" },
{"g" : "\u2833", "n" : "BRAILLE PATTERN DOTS-1256", "h" : "2833" },
{"g" : "\u2834", "n" : "BRAILLE PATTERN DOTS-356", "h" : "2834" },
{"g" : "\u2835", "n" : "BRAILLE PATTERN DOTS-1356", "h" : "2835" },
{"g" : "\u2836", "n" : "BRAILLE PATTERN DOTS-2356", "h" : "2836" },
{"g" : "\u2837", "n" : "BRAILLE PATTERN DOTS-12356", "h" : "2837" },
{"g" : "\u2838", "n" : "BRAILLE PATTERN DOTS-456", "h" : "2838" },
{"g" : "\u2839", "n" : "BRAILLE PATTERN DOTS-1456", "h" : "2839" },
{"g" : "\u283A", "n" : "BRAILLE PATTERN DOTS-2456", "h" : "283A" },
{"g" : "\u283B", "n" : "BRAILLE PATTERN DOTS-12456", "h" : "283B" },
{"g" : "\u283C", "n" : "BRAILLE PATTERN DOTS-3456", "h" : "283C" },
{"g" : "\u283D", "n" : "BRAILLE PATTERN DOTS-13456", "h" : "283D" },
{"g" : "\u283E", "n" : "BRAILLE PATTERN DOTS-23456", "h" : "283E" },
{"g" : "\u283F", "n" : "BRAILLE PATTERN DOTS-123456", "h" : "283F" },
{"g" : "\u2840", "n" : "BRAILLE PATTERN DOTS-7", "h" : "2840" },
{"g" : "\u2841", "n" : "BRAILLE PATTERN DOTS-17", "h" : "2841" },
{"g" : "\u2842", "n" : "BRAILLE PATTERN DOTS-27", "h" : "2842" },
{"g" : "\u2843", "n" : "BRAILLE PATTERN DOTS-127", "h" : "2843" },
{"g" : "\u2844", "n" : "BRAILLE PATTERN DOTS-37", "h" : "2844" },
{"g" : "\u2845", "n" : "BRAILLE PATTERN DOTS-137", "h" : "2845" },
{"g" : "\u2846", "n" : "BRAILLE PATTERN DOTS-237", "h" : "2846" },
{"g" : "\u2847", "n" : "BRAILLE PATTERN DOTS-1237", "h" : "2847" },
{"g" : "\u2848", "n" : "BRAILLE PATTERN DOTS-47", "h" : "2848" },
{"g" : "\u2849", "n" : "BRAILLE PATTERN DOTS-147", "h" : "2849" },
{"g" : "\u284A", "n" : "BRAILLE PATTERN DOTS-247", "h" : "284A" },
{"g" : "\u284B", "n" : "BRAILLE PATTERN DOTS-1247", "h" : "284B" },
{"g" : "\u284C", "n" : "BRAILLE PATTERN DOTS-347", "h" : "284C" },
{"g" : "\u284D", "n" : "BRAILLE PATTERN DOTS-1347", "h" : "284D" },
{"g" : "\u284E", "n" : "BRAILLE PATTERN DOTS-2347", "h" : "284E" },
{"g" : "\u284F", "n" : "BRAILLE PATTERN DOTS-12347", "h" : "284F" },
{"g" : "\u2850", "n" : "BRAILLE PATTERN DOTS-57", "h" : "2850" },
{"g" : "\u2851", "n" : "BRAILLE PATTERN DOTS-157", "h" : "2851" },
{"g" : "\u2852", "n" : "BRAILLE PATTERN DOTS-257", "h" : "2852" },
{"g" : "\u2853", "n" : "BRAILLE PATTERN DOTS-1257", "h" : "2853" },
{"g" : "\u2854", "n" : "BRAILLE PATTERN DOTS-357", "h" : "2854" },
{"g" : "\u2855", "n" : "BRAILLE PATTERN DOTS-1357", "h" : "2855" },
{"g" : "\u2856", "n" : "BRAILLE PATTERN DOTS-2357", "h" : "2856" },
{"g" : "\u2857", "n" : "BRAILLE PATTERN DOTS-12357", "h" : "2857" },
{"g" : "\u2858", "n" : "BRAILLE PATTERN DOTS-457", "h" : "2858" },
{"g" : "\u2859", "n" : "BRAILLE PATTERN DOTS-1457", "h" : "2859" },
{"g" : "\u285A", "n" : "BRAILLE PATTERN DOTS-2457", "h" : "285A" },
{"g" : "\u285B", "n" : "BRAILLE PATTERN DOTS-12457", "h" : "285B" },
{"g" : "\u285C", "n" : "BRAILLE PATTERN DOTS-3457", "h" : "285C" },
{"g" : "\u285D", "n" : "BRAILLE PATTERN DOTS-13457", "h" : "285D" },
{"g" : "\u285E", "n" : "BRAILLE PATTERN DOTS-23457", "h" : "285E" },
{"g" : "\u285F", "n" : "BRAILLE PATTERN DOTS-123457", "h" : "285F" },
{"g" : "\u2860", "n" : "BRAILLE PATTERN DOTS-67", "h" : "2860" },
{"g" : "\u2861", "n" : "BRAILLE PATTERN DOTS-167", "h" : "2861" },
{"g" : "\u2862", "n" : "BRAILLE PATTERN DOTS-267", "h" : "2862" },
{"g" : "\u2863", "n" : "BRAILLE PATTERN DOTS-1267", "h" : "2863" },
{"g" : "\u2864", "n" : "BRAILLE PATTERN DOTS-367", "h" : "2864" },
{"g" : "\u2865", "n" : "BRAILLE PATTERN DOTS-1367", "h" : "2865" },
{"g" : "\u2866", "n" : "BRAILLE PATTERN DOTS-2367", "h" : "2866" },
{"g" : "\u2867", "n" : "BRAILLE PATTERN DOTS-12367", "h" : "2867" },
{"g" : "\u2868", "n" : "BRAILLE PATTERN DOTS-467", "h" : "2868" },
{"g" : "\u2869", "n" : "BRAILLE PATTERN DOTS-1467", "h" : "2869" },
{"g" : "\u286A", "n" : "BRAILLE PATTERN DOTS-2467", "h" : "286A" },
{"g" : "\u286B", "n" : "BRAILLE PATTERN DOTS-12467", "h" : "286B" },
{"g" : "\u286C", "n" : "BRAILLE PATTERN DOTS-3467", "h" : "286C" },
{"g" : "\u286D", "n" : "BRAILLE PATTERN DOTS-13467", "h" : "286D" },
{"g" : "\u286E", "n" : "BRAILLE PATTERN DOTS-23467", "h" : "286E" },
{"g" : "\u286F", "n" : "BRAILLE PATTERN DOTS-123467", "h" : "286F" },
{"g" : "\u2870", "n" : "BRAILLE PATTERN DOTS-567", "h" : "2870" },
{"g" : "\u2871", "n" : "BRAILLE PATTERN DOTS-1567", "h" : "2871" },
{"g" : "\u2872", "n" : "BRAILLE PATTERN DOTS-2567", "h" : "2872" },
{"g" : "\u2873", "n" : "BRAILLE PATTERN DOTS-12567", "h" : "2873" },
{"g" : "\u2874", "n" : "BRAILLE PATTERN DOTS-3567", "h" : "2874" },
{"g" : "\u2875", "n" : "BRAILLE PATTERN DOTS-13567", "h" : "2875" },
{"g" : "\u2876", "n" : "BRAILLE PATTERN DOTS-23567", "h" : "2876" },
{"g" : "\u2877", "n" : "BRAILLE PATTERN DOTS-123567", "h" : "2877" },
{"g" : "\u2878", "n" : "BRAILLE PATTERN DOTS-4567", "h" : "2878" },
{"g" : "\u2879", "n" : "BRAILLE PATTERN DOTS-14567", "h" : "2879" },
{"g" : "\u287A", "n" : "BRAILLE PATTERN DOTS-24567", "h" : "287A" },
{"g" : "\u287B", "n" : "BRAILLE PATTERN DOTS-124567", "h" : "287B" },
{"g" : "\u287C", "n" : "BRAILLE PATTERN DOTS-34567", "h" : "287C" },
{"g" : "\u287D", "n" : "BRAILLE PATTERN DOTS-134567", "h" : "287D" },
{"g" : "\u287E", "n" : "BRAILLE PATTERN DOTS-234567", "h" : "287E" },
{"g" : "\u287F", "n" : "BRAILLE PATTERN DOTS-1234567", "h" : "287F" },
{"g" : "\u2880", "n" : "BRAILLE PATTERN DOTS-8", "h" : "2880" },
{"g" : "\u2881", "n" : "BRAILLE PATTERN DOTS-18", "h" : "2881" },
{"g" : "\u2882", "n" : "BRAILLE PATTERN DOTS-28", "h" : "2882" },
{"g" : "\u2883", "n" : "BRAILLE PATTERN DOTS-128", "h" : "2883" },
{"g" : "\u2884", "n" : "BRAILLE PATTERN DOTS-38", "h" : "2884" },
{"g" : "\u2885", "n" : "BRAILLE PATTERN DOTS-138", "h" : "2885" },
{"g" : "\u2886", "n" : "BRAILLE PATTERN DOTS-238", "h" : "2886" },
{"g" : "\u2887", "n" : "BRAILLE PATTERN DOTS-1238", "h" : "2887" },
{"g" : "\u2888", "n" : "BRAILLE PATTERN DOTS-48", "h" : "2888" },
{"g" : "\u2889", "n" : "BRAILLE PATTERN DOTS-148", "h" : "2889" },
{"g" : "\u288A", "n" : "BRAILLE PATTERN DOTS-248", "h" : "288A" },
{"g" : "\u288B", "n" : "BRAILLE PATTERN DOTS-1248", "h" : "288B" },
{"g" : "\u288C", "n" : "BRAILLE PATTERN DOTS-348", "h" : "288C" },
{"g" : "\u288D", "n" : "BRAILLE PATTERN DOTS-1348", "h" : "288D" },
{"g" : "\u288E", "n" : "BRAILLE PATTERN DOTS-2348", "h" : "288E" },
{"g" : "\u288F", "n" : "BRAILLE PATTERN DOTS-12348", "h" : "288F" },
{"g" : "\u2890", "n" : "BRAILLE PATTERN DOTS-58", "h" : "2890" },
{"g" : "\u2891", "n" : "BRAILLE PATTERN DOTS-158", "h" : "2891" },
{"g" : "\u2892", "n" : "BRAILLE PATTERN DOTS-258", "h" : "2892" },
{"g" : "\u2893", "n" : "BRAILLE PATTERN DOTS-1258", "h" : "2893" },
{"g" : "\u2894", "n" : "BRAILLE PATTERN DOTS-358", "h" : "2894" },
{"g" : "\u2895", "n" : "BRAILLE PATTERN DOTS-1358", "h" : "2895" },
{"g" : "\u2896", "n" : "BRAILLE PATTERN DOTS-2358", "h" : "2896" },
{"g" : "\u2897", "n" : "BRAILLE PATTERN DOTS-12358", "h" : "2897" },
{"g" : "\u2898", "n" : "BRAILLE PATTERN DOTS-458", "h" : "2898" },
{"g" : "\u2899", "n" : "BRAILLE PATTERN DOTS-1458", "h" : "2899" },
{"g" : "\u289A", "n" : "BRAILLE PATTERN DOTS-2458", "h" : "289A" },
{"g" : "\u289B", "n" : "BRAILLE PATTERN DOTS-12458", "h" : "289B" },
{"g" : "\u289C", "n" : "BRAILLE PATTERN DOTS-3458", "h" : "289C" },
{"g" : "\u289D", "n" : "BRAILLE PATTERN DOTS-13458", "h" : "289D" },
{"g" : "\u289E", "n" : "BRAILLE PATTERN DOTS-23458", "h" : "289E" },
{"g" : "\u289F", "n" : "BRAILLE PATTERN DOTS-123458", "h" : "289F" },
{"g" : "\u28A0", "n" : "BRAILLE PATTERN DOTS-68", "h" : "28A0" },
{"g" : "\u28A1", "n" : "BRAILLE PATTERN DOTS-168", "h" : "28A1" },
{"g" : "\u28A2", "n" : "BRAILLE PATTERN DOTS-268", "h" : "28A2" },
{"g" : "\u28A3", "n" : "BRAILLE PATTERN DOTS-1268", "h" : "28A3" },
{"g" : "\u28A4", "n" : "BRAILLE PATTERN DOTS-368", "h" : "28A4" },
{"g" : "\u28A5", "n" : "BRAILLE PATTERN DOTS-1368", "h" : "28A5" },
{"g" : "\u28A6", "n" : "BRAILLE PATTERN DOTS-2368", "h" : "28A6" },
{"g" : "\u28A7", "n" : "BRAILLE PATTERN DOTS-12368", "h" : "28A7" },
{"g" : "\u28A8", "n" : "BRAILLE PATTERN DOTS-468", "h" : "28A8" },
{"g" : "\u28A9", "n" : "BRAILLE PATTERN DOTS-1468", "h" : "28A9" },
{"g" : "\u28AA", "n" : "BRAILLE PATTERN DOTS-2468", "h" : "28AA" },
{"g" : "\u28AB", "n" : "BRAILLE PATTERN DOTS-12468", "h" : "28AB" },
{"g" : "\u28AC", "n" : "BRAILLE PATTERN DOTS-3468", "h" : "28AC" },
{"g" : "\u28AD", "n" : "BRAILLE PATTERN DOTS-13468", "h" : "28AD" },
{"g" : "\u28AE", "n" : "BRAILLE PATTERN DOTS-23468", "h" : "28AE" },
{"g" : "\u28AF", "n" : "BRAILLE PATTERN DOTS-123468", "h" : "28AF" },
{"g" : "\u28B0", "n" : "BRAILLE PATTERN DOTS-568", "h" : "28B0" },
{"g" : "\u28B1", "n" : "BRAILLE PATTERN DOTS-1568", "h" : "28B1" },
{"g" : "\u28B2", "n" : "BRAILLE PATTERN DOTS-2568", "h" : "28B2" },
{"g" : "\u28B3", "n" : "BRAILLE PATTERN DOTS-12568", "h" : "28B3" },
{"g" : "\u28B4", "n" : "BRAILLE PATTERN DOTS-3568", "h" : "28B4" },
{"g" : "\u28B5", "n" : "BRAILLE PATTERN DOTS-13568", "h" : "28B5" },
{"g" : "\u28B6", "n" : "BRAILLE PATTERN DOTS-23568", "h" : "28B6" },
{"g" : "\u28B7", "n" : "BRAILLE PATTERN DOTS-123568", "h" : "28B7" },
{"g" : "\u28B8", "n" : "BRAILLE PATTERN DOTS-4568", "h" : "28B8" },
{"g" : "\u28B9", "n" : "BRAILLE PATTERN DOTS-14568", "h" : "28B9" },
{"g" : "\u28BA", "n" : "BRAILLE PATTERN DOTS-24568", "h" : "28BA" },
{"g" : "\u28BB", "n" : "BRAILLE PATTERN DOTS-124568", "h" : "28BB" },
{"g" : "\u28BC", "n" : "BRAILLE PATTERN DOTS-34568", "h" : "28BC" },
{"g" : "\u28BD", "n" : "BRAILLE PATTERN DOTS-134568", "h" : "28BD" },
{"g" : "\u28BE", "n" : "BRAILLE PATTERN DOTS-234568", "h" : "28BE" },
{"g" : "\u28BF", "n" : "BRAILLE PATTERN DOTS-1234568", "h" : "28BF" },
{"g" : "\u28C0", "n" : "BRAILLE PATTERN DOTS-78", "h" : "28C0" },
{"g" : "\u28C1", "n" : "BRAILLE PATTERN DOTS-178", "h" : "28C1" },
{"g" : "\u28C2", "n" : "BRAILLE PATTERN DOTS-278", "h" : "28C2" },
{"g" : "\u28C3", "n" : "BRAILLE PATTERN DOTS-1278", "h" : "28C3" },
{"g" : "\u28C4", "n" : "BRAILLE PATTERN DOTS-378", "h" : "28C4" },
{"g" : "\u28C5", "n" : "BRAILLE PATTERN DOTS-1378", "h" : "28C5" },
{"g" : "\u28C6", "n" : "BRAILLE PATTERN DOTS-2378", "h" : "28C6" },
{"g" : "\u28C7", "n" : "BRAILLE PATTERN DOTS-12378", "h" : "28C7" },
{"g" : "\u28C8", "n" : "BRAILLE PATTERN DOTS-478", "h" : "28C8" },
{"g" : "\u28C9", "n" : "BRAILLE PATTERN DOTS-1478", "h" : "28C9" },
{"g" : "\u28CA", "n" : "BRAILLE PATTERN DOTS-2478", "h" : "28CA" },
{"g" : "\u28CB", "n" : "BRAILLE PATTERN DOTS-12478", "h" : "28CB" },
{"g" : "\u28CC", "n" : "BRAILLE PATTERN DOTS-3478", "h" : "28CC" },
{"g" : "\u28CD", "n" : "BRAILLE PATTERN DOTS-13478", "h" : "28CD" },
{"g" : "\u28CE", "n" : "BRAILLE PATTERN DOTS-23478", "h" : "28CE" },
{"g" : "\u28CF", "n" : "BRAILLE PATTERN DOTS-123478", "h" : "28CF" },
{"g" : "\u28D0", "n" : "BRAILLE PATTERN DOTS-578", "h" : "28D0" },
{"g" : "\u28D1", "n" : "BRAILLE PATTERN DOTS-1578", "h" : "28D1" },
{"g" : "\u28D2", "n" : "BRAILLE PATTERN DOTS-2578", "h" : "28D2" },
{"g" : "\u28D3", "n" : "BRAILLE PATTERN DOTS-12578", "h" : "28D3" },
{"g" : "\u28D4", "n" : "BRAILLE PATTERN DOTS-3578", "h" : "28D4" },
{"g" : "\u28D5", "n" : "BRAILLE PATTERN DOTS-13578", "h" : "28D5" },
{"g" : "\u28D6", "n" : "BRAILLE PATTERN DOTS-23578", "h" : "28D6" },
{"g" : "\u28D7", "n" : "BRAILLE PATTERN DOTS-123578", "h" : "28D7" },
{"g" : "\u28D8", "n" : "BRAILLE PATTERN DOTS-4578", "h" : "28D8" },
{"g" : "\u28D9", "n" : "BRAILLE PATTERN DOTS-14578", "h" : "28D9" },
{"g" : "\u28DA", "n" : "BRAILLE PATTERN DOTS-24578", "h" : "28DA" },
{"g" : "\u28DB", "n" : "BRAILLE PATTERN DOTS-124578", "h" : "28DB" },
{"g" : "\u28DC", "n" : "BRAILLE PATTERN DOTS-34578", "h" : "28DC" },
{"g" : "\u28DD", "n" : "BRAILLE PATTERN DOTS-134578", "h" : "28DD" },
{"g" : "\u28DE", "n" : "BRAILLE PATTERN DOTS-234578", "h" : "28DE" },
{"g" : "\u28DF", "n" : "BRAILLE PATTERN DOTS-1234578", "h" : "28DF" },
{"g" : "\u28E0", "n" : "BRAILLE PATTERN DOTS-678", "h" : "28E0" },
{"g" : "\u28E1", "n" : "BRAILLE PATTERN DOTS-1678", "h" : "28E1" },
{"g" : "\u28E2", "n" : "BRAILLE PATTERN DOTS-2678", "h" : "28E2" },
{"g" : "\u28E3", "n" : "BRAILLE PATTERN DOTS-12678", "h" : "28E3" },
{"g" : "\u28E4", "n" : "BRAILLE PATTERN DOTS-3678", "h" : "28E4" },
{"g" : "\u28E5", "n" : "BRAILLE PATTERN DOTS-13678", "h" : "28E5" },
{"g" : "\u28E6", "n" : "BRAILLE PATTERN DOTS-23678", "h" : "28E6" },
{"g" : "\u28E7", "n" : "BRAILLE PATTERN DOTS-123678", "h" : "28E7" },
{"g" : "\u28E8", "n" : "BRAILLE PATTERN DOTS-4678", "h" : "28E8" },
{"g" : "\u28E9", "n" : "BRAILLE PATTERN DOTS-14678", "h" : "28E9" },
{"g" : "\u28EA", "n" : "BRAILLE PATTERN DOTS-24678", "h" : "28EA" },
{"g" : "\u28EB", "n" : "BRAILLE PATTERN DOTS-124678", "h" : "28EB" },
{"g" : "\u28EC", "n" : "BRAILLE PATTERN DOTS-34678", "h" : "28EC" },
{"g" : "\u28ED", "n" : "BRAILLE PATTERN DOTS-134678", "h" : "28ED" },
{"g" : "\u28EE", "n" : "BRAILLE PATTERN DOTS-234678", "h" : "28EE" },
{"g" : "\u28EF", "n" : "BRAILLE PATTERN DOTS-1234678", "h" : "28EF" },
{"g" : "\u28F0", "n" : "BRAILLE PATTERN DOTS-5678", "h" : "28F0" },
{"g" : "\u28F1", "n" : "BRAILLE PATTERN DOTS-15678", "h" : "28F1" },
{"g" : "\u28F2", "n" : "BRAILLE PATTERN DOTS-25678", "h" : "28F2" },
{"g" : "\u28F3", "n" : "BRAILLE PATTERN DOTS-125678", "h" : "28F3" },
{"g" : "\u28F4", "n" : "BRAILLE PATTERN DOTS-35678", "h" : "28F4" },
{"g" : "\u28F5", "n" : "BRAILLE PATTERN DOTS-135678", "h" : "28F5" },
{"g" : "\u28F6", "n" : "BRAILLE PATTERN DOTS-235678", "h" : "28F6" },
{"g" : "\u28F7", "n" : "BRAILLE PATTERN DOTS-1235678", "h" : "28F7" },
{"g" : "\u28F8", "n" : "BRAILLE PATTERN DOTS-45678", "h" : "28F8" },
{"g" : "\u28F9", "n" : "BRAILLE PATTERN DOTS-145678", "h" : "28F9" },
{"g" : "\u28FA", "n" : "BRAILLE PATTERN DOTS-245678", "h" : "28FA" },
{"g" : "\u28FB", "n" : "BRAILLE PATTERN DOTS-1245678", "h" : "28FB" },
{"g" : "\u28FC", "n" : "BRAILLE PATTERN DOTS-345678", "h" : "28FC" },
{"g" : "\u28FD", "n" : "BRAILLE PATTERN DOTS-1345678", "h" : "28FD" },
{"g" : "\u28FE", "n" : "BRAILLE PATTERN DOTS-2345678", "h" : "28FE" },
{"g" : "\u28FF", "n" : "BRAILLE PATTERN DOTS-12345678", "h" : "28FF" },

{"g" : "\u{1BC00}", "n" : "DUPLOYAN LETTER H", "h" : "1BC00"},
{"g" : "\u{1BC01}", "n" : "DUPLOYAN LETTER X", "h" : "1BC01"},
{"g" : "\u{1BC02}", "n" : "DUPLOYAN LETTER P", "h" : "1BC02"},
{"g" : "\u{1BC03}", "n" : "DUPLOYAN LETTER T", "h" : "1BC03"},
{"g" : "\u{1BC04}", "n" : "DUPLOYAN LETTER F", "h" : "1BC04"},
{"g" : "\u{1BC05}", "n" : "DUPLOYAN LETTER K", "h" : "1BC05"},
{"g" : "\u{1BC06}", "n" : "DUPLOYAN LETTER L", "h" : "1BC06"},
{"g" : "\u{1BC07}", "n" : "DUPLOYAN LETTER B", "h" : "1BC07"},
{"g" : "\u{1BC08}", "n" : "DUPLOYAN LETTER D", "h" : "1BC08"},
{"g" : "\u{1BC09}", "n" : "DUPLOYAN LETTER V", "h" : "1BC09"},
{"g" : "\u{1BC0A}", "n" : "DUPLOYAN LETTER G", "h" : "1BC0A"},
{"g" : "\u{1BC0B}", "n" : "DUPLOYAN LETTER R", "h" : "1BC0B"},
{"g" : "\u{1BC0C}", "n" : "DUPLOYAN LETTER P N", "h" : "1BC0C"},
{"g" : "\u{1BC0D}", "n" : "DUPLOYAN LETTER D S", "h" : "1BC0D"},
{"g" : "\u{1BC0E}", "n" : "DUPLOYAN LETTER F N", "h" : "1BC0E"},
{"g" : "\u{1BC0F}", "n" : "DUPLOYAN LETTER K M", "h" : "1BC0F"},
{"g" : "\u{1BC10}", "n" : "DUPLOYAN LETTER R S", "h" : "1BC10"},
{"g" : "\u{1BC11}", "n" : "DUPLOYAN LETTER TH", "h" : "1BC11"},
{"g" : "\u{1BC12}", "n" : "DUPLOYAN LETTER SLOAN DH", "h" : "1BC12"},
{"g" : "\u{1BC13}", "n" : "DUPLOYAN LETTER DH", "h" : "1BC13"},
{"g" : "\u{1BC14}", "n" : "DUPLOYAN LETTER KK", "h" : "1BC14"},
{"g" : "\u{1BC15}", "n" : "DUPLOYAN LETTER SLOAN J", "h" : "1BC15"},
{"g" : "\u{1BC16}", "n" : "DUPLOYAN LETTER HL", "h" : "1BC16"},
{"g" : "\u{1BC17}", "n" : "DUPLOYAN LETTER LH", "h" : "1BC17"},
{"g" : "\u{1BC18}", "n" : "DUPLOYAN LETTER RH", "h" : "1BC18"},
{"g" : "\u{1BC19}", "n" : "DUPLOYAN LETTER M", "h" : "1BC19"},
{"g" : "\u{1BC1A}", "n" : "DUPLOYAN LETTER N", "h" : "1BC1A"},
{"g" : "\u{1BC1B}", "n" : "DUPLOYAN LETTER J", "h" : "1BC1B"},
{"g" : "\u{1BC1C}", "n" : "DUPLOYAN LETTER S", "h" : "1BC1C"},
{"g" : "\u{1BC1D}", "n" : "DUPLOYAN LETTER M N", "h" : "1BC1D"},
{"g" : "\u{1BC1E}", "n" : "DUPLOYAN LETTER N M", "h" : "1BC1E"},
{"g" : "\u{1BC1F}", "n" : "DUPLOYAN LETTER J M", "h" : "1BC1F"},
{"g" : "\u{1BC20}", "n" : "DUPLOYAN LETTER S J", "h" : "1BC20"},
{"g" : "\u{1BC21}", "n" : "DUPLOYAN LETTER M WITH DOT", "h" : "1BC21"},
{"g" : "\u{1BC22}", "n" : "DUPLOYAN LETTER N WITH DOT", "h" : "1BC22"},
{"g" : "\u{1BC23}", "n" : "DUPLOYAN LETTER J WITH DOT", "h" : "1BC23"},
{"g" : "\u{1BC24}", "n" : "DUPLOYAN LETTER J WITH DOTS INSIDE AND ABOVE", "h" : "1BC24"},
{"g" : "\u{1BC25}", "n" : "DUPLOYAN LETTER S WITH DOT", "h" : "1BC25"},
{"g" : "\u{1BC26}", "n" : "DUPLOYAN LETTER S WITH DOT BELOW", "h" : "1BC26"},
{"g" : "\u{1BC27}", "n" : "DUPLOYAN LETTER M S", "h" : "1BC27"},
{"g" : "\u{1BC28}", "n" : "DUPLOYAN LETTER N S", "h" : "1BC28"},
{"g" : "\u{1BC29}", "n" : "DUPLOYAN LETTER J S", "h" : "1BC29"},
{"g" : "\u{1BC2A}", "n" : "DUPLOYAN LETTER S S", "h" : "1BC2A"},
{"g" : "\u{1BC2B}", "n" : "DUPLOYAN LETTER M N S", "h" : "1BC2B"},
{"g" : "\u{1BC2C}", "n" : "DUPLOYAN LETTER N M S", "h" : "1BC2C"},
{"g" : "\u{1BC2D}", "n" : "DUPLOYAN LETTER J M S", "h" : "1BC2D"},
{"g" : "\u{1BC2E}", "n" : "DUPLOYAN LETTER S J S", "h" : "1BC2E"},
{"g" : "\u{1BC2F}", "n" : "DUPLOYAN LETTER J S WITH DOT", "h" : "1BC2F"},
{"g" : "\u{1BC30}", "n" : "DUPLOYAN LETTER J N", "h" : "1BC30"},
{"g" : "\u{1BC31}", "n" : "DUPLOYAN LETTER J N S", "h" : "1BC31"},
{"g" : "\u{1BC32}", "n" : "DUPLOYAN LETTER S T", "h" : "1BC32"},
{"g" : "\u{1BC33}", "n" : "DUPLOYAN LETTER S T R", "h" : "1BC33"},
{"g" : "\u{1BC34}", "n" : "DUPLOYAN LETTER S P", "h" : "1BC34"},
{"g" : "\u{1BC35}", "n" : "DUPLOYAN LETTER S P R", "h" : "1BC35"},
{"g" : "\u{1BC36}", "n" : "DUPLOYAN LETTER T S", "h" : "1BC36"},
{"g" : "\u{1BC37}", "n" : "DUPLOYAN LETTER T R S", "h" : "1BC37"},
{"g" : "\u{1BC38}", "n" : "DUPLOYAN LETTER W", "h" : "1BC38"},
{"g" : "\u{1BC39}", "n" : "DUPLOYAN LETTER WH", "h" : "1BC39"},
{"g" : "\u{1BC3A}", "n" : "DUPLOYAN LETTER W R", "h" : "1BC3A"},
{"g" : "\u{1BC3B}", "n" : "DUPLOYAN LETTER S N", "h" : "1BC3B"},
{"g" : "\u{1BC3C}", "n" : "DUPLOYAN LETTER S M", "h" : "1BC3C"},
{"g" : "\u{1BC3D}", "n" : "DUPLOYAN LETTER K R S", "h" : "1BC3D"},
{"g" : "\u{1BC3E}", "n" : "DUPLOYAN LETTER G R S", "h" : "1BC3E"},
{"g" : "\u{1BC3F}", "n" : "DUPLOYAN LETTER S K", "h" : "1BC3F"},
{"g" : "\u{1BC40}", "n" : "DUPLOYAN LETTER S K R", "h" : "1BC40"},
{"g" : "\u{1BC41}", "n" : "DUPLOYAN LETTER A", "h" : "1BC41"},
{"g" : "\u{1BC42}", "n" : "DUPLOYAN LETTER SLOAN OW", "h" : "1BC42"},
{"g" : "\u{1BC43}", "n" : "DUPLOYAN LETTER OA", "h" : "1BC43"},
{"g" : "\u{1BC44}", "n" : "DUPLOYAN LETTER O", "h" : "1BC44"},
{"g" : "\u{1BC45}", "n" : "DUPLOYAN LETTER AOU", "h" : "1BC45"},
{"g" : "\u{1BC46}", "n" : "DUPLOYAN LETTER I", "h" : "1BC46"},
{"g" : "\u{1BC47}", "n" : "DUPLOYAN LETTER E", "h" : "1BC47"},
{"g" : "\u{1BC48}", "n" : "DUPLOYAN LETTER IE", "h" : "1BC48"},
{"g" : "\u{1BC49}", "n" : "DUPLOYAN LETTER SHORT I", "h" : "1BC49"},
{"g" : "\u{1BC4A}", "n" : "DUPLOYAN LETTER UI", "h" : "1BC4A"},
{"g" : "\u{1BC4B}", "n" : "DUPLOYAN LETTER EE", "h" : "1BC4B"},
{"g" : "\u{1BC4C}", "n" : "DUPLOYAN LETTER SLOAN EH", "h" : "1BC4C"},
{"g" : "\u{1BC4D}", "n" : "DUPLOYAN LETTER ROMANIAN I", "h" : "1BC4D"},
{"g" : "\u{1BC4E}", "n" : "DUPLOYAN LETTER SLOAN EE", "h" : "1BC4E"},
{"g" : "\u{1BC4F}", "n" : "DUPLOYAN LETTER LONG I", "h" : "1BC4F"},
{"g" : "\u{1BC50}", "n" : "DUPLOYAN LETTER YE", "h" : "1BC50"},
{"g" : "\u{1BC51}", "n" : "DUPLOYAN LETTER U", "h" : "1BC51"},
{"g" : "\u{1BC52}", "n" : "DUPLOYAN LETTER EU", "h" : "1BC52"},
{"g" : "\u{1BC53}", "n" : "DUPLOYAN LETTER XW", "h" : "1BC53"},
{"g" : "\u{1BC54}", "n" : "DUPLOYAN LETTER U N", "h" : "1BC54"},
{"g" : "\u{1BC55}", "n" : "DUPLOYAN LETTER LONG U", "h" : "1BC55"},
{"g" : "\u{1BC56}", "n" : "DUPLOYAN LETTER ROMANIAN U", "h" : "1BC56"},
{"g" : "\u{1BC57}", "n" : "DUPLOYAN LETTER UH", "h" : "1BC57"},
{"g" : "\u{1BC58}", "n" : "DUPLOYAN LETTER SLOAN U", "h" : "1BC58"},
{"g" : "\u{1BC59}", "n" : "DUPLOYAN LETTER OOH", "h" : "1BC59"},
{"g" : "\u{1BC5A}", "n" : "DUPLOYAN LETTER OW", "h" : "1BC5A"},
{"g" : "\u{1BC5B}", "n" : "DUPLOYAN LETTER OU", "h" : "1BC5B"},
{"g" : "\u{1BC5C}", "n" : "DUPLOYAN LETTER WA", "h" : "1BC5C"},
{"g" : "\u{1BC5D}", "n" : "DUPLOYAN LETTER WO", "h" : "1BC5D"},
{"g" : "\u{1BC5E}", "n" : "DUPLOYAN LETTER WI", "h" : "1BC5E"},
{"g" : "\u{1BC5F}", "n" : "DUPLOYAN LETTER WEI", "h" : "1BC5F"},
{"g" : "\u{1BC60}", "n" : "DUPLOYAN LETTER WOW", "h" : "1BC60"},
{"g" : "\u{1BC61}", "n" : "DUPLOYAN LETTER NASAL U", "h" : "1BC61"},
{"g" : "\u{1BC62}", "n" : "DUPLOYAN LETTER NASAL O", "h" : "1BC62"},
{"g" : "\u{1BC63}", "n" : "DUPLOYAN LETTER NASAL I", "h" : "1BC63"},
{"g" : "\u{1BC64}", "n" : "DUPLOYAN LETTER NASAL A", "h" : "1BC64"},
{"g" : "\u{1BC65}", "n" : "DUPLOYAN LETTER PERNIN AN", "h" : "1BC65"},
{"g" : "\u{1BC66}", "n" : "DUPLOYAN LETTER PERNIN AM", "h" : "1BC66"},
{"g" : "\u{1BC67}", "n" : "DUPLOYAN LETTER SLOAN EN", "h" : "1BC67"},
{"g" : "\u{1BC68}", "n" : "DUPLOYAN LETTER SLOAN AN", "h" : "1BC68"},
{"g" : "\u{1BC69}", "n" : "DUPLOYAN LETTER SLOAN ON", "h" : "1BC69"},
{"g" : "\u{1BC6A}", "n" : "DUPLOYAN LETTER VOCALIC M", "h" : "1BC6A"},

{"g" : "\u{1BC70}", "n" : "DUPLOYAN AFFIX LEFT HORIZONTAL SECANT", "h" : "1BC70"},
{"g" : "\u{1BC71}", "n" : "DUPLOYAN AFFIX MID HORIZONTAL SECANT", "h" : "1BC71"},
{"g" : "\u{1BC72}", "n" : "DUPLOYAN AFFIX RIGHT HORIZONTAL SECANT", "h" : "1BC72"},
{"g" : "\u{1BC73}", "n" : "DUPLOYAN AFFIX LOW VERTICAL SECANT", "h" : "1BC73"},
{"g" : "\u{1BC74}", "n" : "DUPLOYAN AFFIX MID VERTICAL SECANT", "h" : "1BC74"},
{"g" : "\u{1BC75}", "n" : "DUPLOYAN AFFIX HIGH VERTICAL SECANT", "h" : "1BC75"},
{"g" : "\u{1BC76}", "n" : "DUPLOYAN AFFIX ATTACHED SECANT", "h" : "1BC76"},
{"g" : "\u{1BC77}", "n" : "DUPLOYAN AFFIX ATTACHED LEFT-TO-RIGHT SECANT", "h" : "1BC77"},
{"g" : "\u{1BC78}", "n" : "DUPLOYAN AFFIX ATTACHED TANGENT", "h" : "1BC78"},
{"g" : "\u{1BC79}", "n" : "DUPLOYAN AFFIX ATTACHED TAIL", "h" : "1BC79"},
{"g" : "\u{1BC7A}", "n" : "DUPLOYAN AFFIX ATTACHED E HOOK", "h" : "1BC7A"},
{"g" : "\u{1BC7B}", "n" : "DUPLOYAN AFFIX ATTACHED I HOOK", "h" : "1BC7B"},
{"g" : "\u{1BC7C}", "n" : "DUPLOYAN AFFIX ATTACHED TANGENT HOOK", "h" : "1BC7C"},

{"g" : "\u{1BC80}", "n" : "DUPLOYAN AFFIX HIGH ACUTE", "h" : "1BC80"},
{"g" : "\u{1BC81}", "n" : "DUPLOYAN AFFIX HIGH TIGHT ACUTE", "h" : "1BC81"},
{"g" : "\u{1BC82}", "n" : "DUPLOYAN AFFIX HIGH GRAVE", "h" : "1BC82"},
{"g" : "\u{1BC83}", "n" : "DUPLOYAN AFFIX HIGH LONG GRAVE", "h" : "1BC83"},
{"g" : "\u{1BC84}", "n" : "DUPLOYAN AFFIX HIGH DOT", "h" : "1BC84"},
{"g" : "\u{1BC85}", "n" : "DUPLOYAN AFFIX HIGH CIRCLE", "h" : "1BC85"},
{"g" : "\u{1BC86}", "n" : "DUPLOYAN AFFIX HIGH LINE", "h" : "1BC86"},
{"g" : "\u{1BC87}", "n" : "DUPLOYAN AFFIX HIGH WAVE", "h" : "1BC87"},
{"g" : "\u{1BC88}", "n" : "DUPLOYAN AFFIX HIGH VERTICAL", "h" : "1BC88"},

{"g" : "\u{1BC90}", "n" : "DUPLOYAN AFFIX LOW ACUTE", "h" : "1BC90"},
{"g" : "\u{1BC91}", "n" : "DUPLOYAN AFFIX LOW TIGHT ACUTE", "h" : "1BC91"},
{"g" : "\u{1BC92}", "n" : "DUPLOYAN AFFIX LOW GRAVE", "h" : "1BC92"},
{"g" : "\u{1BC93}", "n" : "DUPLOYAN AFFIX LOW LONG GRAVE", "h" : "1BC93"},
{"g" : "\u{1BC94}", "n" : "DUPLOYAN AFFIX LOW DOT", "h" : "1BC94"},
{"g" : "\u{1BC95}", "n" : "DUPLOYAN AFFIX LOW CIRCLE", "h" : "1BC95"},
{"g" : "\u{1BC96}", "n" : "DUPLOYAN AFFIX LOW LINE", "h" : "1BC96"},
{"g" : "\u{1BC97}", "n" : "DUPLOYAN AFFIX LOW WAVE", "h" : "1BC97"},
{"g" : "\u{1BC98}", "n" : "DUPLOYAN AFFIX LOW VERTICAL", "h" : "1BC98"},
{"g" : "\u{1BC99}", "n" : "DUPLOYAN AFFIX LOW ARROW", "h" : "1BC99"},

{"g" : "\u{1BC9C}", "n" : "DUPLOYAN SIGN O WITH CROSS", "h" : "1BC9C"},
{"g" : "\u{1BC9D}", "n" : "DUPLOYAN THICK LETTER SELECTOR", "h" : "1BC9D"},
{"g" : "\u{1BC9E}", "n" : "DUPLOYAN DOUBLE MARK", "h" : "1BC9E"},
{"g" : "\u{1BC9F}", "n" : "DUPLOYAN PUNCTUATION CHINOOK FULL STOP", "h" : "1BC9F"},

{"g" : "\u{1BCA0}", "n" : "SHORTHAND FORMAT LETTER OVERLAP", "h" : "1BCA0"},
{"g" : "\u{1BCA1}", "n" : "SHORTHAND FORMAT CONTINUING OVERLAP", "h" : "1BCA1"},
{"g" : "\u{1BCA2}", "n" : "SHORTHAND FORMAT DOWN STEP", "h" : "1BCA2"},
{"g" : "\u{1BCA3}", "n" : "SHORTHAND FORMAT UP STEP", "h" : "1BCA3"},

{"g" : "\u{1D800}", "n" : "SIGNWRITING HAND-FIST INDEX", "h" : "1D800"},
{"g" : "\u{1D801}", "n" : "SIGNWRITING HAND-CIRCLE INDEX", "h" : "1D801"},
{"g" : "\u{1D802}", "n" : "SIGNWRITING HAND-CUP INDEX", "h" : "1D802"},
{"g" : "\u{1D803}", "n" : "SIGNWRITING HAND-OVAL INDEX", "h" : "1D803"},
{"g" : "\u{1D804}", "n" : "SIGNWRITING HAND-HINGE INDEX", "h" : "1D804"},
{"g" : "\u{1D805}", "n" : "SIGNWRITING HAND-ANGLE INDEX", "h" : "1D805"},
{"g" : "\u{1D806}", "n" : "SIGNWRITING HAND-FIST INDEX BENT", "h" : "1D806"},
{"g" : "\u{1D807}", "n" : "SIGNWRITING HAND-CIRCLE INDEX BENT", "h" : "1D807"},
{"g" : "\u{1D808}", "n" : "SIGNWRITING HAND-FIST THUMB UNDER INDEX BENT", "h" : "1D808"},
{"g" : "\u{1D809}", "n" : "SIGNWRITING HAND-FIST INDEX RAISED KNUCKLE", "h" : "1D809"},
{"g" : "\u{1D80A}", "n" : "SIGNWRITING HAND-FIST INDEX CUPPED", "h" : "1D80A"},
{"g" : "\u{1D80B}", "n" : "SIGNWRITING HAND-FIST INDEX HINGED", "h" : "1D80B"},
{"g" : "\u{1D80C}", "n" : "SIGNWRITING HAND-FIST INDEX HINGED LOW", "h" : "1D80C"},
{"g" : "\u{1D80D}", "n" : "SIGNWRITING HAND-CIRCLE INDEX HINGE", "h" : "1D80D"},
{"g" : "\u{1D80E}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE", "h" : "1D80E"},
{"g" : "\u{1D80F}", "n" : "SIGNWRITING HAND-CIRCLE INDEX MIDDLE", "h" : "1D80F"},
{"g" : "\u{1D810}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE BENT", "h" : "1D810"},
{"g" : "\u{1D811}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE RAISED KNUCKLES", "h" : "1D811"},
{"g" : "\u{1D812}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE HINGED", "h" : "1D812"},
{"g" : "\u{1D813}", "n" : "SIGNWRITING HAND-FIST INDEX UP MIDDLE HINGED", "h" : "1D813"},
{"g" : "\u{1D814}", "n" : "SIGNWRITING HAND-FIST INDEX HINGED MIDDLE UP", "h" : "1D814"},
{"g" : "\u{1D815}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED", "h" : "1D815"},
{"g" : "\u{1D816}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED INDEX BENT", "h" : "1D816"},
{"g" : "\u{1D817}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED MIDDLE BENT", "h" : "1D817"},
{"g" : "\u{1D818}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED CUPPED", "h" : "1D818"},
{"g" : "\u{1D819}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED HINGED", "h" : "1D819"},
{"g" : "\u{1D81A}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CROSSED", "h" : "1D81A"},
{"g" : "\u{1D81B}", "n" : "SIGNWRITING HAND-CIRCLE INDEX MIDDLE CROSSED", "h" : "1D81B"},
{"g" : "\u{1D81C}", "n" : "SIGNWRITING HAND-FIST MIDDLE BENT OVER INDEX", "h" : "1D81C"},
{"g" : "\u{1D81D}", "n" : "SIGNWRITING HAND-FIST INDEX BENT OVER MIDDLE", "h" : "1D81D"},
{"g" : "\u{1D81E}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB", "h" : "1D81E"},
{"g" : "\u{1D81F}", "n" : "SIGNWRITING HAND-CIRCLE INDEX MIDDLE THUMB", "h" : "1D81F"},
{"g" : "\u{1D820}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE STRAIGHT THUMB BENT", "h" : "1D820"},
{"g" : "\u{1D821}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE BENT THUMB STRAIGHT", "h" : "1D821"},
{"g" : "\u{1D822}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB BENT", "h" : "1D822"},
{"g" : "\u{1D823}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE HINGED SPREAD THUMB SIDE", "h" : "1D823"},
{"g" : "\u{1D824}", "n" : "SIGNWRITING HAND-FIST INDEX UP MIDDLE HINGED THUMB SIDE", "h" : "1D824"},
{"g" : "\u{1D825}", "n" : "SIGNWRITING HAND-FIST INDEX UP MIDDLE HINGED THUMB CONJOINED", "h" : "1D825"},
{"g" : "\u{1D826}", "n" : "SIGNWRITING HAND-FIST INDEX HINGED MIDDLE UP THUMB SIDE", "h" : "1D826"},
{"g" : "\u{1D827}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE UP SPREAD THUMB FORWARD", "h" : "1D827"},
{"g" : "\u{1D828}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB CUPPED", "h" : "1D828"},
{"g" : "\u{1D829}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB CIRCLED", "h" : "1D829"},
{"g" : "\u{1D82A}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB HOOKED", "h" : "1D82A"},
{"g" : "\u{1D82B}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB HINGED", "h" : "1D82B"},
{"g" : "\u{1D82C}", "n" : "SIGNWRITING HAND-FIST THUMB BETWEEN INDEX MIDDLE STRAIGHT", "h" : "1D82C"},
{"g" : "\u{1D82D}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB SIDE", "h" : "1D82D"},
{"g" : "\u{1D82E}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB SIDE CONJOINED", "h" : "1D82E"},
{"g" : "\u{1D82F}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB SIDE BENT", "h" : "1D82F"},
{"g" : "\u{1D830}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB HOOKED INDEX UP", "h" : "1D830"},
{"g" : "\u{1D831}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB HOOKED MIDDLE UP", "h" : "1D831"},
{"g" : "\u{1D832}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED HINGED THUMB SIDE", "h" : "1D832"},
{"g" : "\u{1D833}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CROSSED THUMB SIDE", "h" : "1D833"},
{"g" : "\u{1D834}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB FORWARD", "h" : "1D834"},
{"g" : "\u{1D835}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED CUPPED THUMB FORWARD", "h" : "1D835"},
{"g" : "\u{1D836}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB CUPPED INDEX UP", "h" : "1D836"},
{"g" : "\u{1D837}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB CUPPED MIDDLE UP", "h" : "1D837"},
{"g" : "\u{1D838}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB CIRCLED INDEX UP", "h" : "1D838"},
{"g" : "\u{1D839}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB CIRCLED INDEX HINGED", "h" : "1D839"},
{"g" : "\u{1D83A}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB ANGLED OUT MIDDLE UP", "h" : "1D83A"},
{"g" : "\u{1D83B}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB ANGLED IN MIDDLE UP", "h" : "1D83B"},
{"g" : "\u{1D83C}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB CIRCLED MIDDLE UP", "h" : "1D83C"},
{"g" : "\u{1D83D}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB CONJOINED HINGED", "h" : "1D83D"},
{"g" : "\u{1D83E}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB ANGLED OUT", "h" : "1D83E"},
{"g" : "\u{1D83F}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE THUMB ANGLED", "h" : "1D83F"},
{"g" : "\u{1D840}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB ANGLED OUT INDEX UP", "h" : "1D840"},
{"g" : "\u{1D841}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB ANGLED OUT INDEX CROSSED", "h" : "1D841"},
{"g" : "\u{1D842}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB ANGLED INDEX UP", "h" : "1D842"},
{"g" : "\u{1D843}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB HOOKED MIDDLE HINGED", "h" : "1D843"},
{"g" : "\u{1D844}", "n" : "SIGNWRITING HAND-FLAT FOUR FINGERS", "h" : "1D844"},
{"g" : "\u{1D845}", "n" : "SIGNWRITING HAND-FLAT FOUR FINGERS BENT", "h" : "1D845"},
{"g" : "\u{1D846}", "n" : "SIGNWRITING HAND-FLAT FOUR FINGERS HINGED", "h" : "1D846"},
{"g" : "\u{1D847}", "n" : "SIGNWRITING HAND-FLAT FOUR FINGERS CONJOINED", "h" : "1D847"},
{"g" : "\u{1D848}", "n" : "SIGNWRITING HAND-FLAT FOUR FINGERS CONJOINED SPLIT", "h" : "1D848"},
{"g" : "\u{1D849}", "n" : "SIGNWRITING HAND-CLAW FOUR FINGERS CONJOINED", "h" : "1D849"},
{"g" : "\u{1D84A}", "n" : "SIGNWRITING HAND-FIST FOUR FINGERS CONJOINED BENT", "h" : "1D84A"},
{"g" : "\u{1D84B}", "n" : "SIGNWRITING HAND-HINGE FOUR FINGERS CONJOINED", "h" : "1D84B"},
{"g" : "\u{1D84C}", "n" : "SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD", "h" : "1D84C"},
{"g" : "\u{1D84D}", "n" : "SIGNWRITING HAND-FLAT HEEL FIVE FINGERS SPREAD", "h" : "1D84D"},
{"g" : "\u{1D84E}", "n" : "SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD FOUR BENT", "h" : "1D84E"},
{"g" : "\u{1D84F}", "n" : "SIGNWRITING HAND-FLAT HEEL FIVE FINGERS SPREAD FOUR BENT", "h" : "1D84F"},
{"g" : "\u{1D850}", "n" : "SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD BENT", "h" : "1D850"},
{"g" : "\u{1D851}", "n" : "SIGNWRITING HAND-FLAT HEEL FIVE FINGERS SPREAD BENT", "h" : "1D851"},
{"g" : "\u{1D852}", "n" : "SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD THUMB FORWARD", "h" : "1D852"},
{"g" : "\u{1D853}", "n" : "SIGNWRITING HAND-CUP FIVE FINGERS SPREAD", "h" : "1D853"},
{"g" : "\u{1D854}", "n" : "SIGNWRITING HAND-CUP FIVE FINGERS SPREAD OPEN", "h" : "1D854"},
{"g" : "\u{1D855}", "n" : "SIGNWRITING HAND-HINGE FIVE FINGERS SPREAD OPEN", "h" : "1D855"},
{"g" : "\u{1D856}", "n" : "SIGNWRITING HAND-OVAL FIVE FINGERS SPREAD", "h" : "1D856"},
{"g" : "\u{1D857}", "n" : "SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD HINGED", "h" : "1D857"},
{"g" : "\u{1D858}", "n" : "SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD HINGED THUMB SIDE", "h" : "1D858"},
{"g" : "\u{1D859}", "n" : "SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD HINGED NO THUMB", "h" : "1D859"},
{"g" : "\u{1D85A}", "n" : "SIGNWRITING HAND-FLAT", "h" : "1D85A"},
{"g" : "\u{1D85B}", "n" : "SIGNWRITING HAND-FLAT BETWEEN PALM FACINGS", "h" : "1D85B"},
{"g" : "\u{1D85C}", "n" : "SIGNWRITING HAND-FLAT HEEL", "h" : "1D85C"},
{"g" : "\u{1D85D}", "n" : "SIGNWRITING HAND-FLAT THUMB SIDE", "h" : "1D85D"},
{"g" : "\u{1D85E}", "n" : "SIGNWRITING HAND-FLAT HEEL THUMB SIDE", "h" : "1D85E"},
{"g" : "\u{1D85F}", "n" : "SIGNWRITING HAND-FLAT THUMB BENT", "h" : "1D85F"},
{"g" : "\u{1D860}", "n" : "SIGNWRITING HAND-FLAT THUMB FORWARD", "h" : "1D860"},
{"g" : "\u{1D861}", "n" : "SIGNWRITING HAND-FLAT SPLIT INDEX THUMB SIDE", "h" : "1D861"},
{"g" : "\u{1D862}", "n" : "SIGNWRITING HAND-FLAT SPLIT CENTRE", "h" : "1D862"},
{"g" : "\u{1D863}", "n" : "SIGNWRITING HAND-FLAT SPLIT CENTRE THUMB SIDE", "h" : "1D863"},
{"g" : "\u{1D864}", "n" : "SIGNWRITING HAND-FLAT SPLIT CENTRE THUMB SIDE BENT", "h" : "1D864"},
{"g" : "\u{1D865}", "n" : "SIGNWRITING HAND-FLAT SPLIT LITTLE", "h" : "1D865"},
{"g" : "\u{1D866}", "n" : "SIGNWRITING HAND-CLAW", "h" : "1D866"},
{"g" : "\u{1D867}", "n" : "SIGNWRITING HAND-CLAW THUMB SIDE", "h" : "1D867"},
{"g" : "\u{1D868}", "n" : "SIGNWRITING HAND-CLAW NO THUMB", "h" : "1D868"},
{"g" : "\u{1D869}", "n" : "SIGNWRITING HAND-CLAW THUMB FORWARD", "h" : "1D869"},
{"g" : "\u{1D86A}", "n" : "SIGNWRITING HAND-HOOK CURLICUE", "h" : "1D86A"},
{"g" : "\u{1D86B}", "n" : "SIGNWRITING HAND-HOOK", "h" : "1D86B"},
{"g" : "\u{1D86C}", "n" : "SIGNWRITING HAND-CUP OPEN", "h" : "1D86C"},
{"g" : "\u{1D86D}", "n" : "SIGNWRITING HAND-CUP", "h" : "1D86D"},
{"g" : "\u{1D86E}", "n" : "SIGNWRITING HAND-CUP OPEN THUMB SIDE", "h" : "1D86E"},
{"g" : "\u{1D86F}", "n" : "SIGNWRITING HAND-CUP THUMB SIDE", "h" : "1D86F"},
{"g" : "\u{1D870}", "n" : "SIGNWRITING HAND-CUP OPEN NO THUMB", "h" : "1D870"},
{"g" : "\u{1D871}", "n" : "SIGNWRITING HAND-CUP NO THUMB", "h" : "1D871"},
{"g" : "\u{1D872}", "n" : "SIGNWRITING HAND-CUP OPEN THUMB FORWARD", "h" : "1D872"},
{"g" : "\u{1D873}", "n" : "SIGNWRITING HAND-CUP THUMB FORWARD", "h" : "1D873"},
{"g" : "\u{1D874}", "n" : "SIGNWRITING HAND-CURLICUE OPEN", "h" : "1D874"},
{"g" : "\u{1D875}", "n" : "SIGNWRITING HAND-CURLICUE", "h" : "1D875"},
{"g" : "\u{1D876}", "n" : "SIGNWRITING HAND-CIRCLE", "h" : "1D876"},
{"g" : "\u{1D877}", "n" : "SIGNWRITING HAND-OVAL", "h" : "1D877"},
{"g" : "\u{1D878}", "n" : "SIGNWRITING HAND-OVAL THUMB SIDE", "h" : "1D878"},
{"g" : "\u{1D879}", "n" : "SIGNWRITING HAND-OVAL NO THUMB", "h" : "1D879"},
{"g" : "\u{1D87A}", "n" : "SIGNWRITING HAND-OVAL THUMB FORWARD", "h" : "1D87A"},
{"g" : "\u{1D87B}", "n" : "SIGNWRITING HAND-HINGE OPEN", "h" : "1D87B"},
{"g" : "\u{1D87C}", "n" : "SIGNWRITING HAND-HINGE OPEN THUMB FORWARD", "h" : "1D87C"},
{"g" : "\u{1D87D}", "n" : "SIGNWRITING HAND-HINGE", "h" : "1D87D"},
{"g" : "\u{1D87E}", "n" : "SIGNWRITING HAND-HINGE SMALL", "h" : "1D87E"},
{"g" : "\u{1D87F}", "n" : "SIGNWRITING HAND-HINGE OPEN THUMB SIDE", "h" : "1D87F"},
{"g" : "\u{1D880}", "n" : "SIGNWRITING HAND-HINGE THUMB SIDE", "h" : "1D880"},
{"g" : "\u{1D881}", "n" : "SIGNWRITING HAND-HINGE OPEN NO THUMB", "h" : "1D881"},
{"g" : "\u{1D882}", "n" : "SIGNWRITING HAND-HINGE NO THUMB", "h" : "1D882"},
{"g" : "\u{1D883}", "n" : "SIGNWRITING HAND-HINGE THUMB SIDE TOUCHING INDEX", "h" : "1D883"},
{"g" : "\u{1D884}", "n" : "SIGNWRITING HAND-HINGE THUMB BETWEEN MIDDLE RING", "h" : "1D884"},
{"g" : "\u{1D885}", "n" : "SIGNWRITING HAND-ANGLE", "h" : "1D885"},
{"g" : "\u{1D886}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE RING", "h" : "1D886"},
{"g" : "\u{1D887}", "n" : "SIGNWRITING HAND-CIRCLE INDEX MIDDLE RING", "h" : "1D887"},
{"g" : "\u{1D888}", "n" : "SIGNWRITING HAND-HINGE INDEX MIDDLE RING", "h" : "1D888"},
{"g" : "\u{1D889}", "n" : "SIGNWRITING HAND-ANGLE INDEX MIDDLE RING", "h" : "1D889"},
{"g" : "\u{1D88A}", "n" : "SIGNWRITING HAND-HINGE LITTLE", "h" : "1D88A"},
{"g" : "\u{1D88B}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE RING BENT", "h" : "1D88B"},
{"g" : "\u{1D88C}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE RING CONJOINED", "h" : "1D88C"},
{"g" : "\u{1D88D}", "n" : "SIGNWRITING HAND-HINGE INDEX MIDDLE RING CONJOINED", "h" : "1D88D"},
{"g" : "\u{1D88E}", "n" : "SIGNWRITING HAND-FIST LITTLE DOWN", "h" : "1D88E"},
{"g" : "\u{1D88F}", "n" : "SIGNWRITING HAND-FIST LITTLE DOWN RIPPLE STRAIGHT", "h" : "1D88F"},
{"g" : "\u{1D890}", "n" : "SIGNWRITING HAND-FIST LITTLE DOWN RIPPLE CURVED", "h" : "1D890"},
{"g" : "\u{1D891}", "n" : "SIGNWRITING HAND-FIST LITTLE DOWN OTHERS CIRCLED", "h" : "1D891"},
{"g" : "\u{1D892}", "n" : "SIGNWRITING HAND-FIST LITTLE UP", "h" : "1D892"},
{"g" : "\u{1D893}", "n" : "SIGNWRITING HAND-FIST THUMB UNDER LITTLE UP", "h" : "1D893"},
{"g" : "\u{1D894}", "n" : "SIGNWRITING HAND-CIRCLE LITTLE UP", "h" : "1D894"},
{"g" : "\u{1D895}", "n" : "SIGNWRITING HAND-OVAL LITTLE UP", "h" : "1D895"},
{"g" : "\u{1D896}", "n" : "SIGNWRITING HAND-ANGLE LITTLE UP", "h" : "1D896"},
{"g" : "\u{1D897}", "n" : "SIGNWRITING HAND-FIST LITTLE RAISED KNUCKLE", "h" : "1D897"},
{"g" : "\u{1D898}", "n" : "SIGNWRITING HAND-FIST LITTLE BENT", "h" : "1D898"},
{"g" : "\u{1D899}", "n" : "SIGNWRITING HAND-FIST LITTLE TOUCHES THUMB", "h" : "1D899"},
{"g" : "\u{1D89A}", "n" : "SIGNWRITING HAND-FIST LITTLE THUMB", "h" : "1D89A"},
{"g" : "\u{1D89B}", "n" : "SIGNWRITING HAND-HINGE LITTLE THUMB", "h" : "1D89B"},
{"g" : "\u{1D89C}", "n" : "SIGNWRITING HAND-FIST LITTLE INDEX THUMB", "h" : "1D89C"},
{"g" : "\u{1D89D}", "n" : "SIGNWRITING HAND-HINGE LITTLE INDEX THUMB", "h" : "1D89D"},
{"g" : "\u{1D89E}", "n" : "SIGNWRITING HAND-ANGLE LITTLE INDEX THUMB INDEX THUMB OUT", "h" : "1D89E"},
{"g" : "\u{1D89F}", "n" : "SIGNWRITING HAND-ANGLE LITTLE INDEX THUMB INDEX THUMB", "h" : "1D89F"},
{"g" : "\u{1D8A0}", "n" : "SIGNWRITING HAND-FIST LITTLE INDEX", "h" : "1D8A0"},
{"g" : "\u{1D8A1}", "n" : "SIGNWRITING HAND-CIRCLE LITTLE INDEX", "h" : "1D8A1"},
{"g" : "\u{1D8A2}", "n" : "SIGNWRITING HAND-HINGE LITTLE INDEX", "h" : "1D8A2"},
{"g" : "\u{1D8A3}", "n" : "SIGNWRITING HAND-ANGLE LITTLE INDEX", "h" : "1D8A3"},
{"g" : "\u{1D8A4}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE LITTLE", "h" : "1D8A4"},
{"g" : "\u{1D8A5}", "n" : "SIGNWRITING HAND-CIRCLE INDEX MIDDLE LITTLE", "h" : "1D8A5"},
{"g" : "\u{1D8A6}", "n" : "SIGNWRITING HAND-HINGE INDEX MIDDLE LITTLE", "h" : "1D8A6"},
{"g" : "\u{1D8A7}", "n" : "SIGNWRITING HAND-HINGE RING", "h" : "1D8A7"},
{"g" : "\u{1D8A8}", "n" : "SIGNWRITING HAND-ANGLE INDEX MIDDLE LITTLE", "h" : "1D8A8"},
{"g" : "\u{1D8A9}", "n" : "SIGNWRITING HAND-FIST INDEX MIDDLE CROSS LITTLE", "h" : "1D8A9"},
{"g" : "\u{1D8AA}", "n" : "SIGNWRITING HAND-CIRCLE INDEX MIDDLE CROSS LITTLE", "h" : "1D8AA"},
{"g" : "\u{1D8AB}", "n" : "SIGNWRITING HAND-FIST RING DOWN", "h" : "1D8AB"},
{"g" : "\u{1D8AC}", "n" : "SIGNWRITING HAND-HINGE RING DOWN INDEX THUMB HOOK MIDDLE", "h" : "1D8AC"},
{"g" : "\u{1D8AD}", "n" : "SIGNWRITING HAND-ANGLE RING DOWN MIDDLE THUMB INDEX CROSS", "h" : "1D8AD"},
{"g" : "\u{1D8AE}", "n" : "SIGNWRITING HAND-FIST RING UP", "h" : "1D8AE"},
{"g" : "\u{1D8AF}", "n" : "SIGNWRITING HAND-FIST RING RAISED KNUCKLE", "h" : "1D8AF"},
{"g" : "\u{1D8B0}", "n" : "SIGNWRITING HAND-FIST RING LITTLE", "h" : "1D8B0"},
{"g" : "\u{1D8B1}", "n" : "SIGNWRITING HAND-CIRCLE RING LITTLE", "h" : "1D8B1"},
{"g" : "\u{1D8B2}", "n" : "SIGNWRITING HAND-OVAL RING LITTLE", "h" : "1D8B2"},
{"g" : "\u{1D8B3}", "n" : "SIGNWRITING HAND-ANGLE RING LITTLE", "h" : "1D8B3"},
{"g" : "\u{1D8B4}", "n" : "SIGNWRITING HAND-FIST RING MIDDLE", "h" : "1D8B4"},
{"g" : "\u{1D8B5}", "n" : "SIGNWRITING HAND-FIST RING MIDDLE CONJOINED", "h" : "1D8B5"},
{"g" : "\u{1D8B6}", "n" : "SIGNWRITING HAND-FIST RING MIDDLE RAISED KNUCKLES", "h" : "1D8B6"},
{"g" : "\u{1D8B7}", "n" : "SIGNWRITING HAND-FIST RING INDEX", "h" : "1D8B7"},
{"g" : "\u{1D8B8}", "n" : "SIGNWRITING HAND-FIST RING THUMB", "h" : "1D8B8"},
{"g" : "\u{1D8B9}", "n" : "SIGNWRITING HAND-HOOK RING THUMB", "h" : "1D8B9"},
{"g" : "\u{1D8BA}", "n" : "SIGNWRITING HAND-FIST INDEX RING LITTLE", "h" : "1D8BA"},
{"g" : "\u{1D8BB}", "n" : "SIGNWRITING HAND-CIRCLE INDEX RING LITTLE", "h" : "1D8BB"},
{"g" : "\u{1D8BC}", "n" : "SIGNWRITING HAND-CURLICUE INDEX RING LITTLE ON", "h" : "1D8BC"},
{"g" : "\u{1D8BD}", "n" : "SIGNWRITING HAND-HOOK INDEX RING LITTLE OUT", "h" : "1D8BD"},
{"g" : "\u{1D8BE}", "n" : "SIGNWRITING HAND-HOOK INDEX RING LITTLE IN", "h" : "1D8BE"},
{"g" : "\u{1D8BF}", "n" : "SIGNWRITING HAND-HOOK INDEX RING LITTLE UNDER", "h" : "1D8BF"},
{"g" : "\u{1D8C0}", "n" : "SIGNWRITING HAND-CUP INDEX RING LITTLE", "h" : "1D8C0"},
{"g" : "\u{1D8C1}", "n" : "SIGNWRITING HAND-HINGE INDEX RING LITTLE", "h" : "1D8C1"},
{"g" : "\u{1D8C2}", "n" : "SIGNWRITING HAND-ANGLE INDEX RING LITTLE OUT", "h" : "1D8C2"},
{"g" : "\u{1D8C3}", "n" : "SIGNWRITING HAND-ANGLE INDEX RING LITTLE", "h" : "1D8C3"},
{"g" : "\u{1D8C4}", "n" : "SIGNWRITING HAND-FIST MIDDLE DOWN", "h" : "1D8C4"},
{"g" : "\u{1D8C5}", "n" : "SIGNWRITING HAND-HINGE MIDDLE", "h" : "1D8C5"},
{"g" : "\u{1D8C6}", "n" : "SIGNWRITING HAND-FIST MIDDLE UP", "h" : "1D8C6"},
{"g" : "\u{1D8C7}", "n" : "SIGNWRITING HAND-CIRCLE MIDDLE UP", "h" : "1D8C7"},
{"g" : "\u{1D8C8}", "n" : "SIGNWRITING HAND-FIST MIDDLE RAISED KNUCKLE", "h" : "1D8C8"},
{"g" : "\u{1D8C9}", "n" : "SIGNWRITING HAND-FIST MIDDLE UP THUMB SIDE", "h" : "1D8C9"},
{"g" : "\u{1D8CA}", "n" : "SIGNWRITING HAND-HOOK MIDDLE THUMB", "h" : "1D8CA"},
{"g" : "\u{1D8CB}", "n" : "SIGNWRITING HAND-FIST MIDDLE THUMB LITTLE", "h" : "1D8CB"},
{"g" : "\u{1D8CC}", "n" : "SIGNWRITING HAND-FIST MIDDLE LITTLE", "h" : "1D8CC"},
{"g" : "\u{1D8CD}", "n" : "SIGNWRITING HAND-FIST MIDDLE RING LITTLE", "h" : "1D8CD"},
{"g" : "\u{1D8CE}", "n" : "SIGNWRITING HAND-CIRCLE MIDDLE RING LITTLE", "h" : "1D8CE"},
{"g" : "\u{1D8CF}", "n" : "SIGNWRITING HAND-CURLICUE MIDDLE RING LITTLE ON", "h" : "1D8CF"},
{"g" : "\u{1D8D0}", "n" : "SIGNWRITING HAND-CUP MIDDLE RING LITTLE", "h" : "1D8D0"},
{"g" : "\u{1D8D1}", "n" : "SIGNWRITING HAND-HINGE MIDDLE RING LITTLE", "h" : "1D8D1"},
{"g" : "\u{1D8D2}", "n" : "SIGNWRITING HAND-ANGLE MIDDLE RING LITTLE OUT", "h" : "1D8D2"},
{"g" : "\u{1D8D3}", "n" : "SIGNWRITING HAND-ANGLE MIDDLE RING LITTLE IN", "h" : "1D8D3"},
{"g" : "\u{1D8D4}", "n" : "SIGNWRITING HAND-ANGLE MIDDLE RING LITTLE", "h" : "1D8D4"},
{"g" : "\u{1D8D5}", "n" : "SIGNWRITING HAND-CIRCLE MIDDLE RING LITTLE BENT", "h" : "1D8D5"},
{"g" : "\u{1D8D6}", "n" : "SIGNWRITING HAND-CLAW MIDDLE RING LITTLE CONJOINED", "h" : "1D8D6"},
{"g" : "\u{1D8D7}", "n" : "SIGNWRITING HAND-CLAW MIDDLE RING LITTLE CONJOINED SIDE", "h" : "1D8D7"},
{"g" : "\u{1D8D8}", "n" : "SIGNWRITING HAND-HOOK MIDDLE RING LITTLE CONJOINED OUT", "h" : "1D8D8"},
{"g" : "\u{1D8D9}", "n" : "SIGNWRITING HAND-HOOK MIDDLE RING LITTLE CONJOINED IN", "h" : "1D8D9"},
{"g" : "\u{1D8DA}", "n" : "SIGNWRITING HAND-HOOK MIDDLE RING LITTLE CONJOINED", "h" : "1D8DA"},
{"g" : "\u{1D8DB}", "n" : "SIGNWRITING HAND-HINGE INDEX HINGED", "h" : "1D8DB"},
{"g" : "\u{1D8DC}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB SIDE", "h" : "1D8DC"},
{"g" : "\u{1D8DD}", "n" : "SIGNWRITING HAND-HINGE INDEX THUMB SIDE", "h" : "1D8DD"},
{"g" : "\u{1D8DE}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB SIDE THUMB DIAGONAL", "h" : "1D8DE"},
{"g" : "\u{1D8DF}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB SIDE THUMB CONJOINED", "h" : "1D8DF"},
{"g" : "\u{1D8E0}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB SIDE THUMB BENT", "h" : "1D8E0"},
{"g" : "\u{1D8E1}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB SIDE INDEX BENT", "h" : "1D8E1"},
{"g" : "\u{1D8E2}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB SIDE BOTH BENT", "h" : "1D8E2"},
{"g" : "\u{1D8E3}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB SIDE INDEX HINGE", "h" : "1D8E3"},
{"g" : "\u{1D8E4}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB FORWARD INDEX STRAIGHT", "h" : "1D8E4"},
{"g" : "\u{1D8E5}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB FORWARD INDEX BENT", "h" : "1D8E5"},
{"g" : "\u{1D8E6}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB HOOK", "h" : "1D8E6"},
{"g" : "\u{1D8E7}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB CURLICUE", "h" : "1D8E7"},
{"g" : "\u{1D8E8}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB CURVE THUMB INSIDE", "h" : "1D8E8"},
{"g" : "\u{1D8E9}", "n" : "SIGNWRITING HAND-CLAW INDEX THUMB CURVE THUMB INSIDE", "h" : "1D8E9"},
{"g" : "\u{1D8EA}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB CURVE THUMB UNDER", "h" : "1D8EA"},
{"g" : "\u{1D8EB}", "n" : "SIGNWRITING HAND-FIST INDEX THUMB CIRCLE", "h" : "1D8EB"},
{"g" : "\u{1D8EC}", "n" : "SIGNWRITING HAND-CUP INDEX THUMB", "h" : "1D8EC"},
{"g" : "\u{1D8ED}", "n" : "SIGNWRITING HAND-CUP INDEX THUMB OPEN", "h" : "1D8ED"},
{"g" : "\u{1D8EE}", "n" : "SIGNWRITING HAND-HINGE INDEX THUMB OPEN", "h" : "1D8EE"},
{"g" : "\u{1D8EF}", "n" : "SIGNWRITING HAND-HINGE INDEX THUMB LARGE", "h" : "1D8EF"},
{"g" : "\u{1D8F0}", "n" : "SIGNWRITING HAND-HINGE INDEX THUMB", "h" : "1D8F0"},
{"g" : "\u{1D8F1}", "n" : "SIGNWRITING HAND-HINGE INDEX THUMB SMALL", "h" : "1D8F1"},
{"g" : "\u{1D8F2}", "n" : "SIGNWRITING HAND-ANGLE INDEX THUMB OUT", "h" : "1D8F2"},
{"g" : "\u{1D8F3}", "n" : "SIGNWRITING HAND-ANGLE INDEX THUMB IN", "h" : "1D8F3"},
{"g" : "\u{1D8F4}", "n" : "SIGNWRITING HAND-ANGLE INDEX THUMB", "h" : "1D8F4"},
{"g" : "\u{1D8F5}", "n" : "SIGNWRITING HAND-FIST THUMB", "h" : "1D8F5"},
{"g" : "\u{1D8F6}", "n" : "SIGNWRITING HAND-FIST THUMB HEEL", "h" : "1D8F6"},
{"g" : "\u{1D8F7}", "n" : "SIGNWRITING HAND-FIST THUMB SIDE DIAGONAL", "h" : "1D8F7"},
{"g" : "\u{1D8F8}", "n" : "SIGNWRITING HAND-FIST THUMB SIDE CONJOINED", "h" : "1D8F8"},
{"g" : "\u{1D8F9}", "n" : "SIGNWRITING HAND-FIST THUMB SIDE BENT", "h" : "1D8F9"},
{"g" : "\u{1D8FA}", "n" : "SIGNWRITING HAND-FIST THUMB FORWARD", "h" : "1D8FA"},
{"g" : "\u{1D8FB}", "n" : "SIGNWRITING HAND-FIST THUMB BETWEEN INDEX MIDDLE", "h" : "1D8FB"},
{"g" : "\u{1D8FC}", "n" : "SIGNWRITING HAND-FIST THUMB BETWEEN MIDDLE RING", "h" : "1D8FC"},
{"g" : "\u{1D8FD}", "n" : "SIGNWRITING HAND-FIST THUMB BETWEEN RING LITTLE", "h" : "1D8FD"},
{"g" : "\u{1D8FE}", "n" : "SIGNWRITING HAND-FIST THUMB UNDER TWO FINGERS", "h" : "1D8FE"},
{"g" : "\u{1D8FF}", "n" : "SIGNWRITING HAND-FIST THUMB OVER TWO FINGERS", "h" : "1D8FF"},
{"g" : "\u{1D900}", "n" : "SIGNWRITING HAND-FIST THUMB UNDER THREE FINGERS", "h" : "1D900"},
{"g" : "\u{1D901}", "n" : "SIGNWRITING HAND-FIST THUMB UNDER FOUR FINGERS", "h" : "1D901"},
{"g" : "\u{1D902}", "n" : "SIGNWRITING HAND-FIST THUMB OVER FOUR RAISED KNUCKLES", "h" : "1D902"},
{"g" : "\u{1D903}", "n" : "SIGNWRITING HAND-FIST", "h" : "1D903"},
{"g" : "\u{1D904}", "n" : "SIGNWRITING HAND-FIST HEEL", "h" : "1D904"},
{"g" : "\u{1D905}", "n" : "SIGNWRITING TOUCH SINGLE", "h" : "1D905"},
{"g" : "\u{1D906}", "n" : "SIGNWRITING TOUCH MULTIPLE", "h" : "1D906"},
{"g" : "\u{1D907}", "n" : "SIGNWRITING TOUCH BETWEEN", "h" : "1D907"},
{"g" : "\u{1D908}", "n" : "SIGNWRITING GRASP SINGLE", "h" : "1D908"},
{"g" : "\u{1D909}", "n" : "SIGNWRITING GRASP MULTIPLE", "h" : "1D909"},
{"g" : "\u{1D90A}", "n" : "SIGNWRITING GRASP BETWEEN", "h" : "1D90A"},
{"g" : "\u{1D90B}", "n" : "SIGNWRITING STRIKE SINGLE", "h" : "1D90B"},
{"g" : "\u{1D90C}", "n" : "SIGNWRITING STRIKE MULTIPLE", "h" : "1D90C"},
{"g" : "\u{1D90D}", "n" : "SIGNWRITING STRIKE BETWEEN", "h" : "1D90D"},
{"g" : "\u{1D90E}", "n" : "SIGNWRITING BRUSH SINGLE", "h" : "1D90E"},
{"g" : "\u{1D90F}", "n" : "SIGNWRITING BRUSH MULTIPLE", "h" : "1D90F"},
{"g" : "\u{1D910}", "n" : "SIGNWRITING BRUSH BETWEEN", "h" : "1D910"},
{"g" : "\u{1D911}", "n" : "SIGNWRITING RUB SINGLE", "h" : "1D911"},
{"g" : "\u{1D912}", "n" : "SIGNWRITING RUB MULTIPLE", "h" : "1D912"},
{"g" : "\u{1D913}", "n" : "SIGNWRITING RUB BETWEEN", "h" : "1D913"},
{"g" : "\u{1D914}", "n" : "SIGNWRITING SURFACE SYMBOLS", "h" : "1D914"},
{"g" : "\u{1D915}", "n" : "SIGNWRITING SURFACE BETWEEN", "h" : "1D915"},
{"g" : "\u{1D916}", "n" : "SIGNWRITING SQUEEZE LARGE SINGLE", "h" : "1D916"},
{"g" : "\u{1D917}", "n" : "SIGNWRITING SQUEEZE SMALL SINGLE", "h" : "1D917"},
{"g" : "\u{1D918}", "n" : "SIGNWRITING SQUEEZE LARGE MULTIPLE", "h" : "1D918"},
{"g" : "\u{1D919}", "n" : "SIGNWRITING SQUEEZE SMALL MULTIPLE", "h" : "1D919"},
{"g" : "\u{1D91A}", "n" : "SIGNWRITING SQUEEZE SEQUENTIAL", "h" : "1D91A"},
{"g" : "\u{1D91B}", "n" : "SIGNWRITING FLICK LARGE SINGLE", "h" : "1D91B"},
{"g" : "\u{1D91C}", "n" : "SIGNWRITING FLICK SMALL SINGLE", "h" : "1D91C"},
{"g" : "\u{1D91D}", "n" : "SIGNWRITING FLICK LARGE MULTIPLE", "h" : "1D91D"},
{"g" : "\u{1D91E}", "n" : "SIGNWRITING FLICK SMALL MULTIPLE", "h" : "1D91E"},
{"g" : "\u{1D91F}", "n" : "SIGNWRITING FLICK SEQUENTIAL", "h" : "1D91F"},
{"g" : "\u{1D920}", "n" : "SIGNWRITING SQUEEZE FLICK ALTERNATING", "h" : "1D920"},
{"g" : "\u{1D921}", "n" : "SIGNWRITING MOVEMENT-HINGE UP DOWN LARGE", "h" : "1D921"},
{"g" : "\u{1D922}", "n" : "SIGNWRITING MOVEMENT-HINGE UP DOWN SMALL", "h" : "1D922"},
{"g" : "\u{1D923}", "n" : "SIGNWRITING MOVEMENT-HINGE UP SEQUENTIAL", "h" : "1D923"},
{"g" : "\u{1D924}", "n" : "SIGNWRITING MOVEMENT-HINGE DOWN SEQUENTIAL", "h" : "1D924"},
{"g" : "\u{1D925}", "n" : "SIGNWRITING MOVEMENT-HINGE UP DOWN ALTERNATING LARGE", "h" : "1D925"},
{"g" : "\u{1D926}", "n" : "SIGNWRITING MOVEMENT-HINGE UP DOWN ALTERNATING SMALL", "h" : "1D926"},
{"g" : "\u{1D927}", "n" : "SIGNWRITING MOVEMENT-HINGE SIDE TO SIDE SCISSORS", "h" : "1D927"},
{"g" : "\u{1D928}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE FINGER CONTACT", "h" : "1D928"},
{"g" : "\u{1D929}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE FINGER CONTACT", "h" : "1D929"},
{"g" : "\u{1D92A}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT SMALL", "h" : "1D92A"},
{"g" : "\u{1D92B}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT MEDIUM", "h" : "1D92B"},
{"g" : "\u{1D92C}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT LARGE", "h" : "1D92C"},
{"g" : "\u{1D92D}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT LARGEST", "h" : "1D92D"},
{"g" : "\u{1D92E}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE SINGLE WRIST FLEX", "h" : "1D92E"},
{"g" : "\u{1D92F}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE DOUBLE STRAIGHT", "h" : "1D92F"},
{"g" : "\u{1D930}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE DOUBLE WRIST FLEX", "h" : "1D930"},
{"g" : "\u{1D931}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE DOUBLE ALTERNATING", "h" : "1D931"},
{"g" : "\u{1D932}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE DOUBLE ALTERNATING WRIST FLEX", "h" : "1D932"},
{"g" : "\u{1D933}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CROSS", "h" : "1D933"},
{"g" : "\u{1D934}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE TRIPLE STRAIGHT MOVEMENT", "h" : "1D934"},
{"g" : "\u{1D935}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE TRIPLE WRIST FLEX", "h" : "1D935"},
{"g" : "\u{1D936}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE TRIPLE ALTERNATING", "h" : "1D936"},
{"g" : "\u{1D937}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE TRIPLE ALTERNATING WRIST FLEX", "h" : "1D937"},
{"g" : "\u{1D938}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE BEND SMALL", "h" : "1D938"},
{"g" : "\u{1D939}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE BEND MEDIUM", "h" : "1D939"},
{"g" : "\u{1D93A}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE BEND LARGE", "h" : "1D93A"},
{"g" : "\u{1D93B}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CORNER SMALL", "h" : "1D93B"},
{"g" : "\u{1D93C}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CORNER MEDIUM", "h" : "1D93C"},
{"g" : "\u{1D93D}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CORNER LARGE", "h" : "1D93D"},
{"g" : "\u{1D93E}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CORNER ROTATION", "h" : "1D93E"},
{"g" : "\u{1D93F}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CHECK SMALL", "h" : "1D93F"},
{"g" : "\u{1D940}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CHECK MEDIUM", "h" : "1D940"},
{"g" : "\u{1D941}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CHECK LARGE", "h" : "1D941"},
{"g" : "\u{1D942}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE BOX SMALL", "h" : "1D942"},
{"g" : "\u{1D943}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE BOX MEDIUM", "h" : "1D943"},
{"g" : "\u{1D944}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE BOX LARGE", "h" : "1D944"},
{"g" : "\u{1D945}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE ZIGZAG SMALL", "h" : "1D945"},
{"g" : "\u{1D946}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE ZIGZAG MEDIUM", "h" : "1D946"},
{"g" : "\u{1D947}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE ZIGZAG LARGE", "h" : "1D947"},
{"g" : "\u{1D948}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE PEAKS SMALL", "h" : "1D948"},
{"g" : "\u{1D949}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE PEAKS MEDIUM", "h" : "1D949"},
{"g" : "\u{1D94A}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE PEAKS LARGE", "h" : "1D94A"},
{"g" : "\u{1D94B}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ROTATION-WALLPLANE SINGLE", "h" : "1D94B"},
{"g" : "\u{1D94C}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ROTATION-WALLPLANE DOUBLE", "h" : "1D94C"},
{"g" : "\u{1D94D}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ROTATION-WALLPLANE ALTERNATING", "h" : "1D94D"},
{"g" : "\u{1D94E}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ROTATION-FLOORPLANE SINGLE", "h" : "1D94E"},
{"g" : "\u{1D94F}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ROTATION-FLOORPLANE DOUBLE", "h" : "1D94F"},
{"g" : "\u{1D950}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ROTATION-FLOORPLANE ALTERNATING", "h" : "1D950"},
{"g" : "\u{1D951}", "n" : "SIGNWRITING TRAVEL-WALLPLANE SHAKING", "h" : "1D951"},
{"g" : "\u{1D952}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ARM SPIRAL SINGLE", "h" : "1D952"},
{"g" : "\u{1D953}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ARM SPIRAL DOUBLE", "h" : "1D953"},
{"g" : "\u{1D954}", "n" : "SIGNWRITING TRAVEL-WALLPLANE ARM SPIRAL TRIPLE", "h" : "1D954"},
{"g" : "\u{1D955}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL AWAY SMALL", "h" : "1D955"},
{"g" : "\u{1D956}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL AWAY MEDIUM", "h" : "1D956"},
{"g" : "\u{1D957}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL AWAY LARGE", "h" : "1D957"},
{"g" : "\u{1D958}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL AWAY LARGEST", "h" : "1D958"},
{"g" : "\u{1D959}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL TOWARDS SMALL", "h" : "1D959"},
{"g" : "\u{1D95A}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL TOWARDS MEDIUM", "h" : "1D95A"},
{"g" : "\u{1D95B}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL TOWARDS LARGE", "h" : "1D95B"},
{"g" : "\u{1D95C}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL TOWARDS LARGEST", "h" : "1D95C"},
{"g" : "\u{1D95D}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY SMALL", "h" : "1D95D"},
{"g" : "\u{1D95E}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY MEDIUM", "h" : "1D95E"},
{"g" : "\u{1D95F}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY LARGE", "h" : "1D95F"},
{"g" : "\u{1D960}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY LARGEST", "h" : "1D960"},
{"g" : "\u{1D961}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS SMALL", "h" : "1D961"},
{"g" : "\u{1D962}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS MEDIUM", "h" : "1D962"},
{"g" : "\u{1D963}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS LARGE", "h" : "1D963"},
{"g" : "\u{1D964}", "n" : "SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS LARGEST", "h" : "1D964"},
{"g" : "\u{1D965}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT SMALL", "h" : "1D965"},
{"g" : "\u{1D966}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT MEDIUM", "h" : "1D966"},
{"g" : "\u{1D967}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT LARGE", "h" : "1D967"},
{"g" : "\u{1D968}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT LARGEST", "h" : "1D968"},
{"g" : "\u{1D969}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE SINGLE WRIST FLEX", "h" : "1D969"},
{"g" : "\u{1D96A}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE STRAIGHT", "h" : "1D96A"},
{"g" : "\u{1D96B}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE WRIST FLEX", "h" : "1D96B"},
{"g" : "\u{1D96C}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE ALTERNATING", "h" : "1D96C"},
{"g" : "\u{1D96D}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE ALTERNATING WRIST FLEX", "h" : "1D96D"},
{"g" : "\u{1D96E}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CROSS", "h" : "1D96E"},
{"g" : "\u{1D96F}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE STRAIGHT MOVEMENT", "h" : "1D96F"},
{"g" : "\u{1D970}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE WRIST FLEX", "h" : "1D970"},
{"g" : "\u{1D971}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE ALTERNATING MOVEMENT", "h" : "1D971"},
{"g" : "\u{1D972}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE ALTERNATING WRIST FLEX", "h" : "1D972"},
{"g" : "\u{1D973}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE BEND", "h" : "1D973"},
{"g" : "\u{1D974}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CORNER SMALL", "h" : "1D974"},
{"g" : "\u{1D975}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CORNER MEDIUM", "h" : "1D975"},
{"g" : "\u{1D976}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CORNER LARGE", "h" : "1D976"},
{"g" : "\u{1D977}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CHECK", "h" : "1D977"},
{"g" : "\u{1D978}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE BOX SMALL", "h" : "1D978"},
{"g" : "\u{1D979}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE BOX MEDIUM", "h" : "1D979"},
{"g" : "\u{1D97A}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE BOX LARGE", "h" : "1D97A"},
{"g" : "\u{1D97B}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ZIGZAG SMALL", "h" : "1D97B"},
{"g" : "\u{1D97C}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ZIGZAG MEDIUM", "h" : "1D97C"},
{"g" : "\u{1D97D}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ZIGZAG LARGE", "h" : "1D97D"},
{"g" : "\u{1D97E}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE PEAKS SMALL", "h" : "1D97E"},
{"g" : "\u{1D97F}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE PEAKS MEDIUM", "h" : "1D97F"},
{"g" : "\u{1D980}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE PEAKS LARGE", "h" : "1D980"},
{"g" : "\u{1D981}", "n" : "SIGNWRITING TRAVEL-FLOORPLANE ROTATION-FLOORPLANE SINGLE", "h" : "1D981"},
{"g" : "\u{1D982}", "n" : "SIGNWRITING TRAVEL-FLOORPLANE ROTATION-FLOORPLANE DOUBLE", "h" : "1D982"},
{"g" : "\u{1D983}", "n" : "SIGNWRITING TRAVEL-FLOORPLANE ROTATION-FLOORPLANE ALTERNATING", "h" : "1D983"},
{"g" : "\u{1D984}", "n" : "SIGNWRITING TRAVEL-FLOORPLANE ROTATION-WALLPLANE SINGLE", "h" : "1D984"},
{"g" : "\u{1D985}", "n" : "SIGNWRITING TRAVEL-FLOORPLANE ROTATION-WALLPLANE DOUBLE", "h" : "1D985"},
{"g" : "\u{1D986}", "n" : "SIGNWRITING TRAVEL-FLOORPLANE ROTATION-WALLPLANE ALTERNATING", "h" : "1D986"},
{"g" : "\u{1D987}", "n" : "SIGNWRITING TRAVEL-FLOORPLANE SHAKING", "h" : "1D987"},
{"g" : "\u{1D988}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER SMALL", "h" : "1D988"},
{"g" : "\u{1D989}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER MEDIUM", "h" : "1D989"},
{"g" : "\u{1D98A}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER LARGE", "h" : "1D98A"},
{"g" : "\u{1D98B}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER LARGEST", "h" : "1D98B"},
{"g" : "\u{1D98C}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE SMALL", "h" : "1D98C"},
{"g" : "\u{1D98D}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE MEDIUM", "h" : "1D98D"},
{"g" : "\u{1D98E}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE LARGE", "h" : "1D98E"},
{"g" : "\u{1D98F}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE LARGEST", "h" : "1D98F"},
{"g" : "\u{1D990}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE THREE-QUARTER CIRCLE SMALL", "h" : "1D990"},
{"g" : "\u{1D991}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE THREE-QUARTER CIRCLE MEDIUM", "h" : "1D991"},
{"g" : "\u{1D992}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE HUMP SMALL", "h" : "1D992"},
{"g" : "\u{1D993}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE HUMP MEDIUM", "h" : "1D993"},
{"g" : "\u{1D994}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE HUMP LARGE", "h" : "1D994"},
{"g" : "\u{1D995}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE LOOP SMALL", "h" : "1D995"},
{"g" : "\u{1D996}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE LOOP MEDIUM", "h" : "1D996"},
{"g" : "\u{1D997}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE LOOP LARGE", "h" : "1D997"},
{"g" : "\u{1D998}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE LOOP SMALL DOUBLE", "h" : "1D998"},
{"g" : "\u{1D999}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE DOUBLE SMALL", "h" : "1D999"},
{"g" : "\u{1D99A}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE DOUBLE MEDIUM", "h" : "1D99A"},
{"g" : "\u{1D99B}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE DOUBLE LARGE", "h" : "1D99B"},
{"g" : "\u{1D99C}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE TRIPLE SMALL", "h" : "1D99C"},
{"g" : "\u{1D99D}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE TRIPLE MEDIUM", "h" : "1D99D"},
{"g" : "\u{1D99E}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE TRIPLE LARGE", "h" : "1D99E"},
{"g" : "\u{1D99F}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE THEN STRAIGHT", "h" : "1D99F"},
{"g" : "\u{1D9A0}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVED CROSS SMALL", "h" : "1D9A0"},
{"g" : "\u{1D9A1}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVED CROSS MEDIUM", "h" : "1D9A1"},
{"g" : "\u{1D9A2}", "n" : "SIGNWRITING ROTATION-WALLPLANE SINGLE", "h" : "1D9A2"},
{"g" : "\u{1D9A3}", "n" : "SIGNWRITING ROTATION-WALLPLANE DOUBLE", "h" : "1D9A3"},
{"g" : "\u{1D9A4}", "n" : "SIGNWRITING ROTATION-WALLPLANE ALTERNATE", "h" : "1D9A4"},
{"g" : "\u{1D9A5}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE SHAKING", "h" : "1D9A5"},
{"g" : "\u{1D9A6}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE HITTING FRONT WALL", "h" : "1D9A6"},
{"g" : "\u{1D9A7}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE HUMP HITTING FRONT WALL", "h" : "1D9A7"},
{"g" : "\u{1D9A8}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE LOOP HITTING FRONT WALL", "h" : "1D9A8"},
{"g" : "\u{1D9A9}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE HITTING FRONT WALL", "h" : "1D9A9"},
{"g" : "\u{1D9AA}", "n" : "SIGNWRITING ROTATION-WALLPLANE SINGLE HITTING FRONT WALL", "h" : "1D9AA"},
{"g" : "\u{1D9AB}", "n" : "SIGNWRITING ROTATION-WALLPLANE DOUBLE HITTING FRONT WALL", "h" : "1D9AB"},
{"g" : "\u{1D9AC}", "n" : "SIGNWRITING ROTATION-WALLPLANE ALTERNATING HITTING FRONT WALL", "h" : "1D9AC"},
{"g" : "\u{1D9AD}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE CURVE HITTING CHEST", "h" : "1D9AD"},
{"g" : "\u{1D9AE}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE HUMP HITTING CHEST", "h" : "1D9AE"},
{"g" : "\u{1D9AF}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE LOOP HITTING CHEST", "h" : "1D9AF"},
{"g" : "\u{1D9B0}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE HITTING CHEST", "h" : "1D9B0"},
{"g" : "\u{1D9B1}", "n" : "SIGNWRITING ROTATION-WALLPLANE SINGLE HITTING CHEST", "h" : "1D9B1"},
{"g" : "\u{1D9B2}", "n" : "SIGNWRITING ROTATION-WALLPLANE DOUBLE HITTING CHEST", "h" : "1D9B2"},
{"g" : "\u{1D9B3}", "n" : "SIGNWRITING ROTATION-WALLPLANE ALTERNATING HITTING CHEST", "h" : "1D9B3"},
{"g" : "\u{1D9B4}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE DIAGONAL PATH SMALL", "h" : "1D9B4"},
{"g" : "\u{1D9B5}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE DIAGONAL PATH MEDIUM", "h" : "1D9B5"},
{"g" : "\u{1D9B6}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WAVE DIAGONAL PATH LARGE", "h" : "1D9B6"},
{"g" : "\u{1D9B7}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING CEILING SMALL", "h" : "1D9B7"},
{"g" : "\u{1D9B8}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING CEILING LARGE", "h" : "1D9B8"},
{"g" : "\u{1D9B9}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING SMALL DOUBLE", "h" : "1D9B9"},
{"g" : "\u{1D9BA}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING LARGE DOUBLE", "h" : "1D9BA"},
{"g" : "\u{1D9BB}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING SMALL TRIPLE", "h" : "1D9BB"},
{"g" : "\u{1D9BC}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING LARGE TRIPLE", "h" : "1D9BC"},
{"g" : "\u{1D9BD}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING SMALL SINGLE", "h" : "1D9BD"},
{"g" : "\u{1D9BE}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING LARGE SINGLE", "h" : "1D9BE"},
{"g" : "\u{1D9BF}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING SMALL DOUBLE", "h" : "1D9BF"},
{"g" : "\u{1D9C0}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING LARGE DOUBLE", "h" : "1D9C0"},
{"g" : "\u{1D9C1}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING CEILING SMALL", "h" : "1D9C1"},
{"g" : "\u{1D9C2}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING CEILING LARGE", "h" : "1D9C2"},
{"g" : "\u{1D9C3}", "n" : "SIGNWRITING ROTATION-FLOORPLANE SINGLE HITTING CEILING", "h" : "1D9C3"},
{"g" : "\u{1D9C4}", "n" : "SIGNWRITING ROTATION-FLOORPLANE DOUBLE HITTING CEILING", "h" : "1D9C4"},
{"g" : "\u{1D9C5}", "n" : "SIGNWRITING ROTATION-FLOORPLANE ALTERNATING HITTING CEILING", "h" : "1D9C5"},
{"g" : "\u{1D9C6}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING FLOOR SMALL", "h" : "1D9C6"},
{"g" : "\u{1D9C7}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING FLOOR LARGE", "h" : "1D9C7"},
{"g" : "\u{1D9C8}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR SMALL DOUBLE", "h" : "1D9C8"},
{"g" : "\u{1D9C9}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR LARGE DOUBLE", "h" : "1D9C9"},
{"g" : "\u{1D9CA}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR TRIPLE SMALL TRIPLE", "h" : "1D9CA"},
{"g" : "\u{1D9CB}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR TRIPLE LARGE TRIPLE", "h" : "1D9CB"},
{"g" : "\u{1D9CC}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR SMALL SINGLE", "h" : "1D9CC"},
{"g" : "\u{1D9CD}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR LARGE SINGLE", "h" : "1D9CD"},
{"g" : "\u{1D9CE}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR SMALL DOUBLE", "h" : "1D9CE"},
{"g" : "\u{1D9CF}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR LARGE DOUBLE", "h" : "1D9CF"},
{"g" : "\u{1D9D0}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING FLOOR SMALL", "h" : "1D9D0"},
{"g" : "\u{1D9D1}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING FLOOR LARGE", "h" : "1D9D1"},
{"g" : "\u{1D9D2}", "n" : "SIGNWRITING ROTATION-FLOORPLANE SINGLE HITTING FLOOR", "h" : "1D9D2"},
{"g" : "\u{1D9D3}", "n" : "SIGNWRITING ROTATION-FLOORPLANE DOUBLE HITTING FLOOR", "h" : "1D9D3"},
{"g" : "\u{1D9D4}", "n" : "SIGNWRITING ROTATION-FLOORPLANE ALTERNATING HITTING FLOOR", "h" : "1D9D4"},
{"g" : "\u{1D9D5}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE SMALL", "h" : "1D9D5"},
{"g" : "\u{1D9D6}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE MEDIUM", "h" : "1D9D6"},
{"g" : "\u{1D9D7}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE LARGE", "h" : "1D9D7"},
{"g" : "\u{1D9D8}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE LARGEST", "h" : "1D9D8"},
{"g" : "\u{1D9D9}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE CURVE COMBINED", "h" : "1D9D9"},
{"g" : "\u{1D9DA}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE HUMP SMALL", "h" : "1D9DA"},
{"g" : "\u{1D9DB}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE LOOP SMALL", "h" : "1D9DB"},
{"g" : "\u{1D9DC}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WAVE SNAKE", "h" : "1D9DC"},
{"g" : "\u{1D9DD}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WAVE SMALL", "h" : "1D9DD"},
{"g" : "\u{1D9DE}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WAVE LARGE", "h" : "1D9DE"},
{"g" : "\u{1D9DF}", "n" : "SIGNWRITING ROTATION-FLOORPLANE SINGLE", "h" : "1D9DF"},
{"g" : "\u{1D9E0}", "n" : "SIGNWRITING ROTATION-FLOORPLANE DOUBLE", "h" : "1D9E0"},
{"g" : "\u{1D9E1}", "n" : "SIGNWRITING ROTATION-FLOORPLANE ALTERNATING", "h" : "1D9E1"},
{"g" : "\u{1D9E2}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE SHAKING PARALLEL", "h" : "1D9E2"},
{"g" : "\u{1D9E3}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE SMALL SINGLE", "h" : "1D9E3"},
{"g" : "\u{1D9E4}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE MEDIUM SINGLE", "h" : "1D9E4"},
{"g" : "\u{1D9E5}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE SMALL DOUBLE", "h" : "1D9E5"},
{"g" : "\u{1D9E6}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE MEDIUM DOUBLE", "h" : "1D9E6"},
{"g" : "\u{1D9E7}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL SMALL SINGLE", "h" : "1D9E7"},
{"g" : "\u{1D9E8}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL MEDIUM SINGLE", "h" : "1D9E8"},
{"g" : "\u{1D9E9}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL LARGE SINGLE", "h" : "1D9E9"},
{"g" : "\u{1D9EA}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL SMALL DOUBLE", "h" : "1D9EA"},
{"g" : "\u{1D9EB}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL MEDIUM DOUBLE", "h" : "1D9EB"},
{"g" : "\u{1D9EC}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL LARGE DOUBLE", "h" : "1D9EC"},
{"g" : "\u{1D9ED}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WRIST CIRCLE FRONT SINGLE", "h" : "1D9ED"},
{"g" : "\u{1D9EE}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE WRIST CIRCLE FRONT DOUBLE", "h" : "1D9EE"},
{"g" : "\u{1D9EF}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WRIST CIRCLE HITTING WALL SINGLE", "h" : "1D9EF"},
{"g" : "\u{1D9F0}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE WRIST CIRCLE HITTING WALL DOUBLE", "h" : "1D9F0"},
{"g" : "\u{1D9F1}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE FINGER CIRCLES SINGLE", "h" : "1D9F1"},
{"g" : "\u{1D9F2}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE FINGER CIRCLES DOUBLE", "h" : "1D9F2"},
{"g" : "\u{1D9F3}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE FINGER CIRCLES HITTING WALL SINGLE", "h" : "1D9F3"},
{"g" : "\u{1D9F4}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE FINGER CIRCLES HITTING WALL DOUBLE", "h" : "1D9F4"},
{"g" : "\u{1D9F5}", "n" : "SIGNWRITING DYNAMIC ARROWHEAD SMALL", "h" : "1D9F5"},
{"g" : "\u{1D9F6}", "n" : "SIGNWRITING DYNAMIC ARROWHEAD LARGE", "h" : "1D9F6"},
{"g" : "\u{1D9F7}", "n" : "SIGNWRITING DYNAMIC FAST", "h" : "1D9F7"},
{"g" : "\u{1D9F8}", "n" : "SIGNWRITING DYNAMIC SLOW", "h" : "1D9F8"},
{"g" : "\u{1D9F9}", "n" : "SIGNWRITING DYNAMIC TENSE", "h" : "1D9F9"},
{"g" : "\u{1D9FA}", "n" : "SIGNWRITING DYNAMIC RELAXED", "h" : "1D9FA"},
{"g" : "\u{1D9FB}", "n" : "SIGNWRITING DYNAMIC SIMULTANEOUS", "h" : "1D9FB"},
{"g" : "\u{1D9FC}", "n" : "SIGNWRITING DYNAMIC SIMULTANEOUS ALTERNATING", "h" : "1D9FC"},
{"g" : "\u{1D9FD}", "n" : "SIGNWRITING DYNAMIC EVERY OTHER TIME", "h" : "1D9FD"},
{"g" : "\u{1D9FE}", "n" : "SIGNWRITING DYNAMIC GRADUAL", "h" : "1D9FE"},
{"g" : "\u{1D9FF}", "n" : "SIGNWRITING HEAD", "h" : "1D9FF"},
{"g" : "\u{1DA00}", "n" : "SIGNWRITING HEAD RIM", "h" : "1DA00"},
{"g" : "\u{1DA01}", "n" : "SIGNWRITING HEAD MOVEMENT-WALLPLANE STRAIGHT", "h" : "1DA01"},
{"g" : "\u{1DA02}", "n" : "SIGNWRITING HEAD MOVEMENT-WALLPLANE TILT", "h" : "1DA02"},
{"g" : "\u{1DA03}", "n" : "SIGNWRITING HEAD MOVEMENT-FLOORPLANE STRAIGHT", "h" : "1DA03"},
{"g" : "\u{1DA04}", "n" : "SIGNWRITING HEAD MOVEMENT-WALLPLANE CURVE", "h" : "1DA04"},
{"g" : "\u{1DA05}", "n" : "SIGNWRITING HEAD MOVEMENT-FLOORPLANE CURVE", "h" : "1DA05"},
{"g" : "\u{1DA06}", "n" : "SIGNWRITING HEAD MOVEMENT CIRCLE", "h" : "1DA06"},
{"g" : "\u{1DA07}", "n" : "SIGNWRITING FACE DIRECTION POSITION NOSE FORWARD TILTING", "h" : "1DA07"},
{"g" : "\u{1DA08}", "n" : "SIGNWRITING FACE DIRECTION POSITION NOSE UP OR DOWN", "h" : "1DA08"},
{"g" : "\u{1DA09}", "n" : "SIGNWRITING FACE DIRECTION POSITION NOSE UP OR DOWN TILTING", "h" : "1DA09"},
{"g" : "\u{1DA0A}", "n" : "SIGNWRITING EYEBROWS STRAIGHT UP", "h" : "1DA0A"},
{"g" : "\u{1DA0B}", "n" : "SIGNWRITING EYEBROWS STRAIGHT NEUTRAL", "h" : "1DA0B"},
{"g" : "\u{1DA0C}", "n" : "SIGNWRITING EYEBROWS STRAIGHT DOWN", "h" : "1DA0C"},
{"g" : "\u{1DA0D}", "n" : "SIGNWRITING DREAMY EYEBROWS NEUTRAL DOWN", "h" : "1DA0D"},
{"g" : "\u{1DA0E}", "n" : "SIGNWRITING DREAMY EYEBROWS DOWN NEUTRAL", "h" : "1DA0E"},
{"g" : "\u{1DA0F}", "n" : "SIGNWRITING DREAMY EYEBROWS UP NEUTRAL", "h" : "1DA0F"},
{"g" : "\u{1DA10}", "n" : "SIGNWRITING DREAMY EYEBROWS NEUTRAL UP", "h" : "1DA10"},
{"g" : "\u{1DA11}", "n" : "SIGNWRITING FOREHEAD NEUTRAL", "h" : "1DA11"},
{"g" : "\u{1DA12}", "n" : "SIGNWRITING FOREHEAD CONTACT", "h" : "1DA12"},
{"g" : "\u{1DA13}", "n" : "SIGNWRITING FOREHEAD WRINKLED", "h" : "1DA13"},
{"g" : "\u{1DA14}", "n" : "SIGNWRITING EYES OPEN", "h" : "1DA14"},
{"g" : "\u{1DA15}", "n" : "SIGNWRITING EYES SQUEEZED", "h" : "1DA15"},
{"g" : "\u{1DA16}", "n" : "SIGNWRITING EYES CLOSED", "h" : "1DA16"},
{"g" : "\u{1DA17}", "n" : "SIGNWRITING EYE BLINK SINGLE", "h" : "1DA17"},
{"g" : "\u{1DA18}", "n" : "SIGNWRITING EYE BLINK MULTIPLE", "h" : "1DA18"},
{"g" : "\u{1DA19}", "n" : "SIGNWRITING EYES HALF OPEN", "h" : "1DA19"},
{"g" : "\u{1DA1A}", "n" : "SIGNWRITING EYES WIDE OPEN", "h" : "1DA1A"},
{"g" : "\u{1DA1B}", "n" : "SIGNWRITING EYES HALF CLOSED", "h" : "1DA1B"},
{"g" : "\u{1DA1C}", "n" : "SIGNWRITING EYES WIDENING MOVEMENT", "h" : "1DA1C"},
{"g" : "\u{1DA1D}", "n" : "SIGNWRITING EYE WINK", "h" : "1DA1D"},
{"g" : "\u{1DA1E}", "n" : "SIGNWRITING EYELASHES UP", "h" : "1DA1E"},
{"g" : "\u{1DA1F}", "n" : "SIGNWRITING EYELASHES DOWN", "h" : "1DA1F"},
{"g" : "\u{1DA20}", "n" : "SIGNWRITING EYELASHES FLUTTERING", "h" : "1DA20"},
{"g" : "\u{1DA21}", "n" : "SIGNWRITING EYEGAZE-WALLPLANE STRAIGHT", "h" : "1DA21"},
{"g" : "\u{1DA22}", "n" : "SIGNWRITING EYEGAZE-WALLPLANE STRAIGHT DOUBLE", "h" : "1DA22"},
{"g" : "\u{1DA23}", "n" : "SIGNWRITING EYEGAZE-WALLPLANE STRAIGHT ALTERNATING", "h" : "1DA23"},
{"g" : "\u{1DA24}", "n" : "SIGNWRITING EYEGAZE-FLOORPLANE STRAIGHT", "h" : "1DA24"},
{"g" : "\u{1DA25}", "n" : "SIGNWRITING EYEGAZE-FLOORPLANE STRAIGHT DOUBLE", "h" : "1DA25"},
{"g" : "\u{1DA26}", "n" : "SIGNWRITING EYEGAZE-FLOORPLANE STRAIGHT ALTERNATING", "h" : "1DA26"},
{"g" : "\u{1DA27}", "n" : "SIGNWRITING EYEGAZE-WALLPLANE CURVED", "h" : "1DA27"},
{"g" : "\u{1DA28}", "n" : "SIGNWRITING EYEGAZE-FLOORPLANE CURVED", "h" : "1DA28"},
{"g" : "\u{1DA29}", "n" : "SIGNWRITING EYEGAZE-WALLPLANE CIRCLING", "h" : "1DA29"},
{"g" : "\u{1DA2A}", "n" : "SIGNWRITING CHEEKS PUFFED", "h" : "1DA2A"},
{"g" : "\u{1DA2B}", "n" : "SIGNWRITING CHEEKS NEUTRAL", "h" : "1DA2B"},
{"g" : "\u{1DA2C}", "n" : "SIGNWRITING CHEEKS SUCKED", "h" : "1DA2C"},
{"g" : "\u{1DA2D}", "n" : "SIGNWRITING TENSE CHEEKS HIGH", "h" : "1DA2D"},
{"g" : "\u{1DA2E}", "n" : "SIGNWRITING TENSE CHEEKS MIDDLE", "h" : "1DA2E"},
{"g" : "\u{1DA2F}", "n" : "SIGNWRITING TENSE CHEEKS LOW", "h" : "1DA2F"},
{"g" : "\u{1DA30}", "n" : "SIGNWRITING EARS", "h" : "1DA30"},
{"g" : "\u{1DA31}", "n" : "SIGNWRITING NOSE NEUTRAL", "h" : "1DA31"},
{"g" : "\u{1DA32}", "n" : "SIGNWRITING NOSE CONTACT", "h" : "1DA32"},
{"g" : "\u{1DA33}", "n" : "SIGNWRITING NOSE WRINKLES", "h" : "1DA33"},
{"g" : "\u{1DA34}", "n" : "SIGNWRITING NOSE WIGGLES", "h" : "1DA34"},
{"g" : "\u{1DA35}", "n" : "SIGNWRITING AIR BLOWING OUT", "h" : "1DA35"},
{"g" : "\u{1DA36}", "n" : "SIGNWRITING AIR SUCKING IN", "h" : "1DA36"},
{"g" : "\u{1DA37}", "n" : "SIGNWRITING AIR BLOW SMALL ROTATIONS", "h" : "1DA37"},
{"g" : "\u{1DA38}", "n" : "SIGNWRITING AIR SUCK SMALL ROTATIONS", "h" : "1DA38"},
{"g" : "\u{1DA39}", "n" : "SIGNWRITING BREATH INHALE", "h" : "1DA39"},
{"g" : "\u{1DA3A}", "n" : "SIGNWRITING BREATH EXHALE", "h" : "1DA3A"},
{"g" : "\u{1DA3B}", "n" : "SIGNWRITING MOUTH CLOSED NEUTRAL", "h" : "1DA3B"},
{"g" : "\u{1DA3C}", "n" : "SIGNWRITING MOUTH CLOSED FORWARD", "h" : "1DA3C"},
{"g" : "\u{1DA3D}", "n" : "SIGNWRITING MOUTH CLOSED CONTACT", "h" : "1DA3D"},
{"g" : "\u{1DA3E}", "n" : "SIGNWRITING MOUTH SMILE", "h" : "1DA3E"},
{"g" : "\u{1DA3F}", "n" : "SIGNWRITING MOUTH SMILE WRINKLED", "h" : "1DA3F"},
{"g" : "\u{1DA40}", "n" : "SIGNWRITING MOUTH SMILE OPEN", "h" : "1DA40"},
{"g" : "\u{1DA41}", "n" : "SIGNWRITING MOUTH FROWN", "h" : "1DA41"},
{"g" : "\u{1DA42}", "n" : "SIGNWRITING MOUTH FROWN WRINKLED", "h" : "1DA42"},
{"g" : "\u{1DA43}", "n" : "SIGNWRITING MOUTH FROWN OPEN", "h" : "1DA43"},
{"g" : "\u{1DA44}", "n" : "SIGNWRITING MOUTH OPEN CIRCLE", "h" : "1DA44"},
{"g" : "\u{1DA45}", "n" : "SIGNWRITING MOUTH OPEN FORWARD", "h" : "1DA45"},
{"g" : "\u{1DA46}", "n" : "SIGNWRITING MOUTH OPEN WRINKLED", "h" : "1DA46"},
{"g" : "\u{1DA47}", "n" : "SIGNWRITING MOUTH OPEN OVAL", "h" : "1DA47"},
{"g" : "\u{1DA48}", "n" : "SIGNWRITING MOUTH OPEN OVAL WRINKLED", "h" : "1DA48"},
{"g" : "\u{1DA49}", "n" : "SIGNWRITING MOUTH OPEN OVAL YAWN", "h" : "1DA49"},
{"g" : "\u{1DA4A}", "n" : "SIGNWRITING MOUTH OPEN RECTANGLE", "h" : "1DA4A"},
{"g" : "\u{1DA4B}", "n" : "SIGNWRITING MOUTH OPEN RECTANGLE WRINKLED", "h" : "1DA4B"},
{"g" : "\u{1DA4C}", "n" : "SIGNWRITING MOUTH OPEN RECTANGLE YAWN", "h" : "1DA4C"},
{"g" : "\u{1DA4D}", "n" : "SIGNWRITING MOUTH KISS", "h" : "1DA4D"},
{"g" : "\u{1DA4E}", "n" : "SIGNWRITING MOUTH KISS FORWARD", "h" : "1DA4E"},
{"g" : "\u{1DA4F}", "n" : "SIGNWRITING MOUTH KISS WRINKLED", "h" : "1DA4F"},
{"g" : "\u{1DA50}", "n" : "SIGNWRITING MOUTH TENSE", "h" : "1DA50"},
{"g" : "\u{1DA51}", "n" : "SIGNWRITING MOUTH TENSE FORWARD", "h" : "1DA51"},
{"g" : "\u{1DA52}", "n" : "SIGNWRITING MOUTH TENSE SUCKED", "h" : "1DA52"},
{"g" : "\u{1DA53}", "n" : "SIGNWRITING LIPS PRESSED TOGETHER", "h" : "1DA53"},
{"g" : "\u{1DA54}", "n" : "SIGNWRITING LIP LOWER OVER UPPER", "h" : "1DA54"},
{"g" : "\u{1DA55}", "n" : "SIGNWRITING LIP UPPER OVER LOWER", "h" : "1DA55"},
{"g" : "\u{1DA56}", "n" : "SIGNWRITING MOUTH CORNERS", "h" : "1DA56"},
{"g" : "\u{1DA57}", "n" : "SIGNWRITING MOUTH WRINKLES SINGLE", "h" : "1DA57"},
{"g" : "\u{1DA58}", "n" : "SIGNWRITING MOUTH WRINKLES DOUBLE", "h" : "1DA58"},
{"g" : "\u{1DA59}", "n" : "SIGNWRITING TONGUE STICKING OUT FAR", "h" : "1DA59"},
{"g" : "\u{1DA5A}", "n" : "SIGNWRITING TONGUE LICKING LIPS", "h" : "1DA5A"},
{"g" : "\u{1DA5B}", "n" : "SIGNWRITING TONGUE TIP BETWEEN LIPS", "h" : "1DA5B"},
{"g" : "\u{1DA5C}", "n" : "SIGNWRITING TONGUE TIP TOUCHING INSIDE MOUTH", "h" : "1DA5C"},
{"g" : "\u{1DA5D}", "n" : "SIGNWRITING TONGUE INSIDE MOUTH RELAXED", "h" : "1DA5D"},
{"g" : "\u{1DA5E}", "n" : "SIGNWRITING TONGUE MOVES AGAINST CHEEK", "h" : "1DA5E"},
{"g" : "\u{1DA5F}", "n" : "SIGNWRITING TONGUE CENTRE STICKING OUT", "h" : "1DA5F"},
{"g" : "\u{1DA60}", "n" : "SIGNWRITING TONGUE CENTRE INSIDE MOUTH", "h" : "1DA60"},
{"g" : "\u{1DA61}", "n" : "SIGNWRITING TEETH", "h" : "1DA61"},
{"g" : "\u{1DA62}", "n" : "SIGNWRITING TEETH MOVEMENT", "h" : "1DA62"},
{"g" : "\u{1DA63}", "n" : "SIGNWRITING TEETH ON TONGUE", "h" : "1DA63"},
{"g" : "\u{1DA64}", "n" : "SIGNWRITING TEETH ON TONGUE MOVEMENT", "h" : "1DA64"},
{"g" : "\u{1DA65}", "n" : "SIGNWRITING TEETH ON LIPS", "h" : "1DA65"},
{"g" : "\u{1DA66}", "n" : "SIGNWRITING TEETH ON LIPS MOVEMENT", "h" : "1DA66"},
{"g" : "\u{1DA67}", "n" : "SIGNWRITING TEETH BITE LIPS", "h" : "1DA67"},
{"g" : "\u{1DA68}", "n" : "SIGNWRITING MOVEMENT-WALLPLANE JAW", "h" : "1DA68"},
{"g" : "\u{1DA69}", "n" : "SIGNWRITING MOVEMENT-FLOORPLANE JAW", "h" : "1DA69"},
{"g" : "\u{1DA6A}", "n" : "SIGNWRITING NECK", "h" : "1DA6A"},
{"g" : "\u{1DA6B}", "n" : "SIGNWRITING HAIR", "h" : "1DA6B"},
{"g" : "\u{1DA6C}", "n" : "SIGNWRITING EXCITEMENT", "h" : "1DA6C"},
{"g" : "\u{1DA6D}", "n" : "SIGNWRITING SHOULDER HIP SPINE", "h" : "1DA6D"},
{"g" : "\u{1DA6E}", "n" : "SIGNWRITING SHOULDER HIP POSITIONS", "h" : "1DA6E"},
{"g" : "\u{1DA6F}", "n" : "SIGNWRITING WALLPLANE SHOULDER HIP MOVE", "h" : "1DA6F"},
{"g" : "\u{1DA70}", "n" : "SIGNWRITING FLOORPLANE SHOULDER HIP MOVE", "h" : "1DA70"},
{"g" : "\u{1DA71}", "n" : "SIGNWRITING SHOULDER TILTING FROM WAIST", "h" : "1DA71"},
{"g" : "\u{1DA72}", "n" : "SIGNWRITING TORSO-WALLPLANE STRAIGHT STRETCH", "h" : "1DA72"},
{"g" : "\u{1DA73}", "n" : "SIGNWRITING TORSO-WALLPLANE CURVED BEND", "h" : "1DA73"},
{"g" : "\u{1DA74}", "n" : "SIGNWRITING TORSO-FLOORPLANE TWISTING", "h" : "1DA74"},
{"g" : "\u{1DA75}", "n" : "SIGNWRITING UPPER BODY TILTING FROM HIP JOINTS", "h" : "1DA75"},
{"g" : "\u{1DA76}", "n" : "SIGNWRITING LIMB COMBINATION", "h" : "1DA76"},
{"g" : "\u{1DA77}", "n" : "SIGNWRITING LIMB LENGTH-1", "h" : "1DA77"},
{"g" : "\u{1DA78}", "n" : "SIGNWRITING LIMB LENGTH-2", "h" : "1DA78"},
{"g" : "\u{1DA79}", "n" : "SIGNWRITING LIMB LENGTH-3", "h" : "1DA79"},
{"g" : "\u{1DA7A}", "n" : "SIGNWRITING LIMB LENGTH-4", "h" : "1DA7A"},
{"g" : "\u{1DA7B}", "n" : "SIGNWRITING LIMB LENGTH-5", "h" : "1DA7B"},
{"g" : "\u{1DA7C}", "n" : "SIGNWRITING LIMB LENGTH-6", "h" : "1DA7C"},
{"g" : "\u{1DA7D}", "n" : "SIGNWRITING LIMB LENGTH-7", "h" : "1DA7D"},
{"g" : "\u{1DA7E}", "n" : "SIGNWRITING FINGER", "h" : "1DA7E"},
{"g" : "\u{1DA7F}", "n" : "SIGNWRITING LOCATION-WALLPLANE SPACE", "h" : "1DA7F"},
{"g" : "\u{1DA80}", "n" : "SIGNWRITING LOCATION-FLOORPLANE SPACE", "h" : "1DA80"},
{"g" : "\u{1DA81}", "n" : "SIGNWRITING LOCATION HEIGHT", "h" : "1DA81"},
{"g" : "\u{1DA82}", "n" : "SIGNWRITING LOCATION WIDTH", "h" : "1DA82"},
{"g" : "\u{1DA83}", "n" : "SIGNWRITING LOCATION DEPTH", "h" : "1DA83"},
{"g" : "\u{1DA84}", "n" : "SIGNWRITING LOCATION HEAD NECK", "h" : "1DA84"},
{"g" : "\u{1DA85}", "n" : "SIGNWRITING LOCATION TORSO", "h" : "1DA85"},
{"g" : "\u{1DA86}", "n" : "SIGNWRITING LOCATION LIMBS DIGITS", "h" : "1DA86"},
{"g" : "\u{1DA87}", "n" : "SIGNWRITING COMMA", "h" : "1DA87"},
{"g" : "\u{1DA88}", "n" : "SIGNWRITING FULL STOP", "h" : "1DA88"},
{"g" : "\u{1DA89}", "n" : "SIGNWRITING SEMICOLON", "h" : "1DA89"},
{"g" : "\u{1DA8A}", "n" : "SIGNWRITING COLON", "h" : "1DA8A"},
{"g" : "\u{1DA8B}", "n" : "SIGNWRITING PARENTHESIS", "h" : "1DA8B"},

{"g" : "\u{1DA9B}", "n" : "SIGNWRITING FILL MODIFIER-2", "h" : "1DA9B"},
{"g" : "\u{1DA9C}", "n" : "SIGNWRITING FILL MODIFIER-3", "h" : "1DA9C"},
{"g" : "\u{1DA9D}", "n" : "SIGNWRITING FILL MODIFIER-4", "h" : "1DA9D"},
{"g" : "\u{1DA9E}", "n" : "SIGNWRITING FILL MODIFIER-5", "h" : "1DA9E"},
{"g" : "\u{1DA9F}", "n" : "SIGNWRITING FILL MODIFIER-6", "h" : "1DA9F"},

{"g" : "\u{1DAA1}", "n" : "SIGNWRITING ROTATION MODIFIER-2", "h" : "1DAA1"},
{"g" : "\u{1DAA2}", "n" : "SIGNWRITING ROTATION MODIFIER-3", "h" : "1DAA2"},
{"g" : "\u{1DAA3}", "n" : "SIGNWRITING ROTATION MODIFIER-4", "h" : "1DAA3"},
{"g" : "\u{1DAA4}", "n" : "SIGNWRITING ROTATION MODIFIER-5", "h" : "1DAA4"},
{"g" : "\u{1DAA5}", "n" : "SIGNWRITING ROTATION MODIFIER-6", "h" : "1DAA5"},
{"g" : "\u{1DAA6}", "n" : "SIGNWRITING ROTATION MODIFIER-7", "h" : "1DAA6"},
{"g" : "\u{1DAA7}", "n" : "SIGNWRITING ROTATION MODIFIER-8", "h" : "1DAA7"},
{"g" : "\u{1DAA8}", "n" : "SIGNWRITING ROTATION MODIFIER-9", "h" : "1DAA8"},
{"g" : "\u{1DAA9}", "n" : "SIGNWRITING ROTATION MODIFIER-10", "h" : "1DAA9"},
{"g" : "\u{1DAAA}", "n" : "SIGNWRITING ROTATION MODIFIER-11", "h" : "1DAAA"},
{"g" : "\u{1DAAB}", "n" : "SIGNWRITING ROTATION MODIFIER-12", "h" : "1DAAB"},
{"g" : "\u{1DAAC}", "n" : "SIGNWRITING ROTATION MODIFIER-13", "h" : "1DAAC"},
{"g" : "\u{1DAAD}", "n" : "SIGNWRITING ROTATION MODIFIER-14", "h" : "1DAAD"},
{"g" : "\u{1DAAE}", "n" : "SIGNWRITING ROTATION MODIFIER-15", "h" : "1DAAE"},
{"g" : "\u{1DAAF}", "n" : "SIGNWRITING ROTATION MODIFIER-16", "h" : "1DAAF"}
];
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    	var myPara1 = document.createElement('p');
    	var myPara2 = document.createElement('p');
    	var myPara3 = document.createElement('p');
		  var myPara4 = document.createElement('p');
		  var myPara5 = document.createElement('p');
		  var myPara6 = document.createElement('p');

    	myPara1.textContent = glyph;
    	myPara2.textContent = name;
    	myPara3.textContent = 'U+' + hex;
		  myPara4.textContent = '&#x' + hex + ';';
		  myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
		  myPara6.textContent = '\\' + 'u' + hex;

    	myArticle.appendChild(myPara1);
    	myArticle.appendChild(myPara2);
    	myArticle.appendChild(myPara3);
		  myArticle.appendChild(myPara4);
		  myArticle.appendChild(myPara5);
		  myArticle.appendChild(myPara6);

    section.appendChild(myArticle);
  }
}
