var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u13A0", "n" : "CHEROKEE LETTER A", "h" : "13A0" },
{"g" : "\u13A1", "n" : "CHEROKEE LETTER E", "h" : "13A1" },
{"g" : "\u13A2", "n" : "CHEROKEE LETTER I", "h" : "13A2" },
{"g" : "\u13A3", "n" : "CHEROKEE LETTER O", "h" : "13A3" },
{"g" : "\u13A4", "n" : "CHEROKEE LETTER U", "h" : "13A4" },
{"g" : "\u13A5", "n" : "CHEROKEE LETTER V", "h" : "13A5" },
{"g" : "\u13A6", "n" : "CHEROKEE LETTER GA", "h" : "13A6" },
{"g" : "\u13A7", "n" : "CHEROKEE LETTER KA", "h" : "13A7" },
{"g" : "\u13A8", "n" : "CHEROKEE LETTER GE", "h" : "13A8" },
{"g" : "\u13A9", "n" : "CHEROKEE LETTER GI", "h" : "13A9" },
{"g" : "\u13AA", "n" : "CHEROKEE LETTER GO", "h" : "13AA" },
{"g" : "\u13AB", "n" : "CHEROKEE LETTER GU", "h" : "13AB" },
{"g" : "\u13AC", "n" : "CHEROKEE LETTER GV", "h" : "13AC" },
{"g" : "\u13AD", "n" : "CHEROKEE LETTER HA", "h" : "13AD" },
{"g" : "\u13AE", "n" : "CHEROKEE LETTER HE", "h" : "13AE" },
{"g" : "\u13AF", "n" : "CHEROKEE LETTER HI", "h" : "13AF" },
{"g" : "\u13B0", "n" : "CHEROKEE LETTER HO", "h" : "13B0" },
{"g" : "\u13B1", "n" : "CHEROKEE LETTER HU", "h" : "13B1" },
{"g" : "\u13B2", "n" : "CHEROKEE LETTER HV", "h" : "13B2" },
{"g" : "\u13B3", "n" : "CHEROKEE LETTER LA", "h" : "13B3" },
{"g" : "\u13B4", "n" : "CHEROKEE LETTER LE", "h" : "13B4" },
{"g" : "\u13B5", "n" : "CHEROKEE LETTER LI", "h" : "13B5" },
{"g" : "\u13B6", "n" : "CHEROKEE LETTER LO", "h" : "13B6" },
{"g" : "\u13B7", "n" : "CHEROKEE LETTER LU", "h" : "13B7" },
{"g" : "\u13B8", "n" : "CHEROKEE LETTER LV", "h" : "13B8" },
{"g" : "\u13B9", "n" : "CHEROKEE LETTER MA", "h" : "13B9" },
{"g" : "\u13BA", "n" : "CHEROKEE LETTER ME", "h" : "13BA" },
{"g" : "\u13BB", "n" : "CHEROKEE LETTER MI", "h" : "13BB" },
{"g" : "\u13BC", "n" : "CHEROKEE LETTER MO", "h" : "13BC" },
{"g" : "\u13BD", "n" : "CHEROKEE LETTER MU", "h" : "13BD" },
{"g" : "\u13BE", "n" : "CHEROKEE LETTER NA", "h" : "13BE" },
{"g" : "\u13BF", "n" : "CHEROKEE LETTER HNA", "h" : "13BF" },
{"g" : "\u13C0", "n" : "CHEROKEE LETTER NAH", "h" : "13C0" },
{"g" : "\u13C1", "n" : "CHEROKEE LETTER NE", "h" : "13C1" },
{"g" : "\u13C2", "n" : "CHEROKEE LETTER NI", "h" : "13C2" },
{"g" : "\u13C3", "n" : "CHEROKEE LETTER NO", "h" : "13C3" },
{"g" : "\u13C4", "n" : "CHEROKEE LETTER NU", "h" : "13C4" },
{"g" : "\u13C5", "n" : "CHEROKEE LETTER NV", "h" : "13C5" },
{"g" : "\u13C6", "n" : "CHEROKEE LETTER QUA", "h" : "13C6" },
{"g" : "\u13C7", "n" : "CHEROKEE LETTER QUE", "h" : "13C7" },
{"g" : "\u13C8", "n" : "CHEROKEE LETTER QUI", "h" : "13C8" },
{"g" : "\u13C9", "n" : "CHEROKEE LETTER QUO", "h" : "13C9" },
{"g" : "\u13CA", "n" : "CHEROKEE LETTER QUU", "h" : "13CA" },
{"g" : "\u13CB", "n" : "CHEROKEE LETTER QUV", "h" : "13CB" },
{"g" : "\u13CC", "n" : "CHEROKEE LETTER SA", "h" : "13CC" },
{"g" : "\u13CD", "n" : "CHEROKEE LETTER S", "h" : "13CD" },
{"g" : "\u13CE", "n" : "CHEROKEE LETTER SE", "h" : "13CE" },
{"g" : "\u13CF", "n" : "CHEROKEE LETTER SI", "h" : "13CF" },
{"g" : "\u13D0", "n" : "CHEROKEE LETTER SO", "h" : "13D0" },
{"g" : "\u13D1", "n" : "CHEROKEE LETTER SU", "h" : "13D1" },
{"g" : "\u13D2", "n" : "CHEROKEE LETTER SV", "h" : "13D2" },
{"g" : "\u13D3", "n" : "CHEROKEE LETTER DA", "h" : "13D3" },
{"g" : "\u13D4", "n" : "CHEROKEE LETTER TA", "h" : "13D4" },
{"g" : "\u13D5", "n" : "CHEROKEE LETTER DE", "h" : "13D5" },
{"g" : "\u13D6", "n" : "CHEROKEE LETTER TE", "h" : "13D6" },
{"g" : "\u13D7", "n" : "CHEROKEE LETTER DI", "h" : "13D7" },
{"g" : "\u13D8", "n" : "CHEROKEE LETTER TI", "h" : "13D8" },
{"g" : "\u13D9", "n" : "CHEROKEE LETTER DO", "h" : "13D9" },
{"g" : "\u13DA", "n" : "CHEROKEE LETTER DU", "h" : "13DA" },
{"g" : "\u13DB", "n" : "CHEROKEE LETTER DV", "h" : "13DB" },
{"g" : "\u13DC", "n" : "CHEROKEE LETTER DLA", "h" : "13DC" },
{"g" : "\u13DD", "n" : "CHEROKEE LETTER TLA", "h" : "13DD" },
{"g" : "\u13DE", "n" : "CHEROKEE LETTER TLE", "h" : "13DE" },
{"g" : "\u13DF", "n" : "CHEROKEE LETTER TLI", "h" : "13DF" },
{"g" : "\u13E0", "n" : "CHEROKEE LETTER TLO", "h" : "13E0" },
{"g" : "\u13E1", "n" : "CHEROKEE LETTER TLU", "h" : "13E1" },
{"g" : "\u13E2", "n" : "CHEROKEE LETTER TLV", "h" : "13E2" },
{"g" : "\u13E3", "n" : "CHEROKEE LETTER TSA", "h" : "13E3" },
{"g" : "\u13E4", "n" : "CHEROKEE LETTER TSE", "h" : "13E4" },
{"g" : "\u13E5", "n" : "CHEROKEE LETTER TSI", "h" : "13E5" },
{"g" : "\u13E6", "n" : "CHEROKEE LETTER TSO", "h" : "13E6" },
{"g" : "\u13E7", "n" : "CHEROKEE LETTER TSU", "h" : "13E7" },
{"g" : "\u13E8", "n" : "CHEROKEE LETTER TSV", "h" : "13E8" },
{"g" : "\u13E9", "n" : "CHEROKEE LETTER WA", "h" : "13E9" },
{"g" : "\u13EA", "n" : "CHEROKEE LETTER WE", "h" : "13EA" },
{"g" : "\u13EB", "n" : "CHEROKEE LETTER WI", "h" : "13EB" },
{"g" : "\u13EC", "n" : "CHEROKEE LETTER WO", "h" : "13EC" },
{"g" : "\u13ED", "n" : "CHEROKEE LETTER WU", "h" : "13ED" },
{"g" : "\u13EE", "n" : "CHEROKEE LETTER WV", "h" : "13EE" },
{"g" : "\u13EF", "n" : "CHEROKEE LETTER YA", "h" : "13EF" },
{"g" : "\u13F0", "n" : "CHEROKEE LETTER YE", "h" : "13F0" },
{"g" : "\u13F1", "n" : "CHEROKEE LETTER YI", "h" : "13F1" },
{"g" : "\u13F2", "n" : "CHEROKEE LETTER YO", "h" : "13F2" },
{"g" : "\u13F3", "n" : "CHEROKEE LETTER YU", "h" : "13F3" },
{"g" : "\u13F4", "n" : "CHEROKEE LETTER YV", "h" : "13F4" },
{"g" : "\u13F5", "n" : "CHEROKEE LETTER MV", "h" : "13F5" },

{"g" : "\u13F8", "n" : "CHEROKEE SMALL LETTER YE", "h" : "13F8" },
{"g" : "\u13F9", "n" : "CHEROKEE SMALL LETTER YI", "h" : "13F9" },
{"g" : "\u13FA", "n" : "CHEROKEE SMALL LETTER YO", "h" : "13FA" },
{"g" : "\u13FB", "n" : "CHEROKEE SMALL LETTER YU", "h" : "13FB" },
{"g" : "\u13FC", "n" : "CHEROKEE SMALL LETTER YV", "h" : "13FC" },
{"g" : "\u13FD", "n" : "CHEROKEE SMALL LETTER MV", "h" : "13FD" },

{"g" : "\u1400", "n" : "CANADIAN SYLLABICS HYPHEN", "h" : "1400" },
{"g" : "\u1401", "n" : "CANADIAN SYLLABICS E", "h" : "1401" },
{"g" : "\u1402", "n" : "CANADIAN SYLLABICS AAI", "h" : "1402" },
{"g" : "\u1403", "n" : "CANADIAN SYLLABICS I", "h" : "1403" },
{"g" : "\u1404", "n" : "CANADIAN SYLLABICS II", "h" : "1404" },
{"g" : "\u1405", "n" : "CANADIAN SYLLABICS O", "h" : "1405" },
{"g" : "\u1406", "n" : "CANADIAN SYLLABICS OO", "h" : "1406" },
{"g" : "\u1407", "n" : "CANADIAN SYLLABICS Y-CREE OO", "h" : "1407" },
{"g" : "\u1408", "n" : "CANADIAN SYLLABICS CARRIER EE", "h" : "1408" },
{"g" : "\u1409", "n" : "CANADIAN SYLLABICS CARRIER I", "h" : "1409" },
{"g" : "\u140A", "n" : "CANADIAN SYLLABICS A", "h" : "140A" },
{"g" : "\u140B", "n" : "CANADIAN SYLLABICS AA", "h" : "140B" },
{"g" : "\u140C", "n" : "CANADIAN SYLLABICS WE", "h" : "140C" },
{"g" : "\u140D", "n" : "CANADIAN SYLLABICS WEST-CREE WE", "h" : "140D" },
{"g" : "\u140E", "n" : "CANADIAN SYLLABICS WI", "h" : "140E" },
{"g" : "\u140F", "n" : "CANADIAN SYLLABICS WEST-CREE WI", "h" : "140F" },
{"g" : "\u1410", "n" : "CANADIAN SYLLABICS WII", "h" : "1410" },
{"g" : "\u1411", "n" : "CANADIAN SYLLABICS WEST-CREE WII", "h" : "1411" },
{"g" : "\u1412", "n" : "CANADIAN SYLLABICS WO", "h" : "1412" },
{"g" : "\u1413", "n" : "CANADIAN SYLLABICS WEST-CREE WO", "h" : "1413" },
{"g" : "\u1414", "n" : "CANADIAN SYLLABICS WOO", "h" : "1414" },
{"g" : "\u1415", "n" : "CANADIAN SYLLABICS WEST-CREE WOO", "h" : "1415" },
{"g" : "\u1416", "n" : "CANADIAN SYLLABICS NASKAPI WOO", "h" : "1416" },
{"g" : "\u1417", "n" : "CANADIAN SYLLABICS WA", "h" : "1417" },
{"g" : "\u1418", "n" : "CANADIAN SYLLABICS WEST-CREE WA", "h" : "1418" },
{"g" : "\u1419", "n" : "CANADIAN SYLLABICS WAA", "h" : "1419" },
{"g" : "\u141A", "n" : "CANADIAN SYLLABICS WEST-CREE WAA", "h" : "141A" },
{"g" : "\u141B", "n" : "CANADIAN SYLLABICS NASKAPI WAA", "h" : "141B" },
{"g" : "\u141C", "n" : "CANADIAN SYLLABICS AI", "h" : "141C" },
{"g" : "\u141D", "n" : "CANADIAN SYLLABICS Y-CREE W", "h" : "141D" },
{"g" : "\u141E", "n" : "CANADIAN SYLLABICS GLOTTAL STOP", "h" : "141E" },
{"g" : "\u141F", "n" : "CANADIAN SYLLABICS FINAL ACUTE", "h" : "141F" },
{"g" : "\u1420", "n" : "CANADIAN SYLLABICS FINAL GRAVE", "h" : "1420" },
{"g" : "\u1421", "n" : "CANADIAN SYLLABICS FINAL BOTTOM HALF RING", "h" : "1421" },
{"g" : "\u1422", "n" : "CANADIAN SYLLABICS FINAL TOP HALF RING", "h" : "1422" },
{"g" : "\u1423", "n" : "CANADIAN SYLLABICS FINAL RIGHT HALF RING", "h" : "1423" },
{"g" : "\u1424", "n" : "CANADIAN SYLLABICS FINAL RING", "h" : "1424" },
{"g" : "\u1425", "n" : "CANADIAN SYLLABICS FINAL DOUBLE ACUTE", "h" : "1425" },
{"g" : "\u1426", "n" : "CANADIAN SYLLABICS FINAL DOUBLE SHORT VERTICAL STROKES", "h" : "1426" },
{"g" : "\u1427", "n" : "CANADIAN SYLLABICS FINAL MIDDLE DOT", "h" : "1427" },
{"g" : "\u1428", "n" : "CANADIAN SYLLABICS FINAL SHORT HORIZONTAL STROKE", "h" : "1428" },
{"g" : "\u1429", "n" : "CANADIAN SYLLABICS FINAL PLUS", "h" : "1429" },
{"g" : "\u142A", "n" : "CANADIAN SYLLABICS FINAL DOWN TACK", "h" : "142A" },
{"g" : "\u142B", "n" : "CANADIAN SYLLABICS EN", "h" : "142B" },
{"g" : "\u142C", "n" : "CANADIAN SYLLABICS IN", "h" : "142C" },
{"g" : "\u142D", "n" : "CANADIAN SYLLABICS ON", "h" : "142D" },
{"g" : "\u142E", "n" : "CANADIAN SYLLABICS AN", "h" : "142E" },
{"g" : "\u142F", "n" : "CANADIAN SYLLABICS PE", "h" : "142F" },
{"g" : "\u1430", "n" : "CANADIAN SYLLABICS PAAI", "h" : "1430" },
{"g" : "\u1431", "n" : "CANADIAN SYLLABICS PI", "h" : "1431" },
{"g" : "\u1432", "n" : "CANADIAN SYLLABICS PII", "h" : "1432" },
{"g" : "\u1433", "n" : "CANADIAN SYLLABICS PO", "h" : "1433" },
{"g" : "\u1434", "n" : "CANADIAN SYLLABICS POO", "h" : "1434" },
{"g" : "\u1435", "n" : "CANADIAN SYLLABICS Y-CREE POO", "h" : "1435" },
{"g" : "\u1436", "n" : "CANADIAN SYLLABICS CARRIER HEE", "h" : "1436" },
{"g" : "\u1437", "n" : "CANADIAN SYLLABICS CARRIER HI", "h" : "1437" },
{"g" : "\u1438", "n" : "CANADIAN SYLLABICS PA", "h" : "1438" },
{"g" : "\u1439", "n" : "CANADIAN SYLLABICS PAA", "h" : "1439" },
{"g" : "\u143A", "n" : "CANADIAN SYLLABICS PWE", "h" : "143A" },
{"g" : "\u143B", "n" : "CANADIAN SYLLABICS WEST-CREE PWE", "h" : "143B" },
{"g" : "\u143C", "n" : "CANADIAN SYLLABICS PWI", "h" : "143C" },
{"g" : "\u143D", "n" : "CANADIAN SYLLABICS WEST-CREE PWI", "h" : "143D" },
{"g" : "\u143E", "n" : "CANADIAN SYLLABICS PWII", "h" : "143E" },
{"g" : "\u143F", "n" : "CANADIAN SYLLABICS WEST-CREE PWII", "h" : "143F" },
{"g" : "\u1440", "n" : "CANADIAN SYLLABICS PWO", "h" : "1440" },
{"g" : "\u1441", "n" : "CANADIAN SYLLABICS WEST-CREE PWO", "h" : "1441" },
{"g" : "\u1442", "n" : "CANADIAN SYLLABICS PWOO", "h" : "1442" },
{"g" : "\u1443", "n" : "CANADIAN SYLLABICS WEST-CREE PWOO", "h" : "1443" },
{"g" : "\u1444", "n" : "CANADIAN SYLLABICS PWA", "h" : "1444" },
{"g" : "\u1445", "n" : "CANADIAN SYLLABICS WEST-CREE PWA", "h" : "1445" },
{"g" : "\u1446", "n" : "CANADIAN SYLLABICS PWAA", "h" : "1446" },
{"g" : "\u1447", "n" : "CANADIAN SYLLABICS WEST-CREE PWAA", "h" : "1447" },
{"g" : "\u1448", "n" : "CANADIAN SYLLABICS Y-CREE PWAA", "h" : "1448" },
{"g" : "\u1449", "n" : "CANADIAN SYLLABICS P", "h" : "1449" },
{"g" : "\u144A", "n" : "CANADIAN SYLLABICS WEST-CREE P", "h" : "144A" },
{"g" : "\u144B", "n" : "CANADIAN SYLLABICS CARRIER H", "h" : "144B" },
{"g" : "\u144C", "n" : "CANADIAN SYLLABICS TE", "h" : "144C" },
{"g" : "\u144D", "n" : "CANADIAN SYLLABICS TAAI", "h" : "144D" },
{"g" : "\u144E", "n" : "CANADIAN SYLLABICS TI", "h" : "144E" },
{"g" : "\u144F", "n" : "CANADIAN SYLLABICS TII", "h" : "144F" },
{"g" : "\u1450", "n" : "CANADIAN SYLLABICS TO", "h" : "1450" },
{"g" : "\u1451", "n" : "CANADIAN SYLLABICS TOO", "h" : "1451" },
{"g" : "\u1452", "n" : "CANADIAN SYLLABICS Y-CREE TOO", "h" : "1452" },
{"g" : "\u1453", "n" : "CANADIAN SYLLABICS CARRIER DEE", "h" : "1453" },
{"g" : "\u1454", "n" : "CANADIAN SYLLABICS CARRIER DI", "h" : "1454" },
{"g" : "\u1455", "n" : "CANADIAN SYLLABICS TA", "h" : "1455" },
{"g" : "\u1456", "n" : "CANADIAN SYLLABICS TAA", "h" : "1456" },
{"g" : "\u1457", "n" : "CANADIAN SYLLABICS TWE", "h" : "1457" },
{"g" : "\u1458", "n" : "CANADIAN SYLLABICS WEST-CREE TWE", "h" : "1458" },
{"g" : "\u1459", "n" : "CANADIAN SYLLABICS TWI", "h" : "1459" },
{"g" : "\u145A", "n" : "CANADIAN SYLLABICS WEST-CREE TWI", "h" : "145A" },
{"g" : "\u145B", "n" : "CANADIAN SYLLABICS TWII", "h" : "145B" },
{"g" : "\u145C", "n" : "CANADIAN SYLLABICS WEST-CREE TWII", "h" : "145C" },
{"g" : "\u145D", "n" : "CANADIAN SYLLABICS TWO", "h" : "145D" },
{"g" : "\u145E", "n" : "CANADIAN SYLLABICS WEST-CREE TWO", "h" : "145E" },
{"g" : "\u145F", "n" : "CANADIAN SYLLABICS TWOO", "h" : "145F" },
{"g" : "\u1460", "n" : "CANADIAN SYLLABICS WEST-CREE TWOO", "h" : "1460" },
{"g" : "\u1461", "n" : "CANADIAN SYLLABICS TWA", "h" : "1461" },
{"g" : "\u1462", "n" : "CANADIAN SYLLABICS WEST-CREE TWA", "h" : "1462" },
{"g" : "\u1463", "n" : "CANADIAN SYLLABICS TWAA", "h" : "1463" },
{"g" : "\u1464", "n" : "CANADIAN SYLLABICS WEST-CREE TWAA", "h" : "1464" },
{"g" : "\u1465", "n" : "CANADIAN SYLLABICS NASKAPI TWAA", "h" : "1465" },
{"g" : "\u1466", "n" : "CANADIAN SYLLABICS T", "h" : "1466" },
{"g" : "\u1467", "n" : "CANADIAN SYLLABICS TTE", "h" : "1467" },
{"g" : "\u1468", "n" : "CANADIAN SYLLABICS TTI", "h" : "1468" },
{"g" : "\u1469", "n" : "CANADIAN SYLLABICS TTO", "h" : "1469" },
{"g" : "\u146A", "n" : "CANADIAN SYLLABICS TTA", "h" : "146A" },
{"g" : "\u146B", "n" : "CANADIAN SYLLABICS KE", "h" : "146B" },
{"g" : "\u146C", "n" : "CANADIAN SYLLABICS KAAI", "h" : "146C" },
{"g" : "\u146D", "n" : "CANADIAN SYLLABICS KI", "h" : "146D" },
{"g" : "\u146E", "n" : "CANADIAN SYLLABICS KII", "h" : "146E" },
{"g" : "\u146F", "n" : "CANADIAN SYLLABICS KO", "h" : "146F" },
{"g" : "\u1470", "n" : "CANADIAN SYLLABICS KOO", "h" : "1470" },
{"g" : "\u1471", "n" : "CANADIAN SYLLABICS Y-CREE KOO", "h" : "1471" },
{"g" : "\u1472", "n" : "CANADIAN SYLLABICS KA", "h" : "1472" },
{"g" : "\u1473", "n" : "CANADIAN SYLLABICS KAA", "h" : "1473" },
{"g" : "\u1474", "n" : "CANADIAN SYLLABICS KWE", "h" : "1474" },
{"g" : "\u1475", "n" : "CANADIAN SYLLABICS WEST-CREE KWE", "h" : "1475" },
{"g" : "\u1476", "n" : "CANADIAN SYLLABICS KWI", "h" : "1476" },
{"g" : "\u1477", "n" : "CANADIAN SYLLABICS WEST-CREE KWI", "h" : "1477" },
{"g" : "\u1478", "n" : "CANADIAN SYLLABICS KWII", "h" : "1478" },
{"g" : "\u1479", "n" : "CANADIAN SYLLABICS WEST-CREE KWII", "h" : "1479" },
{"g" : "\u147A", "n" : "CANADIAN SYLLABICS KWO", "h" : "147A" },
{"g" : "\u147B", "n" : "CANADIAN SYLLABICS WEST-CREE KWO", "h" : "147B" },
{"g" : "\u147C", "n" : "CANADIAN SYLLABICS KWOO", "h" : "147C" },
{"g" : "\u147D", "n" : "CANADIAN SYLLABICS WEST-CREE KWOO", "h" : "147D" },
{"g" : "\u147E", "n" : "CANADIAN SYLLABICS KWA", "h" : "147E" },
{"g" : "\u147F", "n" : "CANADIAN SYLLABICS WEST-CREE KWA", "h" : "147F" },
{"g" : "\u1480", "n" : "CANADIAN SYLLABICS KWAA", "h" : "1480" },
{"g" : "\u1481", "n" : "CANADIAN SYLLABICS WEST-CREE KWAA", "h" : "1481" },
{"g" : "\u1482", "n" : "CANADIAN SYLLABICS NASKAPI KWAA", "h" : "1482" },
{"g" : "\u1483", "n" : "CANADIAN SYLLABICS K", "h" : "1483" },
{"g" : "\u1484", "n" : "CANADIAN SYLLABICS KW", "h" : "1484" },
{"g" : "\u1485", "n" : "CANADIAN SYLLABICS SOUTH-SLAVEY KEH", "h" : "1485" },
{"g" : "\u1486", "n" : "CANADIAN SYLLABICS SOUTH-SLAVEY KIH", "h" : "1486" },
{"g" : "\u1487", "n" : "CANADIAN SYLLABICS SOUTH-SLAVEY KOH", "h" : "1487" },
{"g" : "\u1488", "n" : "CANADIAN SYLLABICS SOUTH-SLAVEY KAH", "h" : "1488" },
{"g" : "\u1489", "n" : "CANADIAN SYLLABICS CE", "h" : "1489" },
{"g" : "\u148A", "n" : "CANADIAN SYLLABICS CAAI", "h" : "148A" },
{"g" : "\u148B", "n" : "CANADIAN SYLLABICS CI", "h" : "148B" },
{"g" : "\u148C", "n" : "CANADIAN SYLLABICS CII", "h" : "148C" },
{"g" : "\u148D", "n" : "CANADIAN SYLLABICS CO", "h" : "148D" },
{"g" : "\u148E", "n" : "CANADIAN SYLLABICS COO", "h" : "148E" },
{"g" : "\u148F", "n" : "CANADIAN SYLLABICS Y-CREE COO", "h" : "148F" },
{"g" : "\u1490", "n" : "CANADIAN SYLLABICS CA", "h" : "1490" },
{"g" : "\u1491", "n" : "CANADIAN SYLLABICS CAA", "h" : "1491" },
{"g" : "\u1492", "n" : "CANADIAN SYLLABICS CWE", "h" : "1492" },
{"g" : "\u1493", "n" : "CANADIAN SYLLABICS WEST-CREE CWE", "h" : "1493" },
{"g" : "\u1494", "n" : "CANADIAN SYLLABICS CWI", "h" : "1494" },
{"g" : "\u1495", "n" : "CANADIAN SYLLABICS WEST-CREE CWI", "h" : "1495" },
{"g" : "\u1496", "n" : "CANADIAN SYLLABICS CWII", "h" : "1496" },
{"g" : "\u1497", "n" : "CANADIAN SYLLABICS WEST-CREE CWII", "h" : "1497" },
{"g" : "\u1498", "n" : "CANADIAN SYLLABICS CWO", "h" : "1498" },
{"g" : "\u1499", "n" : "CANADIAN SYLLABICS WEST-CREE CWO", "h" : "1499" },
{"g" : "\u149A", "n" : "CANADIAN SYLLABICS CWOO", "h" : "149A" },
{"g" : "\u149B", "n" : "CANADIAN SYLLABICS WEST-CREE CWOO", "h" : "149B" },
{"g" : "\u149C", "n" : "CANADIAN SYLLABICS CWA", "h" : "149C" },
{"g" : "\u149D", "n" : "CANADIAN SYLLABICS WEST-CREE CWA", "h" : "149D" },
{"g" : "\u149E", "n" : "CANADIAN SYLLABICS CWAA", "h" : "149E" },
{"g" : "\u149F", "n" : "CANADIAN SYLLABICS WEST-CREE CWAA", "h" : "149F" },
{"g" : "\u14A0", "n" : "CANADIAN SYLLABICS NASKAPI CWAA", "h" : "14A0" },
{"g" : "\u14A1", "n" : "CANADIAN SYLLABICS C", "h" : "14A1" },
{"g" : "\u14A2", "n" : "CANADIAN SYLLABICS SAYISI TH", "h" : "14A2" },
{"g" : "\u14A3", "n" : "CANADIAN SYLLABICS ME", "h" : "14A3" },
{"g" : "\u14A4", "n" : "CANADIAN SYLLABICS MAAI", "h" : "14A4" },
{"g" : "\u14A5", "n" : "CANADIAN SYLLABICS MI", "h" : "14A5" },
{"g" : "\u14A6", "n" : "CANADIAN SYLLABICS MII", "h" : "14A6" },
{"g" : "\u14A7", "n" : "CANADIAN SYLLABICS MO", "h" : "14A7" },
{"g" : "\u14A8", "n" : "CANADIAN SYLLABICS MOO", "h" : "14A8" },
{"g" : "\u14A9", "n" : "CANADIAN SYLLABICS Y-CREE MOO", "h" : "14A9" },
{"g" : "\u14AA", "n" : "CANADIAN SYLLABICS MA", "h" : "14AA" },
{"g" : "\u14AB", "n" : "CANADIAN SYLLABICS MAA", "h" : "14AB" },
{"g" : "\u14AC", "n" : "CANADIAN SYLLABICS MWE", "h" : "14AC" },
{"g" : "\u14AD", "n" : "CANADIAN SYLLABICS WEST-CREE MWE", "h" : "14AD" },
{"g" : "\u14AE", "n" : "CANADIAN SYLLABICS MWI", "h" : "14AE" },
{"g" : "\u14AF", "n" : "CANADIAN SYLLABICS WEST-CREE MWI", "h" : "14AF" },
{"g" : "\u14B0", "n" : "CANADIAN SYLLABICS MWII", "h" : "14B0" },
{"g" : "\u14B1", "n" : "CANADIAN SYLLABICS WEST-CREE MWII", "h" : "14B1" },
{"g" : "\u14B2", "n" : "CANADIAN SYLLABICS MWO", "h" : "14B2" },
{"g" : "\u14B3", "n" : "CANADIAN SYLLABICS WEST-CREE MWO", "h" : "14B3" },
{"g" : "\u14B4", "n" : "CANADIAN SYLLABICS MWOO", "h" : "14B4" },
{"g" : "\u14B5", "n" : "CANADIAN SYLLABICS WEST-CREE MWOO", "h" : "14B5" },
{"g" : "\u14B6", "n" : "CANADIAN SYLLABICS MWA", "h" : "14B6" },
{"g" : "\u14B7", "n" : "CANADIAN SYLLABICS WEST-CREE MWA", "h" : "14B7" },
{"g" : "\u14B8", "n" : "CANADIAN SYLLABICS MWAA", "h" : "14B8" },
{"g" : "\u14B9", "n" : "CANADIAN SYLLABICS WEST-CREE MWAA", "h" : "14B9" },
{"g" : "\u14BA", "n" : "CANADIAN SYLLABICS NASKAPI MWAA", "h" : "14BA" },
{"g" : "\u14BB", "n" : "CANADIAN SYLLABICS M", "h" : "14BB" },
{"g" : "\u14BC", "n" : "CANADIAN SYLLABICS WEST-CREE M", "h" : "14BC" },
{"g" : "\u14BD", "n" : "CANADIAN SYLLABICS MH", "h" : "14BD" },
{"g" : "\u14BE", "n" : "CANADIAN SYLLABICS ATHAPASCAN M", "h" : "14BE" },
{"g" : "\u14BF", "n" : "CANADIAN SYLLABICS SAYISI M", "h" : "14BF" },
{"g" : "\u14C0", "n" : "CANADIAN SYLLABICS NE", "h" : "14C0" },
{"g" : "\u14C1", "n" : "CANADIAN SYLLABICS NAAI", "h" : "14C1" },
{"g" : "\u14C2", "n" : "CANADIAN SYLLABICS NI", "h" : "14C2" },
{"g" : "\u14C3", "n" : "CANADIAN SYLLABICS NII", "h" : "14C3" },
{"g" : "\u14C4", "n" : "CANADIAN SYLLABICS NO", "h" : "14C4" },
{"g" : "\u14C5", "n" : "CANADIAN SYLLABICS NOO", "h" : "14C5" },
{"g" : "\u14C6", "n" : "CANADIAN SYLLABICS Y-CREE NOO", "h" : "14C6" },
{"g" : "\u14C7", "n" : "CANADIAN SYLLABICS NA", "h" : "14C7" },
{"g" : "\u14C8", "n" : "CANADIAN SYLLABICS NAA", "h" : "14C8" },
{"g" : "\u14C9", "n" : "CANADIAN SYLLABICS NWE", "h" : "14C9" },
{"g" : "\u14CA", "n" : "CANADIAN SYLLABICS WEST-CREE NWE", "h" : "14CA" },
{"g" : "\u14CB", "n" : "CANADIAN SYLLABICS NWA", "h" : "14CB" },
{"g" : "\u14CC", "n" : "CANADIAN SYLLABICS WEST-CREE NWA", "h" : "14CC" },
{"g" : "\u14CD", "n" : "CANADIAN SYLLABICS NWAA", "h" : "14CD" },
{"g" : "\u14CE", "n" : "CANADIAN SYLLABICS WEST-CREE NWAA", "h" : "14CE" },
{"g" : "\u14CF", "n" : "CANADIAN SYLLABICS NASKAPI NWAA", "h" : "14CF" },
{"g" : "\u14D0", "n" : "CANADIAN SYLLABICS N", "h" : "14D0" },
{"g" : "\u14D1", "n" : "CANADIAN SYLLABICS CARRIER NG", "h" : "14D1" },
{"g" : "\u14D2", "n" : "CANADIAN SYLLABICS NH", "h" : "14D2" },
{"g" : "\u14D3", "n" : "CANADIAN SYLLABICS LE", "h" : "14D3" },
{"g" : "\u14D4", "n" : "CANADIAN SYLLABICS LAAI", "h" : "14D4" },
{"g" : "\u14D5", "n" : "CANADIAN SYLLABICS LI", "h" : "14D5" },
{"g" : "\u14D6", "n" : "CANADIAN SYLLABICS LII", "h" : "14D6" },
{"g" : "\u14D7", "n" : "CANADIAN SYLLABICS LO", "h" : "14D7" },
{"g" : "\u14D8", "n" : "CANADIAN SYLLABICS LOO", "h" : "14D8" },
{"g" : "\u14D9", "n" : "CANADIAN SYLLABICS Y-CREE LOO", "h" : "14D9" },
{"g" : "\u14DA", "n" : "CANADIAN SYLLABICS LA", "h" : "14DA" },
{"g" : "\u14DB", "n" : "CANADIAN SYLLABICS LAA", "h" : "14DB" },
{"g" : "\u14DC", "n" : "CANADIAN SYLLABICS LWE", "h" : "14DC" },
{"g" : "\u14DD", "n" : "CANADIAN SYLLABICS WEST-CREE LWE", "h" : "14DD" },
{"g" : "\u14DE", "n" : "CANADIAN SYLLABICS LWI", "h" : "14DE" },
{"g" : "\u14DF", "n" : "CANADIAN SYLLABICS WEST-CREE LWI", "h" : "14DF" },
{"g" : "\u14E0", "n" : "CANADIAN SYLLABICS LWII", "h" : "14E0" },
{"g" : "\u14E1", "n" : "CANADIAN SYLLABICS WEST-CREE LWII", "h" : "14E1" },
{"g" : "\u14E2", "n" : "CANADIAN SYLLABICS LWO", "h" : "14E2" },
{"g" : "\u14E3", "n" : "CANADIAN SYLLABICS WEST-CREE LWO", "h" : "14E3" },
{"g" : "\u14E4", "n" : "CANADIAN SYLLABICS LWOO", "h" : "14E4" },
{"g" : "\u14E5", "n" : "CANADIAN SYLLABICS WEST-CREE LWOO", "h" : "14E5" },
{"g" : "\u14E6", "n" : "CANADIAN SYLLABICS LWA", "h" : "14E6" },
{"g" : "\u14E7", "n" : "CANADIAN SYLLABICS WEST-CREE LWA", "h" : "14E7" },
{"g" : "\u14E8", "n" : "CANADIAN SYLLABICS LWAA", "h" : "14E8" },
{"g" : "\u14E9", "n" : "CANADIAN SYLLABICS WEST-CREE LWAA", "h" : "14E9" },
{"g" : "\u14EA", "n" : "CANADIAN SYLLABICS L", "h" : "14EA" },
{"g" : "\u14EB", "n" : "CANADIAN SYLLABICS WEST-CREE L", "h" : "14EB" },
{"g" : "\u14EC", "n" : "CANADIAN SYLLABICS MEDIAL L", "h" : "14EC" },
{"g" : "\u14ED", "n" : "CANADIAN SYLLABICS SE", "h" : "14ED" },
{"g" : "\u14EE", "n" : "CANADIAN SYLLABICS SAAI", "h" : "14EE" },
{"g" : "\u14EF", "n" : "CANADIAN SYLLABICS SI", "h" : "14EF" },
{"g" : "\u14F0", "n" : "CANADIAN SYLLABICS SII", "h" : "14F0" },
{"g" : "\u14F1", "n" : "CANADIAN SYLLABICS SO", "h" : "14F1" },
{"g" : "\u14F2", "n" : "CANADIAN SYLLABICS SOO", "h" : "14F2" },
{"g" : "\u14F3", "n" : "CANADIAN SYLLABICS Y-CREE SOO", "h" : "14F3" },
{"g" : "\u14F4", "n" : "CANADIAN SYLLABICS SA", "h" : "14F4" },
{"g" : "\u14F5", "n" : "CANADIAN SYLLABICS SAA", "h" : "14F5" },
{"g" : "\u14F6", "n" : "CANADIAN SYLLABICS SWE", "h" : "14F6" },
{"g" : "\u14F7", "n" : "CANADIAN SYLLABICS WEST-CREE SWE", "h" : "14F7" },
{"g" : "\u14F8", "n" : "CANADIAN SYLLABICS SWI", "h" : "14F8" },
{"g" : "\u14F9", "n" : "CANADIAN SYLLABICS WEST-CREE SWI", "h" : "14F9" },
{"g" : "\u14FA", "n" : "CANADIAN SYLLABICS SWII", "h" : "14FA" },
{"g" : "\u14FB", "n" : "CANADIAN SYLLABICS WEST-CREE SWII", "h" : "14FB" },
{"g" : "\u14FC", "n" : "CANADIAN SYLLABICS SWO", "h" : "14FC" },
{"g" : "\u14FD", "n" : "CANADIAN SYLLABICS WEST-CREE SWO", "h" : "14FD" },
{"g" : "\u14FE", "n" : "CANADIAN SYLLABICS SWOO", "h" : "14FE" },
{"g" : "\u14FF", "n" : "CANADIAN SYLLABICS WEST-CREE SWOO", "h" : "14FF" },
{"g" : "\u1500", "n" : "CANADIAN SYLLABICS SWA", "h" : "1500" },
{"g" : "\u1501", "n" : "CANADIAN SYLLABICS WEST-CREE SWA", "h" : "1501" },
{"g" : "\u1502", "n" : "CANADIAN SYLLABICS SWAA", "h" : "1502" },
{"g" : "\u1503", "n" : "CANADIAN SYLLABICS WEST-CREE SWAA", "h" : "1503" },
{"g" : "\u1504", "n" : "CANADIAN SYLLABICS NASKAPI SWAA", "h" : "1504" },
{"g" : "\u1505", "n" : "CANADIAN SYLLABICS S", "h" : "1505" },
{"g" : "\u1506", "n" : "CANADIAN SYLLABICS ATHAPASCAN S", "h" : "1506" },
{"g" : "\u1507", "n" : "CANADIAN SYLLABICS SW", "h" : "1507" },
{"g" : "\u1508", "n" : "CANADIAN SYLLABICS BLACKFOOT S", "h" : "1508" },
{"g" : "\u1509", "n" : "CANADIAN SYLLABICS MOOSE-CREE SK", "h" : "1509" },
{"g" : "\u150A", "n" : "CANADIAN SYLLABICS NASKAPI SKW", "h" : "150A" },
{"g" : "\u150B", "n" : "CANADIAN SYLLABICS NASKAPI S-W", "h" : "150B" },
{"g" : "\u150C", "n" : "CANADIAN SYLLABICS NASKAPI SPWA", "h" : "150C" },
{"g" : "\u150D", "n" : "CANADIAN SYLLABICS NASKAPI STWA", "h" : "150D" },
{"g" : "\u150E", "n" : "CANADIAN SYLLABICS NASKAPI SKWA", "h" : "150E" },
{"g" : "\u150F", "n" : "CANADIAN SYLLABICS NASKAPI SCWA", "h" : "150F" },
{"g" : "\u1510", "n" : "CANADIAN SYLLABICS SHE", "h" : "1510" },
{"g" : "\u1511", "n" : "CANADIAN SYLLABICS SHI", "h" : "1511" },
{"g" : "\u1512", "n" : "CANADIAN SYLLABICS SHII", "h" : "1512" },
{"g" : "\u1513", "n" : "CANADIAN SYLLABICS SHO", "h" : "1513" },
{"g" : "\u1514", "n" : "CANADIAN SYLLABICS SHOO", "h" : "1514" },
{"g" : "\u1515", "n" : "CANADIAN SYLLABICS SHA", "h" : "1515" },
{"g" : "\u1516", "n" : "CANADIAN SYLLABICS SHAA", "h" : "1516" },
{"g" : "\u1517", "n" : "CANADIAN SYLLABICS SHWE", "h" : "1517" },
{"g" : "\u1518", "n" : "CANADIAN SYLLABICS WEST-CREE SHWE", "h" : "1518" },
{"g" : "\u1519", "n" : "CANADIAN SYLLABICS SHWI", "h" : "1519" },
{"g" : "\u151A", "n" : "CANADIAN SYLLABICS WEST-CREE SHWI", "h" : "151A" },
{"g" : "\u151B", "n" : "CANADIAN SYLLABICS SHWII", "h" : "151B" },
{"g" : "\u151C", "n" : "CANADIAN SYLLABICS WEST-CREE SHWII", "h" : "151C" },
{"g" : "\u151D", "n" : "CANADIAN SYLLABICS SHWO", "h" : "151D" },
{"g" : "\u151E", "n" : "CANADIAN SYLLABICS WEST-CREE SHWO", "h" : "151E" },
{"g" : "\u151F", "n" : "CANADIAN SYLLABICS SHWOO", "h" : "151F" },
{"g" : "\u1520", "n" : "CANADIAN SYLLABICS WEST-CREE SHWOO", "h" : "1520" },
{"g" : "\u1521", "n" : "CANADIAN SYLLABICS SHWA", "h" : "1521" },
{"g" : "\u1522", "n" : "CANADIAN SYLLABICS WEST-CREE SHWA", "h" : "1522" },
{"g" : "\u1523", "n" : "CANADIAN SYLLABICS SHWAA", "h" : "1523" },
{"g" : "\u1524", "n" : "CANADIAN SYLLABICS WEST-CREE SHWAA", "h" : "1524" },
{"g" : "\u1525", "n" : "CANADIAN SYLLABICS SH", "h" : "1525" },
{"g" : "\u1526", "n" : "CANADIAN SYLLABICS YE", "h" : "1526" },
{"g" : "\u1527", "n" : "CANADIAN SYLLABICS YAAI", "h" : "1527" },
{"g" : "\u1528", "n" : "CANADIAN SYLLABICS YI", "h" : "1528" },
{"g" : "\u1529", "n" : "CANADIAN SYLLABICS YII", "h" : "1529" },
{"g" : "\u152A", "n" : "CANADIAN SYLLABICS YO", "h" : "152A" },
{"g" : "\u152B", "n" : "CANADIAN SYLLABICS YOO", "h" : "152B" },
{"g" : "\u152C", "n" : "CANADIAN SYLLABICS Y-CREE YOO", "h" : "152C" },
{"g" : "\u152D", "n" : "CANADIAN SYLLABICS YA", "h" : "152D" },
{"g" : "\u152E", "n" : "CANADIAN SYLLABICS YAA", "h" : "152E" },
{"g" : "\u152F", "n" : "CANADIAN SYLLABICS YWE", "h" : "152F" },
{"g" : "\u1530", "n" : "CANADIAN SYLLABICS WEST-CREE YWE", "h" : "1530" },
{"g" : "\u1531", "n" : "CANADIAN SYLLABICS YWI", "h" : "1531" },
{"g" : "\u1532", "n" : "CANADIAN SYLLABICS WEST-CREE YWI", "h" : "1532" },
{"g" : "\u1533", "n" : "CANADIAN SYLLABICS YWII", "h" : "1533" },
{"g" : "\u1534", "n" : "CANADIAN SYLLABICS WEST-CREE YWII", "h" : "1534" },
{"g" : "\u1535", "n" : "CANADIAN SYLLABICS YWO", "h" : "1535" },
{"g" : "\u1536", "n" : "CANADIAN SYLLABICS WEST-CREE YWO", "h" : "1536" },
{"g" : "\u1537", "n" : "CANADIAN SYLLABICS YWOO", "h" : "1537" },
{"g" : "\u1538", "n" : "CANADIAN SYLLABICS WEST-CREE YWOO", "h" : "1538" },
{"g" : "\u1539", "n" : "CANADIAN SYLLABICS YWA", "h" : "1539" },
{"g" : "\u153A", "n" : "CANADIAN SYLLABICS WEST-CREE YWA", "h" : "153A" },
{"g" : "\u153B", "n" : "CANADIAN SYLLABICS YWAA", "h" : "153B" },
{"g" : "\u153C", "n" : "CANADIAN SYLLABICS WEST-CREE YWAA", "h" : "153C" },
{"g" : "\u153D", "n" : "CANADIAN SYLLABICS NASKAPI YWAA", "h" : "153D" },
{"g" : "\u153E", "n" : "CANADIAN SYLLABICS Y", "h" : "153E" },
{"g" : "\u153F", "n" : "CANADIAN SYLLABICS BIBLE-CREE Y", "h" : "153F" },
{"g" : "\u1540", "n" : "CANADIAN SYLLABICS WEST-CREE Y", "h" : "1540" },
{"g" : "\u1541", "n" : "CANADIAN SYLLABICS SAYISI YI", "h" : "1541" },
{"g" : "\u1542", "n" : "CANADIAN SYLLABICS RE", "h" : "1542" },
{"g" : "\u1543", "n" : "CANADIAN SYLLABICS R-CREE RE", "h" : "1543" },
{"g" : "\u1544", "n" : "CANADIAN SYLLABICS WEST-CREE LE", "h" : "1544" },
{"g" : "\u1545", "n" : "CANADIAN SYLLABICS RAAI", "h" : "1545" },
{"g" : "\u1546", "n" : "CANADIAN SYLLABICS RI", "h" : "1546" },
{"g" : "\u1547", "n" : "CANADIAN SYLLABICS RII", "h" : "1547" },
{"g" : "\u1548", "n" : "CANADIAN SYLLABICS RO", "h" : "1548" },
{"g" : "\u1549", "n" : "CANADIAN SYLLABICS ROO", "h" : "1549" },
{"g" : "\u154A", "n" : "CANADIAN SYLLABICS WEST-CREE LO", "h" : "154A" },
{"g" : "\u154B", "n" : "CANADIAN SYLLABICS RA", "h" : "154B" },
{"g" : "\u154C", "n" : "CANADIAN SYLLABICS RAA", "h" : "154C" },
{"g" : "\u154D", "n" : "CANADIAN SYLLABICS WEST-CREE LA", "h" : "154D" },
{"g" : "\u154E", "n" : "CANADIAN SYLLABICS RWAA", "h" : "154E" },
{"g" : "\u154F", "n" : "CANADIAN SYLLABICS WEST-CREE RWAA", "h" : "154F" },
{"g" : "\u1550", "n" : "CANADIAN SYLLABICS R", "h" : "1550" },
{"g" : "\u1551", "n" : "CANADIAN SYLLABICS WEST-CREE R", "h" : "1551" },
{"g" : "\u1552", "n" : "CANADIAN SYLLABICS MEDIAL R", "h" : "1552" },
{"g" : "\u1553", "n" : "CANADIAN SYLLABICS FE", "h" : "1553" },
{"g" : "\u1554", "n" : "CANADIAN SYLLABICS FAAI", "h" : "1554" },
{"g" : "\u1555", "n" : "CANADIAN SYLLABICS FI", "h" : "1555" },
{"g" : "\u1556", "n" : "CANADIAN SYLLABICS FII", "h" : "1556" },
{"g" : "\u1557", "n" : "CANADIAN SYLLABICS FO", "h" : "1557" },
{"g" : "\u1558", "n" : "CANADIAN SYLLABICS FOO", "h" : "1558" },
{"g" : "\u1559", "n" : "CANADIAN SYLLABICS FA", "h" : "1559" },
{"g" : "\u155A", "n" : "CANADIAN SYLLABICS FAA", "h" : "155A" },
{"g" : "\u155B", "n" : "CANADIAN SYLLABICS FWAA", "h" : "155B" },
{"g" : "\u155C", "n" : "CANADIAN SYLLABICS WEST-CREE FWAA", "h" : "155C" },
{"g" : "\u155D", "n" : "CANADIAN SYLLABICS F", "h" : "155D" },
{"g" : "\u155E", "n" : "CANADIAN SYLLABICS THE", "h" : "155E" },
{"g" : "\u155F", "n" : "CANADIAN SYLLABICS N-CREE THE", "h" : "155F" },
{"g" : "\u1560", "n" : "CANADIAN SYLLABICS THI", "h" : "1560" },
{"g" : "\u1561", "n" : "CANADIAN SYLLABICS N-CREE THI", "h" : "1561" },
{"g" : "\u1562", "n" : "CANADIAN SYLLABICS THII", "h" : "1562" },
{"g" : "\u1563", "n" : "CANADIAN SYLLABICS N-CREE THII", "h" : "1563" },
{"g" : "\u1564", "n" : "CANADIAN SYLLABICS THO", "h" : "1564" },
{"g" : "\u1565", "n" : "CANADIAN SYLLABICS THOO", "h" : "1565" },
{"g" : "\u1566", "n" : "CANADIAN SYLLABICS THA", "h" : "1566" },
{"g" : "\u1567", "n" : "CANADIAN SYLLABICS THAA", "h" : "1567" },
{"g" : "\u1568", "n" : "CANADIAN SYLLABICS THWAA", "h" : "1568" },
{"g" : "\u1569", "n" : "CANADIAN SYLLABICS WEST-CREE THWAA", "h" : "1569" },
{"g" : "\u156A", "n" : "CANADIAN SYLLABICS TH", "h" : "156A" },
{"g" : "\u156B", "n" : "CANADIAN SYLLABICS TTHE", "h" : "156B" },
{"g" : "\u156C", "n" : "CANADIAN SYLLABICS TTHI", "h" : "156C" },
{"g" : "\u156D", "n" : "CANADIAN SYLLABICS TTHO", "h" : "156D" },
{"g" : "\u156E", "n" : "CANADIAN SYLLABICS TTHA", "h" : "156E" },
{"g" : "\u156F", "n" : "CANADIAN SYLLABICS TTH", "h" : "156F" },
{"g" : "\u1570", "n" : "CANADIAN SYLLABICS TYE", "h" : "1570" },
{"g" : "\u1571", "n" : "CANADIAN SYLLABICS TYI", "h" : "1571" },
{"g" : "\u1572", "n" : "CANADIAN SYLLABICS TYO", "h" : "1572" },
{"g" : "\u1573", "n" : "CANADIAN SYLLABICS TYA", "h" : "1573" },
{"g" : "\u1574", "n" : "CANADIAN SYLLABICS NUNAVIK HE", "h" : "1574" },
{"g" : "\u1575", "n" : "CANADIAN SYLLABICS NUNAVIK HI", "h" : "1575" },
{"g" : "\u1576", "n" : "CANADIAN SYLLABICS NUNAVIK HII", "h" : "1576" },
{"g" : "\u1577", "n" : "CANADIAN SYLLABICS NUNAVIK HO", "h" : "1577" },
{"g" : "\u1578", "n" : "CANADIAN SYLLABICS NUNAVIK HOO", "h" : "1578" },
{"g" : "\u1579", "n" : "CANADIAN SYLLABICS NUNAVIK HA", "h" : "1579" },
{"g" : "\u157A", "n" : "CANADIAN SYLLABICS NUNAVIK HAA", "h" : "157A" },
{"g" : "\u157B", "n" : "CANADIAN SYLLABICS NUNAVIK H", "h" : "157B" },
{"g" : "\u157C", "n" : "CANADIAN SYLLABICS NUNAVUT H", "h" : "157C" },
{"g" : "\u157D", "n" : "CANADIAN SYLLABICS HK", "h" : "157D" },
{"g" : "\u157E", "n" : "CANADIAN SYLLABICS QAAI", "h" : "157E" },
{"g" : "\u157F", "n" : "CANADIAN SYLLABICS QI", "h" : "157F" },
{"g" : "\u1580", "n" : "CANADIAN SYLLABICS QII", "h" : "1580" },
{"g" : "\u1581", "n" : "CANADIAN SYLLABICS QO", "h" : "1581" },
{"g" : "\u1582", "n" : "CANADIAN SYLLABICS QOO", "h" : "1582" },
{"g" : "\u1583", "n" : "CANADIAN SYLLABICS QA", "h" : "1583" },
{"g" : "\u1584", "n" : "CANADIAN SYLLABICS QAA", "h" : "1584" },
{"g" : "\u1585", "n" : "CANADIAN SYLLABICS Q", "h" : "1585" },
{"g" : "\u1586", "n" : "CANADIAN SYLLABICS TLHE", "h" : "1586" },
{"g" : "\u1587", "n" : "CANADIAN SYLLABICS TLHI", "h" : "1587" },
{"g" : "\u1588", "n" : "CANADIAN SYLLABICS TLHO", "h" : "1588" },
{"g" : "\u1589", "n" : "CANADIAN SYLLABICS TLHA", "h" : "1589" },
{"g" : "\u158A", "n" : "CANADIAN SYLLABICS WEST-CREE RE", "h" : "158A" },
{"g" : "\u158B", "n" : "CANADIAN SYLLABICS WEST-CREE RI", "h" : "158B" },
{"g" : "\u158C", "n" : "CANADIAN SYLLABICS WEST-CREE RO", "h" : "158C" },
{"g" : "\u158D", "n" : "CANADIAN SYLLABICS WEST-CREE RA", "h" : "158D" },
{"g" : "\u158E", "n" : "CANADIAN SYLLABICS NGAAI", "h" : "158E" },
{"g" : "\u158F", "n" : "CANADIAN SYLLABICS NGI", "h" : "158F" },
{"g" : "\u1590", "n" : "CANADIAN SYLLABICS NGII", "h" : "1590" },
{"g" : "\u1591", "n" : "CANADIAN SYLLABICS NGO", "h" : "1591" },
{"g" : "\u1592", "n" : "CANADIAN SYLLABICS NGOO", "h" : "1592" },
{"g" : "\u1593", "n" : "CANADIAN SYLLABICS NGA", "h" : "1593" },
{"g" : "\u1594", "n" : "CANADIAN SYLLABICS NGAA", "h" : "1594" },
{"g" : "\u1595", "n" : "CANADIAN SYLLABICS NG", "h" : "1595" },
{"g" : "\u1596", "n" : "CANADIAN SYLLABICS NNG", "h" : "1596" },
{"g" : "\u1597", "n" : "CANADIAN SYLLABICS SAYISI SHE", "h" : "1597" },
{"g" : "\u1598", "n" : "CANADIAN SYLLABICS SAYISI SHI", "h" : "1598" },
{"g" : "\u1599", "n" : "CANADIAN SYLLABICS SAYISI SHO", "h" : "1599" },
{"g" : "\u159A", "n" : "CANADIAN SYLLABICS SAYISI SHA", "h" : "159A" },
{"g" : "\u159B", "n" : "CANADIAN SYLLABICS WOODS-CREE THE", "h" : "159B" },
{"g" : "\u159C", "n" : "CANADIAN SYLLABICS WOODS-CREE THI", "h" : "159C" },
{"g" : "\u159D", "n" : "CANADIAN SYLLABICS WOODS-CREE THO", "h" : "159D" },
{"g" : "\u159E", "n" : "CANADIAN SYLLABICS WOODS-CREE THA", "h" : "159E" },
{"g" : "\u159F", "n" : "CANADIAN SYLLABICS WOODS-CREE TH", "h" : "159F" },
{"g" : "\u15A0", "n" : "CANADIAN SYLLABICS LHI", "h" : "15A0" },
{"g" : "\u15A1", "n" : "CANADIAN SYLLABICS LHII", "h" : "15A1" },
{"g" : "\u15A2", "n" : "CANADIAN SYLLABICS LHO", "h" : "15A2" },
{"g" : "\u15A3", "n" : "CANADIAN SYLLABICS LHOO", "h" : "15A3" },
{"g" : "\u15A4", "n" : "CANADIAN SYLLABICS LHA", "h" : "15A4" },
{"g" : "\u15A5", "n" : "CANADIAN SYLLABICS LHAA", "h" : "15A5" },
{"g" : "\u15A6", "n" : "CANADIAN SYLLABICS LH", "h" : "15A6" },
{"g" : "\u15A7", "n" : "CANADIAN SYLLABICS TH-CREE THE", "h" : "15A7" },
{"g" : "\u15A8", "n" : "CANADIAN SYLLABICS TH-CREE THI", "h" : "15A8" },
{"g" : "\u15A9", "n" : "CANADIAN SYLLABICS TH-CREE THII", "h" : "15A9" },
{"g" : "\u15AA", "n" : "CANADIAN SYLLABICS TH-CREE THO", "h" : "15AA" },
{"g" : "\u15AB", "n" : "CANADIAN SYLLABICS TH-CREE THOO", "h" : "15AB" },
{"g" : "\u15AC", "n" : "CANADIAN SYLLABICS TH-CREE THA", "h" : "15AC" },
{"g" : "\u15AD", "n" : "CANADIAN SYLLABICS TH-CREE THAA", "h" : "15AD" },
{"g" : "\u15AE", "n" : "CANADIAN SYLLABICS TH-CREE TH", "h" : "15AE" },
{"g" : "\u15AF", "n" : "CANADIAN SYLLABICS AIVILIK B", "h" : "15AF" },
{"g" : "\u15B0", "n" : "CANADIAN SYLLABICS BLACKFOOT E", "h" : "15B0" },
{"g" : "\u15B1", "n" : "CANADIAN SYLLABICS BLACKFOOT I", "h" : "15B1" },
{"g" : "\u15B2", "n" : "CANADIAN SYLLABICS BLACKFOOT O", "h" : "15B2" },
{"g" : "\u15B3", "n" : "CANADIAN SYLLABICS BLACKFOOT A", "h" : "15B3" },
{"g" : "\u15B4", "n" : "CANADIAN SYLLABICS BLACKFOOT WE", "h" : "15B4" },
{"g" : "\u15B5", "n" : "CANADIAN SYLLABICS BLACKFOOT WI", "h" : "15B5" },
{"g" : "\u15B6", "n" : "CANADIAN SYLLABICS BLACKFOOT WO", "h" : "15B6" },
{"g" : "\u15B7", "n" : "CANADIAN SYLLABICS BLACKFOOT WA", "h" : "15B7" },
{"g" : "\u15B8", "n" : "CANADIAN SYLLABICS BLACKFOOT NE", "h" : "15B8" },
{"g" : "\u15B9", "n" : "CANADIAN SYLLABICS BLACKFOOT NI", "h" : "15B9" },
{"g" : "\u15BA", "n" : "CANADIAN SYLLABICS BLACKFOOT NO", "h" : "15BA" },
{"g" : "\u15BB", "n" : "CANADIAN SYLLABICS BLACKFOOT NA", "h" : "15BB" },
{"g" : "\u15BC", "n" : "CANADIAN SYLLABICS BLACKFOOT KE", "h" : "15BC" },
{"g" : "\u15BD", "n" : "CANADIAN SYLLABICS BLACKFOOT KI", "h" : "15BD" },
{"g" : "\u15BE", "n" : "CANADIAN SYLLABICS BLACKFOOT KO", "h" : "15BE" },
{"g" : "\u15BF", "n" : "CANADIAN SYLLABICS BLACKFOOT KA", "h" : "15BF" },
{"g" : "\u15C0", "n" : "CANADIAN SYLLABICS SAYISI HE", "h" : "15C0" },
{"g" : "\u15C1", "n" : "CANADIAN SYLLABICS SAYISI HI", "h" : "15C1" },
{"g" : "\u15C2", "n" : "CANADIAN SYLLABICS SAYISI HO", "h" : "15C2" },
{"g" : "\u15C3", "n" : "CANADIAN SYLLABICS SAYISI HA", "h" : "15C3" },
{"g" : "\u15C4", "n" : "CANADIAN SYLLABICS CARRIER GHU", "h" : "15C4" },
{"g" : "\u15C5", "n" : "CANADIAN SYLLABICS CARRIER GHO", "h" : "15C5" },
{"g" : "\u15C6", "n" : "CANADIAN SYLLABICS CARRIER GHE", "h" : "15C6" },
{"g" : "\u15C7", "n" : "CANADIAN SYLLABICS CARRIER GHEE", "h" : "15C7" },
{"g" : "\u15C8", "n" : "CANADIAN SYLLABICS CARRIER GHI", "h" : "15C8" },
{"g" : "\u15C9", "n" : "CANADIAN SYLLABICS CARRIER GHA", "h" : "15C9" },
{"g" : "\u15CA", "n" : "CANADIAN SYLLABICS CARRIER RU", "h" : "15CA" },
{"g" : "\u15CB", "n" : "CANADIAN SYLLABICS CARRIER RO", "h" : "15CB" },
{"g" : "\u15CC", "n" : "CANADIAN SYLLABICS CARRIER RE", "h" : "15CC" },
{"g" : "\u15CD", "n" : "CANADIAN SYLLABICS CARRIER REE", "h" : "15CD" },
{"g" : "\u15CE", "n" : "CANADIAN SYLLABICS CARRIER RI", "h" : "15CE" },
{"g" : "\u15CF", "n" : "CANADIAN SYLLABICS CARRIER RA", "h" : "15CF" },
{"g" : "\u15D0", "n" : "CANADIAN SYLLABICS CARRIER WU", "h" : "15D0" },
{"g" : "\u15D1", "n" : "CANADIAN SYLLABICS CARRIER WO", "h" : "15D1" },
{"g" : "\u15D2", "n" : "CANADIAN SYLLABICS CARRIER WE", "h" : "15D2" },
{"g" : "\u15D3", "n" : "CANADIAN SYLLABICS CARRIER WEE", "h" : "15D3" },
{"g" : "\u15D4", "n" : "CANADIAN SYLLABICS CARRIER WI", "h" : "15D4" },
{"g" : "\u15D5", "n" : "CANADIAN SYLLABICS CARRIER WA", "h" : "15D5" },
{"g" : "\u15D6", "n" : "CANADIAN SYLLABICS CARRIER HWU", "h" : "15D6" },
{"g" : "\u15D7", "n" : "CANADIAN SYLLABICS CARRIER HWO", "h" : "15D7" },
{"g" : "\u15D8", "n" : "CANADIAN SYLLABICS CARRIER HWE", "h" : "15D8" },
{"g" : "\u15D9", "n" : "CANADIAN SYLLABICS CARRIER HWEE", "h" : "15D9" },
{"g" : "\u15DA", "n" : "CANADIAN SYLLABICS CARRIER HWI", "h" : "15DA" },
{"g" : "\u15DB", "n" : "CANADIAN SYLLABICS CARRIER HWA", "h" : "15DB" },
{"g" : "\u15DC", "n" : "CANADIAN SYLLABICS CARRIER THU", "h" : "15DC" },
{"g" : "\u15DD", "n" : "CANADIAN SYLLABICS CARRIER THO", "h" : "15DD" },
{"g" : "\u15DE", "n" : "CANADIAN SYLLABICS CARRIER THE", "h" : "15DE" },
{"g" : "\u15DF", "n" : "CANADIAN SYLLABICS CARRIER THEE", "h" : "15DF" },
{"g" : "\u15E0", "n" : "CANADIAN SYLLABICS CARRIER THI", "h" : "15E0" },
{"g" : "\u15E1", "n" : "CANADIAN SYLLABICS CARRIER THA", "h" : "15E1" },
{"g" : "\u15E2", "n" : "CANADIAN SYLLABICS CARRIER TTU", "h" : "15E2" },
{"g" : "\u15E3", "n" : "CANADIAN SYLLABICS CARRIER TTO", "h" : "15E3" },
{"g" : "\u15E4", "n" : "CANADIAN SYLLABICS CARRIER TTE", "h" : "15E4" },
{"g" : "\u15E5", "n" : "CANADIAN SYLLABICS CARRIER TTEE", "h" : "15E5" },
{"g" : "\u15E6", "n" : "CANADIAN SYLLABICS CARRIER TTI", "h" : "15E6" },
{"g" : "\u15E7", "n" : "CANADIAN SYLLABICS CARRIER TTA", "h" : "15E7" },
{"g" : "\u15E8", "n" : "CANADIAN SYLLABICS CARRIER PU", "h" : "15E8" },
{"g" : "\u15E9", "n" : "CANADIAN SYLLABICS CARRIER PO", "h" : "15E9" },
{"g" : "\u15EA", "n" : "CANADIAN SYLLABICS CARRIER PE", "h" : "15EA" },
{"g" : "\u15EB", "n" : "CANADIAN SYLLABICS CARRIER PEE", "h" : "15EB" },
{"g" : "\u15EC", "n" : "CANADIAN SYLLABICS CARRIER PI", "h" : "15EC" },
{"g" : "\u15ED", "n" : "CANADIAN SYLLABICS CARRIER PA", "h" : "15ED" },
{"g" : "\u15EE", "n" : "CANADIAN SYLLABICS CARRIER P", "h" : "15EE" },
{"g" : "\u15EF", "n" : "CANADIAN SYLLABICS CARRIER GU", "h" : "15EF" },
{"g" : "\u15F0", "n" : "CANADIAN SYLLABICS CARRIER GO", "h" : "15F0" },
{"g" : "\u15F1", "n" : "CANADIAN SYLLABICS CARRIER GE", "h" : "15F1" },
{"g" : "\u15F2", "n" : "CANADIAN SYLLABICS CARRIER GEE", "h" : "15F2" },
{"g" : "\u15F3", "n" : "CANADIAN SYLLABICS CARRIER GI", "h" : "15F3" },
{"g" : "\u15F4", "n" : "CANADIAN SYLLABICS CARRIER GA", "h" : "15F4" },
{"g" : "\u15F5", "n" : "CANADIAN SYLLABICS CARRIER KHU", "h" : "15F5" },
{"g" : "\u15F6", "n" : "CANADIAN SYLLABICS CARRIER KHO", "h" : "15F6" },
{"g" : "\u15F7", "n" : "CANADIAN SYLLABICS CARRIER KHE", "h" : "15F7" },
{"g" : "\u15F8", "n" : "CANADIAN SYLLABICS CARRIER KHEE", "h" : "15F8" },
{"g" : "\u15F9", "n" : "CANADIAN SYLLABICS CARRIER KHI", "h" : "15F9" },
{"g" : "\u15FA", "n" : "CANADIAN SYLLABICS CARRIER KHA", "h" : "15FA" },
{"g" : "\u15FB", "n" : "CANADIAN SYLLABICS CARRIER KKU", "h" : "15FB" },
{"g" : "\u15FC", "n" : "CANADIAN SYLLABICS CARRIER KKO", "h" : "15FC" },
{"g" : "\u15FD", "n" : "CANADIAN SYLLABICS CARRIER KKE", "h" : "15FD" },
{"g" : "\u15FE", "n" : "CANADIAN SYLLABICS CARRIER KKEE", "h" : "15FE" },
{"g" : "\u15FF", "n" : "CANADIAN SYLLABICS CARRIER KKI", "h" : "15FF" },
{"g" : "\u1600", "n" : "CANADIAN SYLLABICS CARRIER KKA", "h" : "1600" },
{"g" : "\u1601", "n" : "CANADIAN SYLLABICS CARRIER KK", "h" : "1601" },
{"g" : "\u1602", "n" : "CANADIAN SYLLABICS CARRIER NU", "h" : "1602" },
{"g" : "\u1603", "n" : "CANADIAN SYLLABICS CARRIER NO", "h" : "1603" },
{"g" : "\u1604", "n" : "CANADIAN SYLLABICS CARRIER NE", "h" : "1604" },
{"g" : "\u1605", "n" : "CANADIAN SYLLABICS CARRIER NEE", "h" : "1605" },
{"g" : "\u1606", "n" : "CANADIAN SYLLABICS CARRIER NI", "h" : "1606" },
{"g" : "\u1607", "n" : "CANADIAN SYLLABICS CARRIER NA", "h" : "1607" },
{"g" : "\u1608", "n" : "CANADIAN SYLLABICS CARRIER MU", "h" : "1608" },
{"g" : "\u1609", "n" : "CANADIAN SYLLABICS CARRIER MO", "h" : "1609" },
{"g" : "\u160A", "n" : "CANADIAN SYLLABICS CARRIER ME", "h" : "160A" },
{"g" : "\u160B", "n" : "CANADIAN SYLLABICS CARRIER MEE", "h" : "160B" },
{"g" : "\u160C", "n" : "CANADIAN SYLLABICS CARRIER MI", "h" : "160C" },
{"g" : "\u160D", "n" : "CANADIAN SYLLABICS CARRIER MA", "h" : "160D" },
{"g" : "\u160E", "n" : "CANADIAN SYLLABICS CARRIER YU", "h" : "160E" },
{"g" : "\u160F", "n" : "CANADIAN SYLLABICS CARRIER YO", "h" : "160F" },
{"g" : "\u1610", "n" : "CANADIAN SYLLABICS CARRIER YE", "h" : "1610" },
{"g" : "\u1611", "n" : "CANADIAN SYLLABICS CARRIER YEE", "h" : "1611" },
{"g" : "\u1612", "n" : "CANADIAN SYLLABICS CARRIER YI", "h" : "1612" },
{"g" : "\u1613", "n" : "CANADIAN SYLLABICS CARRIER YA", "h" : "1613" },
{"g" : "\u1614", "n" : "CANADIAN SYLLABICS CARRIER JU", "h" : "1614" },
{"g" : "\u1615", "n" : "CANADIAN SYLLABICS SAYISI JU", "h" : "1615" },
{"g" : "\u1616", "n" : "CANADIAN SYLLABICS CARRIER JO", "h" : "1616" },
{"g" : "\u1617", "n" : "CANADIAN SYLLABICS CARRIER JE", "h" : "1617" },
{"g" : "\u1618", "n" : "CANADIAN SYLLABICS CARRIER JEE", "h" : "1618" },
{"g" : "\u1619", "n" : "CANADIAN SYLLABICS CARRIER JI", "h" : "1619" },
{"g" : "\u161A", "n" : "CANADIAN SYLLABICS SAYISI JI", "h" : "161A" },
{"g" : "\u161B", "n" : "CANADIAN SYLLABICS CARRIER JA", "h" : "161B" },
{"g" : "\u161C", "n" : "CANADIAN SYLLABICS CARRIER JJU", "h" : "161C" },
{"g" : "\u161D", "n" : "CANADIAN SYLLABICS CARRIER JJO", "h" : "161D" },
{"g" : "\u161E", "n" : "CANADIAN SYLLABICS CARRIER JJE", "h" : "161E" },
{"g" : "\u161F", "n" : "CANADIAN SYLLABICS CARRIER JJEE", "h" : "161F" },
{"g" : "\u1620", "n" : "CANADIAN SYLLABICS CARRIER JJI", "h" : "1620" },
{"g" : "\u1621", "n" : "CANADIAN SYLLABICS CARRIER JJA", "h" : "1621" },
{"g" : "\u1622", "n" : "CANADIAN SYLLABICS CARRIER LU", "h" : "1622" },
{"g" : "\u1623", "n" : "CANADIAN SYLLABICS CARRIER LO", "h" : "1623" },
{"g" : "\u1624", "n" : "CANADIAN SYLLABICS CARRIER LE", "h" : "1624" },
{"g" : "\u1625", "n" : "CANADIAN SYLLABICS CARRIER LEE", "h" : "1625" },
{"g" : "\u1626", "n" : "CANADIAN SYLLABICS CARRIER LI", "h" : "1626" },
{"g" : "\u1627", "n" : "CANADIAN SYLLABICS CARRIER LA", "h" : "1627" },
{"g" : "\u1628", "n" : "CANADIAN SYLLABICS CARRIER DLU", "h" : "1628" },
{"g" : "\u1629", "n" : "CANADIAN SYLLABICS CARRIER DLO", "h" : "1629" },
{"g" : "\u162A", "n" : "CANADIAN SYLLABICS CARRIER DLE", "h" : "162A" },
{"g" : "\u162B", "n" : "CANADIAN SYLLABICS CARRIER DLEE", "h" : "162B" },
{"g" : "\u162C", "n" : "CANADIAN SYLLABICS CARRIER DLI", "h" : "162C" },
{"g" : "\u162D", "n" : "CANADIAN SYLLABICS CARRIER DLA", "h" : "162D" },
{"g" : "\u162E", "n" : "CANADIAN SYLLABICS CARRIER LHU", "h" : "162E" },
{"g" : "\u162F", "n" : "CANADIAN SYLLABICS CARRIER LHO", "h" : "162F" },
{"g" : "\u1630", "n" : "CANADIAN SYLLABICS CARRIER LHE", "h" : "1630" },
{"g" : "\u1631", "n" : "CANADIAN SYLLABICS CARRIER LHEE", "h" : "1631" },
{"g" : "\u1632", "n" : "CANADIAN SYLLABICS CARRIER LHI", "h" : "1632" },
{"g" : "\u1633", "n" : "CANADIAN SYLLABICS CARRIER LHA", "h" : "1633" },
{"g" : "\u1634", "n" : "CANADIAN SYLLABICS CARRIER TLHU", "h" : "1634" },
{"g" : "\u1635", "n" : "CANADIAN SYLLABICS CARRIER TLHO", "h" : "1635" },
{"g" : "\u1636", "n" : "CANADIAN SYLLABICS CARRIER TLHE", "h" : "1636" },
{"g" : "\u1637", "n" : "CANADIAN SYLLABICS CARRIER TLHEE", "h" : "1637" },
{"g" : "\u1638", "n" : "CANADIAN SYLLABICS CARRIER TLHI", "h" : "1638" },
{"g" : "\u1639", "n" : "CANADIAN SYLLABICS CARRIER TLHA", "h" : "1639" },
{"g" : "\u163A", "n" : "CANADIAN SYLLABICS CARRIER TLU", "h" : "163A" },
{"g" : "\u163B", "n" : "CANADIAN SYLLABICS CARRIER TLO", "h" : "163B" },
{"g" : "\u163C", "n" : "CANADIAN SYLLABICS CARRIER TLE", "h" : "163C" },
{"g" : "\u163D", "n" : "CANADIAN SYLLABICS CARRIER TLEE", "h" : "163D" },
{"g" : "\u163E", "n" : "CANADIAN SYLLABICS CARRIER TLI", "h" : "163E" },
{"g" : "\u163F", "n" : "CANADIAN SYLLABICS CARRIER TLA", "h" : "163F" },
{"g" : "\u1640", "n" : "CANADIAN SYLLABICS CARRIER ZU", "h" : "1640" },
{"g" : "\u1641", "n" : "CANADIAN SYLLABICS CARRIER ZO", "h" : "1641" },
{"g" : "\u1642", "n" : "CANADIAN SYLLABICS CARRIER ZE", "h" : "1642" },
{"g" : "\u1643", "n" : "CANADIAN SYLLABICS CARRIER ZEE", "h" : "1643" },
{"g" : "\u1644", "n" : "CANADIAN SYLLABICS CARRIER ZI", "h" : "1644" },
{"g" : "\u1645", "n" : "CANADIAN SYLLABICS CARRIER ZA", "h" : "1645" },
{"g" : "\u1646", "n" : "CANADIAN SYLLABICS CARRIER Z", "h" : "1646" },
{"g" : "\u1647", "n" : "CANADIAN SYLLABICS CARRIER INITIAL Z", "h" : "1647" },
{"g" : "\u1648", "n" : "CANADIAN SYLLABICS CARRIER DZU", "h" : "1648" },
{"g" : "\u1649", "n" : "CANADIAN SYLLABICS CARRIER DZO", "h" : "1649" },
{"g" : "\u164A", "n" : "CANADIAN SYLLABICS CARRIER DZE", "h" : "164A" },
{"g" : "\u164B", "n" : "CANADIAN SYLLABICS CARRIER DZEE", "h" : "164B" },
{"g" : "\u164C", "n" : "CANADIAN SYLLABICS CARRIER DZI", "h" : "164C" },
{"g" : "\u164D", "n" : "CANADIAN SYLLABICS CARRIER DZA", "h" : "164D" },
{"g" : "\u164E", "n" : "CANADIAN SYLLABICS CARRIER SU", "h" : "164E" },
{"g" : "\u164F", "n" : "CANADIAN SYLLABICS CARRIER SO", "h" : "164F" },
{"g" : "\u1650", "n" : "CANADIAN SYLLABICS CARRIER SE", "h" : "1650" },
{"g" : "\u1651", "n" : "CANADIAN SYLLABICS CARRIER SEE", "h" : "1651" },
{"g" : "\u1652", "n" : "CANADIAN SYLLABICS CARRIER SI", "h" : "1652" },
{"g" : "\u1653", "n" : "CANADIAN SYLLABICS CARRIER SA", "h" : "1653" },
{"g" : "\u1654", "n" : "CANADIAN SYLLABICS CARRIER SHU", "h" : "1654" },
{"g" : "\u1655", "n" : "CANADIAN SYLLABICS CARRIER SHO", "h" : "1655" },
{"g" : "\u1656", "n" : "CANADIAN SYLLABICS CARRIER SHE", "h" : "1656" },
{"g" : "\u1657", "n" : "CANADIAN SYLLABICS CARRIER SHEE", "h" : "1657" },
{"g" : "\u1658", "n" : "CANADIAN SYLLABICS CARRIER SHI", "h" : "1658" },
{"g" : "\u1659", "n" : "CANADIAN SYLLABICS CARRIER SHA", "h" : "1659" },
{"g" : "\u165A", "n" : "CANADIAN SYLLABICS CARRIER SH", "h" : "165A" },
{"g" : "\u165B", "n" : "CANADIAN SYLLABICS CARRIER TSU", "h" : "165B" },
{"g" : "\u165C", "n" : "CANADIAN SYLLABICS CARRIER TSO", "h" : "165C" },
{"g" : "\u165D", "n" : "CANADIAN SYLLABICS CARRIER TSE", "h" : "165D" },
{"g" : "\u165E", "n" : "CANADIAN SYLLABICS CARRIER TSEE", "h" : "165E" },
{"g" : "\u165F", "n" : "CANADIAN SYLLABICS CARRIER TSI", "h" : "165F" },
{"g" : "\u1660", "n" : "CANADIAN SYLLABICS CARRIER TSA", "h" : "1660" },
{"g" : "\u1661", "n" : "CANADIAN SYLLABICS CARRIER CHU", "h" : "1661" },
{"g" : "\u1662", "n" : "CANADIAN SYLLABICS CARRIER CHO", "h" : "1662" },
{"g" : "\u1663", "n" : "CANADIAN SYLLABICS CARRIER CHE", "h" : "1663" },
{"g" : "\u1664", "n" : "CANADIAN SYLLABICS CARRIER CHEE", "h" : "1664" },
{"g" : "\u1665", "n" : "CANADIAN SYLLABICS CARRIER CHI", "h" : "1665" },
{"g" : "\u1666", "n" : "CANADIAN SYLLABICS CARRIER CHA", "h" : "1666" },
{"g" : "\u1667", "n" : "CANADIAN SYLLABICS CARRIER TTSU", "h" : "1667" },
{"g" : "\u1668", "n" : "CANADIAN SYLLABICS CARRIER TTSO", "h" : "1668" },
{"g" : "\u1669", "n" : "CANADIAN SYLLABICS CARRIER TTSE", "h" : "1669" },
{"g" : "\u166A", "n" : "CANADIAN SYLLABICS CARRIER TTSEE", "h" : "166A" },
{"g" : "\u166B", "n" : "CANADIAN SYLLABICS CARRIER TTSI", "h" : "166B" },
{"g" : "\u166C", "n" : "CANADIAN SYLLABICS CARRIER TTSA", "h" : "166C" },
{"g" : "\u166D", "n" : "CANADIAN SYLLABICS CHI SIGN", "h" : "166D" },
{"g" : "\u166E", "n" : "CANADIAN SYLLABICS FULL STOP", "h" : "166E" },
{"g" : "\u166F", "n" : "CANADIAN SYLLABICS QAI", "h" : "166F" },
{"g" : "\u1670", "n" : "CANADIAN SYLLABICS NGAI", "h" : "1670" },
{"g" : "\u1671", "n" : "CANADIAN SYLLABICS NNGI", "h" : "1671" },
{"g" : "\u1672", "n" : "CANADIAN SYLLABICS NNGII", "h" : "1672" },
{"g" : "\u1673", "n" : "CANADIAN SYLLABICS NNGO", "h" : "1673" },
{"g" : "\u1674", "n" : "CANADIAN SYLLABICS NNGOO", "h" : "1674" },
{"g" : "\u1675", "n" : "CANADIAN SYLLABICS NNGA", "h" : "1675" },
{"g" : "\u1676", "n" : "CANADIAN SYLLABICS NNGAA", "h" : "1676" },
{"g" : "\u1677", "n" : "CANADIAN SYLLABICS WOODS-CREE THWEE", "h" : "1677" },
{"g" : "\u1678", "n" : "CANADIAN SYLLABICS WOODS-CREE THWI", "h" : "1678" },
{"g" : "\u1679", "n" : "CANADIAN SYLLABICS WOODS-CREE THWII", "h" : "1679" },
{"g" : "\u167A", "n" : "CANADIAN SYLLABICS WOODS-CREE THWO", "h" : "167A" },
{"g" : "\u167B", "n" : "CANADIAN SYLLABICS WOODS-CREE THWOO", "h" : "167B" },
{"g" : "\u167C", "n" : "CANADIAN SYLLABICS WOODS-CREE THWA", "h" : "167C" },
{"g" : "\u167D", "n" : "CANADIAN SYLLABICS WOODS-CREE THWAA", "h" : "167D" },
{"g" : "\u167E", "n" : "CANADIAN SYLLABICS WOODS-CREE FINAL TH", "h" : "167E" },
{"g" : "\u167F", "n" : "CANADIAN SYLLABICS BLACKFOOT W", "h" : "167F" },

{"g" : "\u18B0", "n" : "CANADIAN SYLLABICS OY", "h" : "18B0" },
{"g" : "\u18B1", "n" : "CANADIAN SYLLABICS AY", "h" : "18B1" },
{"g" : "\u18B2", "n" : "CANADIAN SYLLABICS AAY", "h" : "18B2" },
{"g" : "\u18B3", "n" : "CANADIAN SYLLABICS WAY", "h" : "18B3" },
{"g" : "\u18B4", "n" : "CANADIAN SYLLABICS POY", "h" : "18B4" },
{"g" : "\u18B5", "n" : "CANADIAN SYLLABICS PAY", "h" : "18B5" },
{"g" : "\u18B6", "n" : "CANADIAN SYLLABICS PWOY", "h" : "18B6" },
{"g" : "\u18B7", "n" : "CANADIAN SYLLABICS TAY", "h" : "18B7" },
{"g" : "\u18B8", "n" : "CANADIAN SYLLABICS KAY", "h" : "18B8" },
{"g" : "\u18B9", "n" : "CANADIAN SYLLABICS KWAY", "h" : "18B9" },
{"g" : "\u18BA", "n" : "CANADIAN SYLLABICS MAY", "h" : "18BA" },
{"g" : "\u18BB", "n" : "CANADIAN SYLLABICS NOY", "h" : "18BB" },
{"g" : "\u18BC", "n" : "CANADIAN SYLLABICS NAY", "h" : "18BC" },
{"g" : "\u18BD", "n" : "CANADIAN SYLLABICS LAY", "h" : "18BD" },
{"g" : "\u18BE", "n" : "CANADIAN SYLLABICS SOY", "h" : "18BE" },
{"g" : "\u18BF", "n" : "CANADIAN SYLLABICS SAY", "h" : "18BF" },
{"g" : "\u18C0", "n" : "CANADIAN SYLLABICS SHOY", "h" : "18C0" },
{"g" : "\u18C1", "n" : "CANADIAN SYLLABICS SHAY", "h" : "18C1" },
{"g" : "\u18C2", "n" : "CANADIAN SYLLABICS SHWOY", "h" : "18C2" },
{"g" : "\u18C3", "n" : "CANADIAN SYLLABICS YOY", "h" : "18C3" },
{"g" : "\u18C4", "n" : "CANADIAN SYLLABICS YAY", "h" : "18C4" },
{"g" : "\u18C5", "n" : "CANADIAN SYLLABICS RAY", "h" : "18C5" },
{"g" : "\u18C6", "n" : "CANADIAN SYLLABICS NWI", "h" : "18C6" },
{"g" : "\u18C7", "n" : "CANADIAN SYLLABICS OJIBWAY NWI", "h" : "18C7" },
{"g" : "\u18C8", "n" : "CANADIAN SYLLABICS NWII", "h" : "18C8" },
{"g" : "\u18C9", "n" : "CANADIAN SYLLABICS OJIBWAY NWII", "h" : "18C9" },
{"g" : "\u18CA", "n" : "CANADIAN SYLLABICS NWO", "h" : "18CA" },
{"g" : "\u18CB", "n" : "CANADIAN SYLLABICS OJIBWAY NWO", "h" : "18CB" },
{"g" : "\u18CC", "n" : "CANADIAN SYLLABICS NWOO", "h" : "18CC" },
{"g" : "\u18CD", "n" : "CANADIAN SYLLABICS OJIBWAY NWOO", "h" : "18CD" },
{"g" : "\u18CE", "n" : "CANADIAN SYLLABICS RWEE", "h" : "18CE" },
{"g" : "\u18CF", "n" : "CANADIAN SYLLABICS RWI", "h" : "18CF" },
{"g" : "\u18D0", "n" : "CANADIAN SYLLABICS RWII", "h" : "18D0" },
{"g" : "\u18D1", "n" : "CANADIAN SYLLABICS RWO", "h" : "18D1" },
{"g" : "\u18D2", "n" : "CANADIAN SYLLABICS RWOO", "h" : "18D2" },
{"g" : "\u18D3", "n" : "CANADIAN SYLLABICS RWA", "h" : "18D3" },
{"g" : "\u18D4", "n" : "CANADIAN SYLLABICS OJIBWAY P", "h" : "18D4" },
{"g" : "\u18D5", "n" : "CANADIAN SYLLABICS OJIBWAY T", "h" : "18D5" },
{"g" : "\u18D6", "n" : "CANADIAN SYLLABICS OJIBWAY K", "h" : "18D6" },
{"g" : "\u18D7", "n" : "CANADIAN SYLLABICS OJIBWAY C", "h" : "18D7" },
{"g" : "\u18D8", "n" : "CANADIAN SYLLABICS OJIBWAY M", "h" : "18D8" },
{"g" : "\u18D9", "n" : "CANADIAN SYLLABICS OJIBWAY N", "h" : "18D9" },
{"g" : "\u18DA", "n" : "CANADIAN SYLLABICS OJIBWAY S", "h" : "18DA" },
{"g" : "\u18DB", "n" : "CANADIAN SYLLABICS OJIBWAY SH", "h" : "18DB" },
{"g" : "\u18DC", "n" : "CANADIAN SYLLABICS EASTERN W", "h" : "18DC" },
{"g" : "\u18DD", "n" : "CANADIAN SYLLABICS WESTERN W", "h" : "18DD" },
{"g" : "\u18DE", "n" : "CANADIAN SYLLABICS FINAL SMALL RING", "h" : "18DE" },
{"g" : "\u18DF", "n" : "CANADIAN SYLLABICS FINAL RAISED DOT", "h" : "18DF" },
{"g" : "\u18E0", "n" : "CANADIAN SYLLABICS R-CREE RWE", "h" : "18E0" },
{"g" : "\u18E1", "n" : "CANADIAN SYLLABICS WEST-CREE LOO", "h" : "18E1" },
{"g" : "\u18E2", "n" : "CANADIAN SYLLABICS WEST-CREE LAA", "h" : "18E2" },
{"g" : "\u18E3", "n" : "CANADIAN SYLLABICS THWE", "h" : "18E3" },
{"g" : "\u18E4", "n" : "CANADIAN SYLLABICS THWA", "h" : "18E4" },
{"g" : "\u18E5", "n" : "CANADIAN SYLLABICS TTHWE", "h" : "18E5" },
{"g" : "\u18E6", "n" : "CANADIAN SYLLABICS TTHOO", "h" : "18E6" },
{"g" : "\u18E7", "n" : "CANADIAN SYLLABICS TTHAA", "h" : "18E7" },
{"g" : "\u18E8", "n" : "CANADIAN SYLLABICS TLHWE", "h" : "18E8" },
{"g" : "\u18E9", "n" : "CANADIAN SYLLABICS TLHOO", "h" : "18E9" },
{"g" : "\u18EA", "n" : "CANADIAN SYLLABICS SAYISI SHWE", "h" : "18EA" },
{"g" : "\u18EB", "n" : "CANADIAN SYLLABICS SAYISI SHOO", "h" : "18EB" },
{"g" : "\u18EC", "n" : "CANADIAN SYLLABICS SAYISI HOO", "h" : "18EC" },
{"g" : "\u18ED", "n" : "CANADIAN SYLLABICS CARRIER GWU", "h" : "18ED" },
{"g" : "\u18EE", "n" : "CANADIAN SYLLABICS CARRIER DENE GEE", "h" : "18EE" },
{"g" : "\u18EF", "n" : "CANADIAN SYLLABICS CARRIER GAA", "h" : "18EF" },
{"g" : "\u18F0", "n" : "CANADIAN SYLLABICS CARRIER GWA", "h" : "18F0" },
{"g" : "\u18F1", "n" : "CANADIAN SYLLABICS SAYISI JUU", "h" : "18F1" },
{"g" : "\u18F2", "n" : "CANADIAN SYLLABICS CARRIER JWA", "h" : "18F2" },
{"g" : "\u18F3", "n" : "CANADIAN SYLLABICS BEAVER DENE L", "h" : "18F3" },
{"g" : "\u18F4", "n" : "CANADIAN SYLLABICS BEAVER DENE R", "h" : "18F4" },
{"g" : "\u18F5", "n" : "CANADIAN SYLLABICS CARRIER DENTAL S", "h" : "18F5" },

{"g" : "\uAB70", "n" : "CHEROKEE SMALL LETTER A", "h" : "AB70"},
{"g" : "\uAB71", "n" : "CHEROKEE SMALL LETTER E", "h" : "AB71"},
{"g" : "\uAB72", "n" : "CHEROKEE SMALL LETTER I", "h" : "AB72"},
{"g" : "\uAB73", "n" : "CHEROKEE SMALL LETTER O", "h" : "AB73"},
{"g" : "\uAB74", "n" : "CHEROKEE SMALL LETTER U", "h" : "AB74"},
{"g" : "\uAB75", "n" : "CHEROKEE SMALL LETTER V", "h" : "AB75"},
{"g" : "\uAB76", "n" : "CHEROKEE SMALL LETTER GA", "h" : "AB76"},
{"g" : "\uAB77", "n" : "CHEROKEE SMALL LETTER KA", "h" : "AB77"},
{"g" : "\uAB78", "n" : "CHEROKEE SMALL LETTER GE", "h" : "AB78"},
{"g" : "\uAB79", "n" : "CHEROKEE SMALL LETTER GI", "h" : "AB79"},
{"g" : "\uAB7A", "n" : "CHEROKEE SMALL LETTER GO", "h" : "AB7A"},
{"g" : "\uAB7B", "n" : "CHEROKEE SMALL LETTER GU", "h" : "AB7B"},
{"g" : "\uAB7C", "n" : "CHEROKEE SMALL LETTER GV", "h" : "AB7C"},
{"g" : "\uAB7D", "n" : "CHEROKEE SMALL LETTER HA", "h" : "AB7D"},
{"g" : "\uAB7E", "n" : "CHEROKEE SMALL LETTER HE", "h" : "AB7E"},
{"g" : "\uAB7F", "n" : "CHEROKEE SMALL LETTER HI", "h" : "AB7F"},
{"g" : "\uAB80", "n" : "CHEROKEE SMALL LETTER HO", "h" : "AB80"},
{"g" : "\uAB81", "n" : "CHEROKEE SMALL LETTER HU", "h" : "AB81"},
{"g" : "\uAB82", "n" : "CHEROKEE SMALL LETTER HV", "h" : "AB82"},
{"g" : "\uAB83", "n" : "CHEROKEE SMALL LETTER LA", "h" : "AB83"},
{"g" : "\uAB84", "n" : "CHEROKEE SMALL LETTER LE", "h" : "AB84"},
{"g" : "\uAB85", "n" : "CHEROKEE SMALL LETTER LI", "h" : "AB85"},
{"g" : "\uAB86", "n" : "CHEROKEE SMALL LETTER LO", "h" : "AB86"},
{"g" : "\uAB87", "n" : "CHEROKEE SMALL LETTER LU", "h" : "AB87"},
{"g" : "\uAB88", "n" : "CHEROKEE SMALL LETTER LV", "h" : "AB88"},
{"g" : "\uAB89", "n" : "CHEROKEE SMALL LETTER MA", "h" : "AB89"},
{"g" : "\uAB8A", "n" : "CHEROKEE SMALL LETTER ME", "h" : "AB8A"},
{"g" : "\uAB8B", "n" : "CHEROKEE SMALL LETTER MI", "h" : "AB8B"},
{"g" : "\uAB8C", "n" : "CHEROKEE SMALL LETTER MO", "h" : "AB8C"},
{"g" : "\uAB8D", "n" : "CHEROKEE SMALL LETTER MU", "h" : "AB8D"},
{"g" : "\uAB8E", "n" : "CHEROKEE SMALL LETTER NA", "h" : "AB8E"},
{"g" : "\uAB8F", "n" : "CHEROKEE SMALL LETTER HNA", "h" : "AB8F"},
{"g" : "\uAB90", "n" : "CHEROKEE SMALL LETTER NAH", "h" : "AB90"},
{"g" : "\uAB91", "n" : "CHEROKEE SMALL LETTER NE", "h" : "AB91"},
{"g" : "\uAB92", "n" : "CHEROKEE SMALL LETTER NI", "h" : "AB92"},
{"g" : "\uAB93", "n" : "CHEROKEE SMALL LETTER NO", "h" : "AB93"},
{"g" : "\uAB94", "n" : "CHEROKEE SMALL LETTER NU", "h" : "AB94"},
{"g" : "\uAB95", "n" : "CHEROKEE SMALL LETTER NV", "h" : "AB95"},
{"g" : "\uAB96", "n" : "CHEROKEE SMALL LETTER QUA", "h" : "AB96"},
{"g" : "\uAB97", "n" : "CHEROKEE SMALL LETTER QUE", "h" : "AB97"},
{"g" : "\uAB98", "n" : "CHEROKEE SMALL LETTER QUI", "h" : "AB98"},
{"g" : "\uAB99", "n" : "CHEROKEE SMALL LETTER QUO", "h" : "AB99"},
{"g" : "\uAB9A", "n" : "CHEROKEE SMALL LETTER QUU", "h" : "AB9A"},
{"g" : "\uAB9B", "n" : "CHEROKEE SMALL LETTER QUV", "h" : "AB9B"},
{"g" : "\uAB9C", "n" : "CHEROKEE SMALL LETTER SA", "h" : "AB9C"},
{"g" : "\uAB9D", "n" : "CHEROKEE SMALL LETTER S", "h" : "AB9D"},
{"g" : "\uAB9E", "n" : "CHEROKEE SMALL LETTER SE", "h" : "AB9E"},
{"g" : "\uAB9F", "n" : "CHEROKEE SMALL LETTER SI", "h" : "AB9F"},
{"g" : "\uABA0", "n" : "CHEROKEE SMALL LETTER SO", "h" : "ABA0"},
{"g" : "\uABA1", "n" : "CHEROKEE SMALL LETTER SU", "h" : "ABA1"},
{"g" : "\uABA2", "n" : "CHEROKEE SMALL LETTER SV", "h" : "ABA2"},
{"g" : "\uABA3", "n" : "CHEROKEE SMALL LETTER DA", "h" : "ABA3"},
{"g" : "\uABA4", "n" : "CHEROKEE SMALL LETTER TA", "h" : "ABA4"},
{"g" : "\uABA5", "n" : "CHEROKEE SMALL LETTER DE", "h" : "ABA5"},
{"g" : "\uABA6", "n" : "CHEROKEE SMALL LETTER TE", "h" : "ABA6"},
{"g" : "\uABA7", "n" : "CHEROKEE SMALL LETTER DI", "h" : "ABA7"},
{"g" : "\uABA8", "n" : "CHEROKEE SMALL LETTER TI", "h" : "ABA8"},
{"g" : "\uABA9", "n" : "CHEROKEE SMALL LETTER DO", "h" : "ABA9"},
{"g" : "\uABAA", "n" : "CHEROKEE SMALL LETTER DU", "h" : "ABAA"},
{"g" : "\uABAB", "n" : "CHEROKEE SMALL LETTER DV", "h" : "ABAB"},
{"g" : "\uABAC", "n" : "CHEROKEE SMALL LETTER DLA", "h" : "ABAC"},
{"g" : "\uABAD", "n" : "CHEROKEE SMALL LETTER TLA", "h" : "ABAD"},
{"g" : "\uABAE", "n" : "CHEROKEE SMALL LETTER TLE", "h" : "ABAE"},
{"g" : "\uABAF", "n" : "CHEROKEE SMALL LETTER TLI", "h" : "ABAF"},
{"g" : "\uABB0", "n" : "CHEROKEE SMALL LETTER TLO", "h" : "ABB0"},
{"g" : "\uABB1", "n" : "CHEROKEE SMALL LETTER TLU", "h" : "ABB1"},
{"g" : "\uABB2", "n" : "CHEROKEE SMALL LETTER TLV", "h" : "ABB2"},
{"g" : "\uABB3", "n" : "CHEROKEE SMALL LETTER TSA", "h" : "ABB3"},
{"g" : "\uABB4", "n" : "CHEROKEE SMALL LETTER TSE", "h" : "ABB4"},
{"g" : "\uABB5", "n" : "CHEROKEE SMALL LETTER TSI", "h" : "ABB5"},
{"g" : "\uABB6", "n" : "CHEROKEE SMALL LETTER TSO", "h" : "ABB6"},
{"g" : "\uABB7", "n" : "CHEROKEE SMALL LETTER TSU", "h" : "ABB7"},
{"g" : "\uABB8", "n" : "CHEROKEE SMALL LETTER TSV", "h" : "ABB8"},
{"g" : "\uABB9", "n" : "CHEROKEE SMALL LETTER WA", "h" : "ABB9"},
{"g" : "\uABBA", "n" : "CHEROKEE SMALL LETTER WE", "h" : "ABBA"},
{"g" : "\uABBB", "n" : "CHEROKEE SMALL LETTER WI", "h" : "ABBB"},
{"g" : "\uABBC", "n" : "CHEROKEE SMALL LETTER WO", "h" : "ABBC"},
{"g" : "\uABBD", "n" : "CHEROKEE SMALL LETTER WU", "h" : "ABBD"},
{"g" : "\uABBE", "n" : "CHEROKEE SMALL LETTER WV", "h" : "ABBE"},
{"g" : "\uABBF", "n" : "CHEROKEE SMALL LETTER YA", "h" : "ABBF"},

{"g" : "\u{10400}", "n" : "DESERET CAPITAL LETTER LONG I", "h" : "10400"},
{"g" : "\u{10401}", "n" : "DESERET CAPITAL LETTER LONG E", "h" : "10401"},
{"g" : "\u{10402}", "n" : "DESERET CAPITAL LETTER LONG A", "h" : "10402"},
{"g" : "\u{10403}", "n" : "DESERET CAPITAL LETTER LONG AH", "h" : "10403"},
{"g" : "\u{10404}", "n" : "DESERET CAPITAL LETTER LONG O", "h" : "10404"},
{"g" : "\u{10405}", "n" : "DESERET CAPITAL LETTER LONG OO", "h" : "10405"},
{"g" : "\u{10406}", "n" : "DESERET CAPITAL LETTER SHORT I", "h" : "10406"},
{"g" : "\u{10407}", "n" : "DESERET CAPITAL LETTER SHORT E", "h" : "10407"},
{"g" : "\u{10408}", "n" : "DESERET CAPITAL LETTER SHORT A", "h" : "10408"},
{"g" : "\u{10409}", "n" : "DESERET CAPITAL LETTER SHORT AH", "h" : "10409"},
{"g" : "\u{1040A}", "n" : "DESERET CAPITAL LETTER SHORT O", "h" : "1040A"},
{"g" : "\u{1040B}", "n" : "DESERET CAPITAL LETTER SHORT OO", "h" : "1040B"},
{"g" : "\u{1040C}", "n" : "DESERET CAPITAL LETTER AY", "h" : "1040C"},
{"g" : "\u{1040D}", "n" : "DESERET CAPITAL LETTER OW", "h" : "1040D"},
{"g" : "\u{1040E}", "n" : "DESERET CAPITAL LETTER WU", "h" : "1040E"},
{"g" : "\u{1040F}", "n" : "DESERET CAPITAL LETTER YEE", "h" : "1040F"},
{"g" : "\u{10410}", "n" : "DESERET CAPITAL LETTER H", "h" : "10410"},
{"g" : "\u{10411}", "n" : "DESERET CAPITAL LETTER PEE", "h" : "10411"},
{"g" : "\u{10412}", "n" : "DESERET CAPITAL LETTER BEE", "h" : "10412"},
{"g" : "\u{10413}", "n" : "DESERET CAPITAL LETTER TEE", "h" : "10413"},
{"g" : "\u{10414}", "n" : "DESERET CAPITAL LETTER DEE", "h" : "10414"},
{"g" : "\u{10415}", "n" : "DESERET CAPITAL LETTER CHEE", "h" : "10415"},
{"g" : "\u{10416}", "n" : "DESERET CAPITAL LETTER JEE", "h" : "10416"},
{"g" : "\u{10417}", "n" : "DESERET CAPITAL LETTER KAY", "h" : "10417"},
{"g" : "\u{10418}", "n" : "DESERET CAPITAL LETTER GAY", "h" : "10418"},
{"g" : "\u{10419}", "n" : "DESERET CAPITAL LETTER EF", "h" : "10419"},
{"g" : "\u{1041A}", "n" : "DESERET CAPITAL LETTER VEE", "h" : "1041A"},
{"g" : "\u{1041B}", "n" : "DESERET CAPITAL LETTER ETH", "h" : "1041B"},
{"g" : "\u{1041C}", "n" : "DESERET CAPITAL LETTER THEE", "h" : "1041C"},
{"g" : "\u{1041D}", "n" : "DESERET CAPITAL LETTER ES", "h" : "1041D"},
{"g" : "\u{1041E}", "n" : "DESERET CAPITAL LETTER ZEE", "h" : "1041E"},
{"g" : "\u{1041F}", "n" : "DESERET CAPITAL LETTER ESH", "h" : "1041F"},
{"g" : "\u{10420}", "n" : "DESERET CAPITAL LETTER ZHEE", "h" : "10420"},
{"g" : "\u{10421}", "n" : "DESERET CAPITAL LETTER ER", "h" : "10421"},
{"g" : "\u{10422}", "n" : "DESERET CAPITAL LETTER EL", "h" : "10422"},
{"g" : "\u{10423}", "n" : "DESERET CAPITAL LETTER EM", "h" : "10423"},
{"g" : "\u{10424}", "n" : "DESERET CAPITAL LETTER EN", "h" : "10424"},
{"g" : "\u{10425}", "n" : "DESERET CAPITAL LETTER ENG", "h" : "10425"},
{"g" : "\u{10426}", "n" : "DESERET CAPITAL LETTER OI", "h" : "10426"},
{"g" : "\u{10427}", "n" : "DESERET CAPITAL LETTER EW", "h" : "10427"},
{"g" : "\u{10428}", "n" : "DESERET SMALL LETTER LONG I", "h" : "10428"},
{"g" : "\u{10429}", "n" : "DESERET SMALL LETTER LONG E", "h" : "10429"},
{"g" : "\u{1042A}", "n" : "DESERET SMALL LETTER LONG A", "h" : "1042A"},
{"g" : "\u{1042B}", "n" : "DESERET SMALL LETTER LONG AH", "h" : "1042B"},
{"g" : "\u{1042C}", "n" : "DESERET SMALL LETTER LONG O", "h" : "1042C"},
{"g" : "\u{1042D}", "n" : "DESERET SMALL LETTER LONG OO", "h" : "1042D"},
{"g" : "\u{1042E}", "n" : "DESERET SMALL LETTER SHORT I", "h" : "1042E"},
{"g" : "\u{1042F}", "n" : "DESERET SMALL LETTER SHORT E", "h" : "1042F"},
{"g" : "\u{10430}", "n" : "DESERET SMALL LETTER SHORT A", "h" : "10430"},
{"g" : "\u{10431}", "n" : "DESERET SMALL LETTER SHORT AH", "h" : "10431"},
{"g" : "\u{10432}", "n" : "DESERET SMALL LETTER SHORT O", "h" : "10432"},
{"g" : "\u{10433}", "n" : "DESERET SMALL LETTER SHORT OO", "h" : "10433"},
{"g" : "\u{10434}", "n" : "DESERET SMALL LETTER AY", "h" : "10434"},
{"g" : "\u{10435}", "n" : "DESERET SMALL LETTER OW", "h" : "10435"},
{"g" : "\u{10436}", "n" : "DESERET SMALL LETTER WU", "h" : "10436"},
{"g" : "\u{10437}", "n" : "DESERET SMALL LETTER YEE", "h" : "10437"},
{"g" : "\u{10438}", "n" : "DESERET SMALL LETTER H", "h" : "10438"},
{"g" : "\u{10439}", "n" : "DESERET SMALL LETTER PEE", "h" : "10439"},
{"g" : "\u{1043A}", "n" : "DESERET SMALL LETTER BEE", "h" : "1043A"},
{"g" : "\u{1043B}", "n" : "DESERET SMALL LETTER TEE", "h" : "1043B"},
{"g" : "\u{1043C}", "n" : "DESERET SMALL LETTER DEE", "h" : "1043C"},
{"g" : "\u{1043D}", "n" : "DESERET SMALL LETTER CHEE", "h" : "1043D"},
{"g" : "\u{1043E}", "n" : "DESERET SMALL LETTER JEE", "h" : "1043E"},
{"g" : "\u{1043F}", "n" : "DESERET SMALL LETTER KAY", "h" : "1043F"},
{"g" : "\u{10440}", "n" : "DESERET SMALL LETTER GAY", "h" : "10440"},
{"g" : "\u{10441}", "n" : "DESERET SMALL LETTER EF", "h" : "10441"},
{"g" : "\u{10442}", "n" : "DESERET SMALL LETTER VEE", "h" : "10442"},
{"g" : "\u{10443}", "n" : "DESERET SMALL LETTER ETH", "h" : "10443"},
{"g" : "\u{10444}", "n" : "DESERET SMALL LETTER THEE", "h" : "10444"},
{"g" : "\u{10445}", "n" : "DESERET SMALL LETTER ES", "h" : "10445"},
{"g" : "\u{10446}", "n" : "DESERET SMALL LETTER ZEE", "h" : "10446"},
{"g" : "\u{10447}", "n" : "DESERET SMALL LETTER ESH", "h" : "10447"},
{"g" : "\u{10448}", "n" : "DESERET SMALL LETTER ZHEE", "h" : "10448"},
{"g" : "\u{10449}", "n" : "DESERET SMALL LETTER ER", "h" : "10449"},
{"g" : "\u{1044A}", "n" : "DESERET SMALL LETTER EL", "h" : "1044A"},
{"g" : "\u{1044B}", "n" : "DESERET SMALL LETTER EM", "h" : "1044B"},
{"g" : "\u{1044C}", "n" : "DESERET SMALL LETTER EN", "h" : "1044C"},
{"g" : "\u{1044D}", "n" : "DESERET SMALL LETTER ENG", "h" : "1044D"},
{"g" : "\u{1044E}", "n" : "DESERET SMALL LETTER OI", "h" : "1044E"},
{"g" : "\u{1044F}", "n" : "DESERET SMALL LETTER EW", "h" : "1044F"},

{"g" : "\u{104B0}", "n" : "OSAGE CAPITAL LETTER A", "h" : "104B0"},
{"g" : "\u{104B1}", "n" : "OSAGE CAPITAL LETTER AI", "h" : "104B1"},
{"g" : "\u{104B2}", "n" : "OSAGE CAPITAL LETTER AIN", "h" : "104B2"},
{"g" : "\u{104B3}", "n" : "OSAGE CAPITAL LETTER AH", "h" : "104B3"},
{"g" : "\u{104B4}", "n" : "OSAGE CAPITAL LETTER BRA", "h" : "104B4"},
{"g" : "\u{104B5}", "n" : "OSAGE CAPITAL LETTER CHA", "h" : "104B5"},
{"g" : "\u{104B6}", "n" : "OSAGE CAPITAL LETTER EHCHA", "h" : "104B6"},
{"g" : "\u{104B7}", "n" : "OSAGE CAPITAL LETTER E", "h" : "104B7"},
{"g" : "\u{104B8}", "n" : "OSAGE CAPITAL LETTER EIN", "h" : "104B8"},
{"g" : "\u{104B9}", "n" : "OSAGE CAPITAL LETTER HA", "h" : "104B9"},
{"g" : "\u{104BA}", "n" : "OSAGE CAPITAL LETTER HYA", "h" : "104BA"},
{"g" : "\u{104BB}", "n" : "OSAGE CAPITAL LETTER I", "h" : "104BB"},
{"g" : "\u{104BC}", "n" : "OSAGE CAPITAL LETTER KA", "h" : "104BC"},
{"g" : "\u{104BD}", "n" : "OSAGE CAPITAL LETTER EHKA", "h" : "104BD"},
{"g" : "\u{104BE}", "n" : "OSAGE CAPITAL LETTER KYA", "h" : "104BE"},
{"g" : "\u{104BF}", "n" : "OSAGE CAPITAL LETTER LA", "h" : "104BF"},
{"g" : "\u{104C0}", "n" : "OSAGE CAPITAL LETTER MA", "h" : "104C0"},
{"g" : "\u{104C1}", "n" : "OSAGE CAPITAL LETTER NA", "h" : "104C1"},
{"g" : "\u{104C2}", "n" : "OSAGE CAPITAL LETTER O", "h" : "104C2"},
{"g" : "\u{104C3}", "n" : "OSAGE CAPITAL LETTER OIN", "h" : "104C3"},
{"g" : "\u{104C4}", "n" : "OSAGE CAPITAL LETTER PA", "h" : "104C4"},
{"g" : "\u{104C5}", "n" : "OSAGE CAPITAL LETTER EHPA", "h" : "104C5"},
{"g" : "\u{104C6}", "n" : "OSAGE CAPITAL LETTER SA", "h" : "104C6"},
{"g" : "\u{104C7}", "n" : "OSAGE CAPITAL LETTER SHA", "h" : "104C7"},
{"g" : "\u{104C8}", "n" : "OSAGE CAPITAL LETTER TA", "h" : "104C8"},
{"g" : "\u{104C9}", "n" : "OSAGE CAPITAL LETTER EHTA", "h" : "104C9"},
{"g" : "\u{104CA}", "n" : "OSAGE CAPITAL LETTER TSA", "h" : "104CA"},
{"g" : "\u{104CB}", "n" : "OSAGE CAPITAL LETTER EHTSA", "h" : "104CB"},
{"g" : "\u{104CC}", "n" : "OSAGE CAPITAL LETTER TSHA", "h" : "104CC"},
{"g" : "\u{104CD}", "n" : "OSAGE CAPITAL LETTER DHA", "h" : "104CD"},
{"g" : "\u{104CE}", "n" : "OSAGE CAPITAL LETTER U", "h" : "104CE"},
{"g" : "\u{104CF}", "n" : "OSAGE CAPITAL LETTER WA", "h" : "104CF"},
{"g" : "\u{104D0}", "n" : "OSAGE CAPITAL LETTER KHA", "h" : "104D0"},
{"g" : "\u{104D1}", "n" : "OSAGE CAPITAL LETTER GHA", "h" : "104D1"},
{"g" : "\u{104D2}", "n" : "OSAGE CAPITAL LETTER ZA", "h" : "104D2"},
{"g" : "\u{104D3}", "n" : "OSAGE CAPITAL LETTER ZHA", "h" : "104D3"},

{"g" : "\u{104D8}", "n" : "OSAGE SMALL LETTER A", "h" : "104D8"},
{"g" : "\u{104D9}", "n" : "OSAGE SMALL LETTER AI", "h" : "104D9"},
{"g" : "\u{104DA}", "n" : "OSAGE SMALL LETTER AIN", "h" : "104DA"},
{"g" : "\u{104DB}", "n" : "OSAGE SMALL LETTER AH", "h" : "104DB"},
{"g" : "\u{104DC}", "n" : "OSAGE SMALL LETTER BRA", "h" : "104DC"},
{"g" : "\u{104DD}", "n" : "OSAGE SMALL LETTER CHA", "h" : "104DD"},
{"g" : "\u{104DE}", "n" : "OSAGE SMALL LETTER EHCHA", "h" : "104DE"},
{"g" : "\u{104DF}", "n" : "OSAGE SMALL LETTER E", "h" : "104DF"},
{"g" : "\u{104E0}", "n" : "OSAGE SMALL LETTER EIN", "h" : "104E0"},
{"g" : "\u{104E1}", "n" : "OSAGE SMALL LETTER HA", "h" : "104E1"},
{"g" : "\u{104E2}", "n" : "OSAGE SMALL LETTER HYA", "h" : "104E2"},
{"g" : "\u{104E3}", "n" : "OSAGE SMALL LETTER I", "h" : "104E3"},
{"g" : "\u{104E4}", "n" : "OSAGE SMALL LETTER KA", "h" : "104E4"},
{"g" : "\u{104E5}", "n" : "OSAGE SMALL LETTER EHKA", "h" : "104E5"},
{"g" : "\u{104E6}", "n" : "OSAGE SMALL LETTER KYA", "h" : "104E6"},
{"g" : "\u{104E7}", "n" : "OSAGE SMALL LETTER LA", "h" : "104E7"},
{"g" : "\u{104E8}", "n" : "OSAGE SMALL LETTER MA", "h" : "104E8"},
{"g" : "\u{104E9}", "n" : "OSAGE SMALL LETTER NA", "h" : "104E9"},
{"g" : "\u{104EA}", "n" : "OSAGE SMALL LETTER O", "h" : "104EA"},
{"g" : "\u{104EB}", "n" : "OSAGE SMALL LETTER OIN", "h" : "104EB"},
{"g" : "\u{104EC}", "n" : "OSAGE SMALL LETTER PA", "h" : "104EC"},
{"g" : "\u{104ED}", "n" : "OSAGE SMALL LETTER EHPA", "h" : "104ED"},
{"g" : "\u{104EE}", "n" : "OSAGE SMALL LETTER SA", "h" : "104EE"},
{"g" : "\u{104EF}", "n" : "OSAGE SMALL LETTER SHA", "h" : "104EF"},
{"g" : "\u{104F0}", "n" : "OSAGE SMALL LETTER TA", "h" : "104F0"},
{"g" : "\u{104F1}", "n" : "OSAGE SMALL LETTER EHTA", "h" : "104F1"},
{"g" : "\u{104F2}", "n" : "OSAGE SMALL LETTER TSA", "h" : "104F2"},
{"g" : "\u{104F3}", "n" : "OSAGE SMALL LETTER EHTSA", "h" : "104F3"},
{"g" : "\u{104F4}", "n" : "OSAGE SMALL LETTER TSHA", "h" : "104F4"},
{"g" : "\u{104F5}", "n" : "OSAGE SMALL LETTER DHA", "h" : "104F5"},
{"g" : "\u{104F6}", "n" : "OSAGE SMALL LETTER U", "h" : "104F6"},
{"g" : "\u{104F7}", "n" : "OSAGE SMALL LETTER WA", "h" : "104F7"},
{"g" : "\u{104F8}", "n" : "OSAGE SMALL LETTER KHA", "h" : "104F8"},
{"g" : "\u{104F9}", "n" : "OSAGE SMALL LETTER GHA", "h" : "104F9"},
{"g" : "\u{104FA}", "n" : "OSAGE SMALL LETTER ZA", "h" : "104FA"},
{"g" : "\u{104FB}", "n" : "OSAGE SMALL LETTER ZHA", "h" : "104FB"},

{"g" : "\u{1D2E0}", "n" : "MAYAN NUMERAL ZERO", "h" : "1D2E0"},
{"g" : "\u{1D2E1}", "n" : "MAYAN NUMERAL ONE", "h" : "1D2E1"},
{"g" : "\u{1D2E2}", "n" : "MAYAN NUMERAL TWO", "h" : "1D2E2"},
{"g" : "\u{1D2E3}", "n" : "MAYAN NUMERAL THREE", "h" : "1D2E3"},
{"g" : "\u{1D2E4}", "n" : "MAYAN NUMERAL FOUR", "h" : "1D2E4"},
{"g" : "\u{1D2E5}", "n" : "MAYAN NUMERAL FIVE", "h" : "1D2E5"},
{"g" : "\u{1D2E6}", "n" : "MAYAN NUMERAL SIX", "h" : "1D2E6"},
{"g" : "\u{1D2E7}", "n" : "MAYAN NUMERAL SEVEN", "h" : "1D2E7"},
{"g" : "\u{1D2E8}", "n" : "MAYAN NUMERAL EIGHT", "h" : "1D2E8"},
{"g" : "\u{1D2E9}", "n" : "MAYAN NUMERAL NINE", "h" : "1D2E9"},
{"g" : "\u{1D2EA}", "n" : "MAYAN NUMERAL TEN", "h" : "1D2EA"},
{"g" : "\u{1D2EB}", "n" : "MAYAN NUMERAL ELEVEN", "h" : "1D2EB"},
{"g" : "\u{1D2EC}", "n" : "MAYAN NUMERAL TWELVE", "h" : "1D2EC"},
{"g" : "\u{1D2ED}", "n" : "MAYAN NUMERAL THIRTEEN", "h" : "1D2ED"},
{"g" : "\u{1D2EE}", "n" : "MAYAN NUMERAL FOURTEEN", "h" : "1D2EE"},
{"g" : "\u{1D2EF}", "n" : "MAYAN NUMERAL FIFTEEN", "h" : "1D2EF"},
{"g" : "\u{1D2F0}", "n" : "MAYAN NUMERAL SIXTEEN", "h" : "1D2F0"},
{"g" : "\u{1D2F1}", "n" : "MAYAN NUMERAL SEVENTEEN", "h" : "1D2F1"},
{"g" : "\u{1D2F2}", "n" : "MAYAN NUMERAL EIGHTEEN", "h" : "1D2F2"},
{"g" : "\u{1D2F3}", "n" : "MAYAN NUMERAL NINETEEN", "h" : "1D2F3"}
];
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    	var myPara1 = document.createElement('p');
    	var myPara2 = document.createElement('p');
    	var myPara3 = document.createElement('p');
		  var myPara4 = document.createElement('p');
		  var myPara5 = document.createElement('p');
		  var myPara6 = document.createElement('p');

    	myPara1.textContent = glyph;
    	myPara2.textContent = name;
    	myPara3.textContent = 'U+' + hex;
		  myPara4.textContent = '&#x' + hex + ';';
		  myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
		  myPara6.textContent = '\\' + 'u' + hex;

    	myArticle.appendChild(myPara1);
    	myArticle.appendChild(myPara2);
    	myArticle.appendChild(myPara3);
		  myArticle.appendChild(myPara4);
		  myArticle.appendChild(myPara5);
		  myArticle.appendChild(myPara6);

    section.appendChild(myArticle);
  }
}
