var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u0F00", "n" : "TIBETAN SYLLABLE OM", "h" : "0F00" },
{"g" : "\u0F01", "n" : "TIBETAN MARK GTER YIG MGO TRUNCATED A", "h" : "0F01" },
{"g" : "\u0F02", "n" : "TIBETAN MARK GTER YIG MGO -UM RNAM BCAD MA", "h" : "0F02" },
{"g" : "\u0F03", "n" : "TIBETAN MARK GTER YIG MGO -UM GTER TSHEG MA", "h" : "0F03" },
{"g" : "\u0F04", "n" : "TIBETAN MARK INITIAL YIG MGO MDUN MA", "h" : "0F04" },
{"g" : "\u0F05", "n" : "TIBETAN MARK CLOSING YIG MGO SGAB MA", "h" : "0F05" },
{"g" : "\u0F06", "n" : "TIBETAN MARK CARET YIG MGO PHUR SHAD MA", "h" : "0F06" },
{"g" : "\u0F07", "n" : "TIBETAN MARK YIG MGO TSHEG SHAD MA", "h" : "0F07" },
{"g" : "\u0F08", "n" : "TIBETAN MARK SBRUL SHAD", "h" : "0F08" },
{"g" : "\u0F09", "n" : "TIBETAN MARK BSKUR YIG MGO", "h" : "0F09" },
{"g" : "\u0F0A", "n" : "TIBETAN MARK BKA- SHOG YIG MGO", "h" : "0F0A" },
{"g" : "\u0F0B", "n" : "TIBETAN MARK INTERSYLLABIC TSHEG", "h" : "0F0B" },
{"g" : "\u0F0C", "n" : "TIBETAN MARK DELIMITER TSHEG BSTAR", "h" : "0F0C" },
{"g" : "\u0F0D", "n" : "TIBETAN MARK SHAD", "h" : "0F0D" },
{"g" : "\u0F0E", "n" : "TIBETAN MARK NYIS SHAD", "h" : "0F0E" },
{"g" : "\u0F0F", "n" : "TIBETAN MARK TSHEG SHAD", "h" : "0F0F" },
{"g" : "\u0F10", "n" : "TIBETAN MARK NYIS TSHEG SHAD", "h" : "0F10" },
{"g" : "\u0F11", "n" : "TIBETAN MARK RIN CHEN SPUNGS SHAD", "h" : "0F11" },
{"g" : "\u0F12", "n" : "TIBETAN MARK RGYA GRAM SHAD", "h" : "0F12" },
{"g" : "\u0F13", "n" : "TIBETAN MARK CARET -DZUD RTAGS ME LONG CAN", "h" : "0F13" },
{"g" : "\u0F14", "n" : "TIBETAN MARK GTER TSHEG", "h" : "0F14" },
{"g" : "\u0F15", "n" : "TIBETAN LOGOTYPE SIGN CHAD RTAGS", "h" : "0F15" },
{"g" : "\u0F16", "n" : "TIBETAN LOGOTYPE SIGN LHAG RTAGS", "h" : "0F16" },
{"g" : "\u0F17", "n" : "TIBETAN ASTROLOGICAL SIGN SGRA GCAN -CHAR RTAGS", "h" : "0F17" },
{"g" : "\u0F18", "n" : "TIBETAN ASTROLOGICAL SIGN -KHYUD PA", "h" : "0F18" },
{"g" : "\u0F19", "n" : "TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS", "h" : "0F19" },
{"g" : "\u0F1A", "n" : "TIBETAN SIGN RDEL DKAR GCIG", "h" : "0F1A" },
{"g" : "\u0F1B", "n" : "TIBETAN SIGN RDEL DKAR GNYIS", "h" : "0F1B" },
{"g" : "\u0F1C", "n" : "TIBETAN SIGN RDEL DKAR GSUM", "h" : "0F1C" },
{"g" : "\u0F1D", "n" : "TIBETAN SIGN RDEL NAG GCIG", "h" : "0F1D" },
{"g" : "\u0F1E", "n" : "TIBETAN SIGN RDEL NAG GNYIS", "h" : "0F1E" },
{"g" : "\u0F1F", "n" : "TIBETAN SIGN RDEL DKAR RDEL NAG", "h" : "0F1F" },
{"g" : "\u0F20", "n" : "TIBETAN DIGIT ZERO", "h" : "0F20" },
{"g" : "\u0F21", "n" : "TIBETAN DIGIT ONE", "h" : "0F21" },
{"g" : "\u0F22", "n" : "TIBETAN DIGIT TWO", "h" : "0F22" },
{"g" : "\u0F23", "n" : "TIBETAN DIGIT THREE", "h" : "0F23" },
{"g" : "\u0F24", "n" : "TIBETAN DIGIT FOUR", "h" : "0F24" },
{"g" : "\u0F25", "n" : "TIBETAN DIGIT FIVE", "h" : "0F25" },
{"g" : "\u0F26", "n" : "TIBETAN DIGIT SIX", "h" : "0F26" },
{"g" : "\u0F27", "n" : "TIBETAN DIGIT SEVEN", "h" : "0F27" },
{"g" : "\u0F28", "n" : "TIBETAN DIGIT EIGHT", "h" : "0F28" },
{"g" : "\u0F29", "n" : "TIBETAN DIGIT NINE", "h" : "0F29" },
{"g" : "\u0F2A", "n" : "TIBETAN DIGIT HALF ONE", "h" : "0F2A" },
{"g" : "\u0F2B", "n" : "TIBETAN DIGIT HALF TWO", "h" : "0F2B" },
{"g" : "\u0F2C", "n" : "TIBETAN DIGIT HALF THREE", "h" : "0F2C" },
{"g" : "\u0F2D", "n" : "TIBETAN DIGIT HALF FOUR", "h" : "0F2D" },
{"g" : "\u0F2E", "n" : "TIBETAN DIGIT HALF FIVE", "h" : "0F2E" },
{"g" : "\u0F2F", "n" : "TIBETAN DIGIT HALF SIX", "h" : "0F2F" },
{"g" : "\u0F30", "n" : "TIBETAN DIGIT HALF SEVEN", "h" : "0F30" },
{"g" : "\u0F31", "n" : "TIBETAN DIGIT HALF EIGHT", "h" : "0F31" },
{"g" : "\u0F32", "n" : "TIBETAN DIGIT HALF NINE", "h" : "0F32" },
{"g" : "\u0F33", "n" : "TIBETAN DIGIT HALF ZERO", "h" : "0F33" },
{"g" : "\u0F34", "n" : "TIBETAN MARK BSDUS RTAGS", "h" : "0F34" },
{"g" : "\u0F35", "n" : "TIBETAN MARK NGAS BZUNG NYI ZLA", "h" : "0F35" },
{"g" : "\u0F36", "n" : "TIBETAN MARK CARET -DZUD RTAGS BZHI MIG CAN", "h" : "0F36" },
{"g" : "\u0F37", "n" : "TIBETAN MARK NGAS BZUNG SGOR RTAGS", "h" : "0F37" },
{"g" : "\u0F38", "n" : "TIBETAN MARK CHE MGO", "h" : "0F38" },
{"g" : "\u0F39", "n" : "TIBETAN MARK TSA -PHRU", "h" : "0F39" },
{"g" : "\u0F3A", "n" : "TIBETAN MARK GUG RTAGS GYON", "h" : "0F3A" },
{"g" : "\u0F3B", "n" : "TIBETAN MARK GUG RTAGS GYAS", "h" : "0F3B" },
{"g" : "\u0F3C", "n" : "TIBETAN MARK ANG KHANG GYON", "h" : "0F3C" },
{"g" : "\u0F3D", "n" : "TIBETAN MARK ANG KHANG GYAS", "h" : "0F3D" },
{"g" : "\u0F3E", "n" : "TIBETAN SIGN YAR TSHES", "h" : "0F3E" },
{"g" : "\u0F3F", "n" : "TIBETAN SIGN MAR TSHES", "h" : "0F3F" },
{"g" : "\u0F40", "n" : "TIBETAN LETTER KA", "h" : "0F40" },
{"g" : "\u0F41", "n" : "TIBETAN LETTER KHA", "h" : "0F41" },
{"g" : "\u0F42", "n" : "TIBETAN LETTER GA", "h" : "0F42" },
{"g" : "\u0F43", "n" : "TIBETAN LETTER GHA", "h" : "0F43" },
{"g" : "\u0F44", "n" : "TIBETAN LETTER NGA", "h" : "0F44" },
{"g" : "\u0F45", "n" : "TIBETAN LETTER CA", "h" : "0F45" },
{"g" : "\u0F46", "n" : "TIBETAN LETTER CHA", "h" : "0F46" },
{"g" : "\u0F47", "n" : "TIBETAN LETTER JA", "h" : "0F47" },

{"g" : "\u0F49", "n" : "TIBETAN LETTER NYA", "h" : "0F49" },
{"g" : "\u0F4A", "n" : "TIBETAN LETTER TTA", "h" : "0F4A" },
{"g" : "\u0F4B", "n" : "TIBETAN LETTER TTHA", "h" : "0F4B" },
{"g" : "\u0F4C", "n" : "TIBETAN LETTER DDA", "h" : "0F4C" },
{"g" : "\u0F4D", "n" : "TIBETAN LETTER DDHA", "h" : "0F4D" },
{"g" : "\u0F4E", "n" : "TIBETAN LETTER NNA", "h" : "0F4E" },
{"g" : "\u0F4F", "n" : "TIBETAN LETTER TA", "h" : "0F4F" },
{"g" : "\u0F50", "n" : "TIBETAN LETTER THA", "h" : "0F50" },
{"g" : "\u0F51", "n" : "TIBETAN LETTER DA", "h" : "0F51" },
{"g" : "\u0F52", "n" : "TIBETAN LETTER DHA", "h" : "0F52" },
{"g" : "\u0F53", "n" : "TIBETAN LETTER NA", "h" : "0F53" },
{"g" : "\u0F54", "n" : "TIBETAN LETTER PA", "h" : "0F54" },
{"g" : "\u0F55", "n" : "TIBETAN LETTER PHA", "h" : "0F55" },
{"g" : "\u0F56", "n" : "TIBETAN LETTER BA", "h" : "0F56" },
{"g" : "\u0F57", "n" : "TIBETAN LETTER BHA", "h" : "0F57" },
{"g" : "\u0F58", "n" : "TIBETAN LETTER MA", "h" : "0F58" },
{"g" : "\u0F59", "n" : "TIBETAN LETTER TSA", "h" : "0F59" },
{"g" : "\u0F5A", "n" : "TIBETAN LETTER TSHA", "h" : "0F5A" },
{"g" : "\u0F5B", "n" : "TIBETAN LETTER DZA", "h" : "0F5B" },
{"g" : "\u0F5C", "n" : "TIBETAN LETTER DZHA", "h" : "0F5C" },
{"g" : "\u0F5D", "n" : "TIBETAN LETTER WA", "h" : "0F5D" },
{"g" : "\u0F5E", "n" : "TIBETAN LETTER ZHA", "h" : "0F5E" },
{"g" : "\u0F5F", "n" : "TIBETAN LETTER ZA", "h" : "0F5F" },
{"g" : "\u0F60", "n" : "TIBETAN LETTER -A", "h" : "0F60" },
{"g" : "\u0F61", "n" : "TIBETAN LETTER YA", "h" : "0F61" },
{"g" : "\u0F62", "n" : "TIBETAN LETTER RA", "h" : "0F62" },
{"g" : "\u0F63", "n" : "TIBETAN LETTER LA", "h" : "0F63" },
{"g" : "\u0F64", "n" : "TIBETAN LETTER SHA", "h" : "0F64" },
{"g" : "\u0F65", "n" : "TIBETAN LETTER SSA", "h" : "0F65" },
{"g" : "\u0F66", "n" : "TIBETAN LETTER SA", "h" : "0F66" },
{"g" : "\u0F67", "n" : "TIBETAN LETTER HA", "h" : "0F67" },
{"g" : "\u0F68", "n" : "TIBETAN LETTER A", "h" : "0F68" },
{"g" : "\u0F69", "n" : "TIBETAN LETTER KSSA", "h" : "0F69" },
{"g" : "\u0F6A", "n" : "TIBETAN LETTER FIXED-FORM RA", "h" : "0F6A" },
{"g" : "\u0F6B", "n" : "TIBETAN LETTER KKA", "h" : "0F6B" },
{"g" : "\u0F6C", "n" : "TIBETAN LETTER RRA", "h" : "0F6C" },

{"g" : "\u0F71", "n" : "TIBETAN VOWEL SIGN AA", "h" : "0F71" },
{"g" : "\u0F72", "n" : "TIBETAN VOWEL SIGN I", "h" : "0F72" },
{"g" : "\u0F73", "n" : "TIBETAN VOWEL SIGN II", "h" : "0F73" },
{"g" : "\u0F74", "n" : "TIBETAN VOWEL SIGN U", "h" : "0F74" },
{"g" : "\u0F75", "n" : "TIBETAN VOWEL SIGN UU", "h" : "0F75" },
{"g" : "\u0F76", "n" : "TIBETAN VOWEL SIGN VOCALIC R", "h" : "0F76" },
{"g" : "\u0F77", "n" : "TIBETAN VOWEL SIGN VOCALIC RR", "h" : "0F77" },
{"g" : "\u0F78", "n" : "TIBETAN VOWEL SIGN VOCALIC L", "h" : "0F78" },
{"g" : "\u0F79", "n" : "TIBETAN VOWEL SIGN VOCALIC LL", "h" : "0F79" },
{"g" : "\u0F7A", "n" : "TIBETAN VOWEL SIGN E", "h" : "0F7A" },
{"g" : "\u0F7B", "n" : "TIBETAN VOWEL SIGN EE", "h" : "0F7B" },
{"g" : "\u0F7C", "n" : "TIBETAN VOWEL SIGN O", "h" : "0F7C" },
{"g" : "\u0F7D", "n" : "TIBETAN VOWEL SIGN OO", "h" : "0F7D" },
{"g" : "\u0F7E", "n" : "TIBETAN SIGN RJES SU NGA RO", "h" : "0F7E" },
{"g" : "\u0F7F", "n" : "TIBETAN SIGN RNAM BCAD", "h" : "0F7F" },
{"g" : "\u0F80", "n" : "TIBETAN VOWEL SIGN REVERSED I", "h" : "0F80" },
{"g" : "\u0F81", "n" : "TIBETAN VOWEL SIGN REVERSED II", "h" : "0F81" },
{"g" : "\u0F82", "n" : "TIBETAN SIGN NYI ZLA NAA DA", "h" : "0F82" },
{"g" : "\u0F83", "n" : "TIBETAN SIGN SNA LDAN", "h" : "0F83" },
{"g" : "\u0F84", "n" : "TIBETAN MARK HALANTA", "h" : "0F84" },
{"g" : "\u0F85", "n" : "TIBETAN MARK PALUTA", "h" : "0F85" },
{"g" : "\u0F86", "n" : "TIBETAN SIGN LCI RTAGS", "h" : "0F86" },
{"g" : "\u0F87", "n" : "TIBETAN SIGN YANG RTAGS", "h" : "0F87" },
{"g" : "\u0F88", "n" : "TIBETAN SIGN LCE TSA CAN", "h" : "0F88" },
{"g" : "\u0F89", "n" : "TIBETAN SIGN MCHU CAN", "h" : "0F89" },
{"g" : "\u0F8A", "n" : "TIBETAN SIGN GRU CAN RGYINGS", "h" : "0F8A" },
{"g" : "\u0F8B", "n" : "TIBETAN SIGN GRU MED RGYINGS", "h" : "0F8B" },
{"g" : "\u0F8C", "n" : "TIBETAN SIGN INVERTED MCHU CAN", "h" : "0F8C" },
{"g" : "\u0F8D", "n" : "TIBETAN SUBJOINED SIGN LCE TSA CAN", "h" : "0F8D" },
{"g" : "\u0F8E", "n" : "TIBETAN SUBJOINED SIGN MCHU CAN", "h" : "0F8E" },
{"g" : "\u0F8F", "n" : "TIBETAN SUBJOINED SIGN INVERTED MCHU CAN", "h" : "0F8F" },
{"g" : "\u0F90", "n" : "TIBETAN SUBJOINED LETTER KA", "h" : "0F90" },
{"g" : "\u0F91", "n" : "TIBETAN SUBJOINED LETTER KHA", "h" : "0F91" },
{"g" : "\u0F92", "n" : "TIBETAN SUBJOINED LETTER GA", "h" : "0F92" },
{"g" : "\u0F93", "n" : "TIBETAN SUBJOINED LETTER GHA", "h" : "0F93" },
{"g" : "\u0F94", "n" : "TIBETAN SUBJOINED LETTER NGA", "h" : "0F94" },
{"g" : "\u0F95", "n" : "TIBETAN SUBJOINED LETTER CA", "h" : "0F95" },
{"g" : "\u0F96", "n" : "TIBETAN SUBJOINED LETTER CHA", "h" : "0F96" },
{"g" : "\u0F97", "n" : "TIBETAN SUBJOINED LETTER JA", "h" : "0F97" },

{"g" : "\u0F99", "n" : "TIBETAN SUBJOINED LETTER NYA", "h" : "0F99" },
{"g" : "\u0F9A", "n" : "TIBETAN SUBJOINED LETTER TTA", "h" : "0F9A" },
{"g" : "\u0F9B", "n" : "TIBETAN SUBJOINED LETTER TTHA", "h" : "0F9B" },
{"g" : "\u0F9C", "n" : "TIBETAN SUBJOINED LETTER DDA", "h" : "0F9C" },
{"g" : "\u0F9D", "n" : "TIBETAN SUBJOINED LETTER DDHA", "h" : "0F9D" },
{"g" : "\u0F9E", "n" : "TIBETAN SUBJOINED LETTER NNA", "h" : "0F9E" },
{"g" : "\u0F9F", "n" : "TIBETAN SUBJOINED LETTER TA", "h" : "0F9F" },
{"g" : "\u0FA0", "n" : "TIBETAN SUBJOINED LETTER THA", "h" : "0FA0" },
{"g" : "\u0FA1", "n" : "TIBETAN SUBJOINED LETTER DA", "h" : "0FA1" },
{"g" : "\u0FA2", "n" : "TIBETAN SUBJOINED LETTER DHA", "h" : "0FA2" },
{"g" : "\u0FA3", "n" : "TIBETAN SUBJOINED LETTER NA", "h" : "0FA3" },
{"g" : "\u0FA4", "n" : "TIBETAN SUBJOINED LETTER PA", "h" : "0FA4" },
{"g" : "\u0FA5", "n" : "TIBETAN SUBJOINED LETTER PHA", "h" : "0FA5" },
{"g" : "\u0FA6", "n" : "TIBETAN SUBJOINED LETTER BA", "h" : "0FA6" },
{"g" : "\u0FA7", "n" : "TIBETAN SUBJOINED LETTER BHA", "h" : "0FA7" },
{"g" : "\u0FA8", "n" : "TIBETAN SUBJOINED LETTER MA", "h" : "0FA8" },
{"g" : "\u0FA9", "n" : "TIBETAN SUBJOINED LETTER TSA", "h" : "0FA9" },
{"g" : "\u0FAA", "n" : "TIBETAN SUBJOINED LETTER TSHA", "h" : "0FAA" },
{"g" : "\u0FAB", "n" : "TIBETAN SUBJOINED LETTER DZA", "h" : "0FAB" },
{"g" : "\u0FAC", "n" : "TIBETAN SUBJOINED LETTER DZHA", "h" : "0FAC" },
{"g" : "\u0FAD", "n" : "TIBETAN SUBJOINED LETTER WA", "h" : "0FAD" },
{"g" : "\u0FAE", "n" : "TIBETAN SUBJOINED LETTER ZHA", "h" : "0FAE" },
{"g" : "\u0FAF", "n" : "TIBETAN SUBJOINED LETTER ZA", "h" : "0FAF" },
{"g" : "\u0FB0", "n" : "TIBETAN SUBJOINED LETTER -A", "h" : "0FB0" },
{"g" : "\u0FB1", "n" : "TIBETAN SUBJOINED LETTER YA", "h" : "0FB1" },
{"g" : "\u0FB2", "n" : "TIBETAN SUBJOINED LETTER RA", "h" : "0FB2" },
{"g" : "\u0FB3", "n" : "TIBETAN SUBJOINED LETTER LA", "h" : "0FB3" },
{"g" : "\u0FB4", "n" : "TIBETAN SUBJOINED LETTER SHA", "h" : "0FB4" },
{"g" : "\u0FB5", "n" : "TIBETAN SUBJOINED LETTER SSA", "h" : "0FB5" },
{"g" : "\u0FB6", "n" : "TIBETAN SUBJOINED LETTER SA", "h" : "0FB6" },
{"g" : "\u0FB7", "n" : "TIBETAN SUBJOINED LETTER HA", "h" : "0FB7" },
{"g" : "\u0FB8", "n" : "TIBETAN SUBJOINED LETTER A", "h" : "0FB8" },
{"g" : "\u0FB9", "n" : "TIBETAN SUBJOINED LETTER KSSA", "h" : "0FB9" },
{"g" : "\u0FBA", "n" : "TIBETAN SUBJOINED LETTER FIXED-FORM WA", "h" : "0FBA" },
{"g" : "\u0FBB", "n" : "TIBETAN SUBJOINED LETTER FIXED-FORM YA", "h" : "0FBB" },
{"g" : "\u0FBC", "n" : "TIBETAN SUBJOINED LETTER FIXED-FORM RA", "h" : "0FBC" },

{"g" : "\u0FBE", "n" : "TIBETAN KU RU KHA", "h" : "0FBE" },
{"g" : "\u0FBF", "n" : "TIBETAN KU RU KHA BZHI MIG CAN", "h" : "0FBF" },
{"g" : "\u0FC0", "n" : "TIBETAN CANTILLATION SIGN HEAVY BEAT", "h" : "0FC0" },
{"g" : "\u0FC1", "n" : "TIBETAN CANTILLATION SIGN LIGHT BEAT", "h" : "0FC1" },
{"g" : "\u0FC2", "n" : "TIBETAN CANTILLATION SIGN CANG TE-U", "h" : "0FC2" },
{"g" : "\u0FC3", "n" : "TIBETAN CANTILLATION SIGN SBUB -CHAL", "h" : "0FC3" },
{"g" : "\u0FC4", "n" : "TIBETAN SYMBOL DRIL BU", "h" : "0FC4" },
{"g" : "\u0FC5", "n" : "TIBETAN SYMBOL RDO RJE", "h" : "0FC5" },
{"g" : "\u0FC6", "n" : "TIBETAN SYMBOL PADMA GDAN", "h" : "0FC6" },
{"g" : "\u0FC7", "n" : "TIBETAN SYMBOL RDO RJE RGYA GRAM", "h" : "0FC7" },
{"g" : "\u0FC8", "n" : "TIBETAN SYMBOL PHUR PA", "h" : "0FC8" },
{"g" : "\u0FC9", "n" : "TIBETAN SYMBOL NOR BU", "h" : "0FC9" },
{"g" : "\u0FCA", "n" : "TIBETAN SYMBOL NOR BU NYIS -KHYIL", "h" : "0FCA" },
{"g" : "\u0FCB", "n" : "TIBETAN SYMBOL NOR BU GSUM -KHYIL", "h" : "0FCB" },
{"g" : "\u0FCC", "n" : "TIBETAN SYMBOL NOR BU BZHI -KHYIL", "h" : "0FCC" },

{"g" : "\u0FCE", "n" : "TIBETAN SIGN RDEL NAG RDEL DKAR", "h" : "0FCE" },
{"g" : "\u0FCF", "n" : "TIBETAN SIGN RDEL NAG GSUM", "h" : "0FCF" },
{"g" : "\u0FD0", "n" : "TIBETAN MARK BSKA- SHOG GI MGO RGYAN", "h" : "0FD0" },
{"g" : "\u0FD1", "n" : "TIBETAN MARK MNYAM YIG GI MGO RGYAN", "h" : "0FD1" },
{"g" : "\u0FD2", "n" : "TIBETAN MARK NYIS TSHEG", "h" : "0FD2" },
{"g" : "\u0FD3", "n" : "TIBETAN MARK INITIAL BRDA RNYING YIG MGO MDUN MA", "h" : "0FD3" },
{"g" : "\u0FD4", "n" : "TIBETAN MARK CLOSING BRDA RNYING YIG MGO SGAB MA", "h" : "0FD4" },
{"g" : "\u0FD5", "n" : "RIGHT-FACING SVASTI SIGN", "h" : "0FD5" },
{"g" : "\u0FD6", "n" : "LEFT-FACING SVASTI SIGN", "h" : "0FD6" },
{"g" : "\u0FD7", "n" : "RIGHT-FACING SVASTI SIGN WITH DOTS", "h" : "0FD7" },
{"g" : "\u0FD8", "n" : "LEFT-FACING SVASTI SIGN WITH DOTS", "h" : "0FD8" },
{"g" : "\u0FD9", "n" : "TIBETAN MARK LEADING MCHAN RTAGS", "h" : "0FD9" },
{"g" : "\u0FDA", "n" : "TIBETAN MARK TRAILING MCHAN RTAGS", "h" : "0FDA" },

{"g" : "\u1800", "n" : "MONGOLIAN BIRGA", "h" : "1800" },
{"g" : "\u1801", "n" : "MONGOLIAN ELLIPSIS", "h" : "1801" },
{"g" : "\u1802", "n" : "MONGOLIAN COMMA", "h" : "1802" },
{"g" : "\u1803", "n" : "MONGOLIAN FULL STOP", "h" : "1803" },
{"g" : "\u1804", "n" : "MONGOLIAN COLON", "h" : "1804" },
{"g" : "\u1805", "n" : "MONGOLIAN FOUR DOTS", "h" : "1805" },
{"g" : "\u1806", "n" : "MONGOLIAN TODO SOFT HYPHEN", "h" : "1806" },
{"g" : "\u1807", "n" : "MONGOLIAN SIBE SYLLABLE BOUNDARY MARKER", "h" : "1807" },
{"g" : "\u1808", "n" : "MONGOLIAN MANCHU COMMA", "h" : "1808" },
{"g" : "\u1809", "n" : "MONGOLIAN MANCHU FULL STOP", "h" : "1809" },
{"g" : "\u180A", "n" : "MONGOLIAN NIRUGU", "h" : "180A" },
{"g" : "\u180B", "n" : "MONGOLIAN FREE VARIATION SELECTOR ONE", "h" : "180B" },
{"g" : "\u180C", "n" : "MONGOLIAN FREE VARIATION SELECTOR TWO", "h" : "180C" },
{"g" : "\u180D", "n" : "MONGOLIAN FREE VARIATION SELECTOR THREE", "h" : "180D" },
{"g" : "\u180E", "n" : "MONGOLIAN VOWEL SEPARATOR", "h" : "180E" },

{"g" : "\u1810", "n" : "MONGOLIAN DIGIT ZERO", "h" : "1810" },
{"g" : "\u1811", "n" : "MONGOLIAN DIGIT ONE", "h" : "1811" },
{"g" : "\u1812", "n" : "MONGOLIAN DIGIT TWO", "h" : "1812" },
{"g" : "\u1813", "n" : "MONGOLIAN DIGIT THREE", "h" : "1813" },
{"g" : "\u1814", "n" : "MONGOLIAN DIGIT FOUR", "h" : "1814" },
{"g" : "\u1815", "n" : "MONGOLIAN DIGIT FIVE", "h" : "1815" },
{"g" : "\u1816", "n" : "MONGOLIAN DIGIT SIX", "h" : "1816" },
{"g" : "\u1817", "n" : "MONGOLIAN DIGIT SEVEN", "h" : "1817" },
{"g" : "\u1818", "n" : "MONGOLIAN DIGIT EIGHT", "h" : "1818" },
{"g" : "\u1819", "n" : "MONGOLIAN DIGIT NINE", "h" : "1819" },

{"g" : "\u1820", "n" : "MONGOLIAN LETTER A", "h" : "1820" },
{"g" : "\u1821", "n" : "MONGOLIAN LETTER E", "h" : "1821" },
{"g" : "\u1822", "n" : "MONGOLIAN LETTER I", "h" : "1822" },
{"g" : "\u1823", "n" : "MONGOLIAN LETTER O", "h" : "1823" },
{"g" : "\u1824", "n" : "MONGOLIAN LETTER U", "h" : "1824" },
{"g" : "\u1825", "n" : "MONGOLIAN LETTER OE", "h" : "1825" },
{"g" : "\u1826", "n" : "MONGOLIAN LETTER UE", "h" : "1826" },
{"g" : "\u1827", "n" : "MONGOLIAN LETTER EE", "h" : "1827" },
{"g" : "\u1828", "n" : "MONGOLIAN LETTER NA", "h" : "1828" },
{"g" : "\u1829", "n" : "MONGOLIAN LETTER ANG", "h" : "1829" },
{"g" : "\u182A", "n" : "MONGOLIAN LETTER BA", "h" : "182A" },
{"g" : "\u182B", "n" : "MONGOLIAN LETTER PA", "h" : "182B" },
{"g" : "\u182C", "n" : "MONGOLIAN LETTER QA", "h" : "182C" },
{"g" : "\u182D", "n" : "MONGOLIAN LETTER GA", "h" : "182D" },
{"g" : "\u182E", "n" : "MONGOLIAN LETTER MA", "h" : "182E" },
{"g" : "\u182F", "n" : "MONGOLIAN LETTER LA", "h" : "182F" },
{"g" : "\u1830", "n" : "MONGOLIAN LETTER SA", "h" : "1830" },
{"g" : "\u1831", "n" : "MONGOLIAN LETTER SHA", "h" : "1831" },
{"g" : "\u1832", "n" : "MONGOLIAN LETTER TA", "h" : "1832" },
{"g" : "\u1833", "n" : "MONGOLIAN LETTER DA", "h" : "1833" },
{"g" : "\u1834", "n" : "MONGOLIAN LETTER CHA", "h" : "1834" },
{"g" : "\u1835", "n" : "MONGOLIAN LETTER JA", "h" : "1835" },
{"g" : "\u1836", "n" : "MONGOLIAN LETTER YA", "h" : "1836" },
{"g" : "\u1837", "n" : "MONGOLIAN LETTER RA", "h" : "1837" },
{"g" : "\u1838", "n" : "MONGOLIAN LETTER WA", "h" : "1838" },
{"g" : "\u1839", "n" : "MONGOLIAN LETTER FA", "h" : "1839" },
{"g" : "\u183A", "n" : "MONGOLIAN LETTER KA", "h" : "183A" },
{"g" : "\u183B", "n" : "MONGOLIAN LETTER KHA", "h" : "183B" },
{"g" : "\u183C", "n" : "MONGOLIAN LETTER TSA", "h" : "183C" },
{"g" : "\u183D", "n" : "MONGOLIAN LETTER ZA", "h" : "183D" },
{"g" : "\u183E", "n" : "MONGOLIAN LETTER HAA", "h" : "183E" },
{"g" : "\u183F", "n" : "MONGOLIAN LETTER ZRA", "h" : "183F" },
{"g" : "\u1840", "n" : "MONGOLIAN LETTER LHA", "h" : "1840" },
{"g" : "\u1841", "n" : "MONGOLIAN LETTER ZHI", "h" : "1841" },
{"g" : "\u1842", "n" : "MONGOLIAN LETTER CHI", "h" : "1842" },
{"g" : "\u1843", "n" : "MONGOLIAN LETTER TODO LONG VOWEL SIGN", "h" : "1843" },
{"g" : "\u1844", "n" : "MONGOLIAN LETTER TODO E", "h" : "1844" },
{"g" : "\u1845", "n" : "MONGOLIAN LETTER TODO I", "h" : "1845" },
{"g" : "\u1846", "n" : "MONGOLIAN LETTER TODO O", "h" : "1846" },
{"g" : "\u1847", "n" : "MONGOLIAN LETTER TODO U", "h" : "1847" },
{"g" : "\u1848", "n" : "MONGOLIAN LETTER TODO OE", "h" : "1848" },
{"g" : "\u1849", "n" : "MONGOLIAN LETTER TODO UE", "h" : "1849" },
{"g" : "\u184A", "n" : "MONGOLIAN LETTER TODO ANG", "h" : "184A" },
{"g" : "\u184B", "n" : "MONGOLIAN LETTER TODO BA", "h" : "184B" },
{"g" : "\u184C", "n" : "MONGOLIAN LETTER TODO PA", "h" : "184C" },
{"g" : "\u184D", "n" : "MONGOLIAN LETTER TODO QA", "h" : "184D" },
{"g" : "\u184E", "n" : "MONGOLIAN LETTER TODO GA", "h" : "184E" },
{"g" : "\u184F", "n" : "MONGOLIAN LETTER TODO MA", "h" : "184F" },
{"g" : "\u1850", "n" : "MONGOLIAN LETTER TODO TA", "h" : "1850" },
{"g" : "\u1851", "n" : "MONGOLIAN LETTER TODO DA", "h" : "1851" },
{"g" : "\u1852", "n" : "MONGOLIAN LETTER TODO CHA", "h" : "1852" },
{"g" : "\u1853", "n" : "MONGOLIAN LETTER TODO JA", "h" : "1853" },
{"g" : "\u1854", "n" : "MONGOLIAN LETTER TODO TSA", "h" : "1854" },
{"g" : "\u1855", "n" : "MONGOLIAN LETTER TODO YA", "h" : "1855" },
{"g" : "\u1856", "n" : "MONGOLIAN LETTER TODO WA", "h" : "1856" },
{"g" : "\u1857", "n" : "MONGOLIAN LETTER TODO KA", "h" : "1857" },
{"g" : "\u1858", "n" : "MONGOLIAN LETTER TODO GAA", "h" : "1858" },
{"g" : "\u1859", "n" : "MONGOLIAN LETTER TODO HAA", "h" : "1859" },
{"g" : "\u185A", "n" : "MONGOLIAN LETTER TODO JIA", "h" : "185A" },
{"g" : "\u185B", "n" : "MONGOLIAN LETTER TODO NIA", "h" : "185B" },
{"g" : "\u185C", "n" : "MONGOLIAN LETTER TODO DZA", "h" : "185C" },
{"g" : "\u185D", "n" : "MONGOLIAN LETTER SIBE E", "h" : "185D" },
{"g" : "\u185E", "n" : "MONGOLIAN LETTER SIBE I", "h" : "185E" },
{"g" : "\u185F", "n" : "MONGOLIAN LETTER SIBE IY", "h" : "185F" },
{"g" : "\u1860", "n" : "MONGOLIAN LETTER SIBE UE", "h" : "1860" },
{"g" : "\u1861", "n" : "MONGOLIAN LETTER SIBE U", "h" : "1861" },
{"g" : "\u1862", "n" : "MONGOLIAN LETTER SIBE ANG", "h" : "1862" },
{"g" : "\u1863", "n" : "MONGOLIAN LETTER SIBE KA", "h" : "1863" },
{"g" : "\u1864", "n" : "MONGOLIAN LETTER SIBE GA", "h" : "1864" },
{"g" : "\u1865", "n" : "MONGOLIAN LETTER SIBE HA", "h" : "1865" },
{"g" : "\u1866", "n" : "MONGOLIAN LETTER SIBE PA", "h" : "1866" },
{"g" : "\u1867", "n" : "MONGOLIAN LETTER SIBE SHA", "h" : "1867" },
{"g" : "\u1868", "n" : "MONGOLIAN LETTER SIBE TA", "h" : "1868" },
{"g" : "\u1869", "n" : "MONGOLIAN LETTER SIBE DA", "h" : "1869" },
{"g" : "\u186A", "n" : "MONGOLIAN LETTER SIBE JA", "h" : "186A" },
{"g" : "\u186B", "n" : "MONGOLIAN LETTER SIBE FA", "h" : "186B" },
{"g" : "\u186C", "n" : "MONGOLIAN LETTER SIBE GAA", "h" : "186C" },
{"g" : "\u186D", "n" : "MONGOLIAN LETTER SIBE HAA", "h" : "186D" },
{"g" : "\u186E", "n" : "MONGOLIAN LETTER SIBE TSA", "h" : "186E" },
{"g" : "\u186F", "n" : "MONGOLIAN LETTER SIBE ZA", "h" : "186F" },
{"g" : "\u1870", "n" : "MONGOLIAN LETTER SIBE RAA", "h" : "1870" },
{"g" : "\u1871", "n" : "MONGOLIAN LETTER SIBE CHA", "h" : "1871" },
{"g" : "\u1872", "n" : "MONGOLIAN LETTER SIBE ZHA", "h" : "1872" },
{"g" : "\u1873", "n" : "MONGOLIAN LETTER MANCHU I", "h" : "1873" },
{"g" : "\u1874", "n" : "MONGOLIAN LETTER MANCHU KA", "h" : "1874" },
{"g" : "\u1875", "n" : "MONGOLIAN LETTER MANCHU RA", "h" : "1875" },
{"g" : "\u1876", "n" : "MONGOLIAN LETTER MANCHU FA", "h" : "1876" },
{"g" : "\u1877", "n" : "MONGOLIAN LETTER MANCHU ZHA", "h" : "1877" },
{"g" : "\u1878", "n" : "MONGOLIAN LETTER CHA WITH TWO DOTS", "h" : "1878" },

{"g" : "\u1880", "n" : "MONGOLIAN LETTER ALI GALI ANUSVARA ONE", "h" : "1880" },
{"g" : "\u1881", "n" : "MONGOLIAN LETTER ALI GALI VISARGA ONE", "h" : "1881" },
{"g" : "\u1882", "n" : "MONGOLIAN LETTER ALI GALI DAMARU", "h" : "1882" },
{"g" : "\u1883", "n" : "MONGOLIAN LETTER ALI GALI UBADAMA", "h" : "1883" },
{"g" : "\u1884", "n" : "MONGOLIAN LETTER ALI GALI INVERTED UBADAMA", "h" : "1884" },
{"g" : "\u1885", "n" : "MONGOLIAN LETTER ALI GALI BALUDA", "h" : "1885" },
{"g" : "\u1886", "n" : "MONGOLIAN LETTER ALI GALI THREE BALUDA", "h" : "1886" },
{"g" : "\u1887", "n" : "MONGOLIAN LETTER ALI GALI A", "h" : "1887" },
{"g" : "\u1888", "n" : "MONGOLIAN LETTER ALI GALI I", "h" : "1888" },
{"g" : "\u1889", "n" : "MONGOLIAN LETTER ALI GALI KA", "h" : "1889" },
{"g" : "\u188A", "n" : "MONGOLIAN LETTER ALI GALI NGA", "h" : "188A" },
{"g" : "\u188B", "n" : "MONGOLIAN LETTER ALI GALI CA", "h" : "188B" },
{"g" : "\u188C", "n" : "MONGOLIAN LETTER ALI GALI TTA", "h" : "188C" },
{"g" : "\u188D", "n" : "MONGOLIAN LETTER ALI GALI TTHA", "h" : "188D" },
{"g" : "\u188E", "n" : "MONGOLIAN LETTER ALI GALI DDA", "h" : "188E" },
{"g" : "\u188F", "n" : "MONGOLIAN LETTER ALI GALI NNA", "h" : "188F" },
{"g" : "\u1890", "n" : "MONGOLIAN LETTER ALI GALI TA", "h" : "1890" },
{"g" : "\u1891", "n" : "MONGOLIAN LETTER ALI GALI DA", "h" : "1891" },
{"g" : "\u1892", "n" : "MONGOLIAN LETTER ALI GALI PA", "h" : "1892" },
{"g" : "\u1893", "n" : "MONGOLIAN LETTER ALI GALI PHA", "h" : "1893" },
{"g" : "\u1894", "n" : "MONGOLIAN LETTER ALI GALI SSA", "h" : "1894" },
{"g" : "\u1895", "n" : "MONGOLIAN LETTER ALI GALI ZHA", "h" : "1895" },
{"g" : "\u1896", "n" : "MONGOLIAN LETTER ALI GALI ZA", "h" : "1896" },
{"g" : "\u1897", "n" : "MONGOLIAN LETTER ALI GALI AH", "h" : "1897" },
{"g" : "\u1898", "n" : "MONGOLIAN LETTER TODO ALI GALI TA", "h" : "1898" },
{"g" : "\u1899", "n" : "MONGOLIAN LETTER TODO ALI GALI ZHA", "h" : "1899" },
{"g" : "\u189A", "n" : "MONGOLIAN LETTER MANCHU ALI GALI GHA", "h" : "189A" },
{"g" : "\u189B", "n" : "MONGOLIAN LETTER MANCHU ALI GALI NGA", "h" : "189B" },
{"g" : "\u189C", "n" : "MONGOLIAN LETTER MANCHU ALI GALI CA", "h" : "189C" },
{"g" : "\u189D", "n" : "MONGOLIAN LETTER MANCHU ALI GALI JHA", "h" : "189D" },
{"g" : "\u189E", "n" : "MONGOLIAN LETTER MANCHU ALI GALI TTA", "h" : "189E" },
{"g" : "\u189F", "n" : "MONGOLIAN LETTER MANCHU ALI GALI DDHA", "h" : "189F" },
{"g" : "\u18A0", "n" : "MONGOLIAN LETTER MANCHU ALI GALI TA", "h" : "18A0" },
{"g" : "\u18A1", "n" : "MONGOLIAN LETTER MANCHU ALI GALI DHA", "h" : "18A1" },
{"g" : "\u18A2", "n" : "MONGOLIAN LETTER MANCHU ALI GALI SSA", "h" : "18A2" },
{"g" : "\u18A3", "n" : "MONGOLIAN LETTER MANCHU ALI GALI CYA", "h" : "18A3" },
{"g" : "\u18A4", "n" : "MONGOLIAN LETTER MANCHU ALI GALI ZHA", "h" : "18A4" },
{"g" : "\u18A5", "n" : "MONGOLIAN LETTER MANCHU ALI GALI ZA", "h" : "18A5" },
{"g" : "\u18A6", "n" : "MONGOLIAN LETTER ALI GALI HALF U", "h" : "18A6" },
{"g" : "\u18A7", "n" : "MONGOLIAN LETTER ALI GALI HALF YA", "h" : "18A7" },
{"g" : "\u18A8", "n" : "MONGOLIAN LETTER MANCHU ALI GALI BHA", "h" : "18A8" },
{"g" : "\u18A9", "n" : "MONGOLIAN LETTER ALI GALI DAGALGA", "h" : "18A9" },
{"g" : "\u18AA", "n" : "MONGOLIAN LETTER MANCHU ALI GALI LHA", "h" : "18AA" },

{"g" : "\uA840", "n" : "PHAGS-PA LETTER KA", "h" : "A840"},
{"g" : "\uA841", "n" : "PHAGS-PA LETTER KHA", "h" : "A841"},
{"g" : "\uA842", "n" : "PHAGS-PA LETTER GA", "h" : "A842"},
{"g" : "\uA843", "n" : "PHAGS-PA LETTER NGA", "h" : "A843"},
{"g" : "\uA844", "n" : "PHAGS-PA LETTER CA", "h" : "A844"},
{"g" : "\uA845", "n" : "PHAGS-PA LETTER CHA", "h" : "A845"},
{"g" : "\uA846", "n" : "PHAGS-PA LETTER JA", "h" : "A846"},
{"g" : "\uA847", "n" : "PHAGS-PA LETTER NYA", "h" : "A847"},
{"g" : "\uA848", "n" : "PHAGS-PA LETTER TA", "h" : "A848"},
{"g" : "\uA849", "n" : "PHAGS-PA LETTER THA", "h" : "A849"},
{"g" : "\uA84A", "n" : "PHAGS-PA LETTER DA", "h" : "A84A"},
{"g" : "\uA84B", "n" : "PHAGS-PA LETTER NA", "h" : "A84B"},
{"g" : "\uA84C", "n" : "PHAGS-PA LETTER PA", "h" : "A84C"},
{"g" : "\uA84D", "n" : "PHAGS-PA LETTER PHA", "h" : "A84D"},
{"g" : "\uA84E", "n" : "PHAGS-PA LETTER BA", "h" : "A84E"},
{"g" : "\uA84F", "n" : "PHAGS-PA LETTER MA", "h" : "A84F"},
{"g" : "\uA850", "n" : "PHAGS-PA LETTER TSA", "h" : "A850"},
{"g" : "\uA851", "n" : "PHAGS-PA LETTER TSHA", "h" : "A851"},
{"g" : "\uA852", "n" : "PHAGS-PA LETTER DZA", "h" : "A852"},
{"g" : "\uA853", "n" : "PHAGS-PA LETTER WA", "h" : "A853"},
{"g" : "\uA854", "n" : "PHAGS-PA LETTER ZHA", "h" : "A854"},
{"g" : "\uA855", "n" : "PHAGS-PA LETTER ZA", "h" : "A855"},
{"g" : "\uA856", "n" : "PHAGS-PA LETTER SMALL A", "h" : "A856"},
{"g" : "\uA857", "n" : "PHAGS-PA LETTER YA", "h" : "A857"},
{"g" : "\uA858", "n" : "PHAGS-PA LETTER RA", "h" : "A858"},
{"g" : "\uA859", "n" : "PHAGS-PA LETTER LA", "h" : "A859"},
{"g" : "\uA85A", "n" : "PHAGS-PA LETTER SHA", "h" : "A85A"},
{"g" : "\uA85B", "n" : "PHAGS-PA LETTER SA", "h" : "A85B"},
{"g" : "\uA85C", "n" : "PHAGS-PA LETTER HA", "h" : "A85C"},
{"g" : "\uA85D", "n" : "PHAGS-PA LETTER A", "h" : "A85D"},
{"g" : "\uA85E", "n" : "PHAGS-PA LETTER I", "h" : "A85E"},
{"g" : "\uA85F", "n" : "PHAGS-PA LETTER U", "h" : "A85F"},
{"g" : "\uA860", "n" : "PHAGS-PA LETTER E", "h" : "A860"},
{"g" : "\uA861", "n" : "PHAGS-PA LETTER O", "h" : "A861"},
{"g" : "\uA862", "n" : "PHAGS-PA LETTER QA", "h" : "A862"},
{"g" : "\uA863", "n" : "PHAGS-PA LETTER XA", "h" : "A863"},
{"g" : "\uA864", "n" : "PHAGS-PA LETTER FA", "h" : "A864"},
{"g" : "\uA865", "n" : "PHAGS-PA LETTER GGA", "h" : "A865"},
{"g" : "\uA866", "n" : "PHAGS-PA LETTER EE", "h" : "A866"},
{"g" : "\uA867", "n" : "PHAGS-PA SUBJOINED LETTER WA", "h" : "A867"},
{"g" : "\uA868", "n" : "PHAGS-PA SUBJOINED LETTER YA", "h" : "A868"},
{"g" : "\uA869", "n" : "PHAGS-PA LETTER TTA", "h" : "A869"},
{"g" : "\uA86A", "n" : "PHAGS-PA LETTER TTHA", "h" : "A86A"},
{"g" : "\uA86B", "n" : "PHAGS-PA LETTER DDA", "h" : "A86B"},
{"g" : "\uA86C", "n" : "PHAGS-PA LETTER NNA", "h" : "A86C"},
{"g" : "\uA86D", "n" : "PHAGS-PA LETTER ALTERNATE YA", "h" : "A86D"},
{"g" : "\uA86E", "n" : "PHAGS-PA LETTER VOICELESS SHA", "h" : "A86E"},
{"g" : "\uA86F", "n" : "PHAGS-PA LETTER VOICED HA", "h" : "A86F"},
{"g" : "\uA870", "n" : "PHAGS-PA LETTER ASPIRATED FA", "h" : "A870"},
{"g" : "\uA871", "n" : "PHAGS-PA SUBJOINED LETTER RA", "h" : "A871"},
{"g" : "\uA872", "n" : "PHAGS-PA SUPERFIXED LETTER RA", "h" : "A872"},
{"g" : "\uA873", "n" : "PHAGS-PA LETTER CANDRABINDU", "h" : "A873"},
{"g" : "\uA874", "n" : "PHAGS-PA SINGLE HEAD MARK", "h" : "A874"},
{"g" : "\uA875", "n" : "PHAGS-PA DOUBLE HEAD MARK", "h" : "A875"},
{"g" : "\uA876", "n" : "PHAGS-PA MARK SHAD", "h" : "A876"},
{"g" : "\uA877", "n" : "PHAGS-PA MARK DOUBLE SHAD", "h" : "A877"},

{"g" : "\u{10AC0}", "n" : "MANICHAEAN LETTER ALEPH", "h" : "10AC0"},
{"g" : "\u{10AC1}", "n" : "MANICHAEAN LETTER BETH", "h" : "10AC1"},
{"g" : "\u{10AC2}", "n" : "MANICHAEAN LETTER BHETH", "h" : "10AC2"},
{"g" : "\u{10AC3}", "n" : "MANICHAEAN LETTER GIMEL", "h" : "10AC3"},
{"g" : "\u{10AC4}", "n" : "MANICHAEAN LETTER GHIMEL", "h" : "10AC4"},
{"g" : "\u{10AC5}", "n" : "MANICHAEAN LETTER DALETH", "h" : "10AC5"},
{"g" : "\u{10AC6}", "n" : "MANICHAEAN LETTER HE", "h" : "10AC6"},
{"g" : "\u{10AC7}", "n" : "MANICHAEAN LETTER WAW", "h" : "10AC7"},
{"g" : "\u{10AC8}", "n" : "MANICHAEAN SIGN UD", "h" : "10AC8"},
{"g" : "\u{10AC9}", "n" : "MANICHAEAN LETTER ZAYIN", "h" : "10AC9"},
{"g" : "\u{10ACA}", "n" : "MANICHAEAN LETTER ZHAYIN", "h" : "10ACA"},
{"g" : "\u{10ACB}", "n" : "MANICHAEAN LETTER JAYIN", "h" : "10ACB"},
{"g" : "\u{10ACC}", "n" : "MANICHAEAN LETTER JHAYIN", "h" : "10ACC"},
{"g" : "\u{10ACD}", "n" : "MANICHAEAN LETTER HETH", "h" : "10ACD"},
{"g" : "\u{10ACE}", "n" : "MANICHAEAN LETTER TETH", "h" : "10ACE"},
{"g" : "\u{10ACF}", "n" : "MANICHAEAN LETTER YODH", "h" : "10ACF"},
{"g" : "\u{10AD0}", "n" : "MANICHAEAN LETTER KAPH", "h" : "10AD0"},
{"g" : "\u{10AD1}", "n" : "MANICHAEAN LETTER XAPH", "h" : "10AD1"},
{"g" : "\u{10AD2}", "n" : "MANICHAEAN LETTER KHAPH", "h" : "10AD2"},
{"g" : "\u{10AD3}", "n" : "MANICHAEAN LETTER LAMEDH", "h" : "10AD3"},
{"g" : "\u{10AD4}", "n" : "MANICHAEAN LETTER DHAMEDH", "h" : "10AD4"},
{"g" : "\u{10AD5}", "n" : "MANICHAEAN LETTER THAMEDH", "h" : "10AD5"},
{"g" : "\u{10AD6}", "n" : "MANICHAEAN LETTER MEM", "h" : "10AD6"},
{"g" : "\u{10AD7}", "n" : "MANICHAEAN LETTER NUN", "h" : "10AD7"},
{"g" : "\u{10AD8}", "n" : "MANICHAEAN LETTER SAMEKH", "h" : "10AD8"},
{"g" : "\u{10AD9}", "n" : "MANICHAEAN LETTER AYIN", "h" : "10AD9"},
{"g" : "\u{10ADA}", "n" : "MANICHAEAN LETTER AAYIN", "h" : "10ADA"},
{"g" : "\u{10ADB}", "n" : "MANICHAEAN LETTER PE", "h" : "10ADB"},
{"g" : "\u{10ADC}", "n" : "MANICHAEAN LETTER FE", "h" : "10ADC"},
{"g" : "\u{10ADD}", "n" : "MANICHAEAN LETTER SADHE", "h" : "10ADD"},
{"g" : "\u{10ADE}", "n" : "MANICHAEAN LETTER QOPH", "h" : "10ADE"},
{"g" : "\u{10ADF}", "n" : "MANICHAEAN LETTER XOPH", "h" : "10ADF"},
{"g" : "\u{10AE0}", "n" : "MANICHAEAN LETTER QHOPH", "h" : "10AE0"},
{"g" : "\u{10AE1}", "n" : "MANICHAEAN LETTER RESH", "h" : "10AE1"},
{"g" : "\u{10AE2}", "n" : "MANICHAEAN LETTER SHIN", "h" : "10AE2"},
{"g" : "\u{10AE3}", "n" : "MANICHAEAN LETTER SSHIN", "h" : "10AE3"},
{"g" : "\u{10AE4}", "n" : "MANICHAEAN LETTER TAW", "h" : "10AE4"},
{"g" : "\u{10AE5}", "n" : "MANICHAEAN ABBREVIATION MARK ABOVE", "h" : "10AE5"},
{"g" : "\u{10AE6}", "n" : "MANICHAEAN ABBREVIATION MARK BELOW", "h" : "10AE6"},

{"g" : "\u{10AEB}", "n" : "MANICHAEAN NUMBER ONE", "h" : "10AEB"},
{"g" : "\u{10AEC}", "n" : "MANICHAEAN NUMBER FIVE", "h" : "10AEC"},
{"g" : "\u{10AED}", "n" : "MANICHAEAN NUMBER TEN", "h" : "10AED"},
{"g" : "\u{10AEE}", "n" : "MANICHAEAN NUMBER TWENTY", "h" : "10AEE"},
{"g" : "\u{10AEF}", "n" : "MANICHAEAN NUMBER ONE HUNDRED", "h" : "10AEF"},
{"g" : "\u{10AF0}", "n" : "MANICHAEAN PUNCTUATION STAR", "h" : "10AF0"},
{"g" : "\u{10AF1}", "n" : "MANICHAEAN PUNCTUATION FLEURON", "h" : "10AF1"},
{"g" : "\u{10AF2}", "n" : "MANICHAEAN PUNCTUATION DOUBLE DOT WITHIN DOT", "h" : "10AF2"},
{"g" : "\u{10AF3}", "n" : "MANICHAEAN PUNCTUATION DOT WITHIN DOT", "h" : "10AF3"},
{"g" : "\u{10AF4}", "n" : "MANICHAEAN PUNCTUATION DOT", "h" : "10AF4"},
{"g" : "\u{10AF5}", "n" : "MANICHAEAN PUNCTUATION TWO DOTS", "h" : "10AF5"},
{"g" : "\u{10AF6}", "n" : "MANICHAEAN PUNCTUATION LINE FILLER", "h" : "10AF6"},

{"g" : "\u{10C00}", "n" : "OLD TURKIC LETTER ORKHON A", "h" : "10C00"},
{"g" : "\u{10C01}", "n" : "OLD TURKIC LETTER YENISEI A", "h" : "10C01"},
{"g" : "\u{10C02}", "n" : "OLD TURKIC LETTER YENISEI AE", "h" : "10C02"},
{"g" : "\u{10C03}", "n" : "OLD TURKIC LETTER ORKHON I", "h" : "10C03"},
{"g" : "\u{10C04}", "n" : "OLD TURKIC LETTER YENISEI I", "h" : "10C04"},
{"g" : "\u{10C05}", "n" : "OLD TURKIC LETTER YENISEI E", "h" : "10C05"},
{"g" : "\u{10C06}", "n" : "OLD TURKIC LETTER ORKHON O", "h" : "10C06"},
{"g" : "\u{10C07}", "n" : "OLD TURKIC LETTER ORKHON OE", "h" : "10C07"},
{"g" : "\u{10C08}", "n" : "OLD TURKIC LETTER YENISEI OE", "h" : "10C08"},
{"g" : "\u{10C09}", "n" : "OLD TURKIC LETTER ORKHON AB", "h" : "10C09"},
{"g" : "\u{10C0A}", "n" : "OLD TURKIC LETTER YENISEI AB", "h" : "10C0A"},
{"g" : "\u{10C0B}", "n" : "OLD TURKIC LETTER ORKHON AEB", "h" : "10C0B"},
{"g" : "\u{10C0C}", "n" : "OLD TURKIC LETTER YENISEI AEB", "h" : "10C0C"},
{"g" : "\u{10C0D}", "n" : "OLD TURKIC LETTER ORKHON AG", "h" : "10C0D"},
{"g" : "\u{10C0E}", "n" : "OLD TURKIC LETTER YENISEI AG", "h" : "10C0E"},
{"g" : "\u{10C0F}", "n" : "OLD TURKIC LETTER ORKHON AEG", "h" : "10C0F"},
{"g" : "\u{10C10}", "n" : "OLD TURKIC LETTER YENISEI AEG", "h" : "10C10"},
{"g" : "\u{10C11}", "n" : "OLD TURKIC LETTER ORKHON AD", "h" : "10C11"},
{"g" : "\u{10C12}", "n" : "OLD TURKIC LETTER YENISEI AD", "h" : "10C12"},
{"g" : "\u{10C13}", "n" : "OLD TURKIC LETTER ORKHON AED", "h" : "10C13"},
{"g" : "\u{10C14}", "n" : "OLD TURKIC LETTER ORKHON EZ", "h" : "10C14"},
{"g" : "\u{10C15}", "n" : "OLD TURKIC LETTER YENISEI EZ", "h" : "10C15"},
{"g" : "\u{10C16}", "n" : "OLD TURKIC LETTER ORKHON AY", "h" : "10C16"},
{"g" : "\u{10C17}", "n" : "OLD TURKIC LETTER YENISEI AY", "h" : "10C17"},
{"g" : "\u{10C18}", "n" : "OLD TURKIC LETTER ORKHON AEY", "h" : "10C18"},
{"g" : "\u{10C19}", "n" : "OLD TURKIC LETTER YENISEI AEY", "h" : "10C19"},
{"g" : "\u{10C1A}", "n" : "OLD TURKIC LETTER ORKHON AEK", "h" : "10C1A"},
{"g" : "\u{10C1B}", "n" : "OLD TURKIC LETTER YENISEI AEK", "h" : "10C1B"},
{"g" : "\u{10C1C}", "n" : "OLD TURKIC LETTER ORKHON OEK", "h" : "10C1C"},
{"g" : "\u{10C1D}", "n" : "OLD TURKIC LETTER YENISEI OEK", "h" : "10C1D"},
{"g" : "\u{10C1E}", "n" : "OLD TURKIC LETTER ORKHON AL", "h" : "10C1E"},
{"g" : "\u{10C1F}", "n" : "OLD TURKIC LETTER YENISEI AL", "h" : "10C1F"},
{"g" : "\u{10C20}", "n" : "OLD TURKIC LETTER ORKHON AEL", "h" : "10C20"},
{"g" : "\u{10C21}", "n" : "OLD TURKIC LETTER ORKHON ELT", "h" : "10C21"},
{"g" : "\u{10C22}", "n" : "OLD TURKIC LETTER ORKHON EM", "h" : "10C22"},
{"g" : "\u{10C23}", "n" : "OLD TURKIC LETTER ORKHON AN", "h" : "10C23"},
{"g" : "\u{10C24}", "n" : "OLD TURKIC LETTER ORKHON AEN", "h" : "10C24"},
{"g" : "\u{10C25}", "n" : "OLD TURKIC LETTER YENISEI AEN", "h" : "10C25"},
{"g" : "\u{10C26}", "n" : "OLD TURKIC LETTER ORKHON ENT", "h" : "10C26"},
{"g" : "\u{10C27}", "n" : "OLD TURKIC LETTER YENISEI ENT", "h" : "10C27"},
{"g" : "\u{10C28}", "n" : "OLD TURKIC LETTER ORKHON ENC", "h" : "10C28"},
{"g" : "\u{10C29}", "n" : "OLD TURKIC LETTER YENISEI ENC", "h" : "10C29"},
{"g" : "\u{10C2A}", "n" : "OLD TURKIC LETTER ORKHON ENY", "h" : "10C2A"},
{"g" : "\u{10C2B}", "n" : "OLD TURKIC LETTER YENISEI ENY", "h" : "10C2B"},
{"g" : "\u{10C2C}", "n" : "OLD TURKIC LETTER YENISEI ANG", "h" : "10C2C"},
{"g" : "\u{10C2D}", "n" : "OLD TURKIC LETTER ORKHON ENG", "h" : "10C2D"},
{"g" : "\u{10C2E}", "n" : "OLD TURKIC LETTER YENISEI AENG", "h" : "10C2E"},
{"g" : "\u{10C2F}", "n" : "OLD TURKIC LETTER ORKHON EP", "h" : "10C2F"},
{"g" : "\u{10C30}", "n" : "OLD TURKIC LETTER ORKHON OP", "h" : "10C30"},
{"g" : "\u{10C31}", "n" : "OLD TURKIC LETTER ORKHON IC", "h" : "10C31"},
{"g" : "\u{10C32}", "n" : "OLD TURKIC LETTER ORKHON EC", "h" : "10C32"},
{"g" : "\u{10C33}", "n" : "OLD TURKIC LETTER YENISEI EC", "h" : "10C33"},
{"g" : "\u{10C34}", "n" : "OLD TURKIC LETTER ORKHON AQ", "h" : "10C34"},
{"g" : "\u{10C35}", "n" : "OLD TURKIC LETTER YENISEI AQ", "h" : "10C35"},
{"g" : "\u{10C36}", "n" : "OLD TURKIC LETTER ORKHON IQ", "h" : "10C36"},
{"g" : "\u{10C37}", "n" : "OLD TURKIC LETTER YENISEI IQ", "h" : "10C37"},
{"g" : "\u{10C38}", "n" : "OLD TURKIC LETTER ORKHON OQ", "h" : "10C38"},
{"g" : "\u{10C39}", "n" : "OLD TURKIC LETTER YENISEI OQ", "h" : "10C39"},
{"g" : "\u{10C3A}", "n" : "OLD TURKIC LETTER ORKHON AR", "h" : "10C3A"},
{"g" : "\u{10C3B}", "n" : "OLD TURKIC LETTER YENISEI AR", "h" : "10C3B"},
{"g" : "\u{10C3C}", "n" : "OLD TURKIC LETTER ORKHON AER", "h" : "10C3C"},
{"g" : "\u{10C3D}", "n" : "OLD TURKIC LETTER ORKHON AS", "h" : "10C3D"},
{"g" : "\u{10C3E}", "n" : "OLD TURKIC LETTER ORKHON AES", "h" : "10C3E"},
{"g" : "\u{10C3F}", "n" : "OLD TURKIC LETTER ORKHON ASH", "h" : "10C3F"},
{"g" : "\u{10C40}", "n" : "OLD TURKIC LETTER YENISEI ASH", "h" : "10C40"},
{"g" : "\u{10C41}", "n" : "OLD TURKIC LETTER ORKHON ESH", "h" : "10C41"},
{"g" : "\u{10C42}", "n" : "OLD TURKIC LETTER YENISEI ESH", "h" : "10C42"},
{"g" : "\u{10C43}", "n" : "OLD TURKIC LETTER ORKHON AT", "h" : "10C43"},
{"g" : "\u{10C44}", "n" : "OLD TURKIC LETTER YENISEI AT", "h" : "10C44"},
{"g" : "\u{10C45}", "n" : "OLD TURKIC LETTER ORKHON AET", "h" : "10C45"},
{"g" : "\u{10C46}", "n" : "OLD TURKIC LETTER YENISEI AET", "h" : "10C46"},
{"g" : "\u{10C47}", "n" : "OLD TURKIC LETTER ORKHON OT", "h" : "10C47"},
{"g" : "\u{10C48}", "n" : "OLD TURKIC LETTER ORKHON BASH", "h" : "10C48"},

{"g" : "\u{10F00}", "n" : "OLD SOGDIAN LETTER ALEPH", "h" : "10F00"},
{"g" : "\u{10F01}", "n" : "OLD SOGDIAN LETTER FINAL ALEPH", "h" : "10F01"},
{"g" : "\u{10F02}", "n" : "OLD SOGDIAN LETTER BETH", "h" : "10F02"},
{"g" : "\u{10F03}", "n" : "OLD SOGDIAN LETTER FINAL BETH", "h" : "10F03"},
{"g" : "\u{10F04}", "n" : "OLD SOGDIAN LETTER GIMEL", "h" : "10F04"},
{"g" : "\u{10F05}", "n" : "OLD SOGDIAN LETTER HE", "h" : "10F05"},
{"g" : "\u{10F06}", "n" : "OLD SOGDIAN LETTER FINAL HE", "h" : "10F06"},
{"g" : "\u{10F07}", "n" : "OLD SOGDIAN LETTER WAW", "h" : "10F07"},
{"g" : "\u{10F08}", "n" : "OLD SOGDIAN LETTER ZAYIN", "h" : "10F08"},
{"g" : "\u{10F09}", "n" : "OLD SOGDIAN LETTER HETH", "h" : "10F09"},
{"g" : "\u{10F0A}", "n" : "OLD SOGDIAN LETTER YODH", "h" : "10F0A"},
{"g" : "\u{10F0B}", "n" : "OLD SOGDIAN LETTER KAPH", "h" : "10F0B"},
{"g" : "\u{10F0C}", "n" : "OLD SOGDIAN LETTER LAMEDH", "h" : "10F0C"},
{"g" : "\u{10F0D}", "n" : "OLD SOGDIAN LETTER MEM", "h" : "10F0D"},
{"g" : "\u{10F0E}", "n" : "OLD SOGDIAN LETTER NUN", "h" : "10F0E"},
{"g" : "\u{10F0F}", "n" : "OLD SOGDIAN LETTER FINAL NUN", "h" : "10F0F"},
{"g" : "\u{10F10}", "n" : "OLD SOGDIAN LETTER FINAL NUN WITH VERTICAL TAIL", "h" : "10F10"},
{"g" : "\u{10F11}", "n" : "OLD SOGDIAN LETTER SAMEKH", "h" : "10F11"},
{"g" : "\u{10F12}", "n" : "OLD SOGDIAN LETTER AYIN", "h" : "10F12"},
{"g" : "\u{10F13}", "n" : "OLD SOGDIAN LETTER ALTERNATE AYIN", "h" : "10F13"},
{"g" : "\u{10F14}", "n" : "OLD SOGDIAN LETTER PE", "h" : "10F14"},
{"g" : "\u{10F15}", "n" : "OLD SOGDIAN LETTER SADHE", "h" : "10F15"},
{"g" : "\u{10F16}", "n" : "OLD SOGDIAN LETTER FINAL SADHE", "h" : "10F16"},
{"g" : "\u{10F17}", "n" : "OLD SOGDIAN LETTER FINAL SADHE WITH VERTICAL TAIL", "h" : "10F17"},
{"g" : "\u{10F18}", "n" : "OLD SOGDIAN LETTER RESH-AYIN-DALETH", "h" : "10F18"},
{"g" : "\u{10F19}", "n" : "OLD SOGDIAN LETTER SHIN", "h" : "10F19"},
{"g" : "\u{10F1A}", "n" : "OLD SOGDIAN LETTER TAW", "h" : "10F1A"},
{"g" : "\u{10F1B}", "n" : "OLD SOGDIAN LETTER FINAL TAW", "h" : "10F1B"},
{"g" : "\u{10F1C}", "n" : "OLD SOGDIAN LETTER FINAL TAW WITH VERTICAL TAIL", "h" : "10F1C"},
{"g" : "\u{10F1D}", "n" : "OLD SOGDIAN NUMBER ONE", "h" : "10F1D"},
{"g" : "\u{10F1E}", "n" : "OLD SOGDIAN NUMBER TWO", "h" : "10F1E"},
{"g" : "\u{10F1F}", "n" : "OLD SOGDIAN NUMBER THREE", "h" : "10F1F"},
{"g" : "\u{10F20}", "n" : "OLD SOGDIAN NUMBER FOUR", "h" : "10F20"},
{"g" : "\u{10F21}", "n" : "OLD SOGDIAN NUMBER FIVE", "h" : "10F21"},
{"g" : "\u{10F22}", "n" : "OLD SOGDIAN NUMBER TEN", "h" : "10F22"},
{"g" : "\u{10F23}", "n" : "OLD SOGDIAN NUMBER TWENTY", "h" : "10F23"},
{"g" : "\u{10F24}", "n" : "OLD SOGDIAN NUMBER THIRTY", "h" : "10F24"},
{"g" : "\u{10F25}", "n" : "OLD SOGDIAN NUMBER ONE HUNDRED", "h" : "10F25"},
{"g" : "\u{10F26}", "n" : "OLD SOGDIAN FRACTION ONE HALF", "h" : "10F26"},
{"g" : "\u{10F27}", "n" : "OLD SOGDIAN LIGATURE AYIN-DALETH", "h" : "10F27"},

{"g" : "\u{10F30}", "n" : "SOGDIAN LETTER ALEPH", "h" : "10F30"},
{"g" : "\u{10F31}", "n" : "SOGDIAN LETTER BETH", "h" : "10F31"},
{"g" : "\u{10F32}", "n" : "SOGDIAN LETTER GIMEL", "h" : "10F32"},
{"g" : "\u{10F33}", "n" : "SOGDIAN LETTER HE", "h" : "10F33"},
{"g" : "\u{10F34}", "n" : "SOGDIAN LETTER WAW", "h" : "10F34"},
{"g" : "\u{10F35}", "n" : "SOGDIAN LETTER ZAYIN", "h" : "10F35"},
{"g" : "\u{10F36}", "n" : "SOGDIAN LETTER HETH", "h" : "10F36"},
{"g" : "\u{10F37}", "n" : "SOGDIAN LETTER YODH", "h" : "10F37"},
{"g" : "\u{10F38}", "n" : "SOGDIAN LETTER KAPH", "h" : "10F38"},
{"g" : "\u{10F39}", "n" : "SOGDIAN LETTER LAMEDH", "h" : "10F39"},
{"g" : "\u{10F3A}", "n" : "SOGDIAN LETTER MEM", "h" : "10F3A"},
{"g" : "\u{10F3B}", "n" : "SOGDIAN LETTER NUN", "h" : "10F3B"},
{"g" : "\u{10F3C}", "n" : "SOGDIAN LETTER SAMEKH", "h" : "10F3C"},
{"g" : "\u{10F3D}", "n" : "SOGDIAN LETTER AYIN", "h" : "10F3D"},
{"g" : "\u{10F3E}", "n" : "SOGDIAN LETTER PE", "h" : "10F3E"},
{"g" : "\u{10F3F}", "n" : "SOGDIAN LETTER SADHE", "h" : "10F3F"},
{"g" : "\u{10F40}", "n" : "SOGDIAN LETTER RESH-AYIN", "h" : "10F40"},
{"g" : "\u{10F41}", "n" : "SOGDIAN LETTER SHIN", "h" : "10F41"},
{"g" : "\u{10F42}", "n" : "SOGDIAN LETTER TAW", "h" : "10F42"},
{"g" : "\u{10F43}", "n" : "SOGDIAN LETTER FETH", "h" : "10F43"},
{"g" : "\u{10F44}", "n" : "SOGDIAN LETTER LESH", "h" : "10F44"},
{"g" : "\u{10F45}", "n" : "SOGDIAN INDEPENDENT SHIN", "h" : "10F45"},
{"g" : "\u{10F46}", "n" : "SOGDIAN COMBINING DOT BELOW", "h" : "10F46"},
{"g" : "\u{10F47}", "n" : "SOGDIAN COMBINING TWO DOTS BELOW", "h" : "10F47"},
{"g" : "\u{10F48}", "n" : "SOGDIAN COMBINING DOT ABOVE", "h" : "10F48"},
{"g" : "\u{10F49}", "n" : "SOGDIAN COMBINING TWO DOTS ABOVE", "h" : "10F49"},
{"g" : "\u{10F4A}", "n" : "SOGDIAN COMBINING CURVE ABOVE", "h" : "10F4A"},
{"g" : "\u{10F4B}", "n" : "SOGDIAN COMBINING CURVE BELOW", "h" : "10F4B"},
{"g" : "\u{10F4C}", "n" : "SOGDIAN COMBINING HOOK ABOVE", "h" : "10F4C"},
{"g" : "\u{10F4D}", "n" : "SOGDIAN COMBINING HOOK BELOW", "h" : "10F4D"},
{"g" : "\u{10F4E}", "n" : "SOGDIAN COMBINING LONG HOOK BELOW", "h" : "10F4E"},
{"g" : "\u{10F4F}", "n" : "SOGDIAN COMBINING RESH BELOW", "h" : "10F4F"},
{"g" : "\u{10F50}", "n" : "SOGDIAN COMBINING STROKE BELOW", "h" : "10F50"},
{"g" : "\u{10F51}", "n" : "SOGDIAN NUMBER ONE", "h" : "10F51"},
{"g" : "\u{10F52}", "n" : "SOGDIAN NUMBER TEN", "h" : "10F52"},
{"g" : "\u{10F53}", "n" : "SOGDIAN NUMBER TWENTY", "h" : "10F53"},
{"g" : "\u{10F54}", "n" : "SOGDIAN NUMBER ONE HUNDRED", "h" : "10F54"},
{"g" : "\u{10F55}", "n" : "SOGDIAN PUNCTUATION TWO VERTICAL BARS", "h" : "10F55"},
{"g" : "\u{10F56}", "n" : "SOGDIAN PUNCTUATION TWO VERTICAL BARS WITH DOTS", "h" : "10F56"},
{"g" : "\u{10F57}", "n" : "SOGDIAN PUNCTUATION CIRCLE WITH DOT", "h" : "10F57"},
{"g" : "\u{10F58}", "n" : "SOGDIAN PUNCTUATION TWO CIRCLES WITH DOTS", "h" : "10F58"},
{"g" : "\u{10F59}", "n" : "SOGDIAN PUNCTUATION HALF CIRCLE WITH DOT", "h" : "10F59"},

{"g" : "\u{11660}", "n" : "MONGOLIAN BIRGA WITH ORNAMENT", "h" : "11660"},
{"g" : "\u{11661}", "n" : "MONGOLIAN ROTATED BIRGA", "h" : "11661"},
{"g" : "\u{11662}", "n" : "MONGOLIAN DOUBLE BIRGA WITH ORNAMENT", "h" : "11662"},
{"g" : "\u{11663}", "n" : "MONGOLIAN TRIPLE BIRGA WITH ORNAMENT", "h" : "11663"},
{"g" : "\u{11664}", "n" : "MONGOLIAN BIRGA WITH DOUBLE ORNAMENT", "h" : "11664"},
{"g" : "\u{11665}", "n" : "MONGOLIAN ROTATED BIRGA WITH ORNAMENT", "h" : "11665"},
{"g" : "\u{11666}", "n" : "MONGOLIAN ROTATED BIRGA WITH DOUBLE ORNAMENT", "h" : "11666"},
{"g" : "\u{11667}", "n" : "MONGOLIAN INVERTED BIRGA", "h" : "11667"},
{"g" : "\u{11668}", "n" : "MONGOLIAN INVERTED BIRGA WITH DOUBLE ORNAMENT", "h" : "11668"},
{"g" : "\u{11669}", "n" : "MONGOLIAN SWIRL BIRGA", "h" : "11669"},
{"g" : "\u{1166A}", "n" : "MONGOLIAN SWIRL BIRGA WITH ORNAMENT", "h" : "1166A"},
{"g" : "\u{1166B}", "n" : "MONGOLIAN SWIRL BIRGA WITH DOUBLE ORNAMENT", "h" : "1166B"},
{"g" : "\u{1166C}", "n" : "MONGOLIAN TURNED SWIRL BIRGA WITH DOUBLE ORNAMENT", "h" : "1166C"},

{"g" : "\u{11A00}", "n" : "ZANABAZAR SQUARE LETTER A", "h" : "11A00"},
{"g" : "\u{11A01}", "n" : "ZANABAZAR SQUARE VOWEL SIGN I", "h" : "11A01"},
{"g" : "\u{11A02}", "n" : "ZANABAZAR SQUARE VOWEL SIGN UE", "h" : "11A02"},
{"g" : "\u{11A03}", "n" : "ZANABAZAR SQUARE VOWEL SIGN U", "h" : "11A03"},
{"g" : "\u{11A04}", "n" : "ZANABAZAR SQUARE VOWEL SIGN E", "h" : "11A04"},
{"g" : "\u{11A05}", "n" : "ZANABAZAR SQUARE VOWEL SIGN OE", "h" : "11A05"},
{"g" : "\u{11A06}", "n" : "ZANABAZAR SQUARE VOWEL SIGN O", "h" : "11A06"},
{"g" : "\u{11A07}", "n" : "ZANABAZAR SQUARE VOWEL SIGN AI", "h" : "11A07"},
{"g" : "\u{11A08}", "n" : "ZANABAZAR SQUARE VOWEL SIGN AU", "h" : "11A08"},
{"g" : "\u{11A09}", "n" : "ZANABAZAR SQUARE VOWEL SIGN REVERSED I", "h" : "11A09"},
{"g" : "\u{11A0A}", "n" : "ZANABAZAR SQUARE VOWEL LENGTH MARK", "h" : "11A0A"},
{"g" : "\u{11A0B}", "n" : "ZANABAZAR SQUARE LETTER KA", "h" : "11A0B"},
{"g" : "\u{11A0C}", "n" : "ZANABAZAR SQUARE LETTER KHA", "h" : "11A0C"},
{"g" : "\u{11A0D}", "n" : "ZANABAZAR SQUARE LETTER GA", "h" : "11A0D"},
{"g" : "\u{11A0E}", "n" : "ZANABAZAR SQUARE LETTER GHA", "h" : "11A0E"},
{"g" : "\u{11A0F}", "n" : "ZANABAZAR SQUARE LETTER NGA", "h" : "11A0F"},
{"g" : "\u{11A10}", "n" : "ZANABAZAR SQUARE LETTER CA", "h" : "11A10"},
{"g" : "\u{11A11}", "n" : "ZANABAZAR SQUARE LETTER CHA", "h" : "11A11"},
{"g" : "\u{11A12}", "n" : "ZANABAZAR SQUARE LETTER JA", "h" : "11A12"},
{"g" : "\u{11A13}", "n" : "ZANABAZAR SQUARE LETTER NYA", "h" : "11A13"},
{"g" : "\u{11A14}", "n" : "ZANABAZAR SQUARE LETTER TTA", "h" : "11A14"},
{"g" : "\u{11A15}", "n" : "ZANABAZAR SQUARE LETTER TTHA", "h" : "11A15"},
{"g" : "\u{11A16}", "n" : "ZANABAZAR SQUARE LETTER DDA", "h" : "11A16"},
{"g" : "\u{11A17}", "n" : "ZANABAZAR SQUARE LETTER DDHA", "h" : "11A17"},
{"g" : "\u{11A18}", "n" : "ZANABAZAR SQUARE LETTER NNA", "h" : "11A18"},
{"g" : "\u{11A19}", "n" : "ZANABAZAR SQUARE LETTER TA", "h" : "11A19"},
{"g" : "\u{11A1A}", "n" : "ZANABAZAR SQUARE LETTER THA", "h" : "11A1A"},
{"g" : "\u{11A1B}", "n" : "ZANABAZAR SQUARE LETTER DA", "h" : "11A1B"},
{"g" : "\u{11A1C}", "n" : "ZANABAZAR SQUARE LETTER DHA", "h" : "11A1C"},
{"g" : "\u{11A1D}", "n" : "ZANABAZAR SQUARE LETTER NA", "h" : "11A1D"},
{"g" : "\u{11A1E}", "n" : "ZANABAZAR SQUARE LETTER PA", "h" : "11A1E"},
{"g" : "\u{11A1F}", "n" : "ZANABAZAR SQUARE LETTER PHA", "h" : "11A1F"},
{"g" : "\u{11A20}", "n" : "ZANABAZAR SQUARE LETTER BA", "h" : "11A20"},
{"g" : "\u{11A21}", "n" : "ZANABAZAR SQUARE LETTER BHA", "h" : "11A21"},
{"g" : "\u{11A22}", "n" : "ZANABAZAR SQUARE LETTER MA", "h" : "11A22"},
{"g" : "\u{11A23}", "n" : "ZANABAZAR SQUARE LETTER TSA", "h" : "11A23"},
{"g" : "\u{11A24}", "n" : "ZANABAZAR SQUARE LETTER TSHA", "h" : "11A24"},
{"g" : "\u{11A25}", "n" : "ZANABAZAR SQUARE LETTER DZA", "h" : "11A25"},
{"g" : "\u{11A26}", "n" : "ZANABAZAR SQUARE LETTER DZHA", "h" : "11A26"},
{"g" : "\u{11A27}", "n" : "ZANABAZAR SQUARE LETTER ZHA", "h" : "11A27"},
{"g" : "\u{11A28}", "n" : "ZANABAZAR SQUARE LETTER ZA", "h" : "11A28"},
{"g" : "\u{11A29}", "n" : "ZANABAZAR SQUARE LETTER -A", "h" : "11A29"},
{"g" : "\u{11A2A}", "n" : "ZANABAZAR SQUARE LETTER YA", "h" : "11A2A"},
{"g" : "\u{11A2B}", "n" : "ZANABAZAR SQUARE LETTER RA", "h" : "11A2B"},
{"g" : "\u{11A2C}", "n" : "ZANABAZAR SQUARE LETTER LA", "h" : "11A2C"},
{"g" : "\u{11A2D}", "n" : "ZANABAZAR SQUARE LETTER VA", "h" : "11A2D"},
{"g" : "\u{11A2E}", "n" : "ZANABAZAR SQUARE LETTER SHA", "h" : "11A2E"},
{"g" : "\u{11A2F}", "n" : "ZANABAZAR SQUARE LETTER SSA", "h" : "11A2F"},
{"g" : "\u{11A30}", "n" : "ZANABAZAR SQUARE LETTER SA", "h" : "11A30"},
{"g" : "\u{11A31}", "n" : "ZANABAZAR SQUARE LETTER HA", "h" : "11A31"},
{"g" : "\u{11A32}", "n" : "ZANABAZAR SQUARE LETTER KSSA", "h" : "11A32"},
{"g" : "\u{11A33}", "n" : "ZANABAZAR SQUARE FINAL CONSONANT MARK", "h" : "11A33"},
{"g" : "\u{11A34}", "n" : "ZANABAZAR SQUARE SIGN VIRAMA", "h" : "11A34"},
{"g" : "\u{11A35}", "n" : "ZANABAZAR SQUARE SIGN CANDRABINDU", "h" : "11A35"},
{"g" : "\u{11A36}", "n" : "ZANABAZAR SQUARE SIGN CANDRABINDU WITH ORNAMENT", "h" : "11A36"},
{"g" : "\u{11A37}", "n" : "ZANABAZAR SQUARE SIGN CANDRA WITH ORNAMENT", "h" : "11A37"},
{"g" : "\u{11A38}", "n" : "ZANABAZAR SQUARE SIGN ANUSVARA", "h" : "11A38"},
{"g" : "\u{11A39}", "n" : "ZANABAZAR SQUARE SIGN VISARGA", "h" : "11A39"},
{"g" : "\u{11A3A}", "n" : "ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA", "h" : "11A3A"},
{"g" : "\u{11A3B}", "n" : "ZANABAZAR SQUARE CLUSTER-FINAL LETTER YA", "h" : "11A3B"},
{"g" : "\u{11A3C}", "n" : "ZANABAZAR SQUARE CLUSTER-FINAL LETTER RA", "h" : "11A3C"},
{"g" : "\u{11A3D}", "n" : "ZANABAZAR SQUARE CLUSTER-FINAL LETTER LA", "h" : "11A3D"},
{"g" : "\u{11A3E}", "n" : "ZANABAZAR SQUARE CLUSTER-FINAL LETTER VA", "h" : "11A3E"},
{"g" : "\u{11A3F}", "n" : "ZANABAZAR SQUARE INITIAL HEAD MARK", "h" : "11A3F"},
{"g" : "\u{11A40}", "n" : "ZANABAZAR SQUARE CLOSING HEAD MARK", "h" : "11A40"},
{"g" : "\u{11A41}", "n" : "ZANABAZAR SQUARE MARK TSHEG", "h" : "11A41"},
{"g" : "\u{11A42}", "n" : "ZANABAZAR SQUARE MARK SHAD", "h" : "11A42"},
{"g" : "\u{11A43}", "n" : "ZANABAZAR SQUARE MARK DOUBLE SHAD", "h" : "11A43"},
{"g" : "\u{11A44}", "n" : "ZANABAZAR SQUARE MARK LONG TSHEG", "h" : "11A44"},
{"g" : "\u{11A45}", "n" : "ZANABAZAR SQUARE INITIAL DOUBLE-LINED HEAD MARK", "h" : "11A45"},
{"g" : "\u{11A46}", "n" : "ZANABAZAR SQUARE CLOSING DOUBLE-LINED HEAD MARK", "h" : "11A46"},
{"g" : "\u{11A47}", "n" : "ZANABAZAR SQUARE SUBJOINER", "h" : "11A47"},

{"g" : "\u{11A50}", "n" : "SOYOMBO LETTER A", "h" : "11A50"},
{"g" : "\u{11A51}", "n" : "SOYOMBO VOWEL SIGN I", "h" : "11A51"},
{"g" : "\u{11A52}", "n" : "SOYOMBO VOWEL SIGN UE", "h" : "11A52"},
{"g" : "\u{11A53}", "n" : "SOYOMBO VOWEL SIGN U", "h" : "11A53"},
{"g" : "\u{11A54}", "n" : "SOYOMBO VOWEL SIGN E", "h" : "11A54"},
{"g" : "\u{11A55}", "n" : "SOYOMBO VOWEL SIGN O", "h" : "11A55"},
{"g" : "\u{11A56}", "n" : "SOYOMBO VOWEL SIGN OE", "h" : "11A56"},
{"g" : "\u{11A57}", "n" : "SOYOMBO VOWEL SIGN AI", "h" : "11A57"},
{"g" : "\u{11A58}", "n" : "SOYOMBO VOWEL SIGN AU", "h" : "11A58"},
{"g" : "\u{11A59}", "n" : "SOYOMBO VOWEL SIGN VOCALIC R", "h" : "11A59"},
{"g" : "\u{11A5A}", "n" : "SOYOMBO VOWEL SIGN VOCALIC L", "h" : "11A5A"},
{"g" : "\u{11A5B}", "n" : "SOYOMBO VOWEL LENGTH MARK", "h" : "11A5B"},
{"g" : "\u{11A5C}", "n" : "SOYOMBO LETTER KA", "h" : "11A5C"},
{"g" : "\u{11A5D}", "n" : "SOYOMBO LETTER KHA", "h" : "11A5D"},
{"g" : "\u{11A5E}", "n" : "SOYOMBO LETTER GA", "h" : "11A5E"},
{"g" : "\u{11A5F}", "n" : "SOYOMBO LETTER GHA", "h" : "11A5F"},
{"g" : "\u{11A60}", "n" : "SOYOMBO LETTER NGA", "h" : "11A60"},
{"g" : "\u{11A61}", "n" : "SOYOMBO LETTER CA", "h" : "11A61"},
{"g" : "\u{11A62}", "n" : "SOYOMBO LETTER CHA", "h" : "11A62"},
{"g" : "\u{11A63}", "n" : "SOYOMBO LETTER JA", "h" : "11A63"},
{"g" : "\u{11A64}", "n" : "SOYOMBO LETTER JHA", "h" : "11A64"},
{"g" : "\u{11A65}", "n" : "SOYOMBO LETTER NYA", "h" : "11A65"},
{"g" : "\u{11A66}", "n" : "SOYOMBO LETTER TTA", "h" : "11A66"},
{"g" : "\u{11A67}", "n" : "SOYOMBO LETTER TTHA", "h" : "11A67"},
{"g" : "\u{11A68}", "n" : "SOYOMBO LETTER DDA", "h" : "11A68"},
{"g" : "\u{11A69}", "n" : "SOYOMBO LETTER DDHA", "h" : "11A69"},
{"g" : "\u{11A6A}", "n" : "SOYOMBO LETTER NNA", "h" : "11A6A"},
{"g" : "\u{11A6B}", "n" : "SOYOMBO LETTER TA", "h" : "11A6B"},
{"g" : "\u{11A6C}", "n" : "SOYOMBO LETTER THA", "h" : "11A6C"},
{"g" : "\u{11A6D}", "n" : "SOYOMBO LETTER DA", "h" : "11A6D"},
{"g" : "\u{11A6E}", "n" : "SOYOMBO LETTER DHA", "h" : "11A6E"},
{"g" : "\u{11A6F}", "n" : "SOYOMBO LETTER NA", "h" : "11A6F"},
{"g" : "\u{11A70}", "n" : "SOYOMBO LETTER PA", "h" : "11A70"},
{"g" : "\u{11A71}", "n" : "SOYOMBO LETTER PHA", "h" : "11A71"},
{"g" : "\u{11A72}", "n" : "SOYOMBO LETTER BA", "h" : "11A72"},
{"g" : "\u{11A73}", "n" : "SOYOMBO LETTER BHA", "h" : "11A73"},
{"g" : "\u{11A74}", "n" : "SOYOMBO LETTER MA", "h" : "11A74"},
{"g" : "\u{11A75}", "n" : "SOYOMBO LETTER TSA", "h" : "11A75"},
{"g" : "\u{11A76}", "n" : "SOYOMBO LETTER TSHA", "h" : "11A76"},
{"g" : "\u{11A77}", "n" : "SOYOMBO LETTER DZA", "h" : "11A77"},
{"g" : "\u{11A78}", "n" : "SOYOMBO LETTER ZHA", "h" : "11A78"},
{"g" : "\u{11A79}", "n" : "SOYOMBO LETTER ZA", "h" : "11A79"},
{"g" : "\u{11A7A}", "n" : "SOYOMBO LETTER -A", "h" : "11A7A"},
{"g" : "\u{11A7B}", "n" : "SOYOMBO LETTER YA", "h" : "11A7B"},
{"g" : "\u{11A7C}", "n" : "SOYOMBO LETTER RA", "h" : "11A7C"},
{"g" : "\u{11A7D}", "n" : "SOYOMBO LETTER LA", "h" : "11A7D"},
{"g" : "\u{11A7E}", "n" : "SOYOMBO LETTER VA", "h" : "11A7E"},
{"g" : "\u{11A7F}", "n" : "SOYOMBO LETTER SHA", "h" : "11A7F"},
{"g" : "\u{11A80}", "n" : "SOYOMBO LETTER SSA", "h" : "11A80"},
{"g" : "\u{11A81}", "n" : "SOYOMBO LETTER SA", "h" : "11A81"},
{"g" : "\u{11A82}", "n" : "SOYOMBO LETTER HA", "h" : "11A82"},
{"g" : "\u{11A83}", "n" : "SOYOMBO LETTER KSSA", "h" : "11A83"},
{"g" : "\u{11A84}", "n" : "SOYOMBO SIGN JIHVAMULIYA", "h" : "11A84"},
{"g" : "\u{11A85}", "n" : "SOYOMBO SIGN UPADHMANIYA", "h" : "11A85"},
{"g" : "\u{11A86}", "n" : "SOYOMBO CLUSTER-INITIAL LETTER RA", "h" : "11A86"},
{"g" : "\u{11A87}", "n" : "SOYOMBO CLUSTER-INITIAL LETTER LA", "h" : "11A87"},
{"g" : "\u{11A88}", "n" : "SOYOMBO CLUSTER-INITIAL LETTER SHA", "h" : "11A88"},
{"g" : "\u{11A89}", "n" : "SOYOMBO CLUSTER-INITIAL LETTER SA", "h" : "11A89"},
{"g" : "\u{11A8A}", "n" : "SOYOMBO FINAL CONSONANT SIGN G", "h" : "11A8A"},
{"g" : "\u{11A8B}", "n" : "SOYOMBO FINAL CONSONANT SIGN K", "h" : "11A8B"},
{"g" : "\u{11A8C}", "n" : "SOYOMBO FINAL CONSONANT SIGN NG", "h" : "11A8C"},
{"g" : "\u{11A8D}", "n" : "SOYOMBO FINAL CONSONANT SIGN D", "h" : "11A8D"},
{"g" : "\u{11A8E}", "n" : "SOYOMBO FINAL CONSONANT SIGN N", "h" : "11A8E"},
{"g" : "\u{11A8F}", "n" : "SOYOMBO FINAL CONSONANT SIGN B", "h" : "11A8F"},
{"g" : "\u{11A90}", "n" : "SOYOMBO FINAL CONSONANT SIGN M", "h" : "11A90"},
{"g" : "\u{11A91}", "n" : "SOYOMBO FINAL CONSONANT SIGN R", "h" : "11A91"},
{"g" : "\u{11A92}", "n" : "SOYOMBO FINAL CONSONANT SIGN L", "h" : "11A92"},
{"g" : "\u{11A93}", "n" : "SOYOMBO FINAL CONSONANT SIGN SH", "h" : "11A93"},
{"g" : "\u{11A94}", "n" : "SOYOMBO FINAL CONSONANT SIGN S", "h" : "11A94"},
{"g" : "\u{11A95}", "n" : "SOYOMBO FINAL CONSONANT SIGN -A", "h" : "11A95"},
{"g" : "\u{11A96}", "n" : "SOYOMBO SIGN ANUSVARA", "h" : "11A96"},
{"g" : "\u{11A97}", "n" : "SOYOMBO SIGN VISARGA", "h" : "11A97"},
{"g" : "\u{11A98}", "n" : "SOYOMBO GEMINATION MARK", "h" : "11A98"},
{"g" : "\u{11A99}", "n" : "SOYOMBO SUBJOINER", "h" : "11A99"},
{"g" : "\u{11A9A}", "n" : "SOYOMBO MARK TSHEG", "h" : "11A9A"},
{"g" : "\u{11A9B}", "n" : "SOYOMBO MARK SHAD", "h" : "11A9B"},
{"g" : "\u{11A9C}", "n" : "SOYOMBO MARK DOUBLE SHAD", "h" : "11A9C"},
{"g" : "\u{11A9D}", "n" : "SOYOMBO MARK PLUTA", "h" : "11A9D"},
{"g" : "\u{11A9E}", "n" : "SOYOMBO HEAD MARK WITH MOON AND SUN AND TRIPLE FLAME", "h" : "11A9E"},
{"g" : "\u{11A9F}", "n" : "SOYOMBO HEAD MARK WITH MOON AND SUN AND FLAME", "h" : "11A9F"},
{"g" : "\u{11AA0}", "n" : "SOYOMBO HEAD MARK WITH MOON AND SUN", "h" : "11AA0"},
{"g" : "\u{11AA1}", "n" : "SOYOMBO TERMINAL MARK-1", "h" : "11AA1"},
{"g" : "\u{11AA2}", "n" : "SOYOMBO TERMINAL MARK-2", "h" : "11AA2"},

{"g" : "\u{11C70}", "n" : "MARCHEN HEAD MARK", "h" : "11C70"},
{"g" : "\u{11C71}", "n" : "MARCHEN MARK SHAD", "h" : "11C71"},
{"g" : "\u{11C72}", "n" : "MARCHEN LETTER KA", "h" : "11C72"},
{"g" : "\u{11C73}", "n" : "MARCHEN LETTER KHA", "h" : "11C73"},
{"g" : "\u{11C74}", "n" : "MARCHEN LETTER GA", "h" : "11C74"},
{"g" : "\u{11C75}", "n" : "MARCHEN LETTER NGA", "h" : "11C75"},
{"g" : "\u{11C76}", "n" : "MARCHEN LETTER CA", "h" : "11C76"},
{"g" : "\u{11C77}", "n" : "MARCHEN LETTER CHA", "h" : "11C77"},
{"g" : "\u{11C78}", "n" : "MARCHEN LETTER JA", "h" : "11C78"},
{"g" : "\u{11C79}", "n" : "MARCHEN LETTER NYA", "h" : "11C79"},
{"g" : "\u{11C7A}", "n" : "MARCHEN LETTER TA", "h" : "11C7A"},
{"g" : "\u{11C7B}", "n" : "MARCHEN LETTER THA", "h" : "11C7B"},
{"g" : "\u{11C7C}", "n" : "MARCHEN LETTER DA", "h" : "11C7C"},
{"g" : "\u{11C7D}", "n" : "MARCHEN LETTER NA", "h" : "11C7D"},
{"g" : "\u{11C7E}", "n" : "MARCHEN LETTER PA", "h" : "11C7E"},
{"g" : "\u{11C7F}", "n" : "MARCHEN LETTER PHA", "h" : "11C7F"},
{"g" : "\u{11C80}", "n" : "MARCHEN LETTER BA", "h" : "11C80"},
{"g" : "\u{11C81}", "n" : "MARCHEN LETTER MA", "h" : "11C81"},
{"g" : "\u{11C82}", "n" : "MARCHEN LETTER TSA", "h" : "11C82"},
{"g" : "\u{11C83}", "n" : "MARCHEN LETTER TSHA", "h" : "11C83"},
{"g" : "\u{11C84}", "n" : "MARCHEN LETTER DZA", "h" : "11C84"},
{"g" : "\u{11C85}", "n" : "MARCHEN LETTER WA", "h" : "11C85"},
{"g" : "\u{11C86}", "n" : "MARCHEN LETTER ZHA", "h" : "11C86"},
{"g" : "\u{11C87}", "n" : "MARCHEN LETTER ZA", "h" : "11C87"},
{"g" : "\u{11C88}", "n" : "MARCHEN LETTER -A", "h" : "11C88"},
{"g" : "\u{11C89}", "n" : "MARCHEN LETTER YA", "h" : "11C89"},
{"g" : "\u{11C8A}", "n" : "MARCHEN LETTER RA", "h" : "11C8A"},
{"g" : "\u{11C8B}", "n" : "MARCHEN LETTER LA", "h" : "11C8B"},
{"g" : "\u{11C8C}", "n" : "MARCHEN LETTER SHA", "h" : "11C8C"},
{"g" : "\u{11C8D}", "n" : "MARCHEN LETTER SA", "h" : "11C8D"},
{"g" : "\u{11C8E}", "n" : "MARCHEN LETTER HA", "h" : "11C8E"},
{"g" : "\u{11C8F}", "n" : "MARCHEN LETTER A", "h" : "11C8F"},

{"g" : "\u{11C92}", "n" : "MARCHEN SUBJOINED LETTER KA", "h" : "11C92"},
{"g" : "\u{11C93}", "n" : "MARCHEN SUBJOINED LETTER KHA", "h" : "11C93"},
{"g" : "\u{11C94}", "n" : "MARCHEN SUBJOINED LETTER GA", "h" : "11C94"},
{"g" : "\u{11C95}", "n" : "MARCHEN SUBJOINED LETTER NGA", "h" : "11C95"},
{"g" : "\u{11C96}", "n" : "MARCHEN SUBJOINED LETTER CA", "h" : "11C96"},
{"g" : "\u{11C97}", "n" : "MARCHEN SUBJOINED LETTER CHA", "h" : "11C97"},
{"g" : "\u{11C98}", "n" : "MARCHEN SUBJOINED LETTER JA", "h" : "11C98"},
{"g" : "\u{11C99}", "n" : "MARCHEN SUBJOINED LETTER NYA", "h" : "11C99"},
{"g" : "\u{11C9A}", "n" : "MARCHEN SUBJOINED LETTER TA", "h" : "11C9A"},
{"g" : "\u{11C9B}", "n" : "MARCHEN SUBJOINED LETTER THA", "h" : "11C9B"},
{"g" : "\u{11C9C}", "n" : "MARCHEN SUBJOINED LETTER DA", "h" : "11C9C"},
{"g" : "\u{11C9D}", "n" : "MARCHEN SUBJOINED LETTER NA", "h" : "11C9D"},
{"g" : "\u{11C9E}", "n" : "MARCHEN SUBJOINED LETTER PA", "h" : "11C9E"},
{"g" : "\u{11C9F}", "n" : "MARCHEN SUBJOINED LETTER PHA", "h" : "11C9F"},
{"g" : "\u{11CA0}", "n" : "MARCHEN SUBJOINED LETTER BA", "h" : "11CA0"},
{"g" : "\u{11CA1}", "n" : "MARCHEN SUBJOINED LETTER MA", "h" : "11CA1"},
{"g" : "\u{11CA2}", "n" : "MARCHEN SUBJOINED LETTER TSA", "h" : "11CA2"},
{"g" : "\u{11CA3}", "n" : "MARCHEN SUBJOINED LETTER TSHA", "h" : "11CA3"},
{"g" : "\u{11CA4}", "n" : "MARCHEN SUBJOINED LETTER DZA", "h" : "11CA4"},
{"g" : "\u{11CA5}", "n" : "MARCHEN SUBJOINED LETTER WA", "h" : "11CA5"},
{"g" : "\u{11CA6}", "n" : "MARCHEN SUBJOINED LETTER ZHA", "h" : "11CA6"},
{"g" : "\u{11CA7}", "n" : "MARCHEN SUBJOINED LETTER ZA", "h" : "11CA7"},

{"g" : "\u{11CA9}", "n" : "MARCHEN SUBJOINED LETTER YA", "h" : "11CA9"},
{"g" : "\u{11CAA}", "n" : "MARCHEN SUBJOINED LETTER RA", "h" : "11CAA"},
{"g" : "\u{11CAB}", "n" : "MARCHEN SUBJOINED LETTER LA", "h" : "11CAB"},
{"g" : "\u{11CAC}", "n" : "MARCHEN SUBJOINED LETTER SHA", "h" : "11CAC"},
{"g" : "\u{11CAD}", "n" : "MARCHEN SUBJOINED LETTER SA", "h" : "11CAD"},
{"g" : "\u{11CAE}", "n" : "MARCHEN SUBJOINED LETTER HA", "h" : "11CAE"},
{"g" : "\u{11CAF}", "n" : "MARCHEN SUBJOINED LETTER A", "h" : "11CAF"},
{"g" : "\u{11CB0}", "n" : "MARCHEN VOWEL SIGN AA", "h" : "11CB0"},
{"g" : "\u{11CB1}", "n" : "MARCHEN VOWEL SIGN I", "h" : "11CB1"},
{"g" : "\u{11CB2}", "n" : "MARCHEN VOWEL SIGN U", "h" : "11CB2"},
{"g" : "\u{11CB3}", "n" : "MARCHEN VOWEL SIGN E", "h" : "11CB3"},
{"g" : "\u{11CB4}", "n" : "MARCHEN VOWEL SIGN O", "h" : "11CB4"},
{"g" : "\u{11CB5}", "n" : "MARCHEN SIGN ANUSVARA", "h" : "11CB5"},
{"g" : "\u{11CB6}", "n" : "MARCHEN SIGN CANDRABINDU", "h" : "11CB6"}
];
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    	var myPara1 = document.createElement('p');
    	var myPara2 = document.createElement('p');
    	var myPara3 = document.createElement('p');
		  var myPara4 = document.createElement('p');
		  var myPara5 = document.createElement('p');
		  var myPara6 = document.createElement('p');

    	myPara1.textContent = glyph;
    	myPara2.textContent = name;
    	myPara3.textContent = 'U+' + hex;
		  myPara4.textContent = '&#x' + hex + ';';
		  myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
		  myPara6.textContent = '\\' + 'u' + hex;

    	myArticle.appendChild(myPara1);
    	myArticle.appendChild(myPara2);
    	myArticle.appendChild(myPara3);
		  myArticle.appendChild(myPara4);
		  myArticle.appendChild(myPara5);
		  myArticle.appendChild(myPara6);

      section.appendChild(myArticle);
  }
}
