var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u02B0", "n" : "MODIFIER LETTER SMALL H", "h" : "02B0" },
{"g" : "\u02B1", "n" : "MODIFIER LETTER SMALL H WITH HOOK", "h" : "02B1" },
{"g" : "\u02B2", "n" : "MODIFIER LETTER SMALL J", "h" : "02B2" },
{"g" : "\u02B3", "n" : "MODIFIER LETTER SMALL R", "h" : "02B3" },
{"g" : "\u02B4", "n" : "MODIFIER LETTER SMALL TURNED R", "h" : "02B4" },
{"g" : "\u02B5", "n" : "MODIFIER LETTER SMALL TURNED R WITH HOOK", "h" : "02B5" },
{"g" : "\u02B6", "n" : "MODIFIER LETTER SMALL CAPITAL INVERTED R", "h" : "02B6" },
{"g" : "\u02B7", "n" : "MODIFIER LETTER SMALL W", "h" : "02B7" },
{"g" : "\u02B8", "n" : "MODIFIER LETTER SMALL Y", "h" : "02B8" },
{"g" : "\u02B9", "n" : "MODIFIER LETTER PRIME", "h" : "02B9" },
{"g" : "\u02BA", "n" : "MODIFIER LETTER DOUBLE PRIME", "h" : "02BA" },
{"g" : "\u02BB", "n" : "MODIFIER LETTER TURNED COMMA", "h" : "02BB" },
{"g" : "\u02BC", "n" : "MODIFIER LETTER APOSTROPHE", "h" : "02BC" },
{"g" : "\u02BD", "n" : "MODIFIER LETTER REVERSED COMMA", "h" : "02BD" },
{"g" : "\u02BE", "n" : "MODIFIER LETTER RIGHT HALF RING", "h" : "02BE" },
{"g" : "\u02BF", "n" : "MODIFIER LETTER LEFT HALF RING", "h" : "02BF" },
{"g" : "\u02C0", "n" : "MODIFIER LETTER GLOTTAL STOP", "h" : "02C0" },
{"g" : "\u02C1", "n" : "MODIFIER LETTER REVERSED GLOTTAL STOP", "h" : "02C1" },
{"g" : "\u02C2", "n" : "MODIFIER LETTER LEFT ARROWHEAD", "h" : "02C2" },
{"g" : "\u02C3", "n" : "MODIFIER LETTER RIGHT ARROWHEAD", "h" : "02C3" },
{"g" : "\u02C4", "n" : "MODIFIER LETTER UP ARROWHEAD", "h" : "02C4" },
{"g" : "\u02C5", "n" : "MODIFIER LETTER DOWN ARROWHEAD", "h" : "02C5" },
{"g" : "\u02C6", "n" : "MODIFIER LETTER CIRCUMFLEX ACCENT", "h" : "02C6" },
{"g" : "\u02C7", "n" : "CARON", "h" : "02C7" },
{"g" : "\u02C8", "n" : "MODIFIER LETTER VERTICAL LINE", "h" : "02C8" },
{"g" : "\u02C9", "n" : "MODIFIER LETTER MACRON", "h" : "02C9" },
{"g" : "\u02CA", "n" : "MODIFIER LETTER ACUTE ACCENT", "h" : "02CA" },
{"g" : "\u02CB", "n" : "MODIFIER LETTER GRAVE ACCENT", "h" : "02CB" },
{"g" : "\u02CC", "n" : "MODIFIER LETTER LOW VERTICAL LINE", "h" : "02CC" },
{"g" : "\u02CD", "n" : "MODIFIER LETTER LOW MACRON", "h" : "02CD" },
{"g" : "\u02CE", "n" : "MODIFIER LETTER LOW GRAVE ACCENT", "h" : "02CE" },
{"g" : "\u02CF", "n" : "MODIFIER LETTER LOW ACUTE ACCENT", "h" : "02CF" },
{"g" : "\u02D0", "n" : "MODIFIER LETTER TRIANGULAR COLON", "h" : "02D0" },
{"g" : "\u02D1", "n" : "MODIFIER LETTER HALF TRIANGULAR COLON", "h" : "02D1" },
{"g" : "\u02D2", "n" : "MODIFIER LETTER CENTRED RIGHT HALF RING", "h" : "02D2" },
{"g" : "\u02D3", "n" : "MODIFIER LETTER CENTRED LEFT HALF RING", "h" : "02D3" },
{"g" : "\u02D4", "n" : "MODIFIER LETTER UP TACK", "h" : "02D4" },
{"g" : "\u02D5", "n" : "MODIFIER LETTER DOWN TACK", "h" : "02D5" },
{"g" : "\u02D6", "n" : "MODIFIER LETTER PLUS SIGN", "h" : "02D6" },
{"g" : "\u02D7", "n" : "MODIFIER LETTER MINUS SIGN", "h" : "02D7" },
{"g" : "\u02D8", "n" : "BREVE", "h" : "02D8" },
{"g" : "\u02D9", "n" : "DOT ABOVE", "h" : "02D9" },
{"g" : "\u02DA", "n" : "RING ABOVE", "h" : "02DA" },
{"g" : "\u02DB", "n" : "OGONEK", "h" : "02DB" },
{"g" : "\u02DC", "n" : "SMALL TILDE", "h" : "02DC" },
{"g" : "\u02DD", "n" : "DOUBLE ACUTE ACCENT", "h" : "02DD" },
{"g" : "\u02DE", "n" : "MODIFIER LETTER RHOTIC HOOK", "h" : "02DE" },
{"g" : "\u02DF", "n" : "MODIFIER LETTER CROSS ACCENT", "h" : "02DF" },
{"g" : "\u02E0", "n" : "MODIFIER LETTER SMALL GAMMA", "h" : "02E0" },
{"g" : "\u02E1", "n" : "MODIFIER LETTER SMALL L", "h" : "02E1" },
{"g" : "\u02E2", "n" : "MODIFIER LETTER SMALL S", "h" : "02E2" },
{"g" : "\u02E3", "n" : "MODIFIER LETTER SMALL X", "h" : "02E3" },
{"g" : "\u02E4", "n" : "MODIFIER LETTER SMALL REVERSED GLOTTAL STOP", "h" : "02E4" },
{"g" : "\u02E5", "n" : "MODIFIER LETTER EXTRA-HIGH TONE BAR", "h" : "02E5" },
{"g" : "\u02E6", "n" : "MODIFIER LETTER HIGH TONE BAR", "h" : "02E6" },
{"g" : "\u02E7", "n" : "MODIFIER LETTER MID TONE BAR", "h" : "02E7" },
{"g" : "\u02E8", "n" : "MODIFIER LETTER LOW TONE BAR", "h" : "02E8" },
{"g" : "\u02E9", "n" : "MODIFIER LETTER EXTRA-LOW TONE BAR", "h" : "02E9" },
{"g" : "\u02EA", "n" : "MODIFIER LETTER YIN DEPARTING TONE MARK", "h" : "02EA" },
{"g" : "\u02EB", "n" : "MODIFIER LETTER YANG DEPARTING TONE MARK", "h" : "02EB" },
{"g" : "\u02EC", "n" : "MODIFIER LETTER VOICING", "h" : "02EC" },
{"g" : "\u02ED", "n" : "MODIFIER LETTER UNASPIRATED", "h" : "02ED" },
{"g" : "\u02EE", "n" : "MODIFIER LETTER DOUBLE APOSTROPHE", "h" : "02EE" },
{"g" : "\u02EF", "n" : "MODIFIER LETTER LOW DOWN ARROWHEAD", "h" : "02EF" },
{"g" : "\u02F0", "n" : "MODIFIER LETTER LOW UP ARROWHEAD", "h" : "02F0" },
{"g" : "\u02F1", "n" : "MODIFIER LETTER LOW LEFT ARROWHEAD", "h" : "02F1" },
{"g" : "\u02F2", "n" : "MODIFIER LETTER LOW RIGHT ARROWHEAD", "h" : "02F2" },
{"g" : "\u02F3", "n" : "MODIFIER LETTER LOW RING", "h" : "02F3" },
{"g" : "\u02F4", "n" : "MODIFIER LETTER MIDDLE GRAVE ACCENT", "h" : "02F4" },
{"g" : "\u02F5", "n" : "MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT", "h" : "02F5" },
{"g" : "\u02F6", "n" : "MODIFIER LETTER MIDDLE DOUBLE ACUTE ACCENT", "h" : "02F6" },
{"g" : "\u02F7", "n" : "MODIFIER LETTER LOW TILDE", "h" : "02F7" },
{"g" : "\u02F8", "n" : "MODIFIER LETTER RAISED COLON", "h" : "02F8" },
{"g" : "\u02F9", "n" : "MODIFIER LETTER BEGIN HIGH TONE", "h" : "02F9" },
{"g" : "\u02FA", "n" : "MODIFIER LETTER END HIGH TONE", "h" : "02FA" },
{"g" : "\u02FB", "n" : "MODIFIER LETTER BEGIN LOW TONE", "h" : "02FB" },
{"g" : "\u02FC", "n" : "MODIFIER LETTER END LOW TONE", "h" : "02FC" },
{"g" : "\u02FD", "n" : "MODIFIER LETTER SHELF", "h" : "02FD" },
{"g" : "\u02FE", "n" : "MODIFIER LETTER OPEN SHELF", "h" : "02FE" },
{"g" : "\u02FF", "n" : "MODIFIER LETTER LOW LEFT ARROW", "h" : "02FF" },

{"g" : "\u0300", "n" : "COMBINING GRAVE ACCENT", "h" : "0300" },
{"g" : "\u0301", "n" : "COMBINING ACUTE ACCENT", "h" : "0301" },
{"g" : "\u0302", "n" : "COMBINING CIRCUMFLEX ACCENT", "h" : "0302" },
{"g" : "\u0303", "n" : "COMBINING TILDE", "h" : "0303" },
{"g" : "\u0304", "n" : "COMBINING MACRON", "h" : "0304" },
{"g" : "\u0305", "n" : "COMBINING OVERLINE", "h" : "0305" },
{"g" : "\u0306", "n" : "COMBINING BREVE", "h" : "0306" },
{"g" : "\u0307", "n" : "COMBINING DOT ABOVE", "h" : "0307" },
{"g" : "\u0308", "n" : "COMBINING DIAERESIS", "h" : "0308" },
{"g" : "\u0309", "n" : "COMBINING HOOK ABOVE", "h" : "0309" },
{"g" : "\u030A", "n" : "COMBINING RING ABOVE", "h" : "030A" },
{"g" : "\u030B", "n" : "COMBINING DOUBLE ACUTE ACCENT", "h" : "030B" },
{"g" : "\u030C", "n" : "COMBINING CARON", "h" : "030C" },
{"g" : "\u030D", "n" : "COMBINING VERTICAL LINE ABOVE", "h" : "030D" },
{"g" : "\u030E", "n" : "COMBINING DOUBLE VERTICAL LINE ABOVE", "h" : "030E" },
{"g" : "\u030F", "n" : "COMBINING DOUBLE GRAVE ACCENT", "h" : "030F" },
{"g" : "\u0310", "n" : "COMBINING CANDRABINDU", "h" : "0310" },
{"g" : "\u0311", "n" : "COMBINING INVERTED BREVE", "h" : "0311" },
{"g" : "\u0312", "n" : "COMBINING TURNED COMMA ABOVE", "h" : "0312" },
{"g" : "\u0313", "n" : "COMBINING COMMA ABOVE", "h" : "0313" },
{"g" : "\u0314", "n" : "COMBINING REVERSED COMMA ABOVE", "h" : "0314" },
{"g" : "\u0315", "n" : "COMBINING COMMA ABOVE RIGHT", "h" : "0315" },
{"g" : "\u0316", "n" : "COMBINING GRAVE ACCENT BELOW", "h" : "0316" },
{"g" : "\u0317", "n" : "COMBINING ACUTE ACCENT BELOW", "h" : "0317" },
{"g" : "\u0318", "n" : "COMBINING LEFT TACK BELOW", "h" : "0318" },
{"g" : "\u0319", "n" : "COMBINING RIGHT TACK BELOW", "h" : "0319" },
{"g" : "\u031A", "n" : "COMBINING LEFT ANGLE ABOVE", "h" : "031A" },
{"g" : "\u031B", "n" : "COMBINING HORN", "h" : "031B" },
{"g" : "\u031C", "n" : "COMBINING LEFT HALF RING BELOW", "h" : "031C" },
{"g" : "\u031D", "n" : "COMBINING UP TACK BELOW", "h" : "031D" },
{"g" : "\u031E", "n" : "COMBINING DOWN TACK BELOW", "h" : "031E" },
{"g" : "\u031F", "n" : "COMBINING PLUS SIGN BELOW", "h" : "031F" },
{"g" : "\u0320", "n" : "COMBINING MINUS SIGN BELOW", "h" : "0320" },
{"g" : "\u0321", "n" : "COMBINING PALATALIZED HOOK BELOW", "h" : "0321" },
{"g" : "\u0322", "n" : "COMBINING RETROFLEX HOOK BELOW", "h" : "0322" },
{"g" : "\u0323", "n" : "COMBINING DOT BELOW", "h" : "0323" },
{"g" : "\u0324", "n" : "COMBINING DIAERESIS BELOW", "h" : "0324" },
{"g" : "\u0325", "n" : "COMBINING RING BELOW", "h" : "0325" },
{"g" : "\u0326", "n" : "COMBINING COMMA BELOW", "h" : "0326" },
{"g" : "\u0327", "n" : "COMBINING CEDILLA", "h" : "0327" },
{"g" : "\u0328", "n" : "COMBINING OGONEK", "h" : "0328" },
{"g" : "\u0329", "n" : "COMBINING VERTICAL LINE BELOW", "h" : "0329" },
{"g" : "\u032A", "n" : "COMBINING BRIDGE BELOW", "h" : "032A" },
{"g" : "\u032B", "n" : "COMBINING INVERTED DOUBLE ARCH BELOW", "h" : "032B" },
{"g" : "\u032C", "n" : "COMBINING CARON BELOW", "h" : "032C" },
{"g" : "\u032D", "n" : "COMBINING CIRCUMFLEX ACCENT BELOW", "h" : "032D" },
{"g" : "\u032E", "n" : "COMBINING BREVE BELOW", "h" : "032E" },
{"g" : "\u032F", "n" : "COMBINING INVERTED BREVE BELOW", "h" : "032F" },
{"g" : "\u0330", "n" : "COMBINING TILDE BELOW", "h" : "0330" },
{"g" : "\u0331", "n" : "COMBINING MACRON BELOW", "h" : "0331" },
{"g" : "\u0332", "n" : "COMBINING LOW LINE", "h" : "0332" },
{"g" : "\u0333", "n" : "COMBINING DOUBLE LOW LINE", "h" : "0333" },
{"g" : "\u0334", "n" : "COMBINING TILDE OVERLAY", "h" : "0334" },
{"g" : "\u0335", "n" : "COMBINING SHORT STROKE OVERLAY", "h" : "0335" },
{"g" : "\u0336", "n" : "COMBINING LONG STROKE OVERLAY", "h" : "0336" },
{"g" : "\u0337", "n" : "COMBINING SHORT SOLIDUS OVERLAY", "h" : "0337" },
{"g" : "\u0338", "n" : "COMBINING LONG SOLIDUS OVERLAY", "h" : "0338" },
{"g" : "\u0339", "n" : "COMBINING RIGHT HALF RING BELOW", "h" : "0339" },
{"g" : "\u033A", "n" : "COMBINING INVERTED BRIDGE BELOW", "h" : "033A" },
{"g" : "\u033B", "n" : "COMBINING SQUARE BELOW", "h" : "033B" },
{"g" : "\u033C", "n" : "COMBINING SEAGULL BELOW", "h" : "033C" },
{"g" : "\u033D", "n" : "COMBINING X ABOVE", "h" : "033D" },
{"g" : "\u033E", "n" : "COMBINING VERTICAL TILDE", "h" : "033E" },
{"g" : "\u033F", "n" : "COMBINING DOUBLE OVERLINE", "h" : "033F" },
{"g" : "\u0340", "n" : "COMBINING GRAVE TONE MARK", "h" : "0340" },
{"g" : "\u0341", "n" : "COMBINING ACUTE TONE MARK", "h" : "0341" },
{"g" : "\u0342", "n" : "COMBINING GREEK PERISPOMENI", "h" : "0342" },
{"g" : "\u0343", "n" : "COMBINING GREEK KORONIS", "h" : "0343" },
{"g" : "\u0344", "n" : "COMBINING GREEK DIALYTIKA TONOS", "h" : "0344" },
{"g" : "\u0345", "n" : "COMBINING GREEK YPOGEGRAMMENI", "h" : "0345" },
{"g" : "\u0346", "n" : "COMBINING BRIDGE ABOVE", "h" : "0346" },
{"g" : "\u0347", "n" : "COMBINING EQUALS SIGN BELOW", "h" : "0347" },
{"g" : "\u0348", "n" : "COMBINING DOUBLE VERTICAL LINE BELOW", "h" : "0348" },
{"g" : "\u0349", "n" : "COMBINING LEFT ANGLE BELOW", "h" : "0349" },
{"g" : "\u034A", "n" : "COMBINING NOT TILDE ABOVE", "h" : "034A" },
{"g" : "\u034B", "n" : "COMBINING HOMOTHETIC ABOVE", "h" : "034B" },
{"g" : "\u034C", "n" : "COMBINING ALMOST EQUAL TO ABOVE", "h" : "034C" },
{"g" : "\u034D", "n" : "COMBINING LEFT RIGHT ARROW BELOW", "h" : "034D" },
{"g" : "\u034E", "n" : "COMBINING UPWARDS ARROW BELOW", "h" : "034E" },
{"g" : "\u034F", "n" : "COMBINING GRAPHEME JOINER", "h" : "034F" },
{"g" : "\u0350", "n" : "COMBINING RIGHT ARROWHEAD ABOVE", "h" : "0350" },
{"g" : "\u0351", "n" : "COMBINING LEFT HALF RING ABOVE", "h" : "0351" },
{"g" : "\u0352", "n" : "COMBINING FERMATA", "h" : "0352" },
{"g" : "\u0353", "n" : "COMBINING X BELOW", "h" : "0353" },
{"g" : "\u0354", "n" : "COMBINING LEFT ARROWHEAD BELOW", "h" : "0354" },
{"g" : "\u0355", "n" : "COMBINING RIGHT ARROWHEAD BELOW", "h" : "0355" },
{"g" : "\u0356", "n" : "COMBINING RIGHT ARROWHEAD AND UP ARROWHEAD BELOW", "h" : "0356" },
{"g" : "\u0357", "n" : "COMBINING RIGHT HALF RING ABOVE", "h" : "0357" },
{"g" : "\u0358", "n" : "COMBINING DOT ABOVE RIGHT", "h" : "0358" },
{"g" : "\u0359", "n" : "COMBINING ASTERISK BELOW", "h" : "0359" },
{"g" : "\u035A", "n" : "COMBINING DOUBLE RING BELOW", "h" : "035A" },
{"g" : "\u035B", "n" : "COMBINING ZIGZAG ABOVE", "h" : "035B" },
{"g" : "\u035C", "n" : "COMBINING DOUBLE BREVE BELOW", "h" : "035C" },
{"g" : "\u035D", "n" : "COMBINING DOUBLE BREVE", "h" : "035D" },
{"g" : "\u035E", "n" : "COMBINING DOUBLE MACRON", "h" : "035E" },
{"g" : "\u035F", "n" : "COMBINING DOUBLE MACRON BELOW", "h" : "035F" },
{"g" : "\u0360", "n" : "COMBINING DOUBLE TILDE", "h" : "0360" },
{"g" : "\u0361", "n" : "COMBINING DOUBLE INVERTED BREVE", "h" : "0361" },
{"g" : "\u0362", "n" : "COMBINING DOUBLE RIGHTWARDS ARROW BELOW", "h" : "0362" },
{"g" : "\u0363", "n" : "COMBINING LATIN SMALL LETTER A", "h" : "0363" },
{"g" : "\u0364", "n" : "COMBINING LATIN SMALL LETTER E", "h" : "0364" },
{"g" : "\u0365", "n" : "COMBINING LATIN SMALL LETTER I", "h" : "0365" },
{"g" : "\u0366", "n" : "COMBINING LATIN SMALL LETTER O", "h" : "0366" },
{"g" : "\u0367", "n" : "COMBINING LATIN SMALL LETTER U", "h" : "0367" },
{"g" : "\u0368", "n" : "COMBINING LATIN SMALL LETTER C", "h" : "0368" },
{"g" : "\u0369", "n" : "COMBINING LATIN SMALL LETTER D", "h" : "0369" },
{"g" : "\u036A", "n" : "COMBINING LATIN SMALL LETTER H", "h" : "036A" },
{"g" : "\u036B", "n" : "COMBINING LATIN SMALL LETTER M", "h" : "036B" },
{"g" : "\u036C", "n" : "COMBINING LATIN SMALL LETTER R", "h" : "036C" },
{"g" : "\u036D", "n" : "COMBINING LATIN SMALL LETTER T", "h" : "036D" },
{"g" : "\u036E", "n" : "COMBINING LATIN SMALL LETTER V", "h" : "036E" },
{"g" : "\u036F", "n" : "COMBINING LATIN SMALL LETTER X", "h" : "036F" },

{"g" : "\u1AB0", "n" : "COMBINING DOUBLED CIRCUMFLEX ACCENT", "h" : "1AB0" },
{"g" : "\u1AB1", "n" : "COMBINING DIAERESIS-RING", "h" : "1AB1" },
{"g" : "\u1AB2", "n" : "COMBINING INFINITY", "h" : "1AB2" },
{"g" : "\u1AB3", "n" : "COMBINING DOWNWARDS ARROW", "h" : "1AB3" },
{"g" : "\u1AB4", "n" : "COMBINING TRIPLE DOT", "h" : "1AB4" },
{"g" : "\u1AB5", "n" : "COMBINING X-X BELOW", "h" : "1AB5" },
{"g" : "\u1AB6", "n" : "COMBINING WIGGLY LINE BELOW", "h" : "1AB6" },
{"g" : "\u1AB7", "n" : "COMBINING OPEN MARK BELOW", "h" : "1AB7" },
{"g" : "\u1AB8", "n" : "COMBINING DOUBLE OPEN MARK BELOW", "h" : "1AB8" },
{"g" : "\u1AB9", "n" : "COMBINING LIGHT CENTRALIZATION STROKE BELOW", "h" : "1AB9" },
{"g" : "\u1ABA", "n" : "COMBINING STRONG CENTRALIZATION STROKE BELOW", "h" : "1ABA" },
{"g" : "\u1ABB", "n" : "COMBINING PARENTHESES ABOVE", "h" : "1ABB" },
{"g" : "\u1ABC", "n" : "COMBINING DOUBLE PARENTHESES ABOVE", "h" : "1ABC" },
{"g" : "\u1ABD", "n" : "COMBINING PARENTHESES BELOW", "h" : "1ABD" },
{"g" : "\u1ABE", "n" : "COMBINING PARENTHESES OVERLAY", "h" : "1ABE" },
{"g" : "\u1ABF", "n" : "COMBINING LATIN SMALL LETTER W BELOW", "h" : "1ABF" },
{"g" : "\u1AC0", "n" : "COMBINING LATIN SMALL LETTER TURNED W BELOW", "h" : "1AC0" },

{"g" : "\u1D2C", "n" : "MODIFIER LETTER CAPITAL A", "h" : "1D2C" },
{"g" : "\u1D2D", "n" : "MODIFIER LETTER CAPITAL AE", "h" : "1D2D" },
{"g" : "\u1D2E", "n" : "MODIFIER LETTER CAPITAL B", "h" : "1D2E" },
{"g" : "\u1D2F", "n" : "MODIFIER LETTER CAPITAL BARRED B", "h" : "1D2F" },
{"g" : "\u1D30", "n" : "MODIFIER LETTER CAPITAL D", "h" : "1D30" },
{"g" : "\u1D31", "n" : "MODIFIER LETTER CAPITAL E", "h" : "1D31" },
{"g" : "\u1D32", "n" : "MODIFIER LETTER CAPITAL REVERSED E", "h" : "1D32" },
{"g" : "\u1D33", "n" : "MODIFIER LETTER CAPITAL G", "h" : "1D33" },
{"g" : "\u1D34", "n" : "MODIFIER LETTER CAPITAL H", "h" : "1D34" },
{"g" : "\u1D35", "n" : "MODIFIER LETTER CAPITAL I", "h" : "1D35" },
{"g" : "\u1D36", "n" : "MODIFIER LETTER CAPITAL J", "h" : "1D36" },
{"g" : "\u1D37", "n" : "MODIFIER LETTER CAPITAL K", "h" : "1D37" },
{"g" : "\u1D38", "n" : "MODIFIER LETTER CAPITAL L", "h" : "1D38" },
{"g" : "\u1D39", "n" : "MODIFIER LETTER CAPITAL M", "h" : "1D39" },
{"g" : "\u1D3A", "n" : "MODIFIER LETTER CAPITAL N", "h" : "1D3A" },
{"g" : "\u1D3B", "n" : "MODIFIER LETTER CAPITAL REVERSED N", "h" : "1D3B" },
{"g" : "\u1D3C", "n" : "MODIFIER LETTER CAPITAL O", "h" : "1D3C" },
{"g" : "\u1D3D", "n" : "MODIFIER LETTER CAPITAL OU", "h" : "1D3D" },
{"g" : "\u1D3E", "n" : "MODIFIER LETTER CAPITAL P", "h" : "1D3E" },
{"g" : "\u1D3F", "n" : "MODIFIER LETTER CAPITAL R", "h" : "1D3F" },
{"g" : "\u1D40", "n" : "MODIFIER LETTER CAPITAL T", "h" : "1D40" },
{"g" : "\u1D41", "n" : "MODIFIER LETTER CAPITAL U", "h" : "1D41" },
{"g" : "\u1D42", "n" : "MODIFIER LETTER CAPITAL W", "h" : "1D42" },
{"g" : "\u1D43", "n" : "MODIFIER LETTER SMALL A", "h" : "1D43" },
{"g" : "\u1D44", "n" : "MODIFIER LETTER SMALL TURNED A", "h" : "1D44" },
{"g" : "\u1D45", "n" : "MODIFIER LETTER SMALL ALPHA", "h" : "1D45" },
{"g" : "\u1D46", "n" : "MODIFIER LETTER SMALL TURNED AE", "h" : "1D46" },
{"g" : "\u1D47", "n" : "MODIFIER LETTER SMALL B", "h" : "1D47" },
{"g" : "\u1D48", "n" : "MODIFIER LETTER SMALL D", "h" : "1D48" },
{"g" : "\u1D49", "n" : "MODIFIER LETTER SMALL E", "h" : "1D49" },
{"g" : "\u1D4A", "n" : "MODIFIER LETTER SMALL SCHWA", "h" : "1D4A" },
{"g" : "\u1D4B", "n" : "MODIFIER LETTER SMALL OPEN E", "h" : "1D4B" },
{"g" : "\u1D4C", "n" : "MODIFIER LETTER SMALL TURNED OPEN E", "h" : "1D4C" },
{"g" : "\u1D4D", "n" : "MODIFIER LETTER SMALL G", "h" : "1D4D" },
{"g" : "\u1D4E", "n" : "MODIFIER LETTER SMALL TURNED I", "h" : "1D4E" },
{"g" : "\u1D4F", "n" : "MODIFIER LETTER SMALL K", "h" : "1D4F" },
{"g" : "\u1D50", "n" : "MODIFIER LETTER SMALL M", "h" : "1D50" },
{"g" : "\u1D51", "n" : "MODIFIER LETTER SMALL ENG", "h" : "1D51" },
{"g" : "\u1D52", "n" : "MODIFIER LETTER SMALL O", "h" : "1D52" },
{"g" : "\u1D53", "n" : "MODIFIER LETTER SMALL OPEN O", "h" : "1D53" },
{"g" : "\u1D54", "n" : "MODIFIER LETTER SMALL TOP HALF O", "h" : "1D54" },
{"g" : "\u1D55", "n" : "MODIFIER LETTER SMALL BOTTOM HALF O", "h" : "1D55" },
{"g" : "\u1D56", "n" : "MODIFIER LETTER SMALL P", "h" : "1D56" },
{"g" : "\u1D57", "n" : "MODIFIER LETTER SMALL T", "h" : "1D57" },
{"g" : "\u1D58", "n" : "MODIFIER LETTER SMALL U", "h" : "1D58" },
{"g" : "\u1D59", "n" : "MODIFIER LETTER SMALL SIDEWAYS U", "h" : "1D59" },
{"g" : "\u1D5A", "n" : "MODIFIER LETTER SMALL TURNED M", "h" : "1D5A" },
{"g" : "\u1D5B", "n" : "MODIFIER LETTER SMALL V", "h" : "1D5B" },
{"g" : "\u1D5C", "n" : "MODIFIER LETTER SMALL AIN", "h" : "1D5C" },
{"g" : "\u1D5D", "n" : "MODIFIER LETTER SMALL BETA", "h" : "1D5D" },
{"g" : "\u1D5E", "n" : "MODIFIER LETTER SMALL GREEK GAMMA", "h" : "1D5E" },
{"g" : "\u1D5F", "n" : "MODIFIER LETTER SMALL DELTA", "h" : "1D5F" },
{"g" : "\u1D60", "n" : "MODIFIER LETTER SMALL GREEK PHI", "h" : "1D60" },
{"g" : "\u1D61", "n" : "MODIFIER LETTER SMALL CHI", "h" : "1D61" },

{"g" : "\u1D78", "n" : "MODIFIER LETTER CYRILLIC EN", "h" : "1D78" },

{"g" : "\u1D9B", "n" : "MODIFIER LETTER SMALL TURNED ALPHA", "h" : "1D9B" },
{"g" : "\u1D9C", "n" : "MODIFIER LETTER SMALL C", "h" : "1D9C" },
{"g" : "\u1D9D", "n" : "MODIFIER LETTER SMALL C WITH CURL", "h" : "1D9D" },
{"g" : "\u1D9E", "n" : "MODIFIER LETTER SMALL ETH", "h" : "1D9E" },
{"g" : "\u1D9F", "n" : "MODIFIER LETTER SMALL REVERSED OPEN E", "h" : "1D9F" },
{"g" : "\u1DA0", "n" : "MODIFIER LETTER SMALL F", "h" : "1DA0" },
{"g" : "\u1DA1", "n" : "MODIFIER LETTER SMALL DOTLESS J WITH STROKE", "h" : "1DA1" },
{"g" : "\u1DA2", "n" : "MODIFIER LETTER SMALL SCRIPT G", "h" : "1DA2" },
{"g" : "\u1DA3", "n" : "MODIFIER LETTER SMALL TURNED H", "h" : "1DA3" },
{"g" : "\u1DA4", "n" : "MODIFIER LETTER SMALL I WITH STROKE", "h" : "1DA4" },
{"g" : "\u1DA5", "n" : "MODIFIER LETTER SMALL IOTA", "h" : "1DA5" },
{"g" : "\u1DA6", "n" : "MODIFIER LETTER SMALL CAPITAL I", "h" : "1DA6" },
{"g" : "\u1DA7", "n" : "MODIFIER LETTER SMALL CAPITAL I WITH STROKE", "h" : "1DA7" },
{"g" : "\u1DA8", "n" : "MODIFIER LETTER SMALL J WITH CROSSED-TAIL", "h" : "1DA8" },
{"g" : "\u1DA9", "n" : "MODIFIER LETTER SMALL L WITH RETROFLEX HOOK", "h" : "1DA9" },
{"g" : "\u1DAA", "n" : "MODIFIER LETTER SMALL L WITH PALATAL HOOK", "h" : "1DAA" },
{"g" : "\u1DAB", "n" : "MODIFIER LETTER SMALL CAPITAL L", "h" : "1DAB" },
{"g" : "\u1DAC", "n" : "MODIFIER LETTER SMALL M WITH HOOK", "h" : "1DAC" },
{"g" : "\u1DAD", "n" : "MODIFIER LETTER SMALL TURNED M WITH LONG LEG", "h" : "1DAD" },
{"g" : "\u1DAE", "n" : "MODIFIER LETTER SMALL N WITH LEFT HOOK", "h" : "1DAE" },
{"g" : "\u1DAF", "n" : "MODIFIER LETTER SMALL N WITH RETROFLEX HOOK", "h" : "1DAF" },
{"g" : "\u1DB0", "n" : "MODIFIER LETTER SMALL CAPITAL N", "h" : "1DB0" },
{"g" : "\u1DB1", "n" : "MODIFIER LETTER SMALL BARRED O", "h" : "1DB1" },
{"g" : "\u1DB2", "n" : "MODIFIER LETTER SMALL PHI", "h" : "1DB2" },
{"g" : "\u1DB3", "n" : "MODIFIER LETTER SMALL S WITH HOOK", "h" : "1DB3" },
{"g" : "\u1DB4", "n" : "MODIFIER LETTER SMALL ESH", "h" : "1DB4" },
{"g" : "\u1DB5", "n" : "MODIFIER LETTER SMALL T WITH PALATAL HOOK", "h" : "1DB5" },
{"g" : "\u1DB6", "n" : "MODIFIER LETTER SMALL U BAR", "h" : "1DB6" },
{"g" : "\u1DB7", "n" : "MODIFIER LETTER SMALL UPSILON", "h" : "1DB7" },
{"g" : "\u1DB8", "n" : "MODIFIER LETTER SMALL CAPITAL U", "h" : "1DB8" },
{"g" : "\u1DB9", "n" : "MODIFIER LETTER SMALL V WITH HOOK", "h" : "1DB9" },
{"g" : "\u1DBA", "n" : "MODIFIER LETTER SMALL TURNED V", "h" : "1DBA" },
{"g" : "\u1DBB", "n" : "MODIFIER LETTER SMALL Z", "h" : "1DBB" },
{"g" : "\u1DBC", "n" : "MODIFIER LETTER SMALL Z WITH RETROFLEX HOOK", "h" : "1DBC" },
{"g" : "\u1DBD", "n" : "MODIFIER LETTER SMALL Z WITH CURL", "h" : "1DBD" },
{"g" : "\u1DBE", "n" : "MODIFIER LETTER SMALL EZH", "h" : "1DBE" },
{"g" : "\u1DBF", "n" : "MODIFIER LETTER SMALL THETA", "h" : "1DBF" },

{"g" : "\u1DC0", "n" : "COMBINING DOTTED GRAVE ACCENT", "h" : "1DC0" },
{"g" : "\u1DC1", "n" : "COMBINING DOTTED ACUTE ACCENT", "h" : "1DC1" },
{"g" : "\u1DC2", "n" : "COMBINING SNAKE BELOW", "h" : "1DC2" },
{"g" : "\u1DC3", "n" : "COMBINING SUSPENSION MARK", "h" : "1DC3" },
{"g" : "\u1DC4", "n" : "COMBINING MACRON-ACUTE", "h" : "1DC4" },
{"g" : "\u1DC5", "n" : "COMBINING GRAVE-MACRON", "h" : "1DC5" },
{"g" : "\u1DC6", "n" : "COMBINING MACRON-GRAVE", "h" : "1DC6" },
{"g" : "\u1DC7", "n" : "COMBINING ACUTE-MACRON", "h" : "1DC7" },
{"g" : "\u1DC8", "n" : "COMBINING GRAVE-ACUTE-GRAVE", "h" : "1DC8" },
{"g" : "\u1DC9", "n" : "COMBINING ACUTE-GRAVE-ACUTE", "h" : "1DC9" },
{"g" : "\u1DCA", "n" : "COMBINING LATIN SMALL LETTER R BELOW", "h" : "1DCA" },
{"g" : "\u1DCB", "n" : "COMBINING BREVE-MACRON", "h" : "1DCB" },
{"g" : "\u1DCC", "n" : "COMBINING MACRON-BREVE", "h" : "1DCC" },
{"g" : "\u1DCD", "n" : "COMBINING DOUBLE CIRCUMFLEX ABOVE", "h" : "1DCD" },
{"g" : "\u1DCE", "n" : "COMBINING OGONEK ABOVE", "h" : "1DCE" },
{"g" : "\u1DCF", "n" : "COMBINING ZIGZAG BELOW", "h" : "1DCF" },
{"g" : "\u1DD0", "n" : "COMBINING IS BELOW", "h" : "1DD0" },
{"g" : "\u1DD1", "n" : "COMBINING UR ABOVE", "h" : "1DD1" },
{"g" : "\u1DD2", "n" : "COMBINING US ABOVE", "h" : "1DD2" },
{"g" : "\u1DD3", "n" : "COMBINING LATIN SMALL LETTER FLATTENED OPEN A ABOVE", "h" : "1DD3" },
{"g" : "\u1DD4", "n" : "COMBINING LATIN SMALL LETTER AE", "h" : "1DD4" },
{"g" : "\u1DD5", "n" : "COMBINING LATIN SMALL LETTER AO", "h" : "1DD5" },
{"g" : "\u1DD6", "n" : "COMBINING LATIN SMALL LETTER AV", "h" : "1DD6" },
{"g" : "\u1DD7", "n" : "COMBINING LATIN SMALL LETTER C CEDILLA", "h" : "1DD7" },
{"g" : "\u1DD8", "n" : "COMBINING LATIN SMALL LETTER INSULAR D", "h" : "1DD8" },
{"g" : "\u1DD9", "n" : "COMBINING LATIN SMALL LETTER ETH", "h" : "1DD9" },
{"g" : "\u1DDA", "n" : "COMBINING LATIN SMALL LETTER G", "h" : "1DDA" },
{"g" : "\u1DDB", "n" : "COMBINING LATIN LETTER SMALL CAPITAL G", "h" : "1DDB" },
{"g" : "\u1DDC", "n" : "COMBINING LATIN SMALL LETTER K", "h" : "1DDC" },
{"g" : "\u1DDD", "n" : "COMBINING LATIN SMALL LETTER L", "h" : "1DDD" },
{"g" : "\u1DDE", "n" : "COMBINING LATIN LETTER SMALL CAPITAL L", "h" : "1DDE" },
{"g" : "\u1DDF", "n" : "COMBINING LATIN LETTER SMALL CAPITAL M", "h" : "1DDF" },
{"g" : "\u1DE0", "n" : "COMBINING LATIN SMALL LETTER N", "h" : "1DE0" },
{"g" : "\u1DE1", "n" : "COMBINING LATIN LETTER SMALL CAPITAL N", "h" : "1DE1" },
{"g" : "\u1DE2", "n" : "COMBINING LATIN LETTER SMALL CAPITAL R", "h" : "1DE2" },
{"g" : "\u1DE3", "n" : "COMBINING LATIN SMALL LETTER R ROTUNDA", "h" : "1DE3" },
{"g" : "\u1DE4", "n" : "COMBINING LATIN SMALL LETTER S", "h" : "1DE4" },
{"g" : "\u1DE5", "n" : "COMBINING LATIN SMALL LETTER LONG S", "h" : "1DE5" },
{"g" : "\u1DE6", "n" : "COMBINING LATIN SMALL LETTER Z", "h" : "1DE6" },
{"g" : "\u1DE7", "n" : "COMBINING LATIN SMALL LETTER ALPHA", "h" : "1DE7" },
{"g" : "\u1DE8", "n" : "COMBINING LATIN SMALL LETTER B", "h" : "1DE8" },
{"g" : "\u1DE9", "n" : "COMBINING LATIN SMALL LETTER BETA", "h" : "1DE9" },
{"g" : "\u1DEA", "n" : "COMBINING LATIN SMALL LETTER SCHWA", "h" : "1DEA" },
{"g" : "\u1DEB", "n" : "COMBINING LATIN SMALL LETTER F", "h" : "1DEB" },
{"g" : "\u1DEC", "n" : "COMBINING LATIN SMALL LETTER L WITH DOUBLE MIDDLE TILDE", "h" : "1DEC" },
{"g" : "\u1DED", "n" : "COMBINING LATIN SMALL LETTER O WITH LIGHT CENTRALIZATION STROKE", "h" : "1DED" },
{"g" : "\u1DEE", "n" : "COMBINING LATIN SMALL LETTER P", "h" : "1DEE" },
{"g" : "\u1DEF", "n" : "COMBINING LATIN SMALL LETTER ESH", "h" : "1DEF" },
{"g" : "\u1DF0", "n" : "COMBINING LATIN SMALL LETTER U WITH LIGHT CENTRALIZATION STROKE", "h" : "1DF0" },
{"g" : "\u1DF1", "n" : "COMBINING LATIN SMALL LETTER W", "h" : "1DF1" },
{"g" : "\u1DF2", "n" : "COMBINING LATIN SMALL LETTER A WITH DIAERESIS", "h" : "1DF2" },
{"g" : "\u1DF3", "n" : "COMBINING LATIN SMALL LETTER O WITH DIAERESIS", "h" : "1DF3" },
{"g" : "\u1DF4", "n" : "COMBINING LATIN SMALL LETTER U WITH DIAERESIS", "h" : "1DF4" },
{"g" : "\u1DF5", "n" : "COMBINING UP TACK ABOVE", "h" : "1DF5" },
{"g" : "\u1DF6", "n" : "COMBINING KAVYKA ABOVE RIGHT", "h" : "1DF6" },
{"g" : "\u1DF7", "n" : "COMBINING KAVYKA ABOVE LEFT", "h" : "1DF7" },
{"g" : "\u1DF8", "n" : "COMBINING DOT ABOVE LEFT", "h" : "1DF8" },
{"g" : "\u1DF9", "n" : "COMBINING WIDE INVERTED BRIDGE BELOW", "h" : "1DF9" },

{"g" : "\u1DFB", "n" : "COMBINING DELETION MARK", "h" : "1DFB" },
{"g" : "\u1DFC", "n" : "COMBINING DOUBLE INVERTED BREVE BELOW", "h" : "1DFC" },
{"g" : "\u1DFD", "n" : "COMBINING ALMOST EQUAL TO BELOW", "h" : "1DFD" },
{"g" : "\u1DFE", "n" : "COMBINING LEFT ARROWHEAD ABOVE", "h" : "1DFE" },
{"g" : "\u1DFF", "n" : "COMBINING RIGHT ARROWHEAD AND DOWN ARROWHEAD BELOW", "h" : "1DFF" },

{"g" : "\u20D0", "n" : "COMBINING LEFT HARPOON ABOVE", "h" : "20D0" },
{"g" : "\u20D1", "n" : "COMBINING RIGHT HARPOON ABOVE", "h" : "20D1" },
{"g" : "\u20D2", "n" : "COMBINING LONG VERTICAL LINE OVERLAY", "h" : "20D2" },
{"g" : "\u20D3", "n" : "COMBINING SHORT VERTICAL LINE OVERLAY", "h" : "20D3" },
{"g" : "\u20D4", "n" : "COMBINING ANTICLOCKWISE ARROW ABOVE", "h" : "20D4" },
{"g" : "\u20D5", "n" : "COMBINING CLOCKWISE ARROW ABOVE", "h" : "20D5" },
{"g" : "\u20D6", "n" : "COMBINING LEFT ARROW ABOVE", "h" : "20D6" },
{"g" : "\u20D7", "n" : "COMBINING RIGHT ARROW ABOVE", "h" : "20D7" },
{"g" : "\u20D8", "n" : "COMBINING RING OVERLAY", "h" : "20D8" },
{"g" : "\u20D9", "n" : "COMBINING CLOCKWISE RING OVERLAY", "h" : "20D9" },
{"g" : "\u20DA", "n" : "COMBINING ANTICLOCKWISE RING OVERLAY", "h" : "20DA" },
{"g" : "\u20DB", "n" : "COMBINING THREE DOTS ABOVE", "h" : "20DB" },
{"g" : "\u20DC", "n" : "COMBINING FOUR DOTS ABOVE", "h" : "20DC" },
{"g" : "\u20DD", "n" : "COMBINING ENCLOSING CIRCLE", "h" : "20DD" },
{"g" : "\u20DE", "n" : "COMBINING ENCLOSING SQUARE", "h" : "20DE" },
{"g" : "\u20DF", "n" : "COMBINING ENCLOSING DIAMOND", "h" : "20DF" },
{"g" : "\u20E0", "n" : "COMBINING ENCLOSING CIRCLE BACKSLASH", "h" : "20E0" },
{"g" : "\u20E1", "n" : "COMBINING LEFT RIGHT ARROW ABOVE", "h" : "20E1" },
{"g" : "\u20E2", "n" : "COMBINING ENCLOSING SCREEN", "h" : "20E2" },
{"g" : "\u20E3", "n" : "COMBINING ENCLOSING KEYCAP", "h" : "20E3" },
{"g" : "\u20E4", "n" : "COMBINING ENCLOSING UPWARD POINTING TRIANGLE", "h" : "20E4" },
{"g" : "\u20E5", "n" : "COMBINING REVERSE SOLIDUS OVERLAY", "h" : "20E5" },
{"g" : "\u20E6", "n" : "COMBINING DOUBLE VERTICAL STROKE OVERLAY", "h" : "20E6" },
{"g" : "\u20E7", "n" : "COMBINING ANNUITY SYMBOL", "h" : "20E7" },
{"g" : "\u20E8", "n" : "COMBINING TRIPLE UNDERDOT", "h" : "20E8" },
{"g" : "\u20E9", "n" : "COMBINING WIDE BRIDGE ABOVE", "h" : "20E9" },
{"g" : "\u20EA", "n" : "COMBINING LEFTWARDS ARROW OVERLAY", "h" : "20EA" },
{"g" : "\u20EB", "n" : "COMBINING LONG DOUBLE SOLIDUS OVERLAY", "h" : "20EB" },
{"g" : "\u20EC", "n" : "COMBINING RIGHTWARDS HARPOON WITH BARB DOWNWARDS", "h" : "20EC" },
{"g" : "\u20ED", "n" : "COMBINING LEFTWARDS HARPOON WITH BARB DOWNWARDS", "h" : "20ED" },
{"g" : "\u20EE", "n" : "COMBINING LEFT ARROW BELOW", "h" : "20EE" },
{"g" : "\u20EF", "n" : "COMBINING RIGHT ARROW BELOW", "h" : "20EF" },
{"g" : "\u20F0", "n" : "COMBINING ASTERISK ABOVE", "h" : "20F0" },

{"g" : "\u2C7D", "n" : "MODIFIER LETTER CAPITAL V", "h" : "2C7D" },

{"g" : "\u2DE0", "n" : "COMBINING CYRILLIC LETTER BE", "h" : "2DE0" },
{"g" : "\u2DE1", "n" : "COMBINING CYRILLIC LETTER VE", "h" : "2DE1" },
{"g" : "\u2DE2", "n" : "COMBINING CYRILLIC LETTER GHE", "h" : "2DE2" },
{"g" : "\u2DE3", "n" : "COMBINING CYRILLIC LETTER DE", "h" : "2DE3" },
{"g" : "\u2DE4", "n" : "COMBINING CYRILLIC LETTER ZHE", "h" : "2DE4" },
{"g" : "\u2DE5", "n" : "COMBINING CYRILLIC LETTER ZE", "h" : "2DE5" },
{"g" : "\u2DE6", "n" : "COMBINING CYRILLIC LETTER KA", "h" : "2DE6" },
{"g" : "\u2DE7", "n" : "COMBINING CYRILLIC LETTER EL", "h" : "2DE7" },
{"g" : "\u2DE8", "n" : "COMBINING CYRILLIC LETTER EM", "h" : "2DE8" },
{"g" : "\u2DE9", "n" : "COMBINING CYRILLIC LETTER EN", "h" : "2DE9" },
{"g" : "\u2DEA", "n" : "COMBINING CYRILLIC LETTER O", "h" : "2DEA" },
{"g" : "\u2DEB", "n" : "COMBINING CYRILLIC LETTER PE", "h" : "2DEB" },
{"g" : "\u2DEC", "n" : "COMBINING CYRILLIC LETTER ER", "h" : "2DEC" },
{"g" : "\u2DED", "n" : "COMBINING CYRILLIC LETTER ES", "h" : "2DED" },
{"g" : "\u2DEE", "n" : "COMBINING CYRILLIC LETTER TE", "h" : "2DEE" },
{"g" : "\u2DEF", "n" : "COMBINING CYRILLIC LETTER HA", "h" : "2DEF" },
{"g" : "\u2DF0", "n" : "COMBINING CYRILLIC LETTER TSE", "h" : "2DF0" },
{"g" : "\u2DF1", "n" : "COMBINING CYRILLIC LETTER CHE", "h" : "2DF1" },
{"g" : "\u2DF2", "n" : "COMBINING CYRILLIC LETTER SHA", "h" : "2DF2" },
{"g" : "\u2DF3", "n" : "COMBINING CYRILLIC LETTER SHCHA", "h" : "2DF3" },
{"g" : "\u2DF4", "n" : "COMBINING CYRILLIC LETTER FITA", "h" : "2DF4" },
{"g" : "\u2DF5", "n" : "COMBINING CYRILLIC LETTER ES-TE", "h" : "2DF5" },
{"g" : "\u2DF6", "n" : "COMBINING CYRILLIC LETTER A", "h" : "2DF6" },
{"g" : "\u2DF7", "n" : "COMBINING CYRILLIC LETTER IE", "h" : "2DF7" },
{"g" : "\u2DF8", "n" : "COMBINING CYRILLIC LETTER DJERV", "h" : "2DF8" },
{"g" : "\u2DF9", "n" : "COMBINING CYRILLIC LETTER MONOGRAPH UK", "h" : "2DF9" },
{"g" : "\u2DFA", "n" : "COMBINING CYRILLIC LETTER YAT", "h" : "2DFA" },
{"g" : "\u2DFB", "n" : "COMBINING CYRILLIC LETTER YU", "h" : "2DFB" },
{"g" : "\u2DFC", "n" : "COMBINING CYRILLIC LETTER IOTIFIED A", "h" : "2DFC" },
{"g" : "\u2DFD", "n" : "COMBINING CYRILLIC LETTER LITTLE YUS", "h" : "2DFD" },
{"g" : "\u2DFE", "n" : "COMBINING CYRILLIC LETTER BIG YUS", "h" : "2DFE" },
{"g" : "\u2DFF", "n" : "COMBINING CYRILLIC LETTER IOTIFIED BIG YUS", "h" : "2DFF" },
	
{"g" : "\u302A", "n" : "IDEOGRAPHIC LEVEL TONE MARK", "h" : "302A" },
{"g" : "\u302B", "n" : "IDEOGRAPHIC RISING TONE MARK", "h" : "302B" },
{"g" : "\u302C", "n" : "IDEOGRAPHIC DEPARTING TONE MARK", "h" : "302C" },
{"g" : "\u302D", "n" : "IDEOGRAPHIC ENTERING TONE MARK", "h" : "302D" },
{"g" : "\u302E", "n" : "HANGUL SINGLE DOT TONE MARK", "h" : "302E" },
{"g" : "\u302F", "n" : "HANGUL DOUBLE DOT TONE MARK", "h" : "302F" },

{"g" : "\uA66F", "n" : "COMBINING CYRILLIC VZMET", "h" : "A66F"},
{"g" : "\uA670", "n" : "COMBINING CYRILLIC TEN MILLIONS SIGN", "h" : "A670"},
{"g" : "\uA671", "n" : "COMBINING CYRILLIC HUNDRED MILLIONS SIGN", "h" : "A671"},
{"g" : "\uA672", "n" : "COMBINING CYRILLIC THOUSAND MILLIONS SIGN", "h" : "A672"},

{"g" : "\uA674", "n" : "COMBINING CYRILLIC LETTER UKRAINIAN IE", "h" : "A674"},
{"g" : "\uA675", "n" : "COMBINING CYRILLIC LETTER I", "h" : "A675"},
{"g" : "\uA676", "n" : "COMBINING CYRILLIC LETTER YI", "h" : "A676"},
{"g" : "\uA677", "n" : "COMBINING CYRILLIC LETTER U", "h" : "A677"},
{"g" : "\uA678", "n" : "COMBINING CYRILLIC LETTER HARD SIGN", "h" : "A678"},
{"g" : "\uA679", "n" : "COMBINING CYRILLIC LETTER YERU", "h" : "A679"},
{"g" : "\uA67A", "n" : "COMBINING CYRILLIC LETTER SOFT SIGN", "h" : "A67A"},
{"g" : "\uA67B", "n" : "COMBINING CYRILLIC LETTER OMEGA", "h" : "A67B"},
{"g" : "\uA67C", "n" : "COMBINING CYRILLIC KAVYKA", "h" : "A67C"},
{"g" : "\uA67D", "n" : "COMBINING CYRILLIC PAYEROK", "h" : "A67D"},

{"g" : "\uA69C", "n" : "MODIFIER LETTER CYRILLIC HARD SIGN", "h" : "A69C"},
{"g" : "\uA69D", "n" : "MODIFIER LETTER CYRILLIC SOFT SIGN", "h" : "A69D"},
{"g" : "\uA69E", "n" : "COMBINING CYRILLIC LETTER EF", "h" : "A69E"},
{"g" : "\uA69F", "n" : "COMBINING CYRILLIC LETTER IOTIFIED E", "h" : "A69F"},

{"g" : "\uA700", "n" : "MODIFIER LETTER CHINESE TONE YIN PING", "h" : "A700"},
{"g" : "\uA701", "n" : "MODIFIER LETTER CHINESE TONE YANG PING", "h" : "A701"},
{"g" : "\uA702", "n" : "MODIFIER LETTER CHINESE TONE YIN SHANG", "h" : "A702"},
{"g" : "\uA703", "n" : "MODIFIER LETTER CHINESE TONE YANG SHANG", "h" : "A703"},
{"g" : "\uA704", "n" : "MODIFIER LETTER CHINESE TONE YIN QU", "h" : "A704"},
{"g" : "\uA705", "n" : "MODIFIER LETTER CHINESE TONE YANG QU", "h" : "A705"},
{"g" : "\uA706", "n" : "MODIFIER LETTER CHINESE TONE YIN RU", "h" : "A706"},
{"g" : "\uA707", "n" : "MODIFIER LETTER CHINESE TONE YANG RU", "h" : "A707"},
{"g" : "\uA708", "n" : "MODIFIER LETTER EXTRA-HIGH DOTTED TONE BAR", "h" : "A708"},
{"g" : "\uA709", "n" : "MODIFIER LETTER HIGH DOTTED TONE BAR", "h" : "A709"},
{"g" : "\uA70A", "n" : "MODIFIER LETTER MID DOTTED TONE BAR", "h" : "A70A"},
{"g" : "\uA70B", "n" : "MODIFIER LETTER LOW DOTTED TONE BAR", "h" : "A70B"},
{"g" : "\uA70C", "n" : "MODIFIER LETTER EXTRA-LOW DOTTED TONE BAR", "h" : "A70C"},
{"g" : "\uA70D", "n" : "MODIFIER LETTER EXTRA-HIGH DOTTED LEFT-STEM TONE BAR", "h" : "A70D"},
{"g" : "\uA70E", "n" : "MODIFIER LETTER HIGH DOTTED LEFT-STEM TONE BAR", "h" : "A70E"},
{"g" : "\uA70F", "n" : "MODIFIER LETTER MID DOTTED LEFT-STEM TONE BAR", "h" : "A70F"},
{"g" : "\uA710", "n" : "MODIFIER LETTER LOW DOTTED LEFT-STEM TONE BAR", "h" : "A710"},
{"g" : "\uA711", "n" : "MODIFIER LETTER EXTRA-LOW DOTTED LEFT-STEM TONE BAR", "h" : "A711"},
{"g" : "\uA712", "n" : "MODIFIER LETTER EXTRA-HIGH LEFT-STEM TONE BAR", "h" : "A712"},
{"g" : "\uA713", "n" : "MODIFIER LETTER HIGH LEFT-STEM TONE BAR", "h" : "A713"},
{"g" : "\uA714", "n" : "MODIFIER LETTER MID LEFT-STEM TONE BAR", "h" : "A714"},
{"g" : "\uA715", "n" : "MODIFIER LETTER LOW LEFT-STEM TONE BAR", "h" : "A715"},
{"g" : "\uA716", "n" : "MODIFIER LETTER EXTRA-LOW LEFT-STEM TONE BAR", "h" : "A716"},
{"g" : "\uA717", "n" : "MODIFIER LETTER DOT VERTICAL BAR", "h" : "A717"},
{"g" : "\uA718", "n" : "MODIFIER LETTER DOT SLASH", "h" : "A718"},
{"g" : "\uA719", "n" : "MODIFIER LETTER DOT HORIZONTAL BAR", "h" : "A719"},
{"g" : "\uA71A", "n" : "MODIFIER LETTER LOWER RIGHT CORNER ANGLE", "h" : "A71A"},
{"g" : "\uA71B", "n" : "MODIFIER LETTER RAISED UP ARROW", "h" : "A71B"},
{"g" : "\uA71C", "n" : "MODIFIER LETTER RAISED DOWN ARROW", "h" : "A71C"},
{"g" : "\uA71D", "n" : "MODIFIER LETTER RAISED EXCLAMATION MARK", "h" : "A71D"},
{"g" : "\uA71E", "n" : "MODIFIER LETTER RAISED INVERTED EXCLAMATION MARK", "h" : "A71E"},
{"g" : "\uA71F", "n" : "MODIFIER LETTER LOW INVERTED EXCLAMATION MARK", "h" : "A71F"},

{"g" : "\uA720", "n" : "MODIFIER LETTER STRESS AND HIGH TONE", "h" : "A720"},
{"g" : "\uA721", "n" : "MODIFIER LETTER STRESS AND LOW TONE", "h" : "A721"},

{"g" : "\uA770", "n" : "MODIFIER LETTER US", "h" : "A770"},

{"g" : "\uA788", "n" : "MODIFIER LETTER LOW CIRCUMFLEX ACCENT", "h" : "A788"},
{"g" : "\uA789", "n" : "MODIFIER LETTER COLON", "h" : "A789"},
{"g" : "\uA78A", "n" : "MODIFIER LETTER SHORT EQUALS SIGN", "h" : "A78A"},

{"g" : "\uA7F8", "n" : "MODIFIER LETTER CAPITAL H WITH STROKE", "h" : "A7F8"},
{"g" : "\uA7F9", "n" : "MODIFIER LETTER SMALL LIGATURE OE", "h" : "A7F9"},

{"g" : "\uAB5B", "n" : "MODIFIER BREVE WITH INVERTED BREVE", "h" : "AB5B"},
{"g" : "\uAB5C", "n" : "MODIFIER LETTER SMALL HENG", "h" : "AB5C"},
{"g" : "\uAB5D", "n" : "MODIFIER LETTER SMALL L WITH INVERTED LAZY S", "h" : "AB5D"},
{"g" : "\uAB5E", "n" : "MODIFIER LETTER SMALL L WITH MIDDLE TILDE", "h" : "AB5E"},
{"g" : "\uAB5F", "n" : "MODIFIER LETTER SMALL U WITH LEFT HOOK", "h" : "AB5F"},

{"g" : "\uAB69", "n" : "MODIFIER LETTER SMALL TURNED W", "h" : "AB69"},
{"g" : "\uAB6A", "n" : "MODIFIER LETTER LEFT TACK", "h" : "AB6A"},
{"g" : "\uAB6B", "n" : "MODIFIER LETTER RIGHT TACK", "h" : "AB6B"},

{"g" : "\uFE20", "n" : "COMBINING LIGATURE LEFT HALF", "h" : "FE20"},
{"g" : "\uFE21", "n" : "COMBINING LIGATURE RIGHT HALF", "h" : "FE21"},
{"g" : "\uFE22", "n" : "COMBINING DOUBLE TILDE LEFT HALF", "h" : "FE22"},
{"g" : "\uFE23", "n" : "COMBINING DOUBLE TILDE RIGHT HALF", "h" : "FE23"},
{"g" : "\uFE24", "n" : "COMBINING MACRON LEFT HALF", "h" : "FE24"},
{"g" : "\uFE25", "n" : "COMBINING MACRON RIGHT HALF", "h" : "FE25"},
{"g" : "\uFE26", "n" : "COMBINING CONJOINING MACRON", "h" : "FE26"},
{"g" : "\uFE27", "n" : "COMBINING LIGATURE LEFT HALF BELOW", "h" : "FE27"},
{"g" : "\uFE28", "n" : "COMBINING LIGATURE RIGHT HALF BELOW", "h" : "FE28"},
{"g" : "\uFE29", "n" : "COMBINING TILDE LEFT HALF BELOW", "h" : "FE29"},
{"g" : "\uFE2A", "n" : "COMBINING TILDE RIGHT HALF BELOW", "h" : "FE2A"},
{"g" : "\uFE2B", "n" : "COMBINING MACRON LEFT HALF BELOW", "h" : "FE2B"},
{"g" : "\uFE2C", "n" : "COMBINING MACRON RIGHT HALF BELOW", "h" : "FE2C"},
{"g" : "\uFE2D", "n" : "COMBINING CONJOINING MACRON BELOW", "h" : "FE2D"},
{"g" : "\uFE2E", "n" : "COMBINING CYRILLIC TITLO LEFT HALF", "h" : "FE2E"},
{"g" : "\uFE2F", "n" : "COMBINING CYRILLIC TITLO RIGHT HALF", "h" : "FE2F"},

{"g" : "\u{10376}", "n" : "COMBINING OLD PERMIC LETTER AN", "h" : "10376"},
{"g" : "\u{10377}", "n" : "COMBINING OLD PERMIC LETTER DOI", "h" : "10377"},
{"g" : "\u{10378}", "n" : "COMBINING OLD PERMIC LETTER ZATA", "h" : "10378"},
{"g" : "\u{10379}", "n" : "COMBINING OLD PERMIC LETTER NENOE", "h" : "10379"},
{"g" : "\u{1037A}", "n" : "COMBINING OLD PERMIC LETTER SII", "h" : "1037A"},
	
{"g" : "\u{10EAB}", "n" : "YEZIDI COMBINING HAMZA MARK", "h" : "10EAB"},
{"g" : "\u{10EAC}", "n" : "YEZIDI COMBINING MADDA MARK", "h" : "10EAC"},

{"g" : "\u{1E000}", "n" : "COMBINING GLAGOLITIC LETTER AZU", "h" : "1E000"},
{"g" : "\u{1E001}", "n" : "COMBINING GLAGOLITIC LETTER BUKY", "h" : "1E001"},
{"g" : "\u{1E002}", "n" : "COMBINING GLAGOLITIC LETTER VEDE", "h" : "1E002"},
{"g" : "\u{1E003}", "n" : "COMBINING GLAGOLITIC LETTER GLAGOLI", "h" : "1E003"},
{"g" : "\u{1E004}", "n" : "COMBINING GLAGOLITIC LETTER DOBRO", "h" : "1E004"},
{"g" : "\u{1E005}", "n" : "COMBINING GLAGOLITIC LETTER YESTU", "h" : "1E005"},
{"g" : "\u{1E006}", "n" : "COMBINING GLAGOLITIC LETTER ZHIVETE", "h" : "1E006"},

{"g" : "\u{1E008}", "n" : "COMBINING GLAGOLITIC LETTER ZEMLJA", "h" : "1E008"},
{"g" : "\u{1E009}", "n" : "COMBINING GLAGOLITIC LETTER IZHE", "h" : "1E009"},
{"g" : "\u{1E00A}", "n" : "COMBINING GLAGOLITIC LETTER INITIAL IZHE", "h" : "1E00A"},
{"g" : "\u{1E00B}", "n" : "COMBINING GLAGOLITIC LETTER I", "h" : "1E00B"},
{"g" : "\u{1E00C}", "n" : "COMBINING GLAGOLITIC LETTER DJERVI", "h" : "1E00C"},
{"g" : "\u{1E00D}", "n" : "COMBINING GLAGOLITIC LETTER KAKO", "h" : "1E00D"},
{"g" : "\u{1E00E}", "n" : "COMBINING GLAGOLITIC LETTER LJUDIJE", "h" : "1E00E"},
{"g" : "\u{1E00F}", "n" : "COMBINING GLAGOLITIC LETTER MYSLITE", "h" : "1E00F"},
{"g" : "\u{1E010}", "n" : "COMBINING GLAGOLITIC LETTER NASHI", "h" : "1E010"},
{"g" : "\u{1E011}", "n" : "COMBINING GLAGOLITIC LETTER ONU", "h" : "1E011"},
{"g" : "\u{1E012}", "n" : "COMBINING GLAGOLITIC LETTER POKOJI", "h" : "1E012"},
{"g" : "\u{1E013}", "n" : "COMBINING GLAGOLITIC LETTER RITSI", "h" : "1E013"},
{"g" : "\u{1E014}", "n" : "COMBINING GLAGOLITIC LETTER SLOVO", "h" : "1E014"},
{"g" : "\u{1E015}", "n" : "COMBINING GLAGOLITIC LETTER TVRIDO", "h" : "1E015"},
{"g" : "\u{1E016}", "n" : "COMBINING GLAGOLITIC LETTER UKU", "h" : "1E016"},
{"g" : "\u{1E017}", "n" : "COMBINING GLAGOLITIC LETTER FRITU", "h" : "1E017"},
{"g" : "\u{1E018}", "n" : "COMBINING GLAGOLITIC LETTER HERU", "h" : "1E018"},

{"g" : "\u{1E01B}", "n" : "COMBINING GLAGOLITIC LETTER SHTA", "h" : "1E01B"},
{"g" : "\u{1E01C}", "n" : "COMBINING GLAGOLITIC LETTER TSI", "h" : "1E01C"},
{"g" : "\u{1E01D}", "n" : "COMBINING GLAGOLITIC LETTER CHRIVI", "h" : "1E01D"},
{"g" : "\u{1E01E}", "n" : "COMBINING GLAGOLITIC LETTER SHA", "h" : "1E01E"},
{"g" : "\u{1E01F}", "n" : "COMBINING GLAGOLITIC LETTER YERU", "h" : "1E01F"},
{"g" : "\u{1E020}", "n" : "COMBINING GLAGOLITIC LETTER YERI", "h" : "1E020"},
{"g" : "\u{1E021}", "n" : "COMBINING GLAGOLITIC LETTER YATI", "h" : "1E021"},

{"g" : "\u{1E023}", "n" : "COMBINING GLAGOLITIC LETTER YU", "h" : "1E023"},
{"g" : "\u{1E024}", "n" : "COMBINING GLAGOLITIC LETTER SMALL YUS", "h" : "1E024"},

{"g" : "\u{1E026}", "n" : "COMBINING GLAGOLITIC LETTER YO", "h" : "1E026"},
{"g" : "\u{1E027}", "n" : "COMBINING GLAGOLITIC LETTER IOTATED SMALL YUS", "h" : "1E027"},
{"g" : "\u{1E028}", "n" : "COMBINING GLAGOLITIC LETTER BIG YUS", "h" : "1E028"},
{"g" : "\u{1E029}", "n" : "COMBINING GLAGOLITIC LETTER IOTATED BIG YUS", "h" : "1E029"},
{"g" : "\u{1E02A}", "n" : "COMBINING GLAGOLITIC LETTER FITA", "h" : "1E02A"}
];
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    	var myPara1 = document.createElement('p');
    	var myPara2 = document.createElement('p');
    	var myPara3 = document.createElement('p');
		  var myPara4 = document.createElement('p');
		  var myPara5 = document.createElement('p');
		  var myPara6 = document.createElement('p');

    	myPara1.textContent = glyph;
    	myPara2.textContent = name;
    	myPara3.textContent = 'U+' + hex;
		  myPara4.textContent = '&#x' + hex + ';';
		  myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
		  myPara6.textContent = '\\' + 'u' + hex;

    	myArticle.appendChild(myPara1);
    	myArticle.appendChild(myPara2);
    	myArticle.appendChild(myPara3);
		  myArticle.appendChild(myPara4);
		  myArticle.appendChild(myPara5);
		  myArticle.appendChild(myPara6);

    section.appendChild(myArticle);
  }
}
