var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u1700", "n" : "TAGALOG LETTER A", "h" : "1700" },
{"g" : "\u1701", "n" : "TAGALOG LETTER I", "h" : "1701" },
{"g" : "\u1702", "n" : "TAGALOG LETTER U", "h" : "1702" },
{"g" : "\u1703", "n" : "TAGALOG LETTER KA", "h" : "1703" },
{"g" : "\u1704", "n" : "TAGALOG LETTER GA", "h" : "1704" },
{"g" : "\u1705", "n" : "TAGALOG LETTER NGA", "h" : "1705" },
{"g" : "\u1706", "n" : "TAGALOG LETTER TA", "h" : "1706" },
{"g" : "\u1707", "n" : "TAGALOG LETTER DA", "h" : "1707" },
{"g" : "\u1708", "n" : "TAGALOG LETTER NA", "h" : "1708" },
{"g" : "\u1709", "n" : "TAGALOG LETTER PA", "h" : "1709" },
{"g" : "\u170A", "n" : "TAGALOG LETTER BA", "h" : "170A" },
{"g" : "\u170B", "n" : "TAGALOG LETTER MA", "h" : "170B" },
{"g" : "\u170C", "n" : "TAGALOG LETTER YA", "h" : "170C" },

{"g" : "\u170E", "n" : "TAGALOG LETTER LA", "h" : "170E" },
{"g" : "\u170F", "n" : "TAGALOG LETTER WA", "h" : "170F" },
{"g" : "\u1710", "n" : "TAGALOG LETTER SA", "h" : "1710" },
{"g" : "\u1711", "n" : "TAGALOG LETTER HA", "h" : "1711" },
{"g" : "\u1712", "n" : "TAGALOG VOWEL SIGN I", "h" : "1712" },
{"g" : "\u1713", "n" : "TAGALOG VOWEL SIGN U", "h" : "1713" },
{"g" : "\u1714", "n" : "TAGALOG SIGN VIRAMA", "h" : "1714" },

{"g" : "\u1720", "n" : "HANUNOO LETTER A", "h" : "1720" },
{"g" : "\u1721", "n" : "HANUNOO LETTER I", "h" : "1721" },
{"g" : "\u1722", "n" : "HANUNOO LETTER U", "h" : "1722" },
{"g" : "\u1723", "n" : "HANUNOO LETTER KA", "h" : "1723" },
{"g" : "\u1724", "n" : "HANUNOO LETTER GA", "h" : "1724" },
{"g" : "\u1725", "n" : "HANUNOO LETTER NGA", "h" : "1725" },
{"g" : "\u1726", "n" : "HANUNOO LETTER TA", "h" : "1726" },
{"g" : "\u1727", "n" : "HANUNOO LETTER DA", "h" : "1727" },
{"g" : "\u1728", "n" : "HANUNOO LETTER NA", "h" : "1728" },
{"g" : "\u1729", "n" : "HANUNOO LETTER PA", "h" : "1729" },
{"g" : "\u172A", "n" : "HANUNOO LETTER BA", "h" : "172A" },
{"g" : "\u172B", "n" : "HANUNOO LETTER MA", "h" : "172B" },
{"g" : "\u172C", "n" : "HANUNOO LETTER YA", "h" : "172C" },
{"g" : "\u172D", "n" : "HANUNOO LETTER RA", "h" : "172D" },
{"g" : "\u172E", "n" : "HANUNOO LETTER LA", "h" : "172E" },
{"g" : "\u172F", "n" : "HANUNOO LETTER WA", "h" : "172F" },
{"g" : "\u1730", "n" : "HANUNOO LETTER SA", "h" : "1730" },
{"g" : "\u1731", "n" : "HANUNOO LETTER HA", "h" : "1731" },
{"g" : "\u1732", "n" : "HANUNOO VOWEL SIGN I", "h" : "1732" },
{"g" : "\u1733", "n" : "HANUNOO VOWEL SIGN U", "h" : "1733" },
{"g" : "\u1734", "n" : "HANUNOO SIGN PAMUDPOD", "h" : "1734" },
{"g" : "\u1735", "n" : "PHILIPPINE SINGLE PUNCTUATION", "h" : "1735" },
{"g" : "\u1736", "n" : "PHILIPPINE DOUBLE PUNCTUATION", "h" : "1736" },

{"g" : "\u1740", "n" : "BUHID LETTER A", "h" : "1740" },
{"g" : "\u1741", "n" : "BUHID LETTER I", "h" : "1741" },
{"g" : "\u1742", "n" : "BUHID LETTER U", "h" : "1742" },
{"g" : "\u1743", "n" : "BUHID LETTER KA", "h" : "1743" },
{"g" : "\u1744", "n" : "BUHID LETTER GA", "h" : "1744" },
{"g" : "\u1745", "n" : "BUHID LETTER NGA", "h" : "1745" },
{"g" : "\u1746", "n" : "BUHID LETTER TA", "h" : "1746" },
{"g" : "\u1747", "n" : "BUHID LETTER DA", "h" : "1747" },
{"g" : "\u1748", "n" : "BUHID LETTER NA", "h" : "1748" },
{"g" : "\u1749", "n" : "BUHID LETTER PA", "h" : "1749" },
{"g" : "\u174A", "n" : "BUHID LETTER BA", "h" : "174A" },
{"g" : "\u174B", "n" : "BUHID LETTER MA", "h" : "174B" },
{"g" : "\u174C", "n" : "BUHID LETTER YA", "h" : "174C" },
{"g" : "\u174D", "n" : "BUHID LETTER RA", "h" : "174D" },
{"g" : "\u174E", "n" : "BUHID LETTER LA", "h" : "174E" },
{"g" : "\u174F", "n" : "BUHID LETTER WA", "h" : "174F" },
{"g" : "\u1750", "n" : "BUHID LETTER SA", "h" : "1750" },
{"g" : "\u1751", "n" : "BUHID LETTER HA", "h" : "1751" },
{"g" : "\u1752", "n" : "BUHID VOWEL SIGN I", "h" : "1752" },
{"g" : "\u1753", "n" : "BUHID VOWEL SIGN U", "h" : "1753" },

{"g" : "\u1760", "n" : "TAGBANWA LETTER A", "h" : "1760" },
{"g" : "\u1761", "n" : "TAGBANWA LETTER I", "h" : "1761" },
{"g" : "\u1762", "n" : "TAGBANWA LETTER U", "h" : "1762" },
{"g" : "\u1763", "n" : "TAGBANWA LETTER KA", "h" : "1763" },
{"g" : "\u1764", "n" : "TAGBANWA LETTER GA", "h" : "1764" },
{"g" : "\u1765", "n" : "TAGBANWA LETTER NGA", "h" : "1765" },
{"g" : "\u1766", "n" : "TAGBANWA LETTER TA", "h" : "1766" },
{"g" : "\u1767", "n" : "TAGBANWA LETTER DA", "h" : "1767" },
{"g" : "\u1768", "n" : "TAGBANWA LETTER NA", "h" : "1768" },
{"g" : "\u1769", "n" : "TAGBANWA LETTER PA", "h" : "1769" },
{"g" : "\u176A", "n" : "TAGBANWA LETTER BA", "h" : "176A" },
{"g" : "\u176B", "n" : "TAGBANWA LETTER MA", "h" : "176B" },
{"g" : "\u176C", "n" : "TAGBANWA LETTER YA", "h" : "176C" },

{"g" : "\u176E", "n" : "TAGBANWA LETTER LA", "h" : "176E" },
{"g" : "\u176F", "n" : "TAGBANWA LETTER WA", "h" : "176F" },
{"g" : "\u1770", "n" : "TAGBANWA LETTER SA", "h" : "1770" },

{"g" : "\u1772", "n" : "TAGBANWA VOWEL SIGN I", "h" : "1772" },
{"g" : "\u1773", "n" : "TAGBANWA VOWEL SIGN U", "h" : "1773" },

{"g" : "\u1A00", "n" : "BUGINESE LETTER KA", "h" : "1A00" },
{"g" : "\u1A01", "n" : "BUGINESE LETTER GA", "h" : "1A01" },
{"g" : "\u1A02", "n" : "BUGINESE LETTER NGA", "h" : "1A02" },
{"g" : "\u1A03", "n" : "BUGINESE LETTER NGKA", "h" : "1A03" },
{"g" : "\u1A04", "n" : "BUGINESE LETTER PA", "h" : "1A04" },
{"g" : "\u1A05", "n" : "BUGINESE LETTER BA", "h" : "1A05" },
{"g" : "\u1A06", "n" : "BUGINESE LETTER MA", "h" : "1A06" },
{"g" : "\u1A07", "n" : "BUGINESE LETTER MPA", "h" : "1A07" },
{"g" : "\u1A08", "n" : "BUGINESE LETTER TA", "h" : "1A08" },
{"g" : "\u1A09", "n" : "BUGINESE LETTER DA", "h" : "1A09" },
{"g" : "\u1A0A", "n" : "BUGINESE LETTER NA", "h" : "1A0A" },
{"g" : "\u1A0B", "n" : "BUGINESE LETTER NRA", "h" : "1A0B" },
{"g" : "\u1A0C", "n" : "BUGINESE LETTER CA", "h" : "1A0C" },
{"g" : "\u1A0D", "n" : "BUGINESE LETTER JA", "h" : "1A0D" },
{"g" : "\u1A0E", "n" : "BUGINESE LETTER NYA", "h" : "1A0E" },
{"g" : "\u1A0F", "n" : "BUGINESE LETTER NYCA", "h" : "1A0F" },
{"g" : "\u1A10", "n" : "BUGINESE LETTER YA", "h" : "1A10" },
{"g" : "\u1A11", "n" : "BUGINESE LETTER RA", "h" : "1A11" },
{"g" : "\u1A12", "n" : "BUGINESE LETTER LA", "h" : "1A12" },
{"g" : "\u1A13", "n" : "BUGINESE LETTER VA", "h" : "1A13" },
{"g" : "\u1A14", "n" : "BUGINESE LETTER SA", "h" : "1A14" },
{"g" : "\u1A15", "n" : "BUGINESE LETTER A", "h" : "1A15" },
{"g" : "\u1A16", "n" : "BUGINESE LETTER HA", "h" : "1A16" },
{"g" : "\u1A17", "n" : "BUGINESE VOWEL SIGN I", "h" : "1A17" },
{"g" : "\u1A18", "n" : "BUGINESE VOWEL SIGN U", "h" : "1A18" },
{"g" : "\u1A19", "n" : "BUGINESE VOWEL SIGN E", "h" : "1A19" },
{"g" : "\u1A1A", "n" : "BUGINESE VOWEL SIGN O", "h" : "1A1A" },
{"g" : "\u1A1B", "n" : "BUGINESE VOWEL SIGN AE", "h" : "1A1B" },

{"g" : "\u1A1E", "n" : "BUGINESE PALLAWA", "h" : "1A1E" },
{"g" : "\u1A1F", "n" : "BUGINESE END OF SECTION", "h" : "1A1F" },

{"g" : "\u1B00", "n" : "BALINESE SIGN ULU RICEM", "h" : "1B00" },
{"g" : "\u1B01", "n" : "BALINESE SIGN ULU CANDRA", "h" : "1B01" },
{"g" : "\u1B02", "n" : "BALINESE SIGN CECEK", "h" : "1B02" },
{"g" : "\u1B03", "n" : "BALINESE SIGN SURANG", "h" : "1B03" },
{"g" : "\u1B04", "n" : "BALINESE SIGN BISAH", "h" : "1B04" },
{"g" : "\u1B05", "n" : "BALINESE LETTER AKARA", "h" : "1B05" },
{"g" : "\u1B06", "n" : "BALINESE LETTER AKARA TEDUNG", "h" : "1B06" },
{"g" : "\u1B07", "n" : "BALINESE LETTER IKARA", "h" : "1B07" },
{"g" : "\u1B08", "n" : "BALINESE LETTER IKARA TEDUNG", "h" : "1B08" },
{"g" : "\u1B09", "n" : "BALINESE LETTER UKARA", "h" : "1B09" },
{"g" : "\u1B0A", "n" : "BALINESE LETTER UKARA TEDUNG", "h" : "1B0A" },
{"g" : "\u1B0B", "n" : "BALINESE LETTER RA REPA", "h" : "1B0B" },
{"g" : "\u1B0C", "n" : "BALINESE LETTER RA REPA TEDUNG", "h" : "1B0C" },
{"g" : "\u1B0D", "n" : "BALINESE LETTER LA LENGA", "h" : "1B0D" },
{"g" : "\u1B0E", "n" : "BALINESE LETTER LA LENGA TEDUNG", "h" : "1B0E" },
{"g" : "\u1B0F", "n" : "BALINESE LETTER EKARA", "h" : "1B0F" },
{"g" : "\u1B10", "n" : "BALINESE LETTER AIKARA", "h" : "1B10" },
{"g" : "\u1B11", "n" : "BALINESE LETTER OKARA", "h" : "1B11" },
{"g" : "\u1B12", "n" : "BALINESE LETTER OKARA TEDUNG", "h" : "1B12" },
{"g" : "\u1B13", "n" : "BALINESE LETTER KA", "h" : "1B13" },
{"g" : "\u1B14", "n" : "BALINESE LETTER KA MAHAPRANA", "h" : "1B14" },
{"g" : "\u1B15", "n" : "BALINESE LETTER GA", "h" : "1B15" },
{"g" : "\u1B16", "n" : "BALINESE LETTER GA GORA", "h" : "1B16" },
{"g" : "\u1B17", "n" : "BALINESE LETTER NGA", "h" : "1B17" },
{"g" : "\u1B18", "n" : "BALINESE LETTER CA", "h" : "1B18" },
{"g" : "\u1B19", "n" : "BALINESE LETTER CA LACA", "h" : "1B19" },
{"g" : "\u1B1A", "n" : "BALINESE LETTER JA", "h" : "1B1A" },
{"g" : "\u1B1B", "n" : "BALINESE LETTER JA JERA", "h" : "1B1B" },
{"g" : "\u1B1C", "n" : "BALINESE LETTER NYA", "h" : "1B1C" },
{"g" : "\u1B1D", "n" : "BALINESE LETTER TA LATIK", "h" : "1B1D" },
{"g" : "\u1B1E", "n" : "BALINESE LETTER TA MURDA MAHAPRANA", "h" : "1B1E" },
{"g" : "\u1B1F", "n" : "BALINESE LETTER DA MURDA ALPAPRANA", "h" : "1B1F" },
{"g" : "\u1B20", "n" : "BALINESE LETTER DA MURDA MAHAPRANA", "h" : "1B20" },
{"g" : "\u1B21", "n" : "BALINESE LETTER NA RAMBAT", "h" : "1B21" },
{"g" : "\u1B22", "n" : "BALINESE LETTER TA", "h" : "1B22" },
{"g" : "\u1B23", "n" : "BALINESE LETTER TA TAWA", "h" : "1B23" },
{"g" : "\u1B24", "n" : "BALINESE LETTER DA", "h" : "1B24" },
{"g" : "\u1B25", "n" : "BALINESE LETTER DA MADU", "h" : "1B25" },
{"g" : "\u1B26", "n" : "BALINESE LETTER NA", "h" : "1B26" },
{"g" : "\u1B27", "n" : "BALINESE LETTER PA", "h" : "1B27" },
{"g" : "\u1B28", "n" : "BALINESE LETTER PA KAPAL", "h" : "1B28" },
{"g" : "\u1B29", "n" : "BALINESE LETTER BA", "h" : "1B29" },
{"g" : "\u1B2A", "n" : "BALINESE LETTER BA KEMBANG", "h" : "1B2A" },
{"g" : "\u1B2B", "n" : "BALINESE LETTER MA", "h" : "1B2B" },
{"g" : "\u1B2C", "n" : "BALINESE LETTER YA", "h" : "1B2C" },
{"g" : "\u1B2D", "n" : "BALINESE LETTER RA", "h" : "1B2D" },
{"g" : "\u1B2E", "n" : "BALINESE LETTER LA", "h" : "1B2E" },
{"g" : "\u1B2F", "n" : "BALINESE LETTER WA", "h" : "1B2F" },
{"g" : "\u1B30", "n" : "BALINESE LETTER SA SAGA", "h" : "1B30" },
{"g" : "\u1B31", "n" : "BALINESE LETTER SA SAPA", "h" : "1B31" },
{"g" : "\u1B32", "n" : "BALINESE LETTER SA", "h" : "1B32" },
{"g" : "\u1B33", "n" : "BALINESE LETTER HA", "h" : "1B33" },
{"g" : "\u1B34", "n" : "BALINESE SIGN REREKAN", "h" : "1B34" },
{"g" : "\u1B35", "n" : "BALINESE VOWEL SIGN TEDUNG", "h" : "1B35" },
{"g" : "\u1B36", "n" : "BALINESE VOWEL SIGN ULU", "h" : "1B36" },
{"g" : "\u1B37", "n" : "BALINESE VOWEL SIGN ULU SARI", "h" : "1B37" },
{"g" : "\u1B38", "n" : "BALINESE VOWEL SIGN SUKU", "h" : "1B38" },
{"g" : "\u1B39", "n" : "BALINESE VOWEL SIGN SUKU ILUT", "h" : "1B39" },
{"g" : "\u1B3A", "n" : "BALINESE VOWEL SIGN RA REPA", "h" : "1B3A" },
{"g" : "\u1B3B", "n" : "BALINESE VOWEL SIGN RA REPA TEDUNG", "h" : "1B3B" },
{"g" : "\u1B3C", "n" : "BALINESE VOWEL SIGN LA LENGA", "h" : "1B3C" },
{"g" : "\u1B3D", "n" : "BALINESE VOWEL SIGN LA LENGA TEDUNG", "h" : "1B3D" },
{"g" : "\u1B3E", "n" : "BALINESE VOWEL SIGN TALING", "h" : "1B3E" },
{"g" : "\u1B3F", "n" : "BALINESE VOWEL SIGN TALING REPA", "h" : "1B3F" },
{"g" : "\u1B40", "n" : "BALINESE VOWEL SIGN TALING TEDUNG", "h" : "1B40" },
{"g" : "\u1B41", "n" : "BALINESE VOWEL SIGN TALING REPA TEDUNG", "h" : "1B41" },
{"g" : "\u1B42", "n" : "BALINESE VOWEL SIGN PEPET", "h" : "1B42" },
{"g" : "\u1B43", "n" : "BALINESE VOWEL SIGN PEPET TEDUNG", "h" : "1B43" },
{"g" : "\u1B44", "n" : "BALINESE ADEG ADEG", "h" : "1B44" },
{"g" : "\u1B45", "n" : "BALINESE LETTER KAF SASAK", "h" : "1B45" },
{"g" : "\u1B46", "n" : "BALINESE LETTER KHOT SASAK", "h" : "1B46" },
{"g" : "\u1B47", "n" : "BALINESE LETTER TZIR SASAK", "h" : "1B47" },
{"g" : "\u1B48", "n" : "BALINESE LETTER EF SASAK", "h" : "1B48" },
{"g" : "\u1B49", "n" : "BALINESE LETTER VE SASAK", "h" : "1B49" },
{"g" : "\u1B4A", "n" : "BALINESE LETTER ZAL SASAK", "h" : "1B4A" },
{"g" : "\u1B4B", "n" : "BALINESE LETTER ASYURA SASAK", "h" : "1B4B" },

{"g" : "\u1B50", "n" : "BALINESE DIGIT ZERO", "h" : "1B50" },
{"g" : "\u1B51", "n" : "BALINESE DIGIT ONE", "h" : "1B51" },
{"g" : "\u1B52", "n" : "BALINESE DIGIT TWO", "h" : "1B52" },
{"g" : "\u1B53", "n" : "BALINESE DIGIT THREE", "h" : "1B53" },
{"g" : "\u1B54", "n" : "BALINESE DIGIT FOUR", "h" : "1B54" },
{"g" : "\u1B55", "n" : "BALINESE DIGIT FIVE", "h" : "1B55" },
{"g" : "\u1B56", "n" : "BALINESE DIGIT SIX", "h" : "1B56" },
{"g" : "\u1B57", "n" : "BALINESE DIGIT SEVEN", "h" : "1B57" },
{"g" : "\u1B58", "n" : "BALINESE DIGIT EIGHT", "h" : "1B58" },
{"g" : "\u1B59", "n" : "BALINESE DIGIT NINE", "h" : "1B59" },
{"g" : "\u1B5A", "n" : "BALINESE PANTI", "h" : "1B5A" },
{"g" : "\u1B5B", "n" : "BALINESE PAMADA", "h" : "1B5B" },
{"g" : "\u1B5C", "n" : "BALINESE WINDU", "h" : "1B5C" },
{"g" : "\u1B5D", "n" : "BALINESE CARIK PAMUNGKAH", "h" : "1B5D" },
{"g" : "\u1B5E", "n" : "BALINESE CARIK SIKI", "h" : "1B5E" },
{"g" : "\u1B5F", "n" : "BALINESE CARIK PAREREN", "h" : "1B5F" },
{"g" : "\u1B60", "n" : "BALINESE PAMENENG", "h" : "1B60" },
{"g" : "\u1B61", "n" : "BALINESE MUSICAL SYMBOL DONG", "h" : "1B61" },
{"g" : "\u1B62", "n" : "BALINESE MUSICAL SYMBOL DENG", "h" : "1B62" },
{"g" : "\u1B63", "n" : "BALINESE MUSICAL SYMBOL DUNG", "h" : "1B63" },
{"g" : "\u1B64", "n" : "BALINESE MUSICAL SYMBOL DANG", "h" : "1B64" },
{"g" : "\u1B65", "n" : "BALINESE MUSICAL SYMBOL DANG SURANG", "h" : "1B65" },
{"g" : "\u1B66", "n" : "BALINESE MUSICAL SYMBOL DING", "h" : "1B66" },
{"g" : "\u1B67", "n" : "BALINESE MUSICAL SYMBOL DAENG", "h" : "1B67" },
{"g" : "\u1B68", "n" : "BALINESE MUSICAL SYMBOL DEUNG", "h" : "1B68" },
{"g" : "\u1B69", "n" : "BALINESE MUSICAL SYMBOL DAING", "h" : "1B69" },
{"g" : "\u1B6A", "n" : "BALINESE MUSICAL SYMBOL DANG GEDE", "h" : "1B6A" },
{"g" : "\u1B6B", "n" : "BALINESE MUSICAL SYMBOL COMBINING TEGEH", "h" : "1B6B" },
{"g" : "\u1B6C", "n" : "BALINESE MUSICAL SYMBOL COMBINING ENDEP", "h" : "1B6C" },
{"g" : "\u1B6D", "n" : "BALINESE MUSICAL SYMBOL COMBINING KEMPUL", "h" : "1B6D" },
{"g" : "\u1B6E", "n" : "BALINESE MUSICAL SYMBOL COMBINING KEMPLI", "h" : "1B6E" },
{"g" : "\u1B6F", "n" : "BALINESE MUSICAL SYMBOL COMBINING JEGOGAN", "h" : "1B6F" },
{"g" : "\u1B70", "n" : "BALINESE MUSICAL SYMBOL COMBINING KEMPUL WITH JEGOGAN", "h" : "1B70" },
{"g" : "\u1B71", "n" : "BALINESE MUSICAL SYMBOL COMBINING KEMPLI WITH JEGOGAN", "h" : "1B71" },
{"g" : "\u1B72", "n" : "BALINESE MUSICAL SYMBOL COMBINING BENDE", "h" : "1B72" },
{"g" : "\u1B73", "n" : "BALINESE MUSICAL SYMBOL COMBINING GONG", "h" : "1B73" },
{"g" : "\u1B74", "n" : "BALINESE MUSICAL SYMBOL RIGHT-HAND OPEN DUG", "h" : "1B74" },
{"g" : "\u1B75", "n" : "BALINESE MUSICAL SYMBOL RIGHT-HAND OPEN DAG", "h" : "1B75" },
{"g" : "\u1B76", "n" : "BALINESE MUSICAL SYMBOL RIGHT-HAND CLOSED TUK", "h" : "1B76" },
{"g" : "\u1B77", "n" : "BALINESE MUSICAL SYMBOL RIGHT-HAND CLOSED TAK", "h" : "1B77" },
{"g" : "\u1B78", "n" : "BALINESE MUSICAL SYMBOL LEFT-HAND OPEN PANG", "h" : "1B78" },
{"g" : "\u1B79", "n" : "BALINESE MUSICAL SYMBOL LEFT-HAND OPEN PUNG", "h" : "1B79" },
{"g" : "\u1B7A", "n" : "BALINESE MUSICAL SYMBOL LEFT-HAND CLOSED PLAK", "h" : "1B7A" },
{"g" : "\u1B7B", "n" : "BALINESE MUSICAL SYMBOL LEFT-HAND CLOSED PLUK",  "h" : "1B7B" },
{"g" : "\u1B7C", "n" : "BALINESE MUSICAL SYMBOL LEFT-HAND OPEN PING", "h" : "1B7C" },

{"g" : "\u1B80", "n" : "SUNDANESE SIGN PANYECEK", "h" : "1B80" },
{"g" : "\u1B81", "n" : "SUNDANESE SIGN PANGLAYAR", "h" : "1B81" },
{"g" : "\u1B82", "n" : "SUNDANESE SIGN PANGWISAD", "h" : "1B82" },
{"g" : "\u1B83", "n" : "SUNDANESE LETTER A", "h" : "1B83" },
{"g" : "\u1B84", "n" : "SUNDANESE LETTER I", "h" : "1B84" },
{"g" : "\u1B85", "n" : "SUNDANESE LETTER U", "h" : "1B85" },
{"g" : "\u1B86", "n" : "SUNDANESE LETTER AE", "h" : "1B86" },
{"g" : "\u1B87", "n" : "SUNDANESE LETTER O", "h" : "1B87" },
{"g" : "\u1B88", "n" : "SUNDANESE LETTER E", "h" : "1B88" },
{"g" : "\u1B89", "n" : "SUNDANESE LETTER EU", "h" : "1B89" },
{"g" : "\u1B8A", "n" : "SUNDANESE LETTER KA", "h" : "1B8A" },
{"g" : "\u1B8B", "n" : "SUNDANESE LETTER QA", "h" : "1B8B" },
{"g" : "\u1B8C", "n" : "SUNDANESE LETTER GA", "h" : "1B8C" },
{"g" : "\u1B8D", "n" : "SUNDANESE LETTER NGA", "h" : "1B8D" },
{"g" : "\u1B8E", "n" : "SUNDANESE LETTER CA", "h" : "1B8E" },
{"g" : "\u1B8F", "n" : "SUNDANESE LETTER JA", "h" : "1B8F" },
{"g" : "\u1B90", "n" : "SUNDANESE LETTER ZA", "h" : "1B90" },
{"g" : "\u1B91", "n" : "SUNDANESE LETTER NYA", "h" : "1B91" },
{"g" : "\u1B92", "n" : "SUNDANESE LETTER TA", "h" : "1B92" },
{"g" : "\u1B93", "n" : "SUNDANESE LETTER DA", "h" : "1B93" },
{"g" : "\u1B94", "n" : "SUNDANESE LETTER NA", "h" : "1B94" },
{"g" : "\u1B95", "n" : "SUNDANESE LETTER PA", "h" : "1B95" },
{"g" : "\u1B96", "n" : "SUNDANESE LETTER FA", "h" : "1B96" },
{"g" : "\u1B97", "n" : "SUNDANESE LETTER VA", "h" : "1B97" },
{"g" : "\u1B98", "n" : "SUNDANESE LETTER BA", "h" : "1B98" },
{"g" : "\u1B99", "n" : "SUNDANESE LETTER MA", "h" : "1B99" },
{"g" : "\u1B9A", "n" : "SUNDANESE LETTER YA", "h" : "1B9A" },
{"g" : "\u1B9B", "n" : "SUNDANESE LETTER RA", "h" : "1B9B" },
{"g" : "\u1B9C", "n" : "SUNDANESE LETTER LA", "h" : "1B9C" },
{"g" : "\u1B9D", "n" : "SUNDANESE LETTER WA", "h" : "1B9D" },
{"g" : "\u1B9E", "n" : "SUNDANESE LETTER SA", "h" : "1B9E" },
{"g" : "\u1B9F", "n" : "SUNDANESE LETTER XA", "h" : "1B9F" },
{"g" : "\u1BA0", "n" : "SUNDANESE LETTER HA", "h" : "1BA0" },
{"g" : "\u1BA1", "n" : "SUNDANESE CONSONANT SIGN PAMINGKAL", "h" : "1BA1" },
{"g" : "\u1BA2", "n" : "SUNDANESE CONSONANT SIGN PANYAKRA", "h" : "1BA2" },
{"g" : "\u1BA3", "n" : "SUNDANESE CONSONANT SIGN PANYIKU", "h" : "1BA3" },
{"g" : "\u1BA4", "n" : "SUNDANESE VOWEL SIGN PANGHULU", "h" : "1BA4" },
{"g" : "\u1BA5", "n" : "SUNDANESE VOWEL SIGN PANYUKU", "h" : "1BA5" },
{"g" : "\u1BA6", "n" : "SUNDANESE VOWEL SIGN PANAELAENG", "h" : "1BA6" },
{"g" : "\u1BA7", "n" : "SUNDANESE VOWEL SIGN PANOLONG", "h" : "1BA7" },
{"g" : "\u1BA8", "n" : "SUNDANESE VOWEL SIGN PAMEPET", "h" : "1BA8" },
{"g" : "\u1BA9", "n" : "SUNDANESE VOWEL SIGN PANEULEUNG", "h" : "1BA9" },
{"g" : "\u1BAA", "n" : "SUNDANESE SIGN PAMAAEH", "h" : "1BAA" },
{"g" : "\u1BAB", "n" : "SUNDANESE SIGN VIRAMA", "h" : "1BAB" },
{"g" : "\u1BAC", "n" : "SUNDANESE CONSONANT SIGN PASANGAN MA", "h" : "1BAC" },
{"g" : "\u1BAD", "n" : "SUNDANESE CONSONANT SIGN PASANGAN WA", "h" : "1BAD" },
{"g" : "\u1BAE", "n" : "SUNDANESE LETTER KHA", "h" : "1BAE" },
{"g" : "\u1BAF", "n" : "SUNDANESE LETTER SYA", "h" : "1BAF" },
{"g" : "\u1BB0", "n" : "SUNDANESE DIGIT ZERO", "h" : "1BB0" },
{"g" : "\u1BB1", "n" : "SUNDANESE DIGIT ONE", "h" : "1BB1" },
{"g" : "\u1BB2", "n" : "SUNDANESE DIGIT TWO", "h" : "1BB2" },
{"g" : "\u1BB3", "n" : "SUNDANESE DIGIT THREE", "h" : "1BB3" },
{"g" : "\u1BB4", "n" : "SUNDANESE DIGIT FOUR", "h" : "1BB4" },
{"g" : "\u1BB5", "n" : "SUNDANESE DIGIT FIVE", "h" : "1BB5" },
{"g" : "\u1BB6", "n" : "SUNDANESE DIGIT SIX", "h" : "1BB6" },
{"g" : "\u1BB7", "n" : "SUNDANESE DIGIT SEVEN", "h" : "1BB7" },
{"g" : "\u1BB8", "n" : "SUNDANESE DIGIT EIGHT", "h" : "1BB8" },
{"g" : "\u1BB9", "n" : "SUNDANESE DIGIT NINE", "h" : "1BB9" },
{"g" : "\u1BBA", "n" : "SUNDANESE AVAGRAHA", "h" : "1BBA" },
{"g" : "\u1BBB", "n" : "SUNDANESE LETTER REU", "h" : "1BBB" },
{"g" : "\u1BBC", "n" : "SUNDANESE LETTER LEU", "h" : "1BBC" },
{"g" : "\u1BBD", "n" : "SUNDANESE LETTER BHA", "h" : "1BBD" },
{"g" : "\u1BBE", "n" : "SUNDANESE LETTER FINAL K", "h" : "1BBE" },
{"g" : "\u1BBF", "n" : "SUNDANESE LETTER FINAL M", "h" : "1BBF" },

{"g" : "\u1BC0", "n" : "BATAK LETTER A", "h" : "1BC0" },
{"g" : "\u1BC1", "n" : "BATAK LETTER SIMALUNGUN A", "h" : "1BC1" },
{"g" : "\u1BC2", "n" : "BATAK LETTER HA", "h" : "1BC2" },
{"g" : "\u1BC3", "n" : "BATAK LETTER SIMALUNGUN HA", "h" : "1BC3" },
{"g" : "\u1BC4", "n" : "BATAK LETTER MANDAILING HA", "h" : "1BC4" },
{"g" : "\u1BC5", "n" : "BATAK LETTER BA", "h" : "1BC5" },
{"g" : "\u1BC6", "n" : "BATAK LETTER KARO BA", "h" : "1BC6" },
{"g" : "\u1BC7", "n" : "BATAK LETTER PA", "h" : "1BC7" },
{"g" : "\u1BC8", "n" : "BATAK LETTER SIMALUNGUN PA", "h" : "1BC8" },
{"g" : "\u1BC9", "n" : "BATAK LETTER NA", "h" : "1BC9" },
{"g" : "\u1BCA", "n" : "BATAK LETTER MANDAILING NA", "h" : "1BCA" },
{"g" : "\u1BCB", "n" : "BATAK LETTER WA", "h" : "1BCB" },
{"g" : "\u1BCC", "n" : "BATAK LETTER SIMALUNGUN WA", "h" : "1BCC" },
{"g" : "\u1BCD", "n" : "BATAK LETTER PAKPAK WA", "h" : "1BCD" },
{"g" : "\u1BCE", "n" : "BATAK LETTER GA", "h" : "1BCE" },
{"g" : "\u1BCF", "n" : "BATAK LETTER SIMALUNGUN GA", "h" : "1BCF" },
{"g" : "\u1BD0", "n" : "BATAK LETTER JA", "h" : "1BD0" },
{"g" : "\u1BD1", "n" : "BATAK LETTER DA", "h" : "1BD1" },
{"g" : "\u1BD2", "n" : "BATAK LETTER RA", "h" : "1BD2" },
{"g" : "\u1BD3", "n" : "BATAK LETTER SIMALUNGUN RA", "h" : "1BD3" },
{"g" : "\u1BD4", "n" : "BATAK LETTER MA", "h" : "1BD4" },
{"g" : "\u1BD5", "n" : "BATAK LETTER SIMALUNGUN MA", "h" : "1BD5" },
{"g" : "\u1BD6", "n" : "BATAK LETTER SOUTHERN TA", "h" : "1BD6" },
{"g" : "\u1BD7", "n" : "BATAK LETTER NORTHERN TA", "h" : "1BD7" },
{"g" : "\u1BD8", "n" : "BATAK LETTER SA", "h" : "1BD8" },
{"g" : "\u1BD9", "n" : "BATAK LETTER SIMALUNGUN SA", "h" : "1BD9" },
{"g" : "\u1BDA", "n" : "BATAK LETTER MANDAILING SA", "h" : "1BDA" },
{"g" : "\u1BDB", "n" : "BATAK LETTER YA", "h" : "1BDB" },
{"g" : "\u1BDC", "n" : "BATAK LETTER SIMALUNGUN YA", "h" : "1BDC" },
{"g" : "\u1BDD", "n" : "BATAK LETTER NGA", "h" : "1BDD" },
{"g" : "\u1BDE", "n" : "BATAK LETTER LA", "h" : "1BDE" },
{"g" : "\u1BDF", "n" : "BATAK LETTER SIMALUNGUN LA", "h" : "1BDF" },
{"g" : "\u1BE0", "n" : "BATAK LETTER NYA", "h" : "1BE0" },
{"g" : "\u1BE1", "n" : "BATAK LETTER CA", "h" : "1BE1" },
{"g" : "\u1BE2", "n" : "BATAK LETTER NDA", "h" : "1BE2" },
{"g" : "\u1BE3", "n" : "BATAK LETTER MBA", "h" : "1BE3" },
{"g" : "\u1BE4", "n" : "BATAK LETTER I", "h" : "1BE4" },
{"g" : "\u1BE5", "n" : "BATAK LETTER U", "h" : "1BE5" },
{"g" : "\u1BE6", "n" : "BATAK SIGN TOMPI", "h" : "1BE6" },
{"g" : "\u1BE7", "n" : "BATAK VOWEL SIGN E", "h" : "1BE7" },
{"g" : "\u1BE8", "n" : "BATAK VOWEL SIGN PAKPAK E", "h" : "1BE8" },
{"g" : "\u1BE9", "n" : "BATAK VOWEL SIGN EE", "h" : "1BE9" },
{"g" : "\u1BEA", "n" : "BATAK VOWEL SIGN I", "h" : "1BEA" },
{"g" : "\u1BEB", "n" : "BATAK VOWEL SIGN KARO I", "h" : "1BEB" },
{"g" : "\u1BEC", "n" : "BATAK VOWEL SIGN O", "h" : "1BEC" },
{"g" : "\u1BED", "n" : "BATAK VOWEL SIGN KARO O", "h" : "1BED" },
{"g" : "\u1BEE", "n" : "BATAK VOWEL SIGN U", "h" : "1BEE" },
{"g" : "\u1BEF", "n" : "BATAK VOWEL SIGN U FOR SIMALUNGUN SA", "h" : "1BEF" },
{"g" : "\u1BF0", "n" : "BATAK CONSONANT SIGN NG", "h" : "1BF0" },
{"g" : "\u1BF1", "n" : "BATAK CONSONANT SIGN H", "h" : "1BF1" },
{"g" : "\u1BF2", "n" : "BATAK PANGOLAT", "h" : "1BF2" },
{"g" : "\u1BF3", "n" : "BATAK PANONGONAN", "h" : "1BF3" },

{"g" : "\u1BFC", "n" : "BATAK SYMBOL BINDU NA METEK", "h" : "1BFC" },
{"g" : "\u1BFD", "n" : "BATAK SYMBOL BINDU PINARBORAS", "h" : "1BFD" },
{"g" : "\u1BFE", "n" : "BATAK SYMBOL BINDU JUDUL", "h" : "1BFE" },
{"g" : "\u1BFF", "n" : "BATAK SYMBOL BINDU PANGOLAT", "h" : "1BFF" },

{"g" : "\u1CC0", "n" : "SUNDANESE PUNCTUATION BINDU SURYA", "h" : "1CC0" },
{"g" : "\u1CC1", "n" : "SUNDANESE PUNCTUATION BINDU PANGLONG", "h" : "1CC1" },
{"g" : "\u1CC2", "n" : "SUNDANESE PUNCTUATION BINDU PURNAMA", "h" : "1CC2" },
{"g" : "\u1CC3", "n" : "SUNDANESE PUNCTUATION BINDU CAKRA", "h" : "1CC3" },
{"g" : "\u1CC4", "n" : "SUNDANESE PUNCTUATION BINDU LEU SATANGA", "h" : "1CC4" },
{"g" : "\u1CC5", "n" : "SUNDANESE PUNCTUATION BINDU KA SATANGA", "h" : "1CC5" },
{"g" : "\u1CC6", "n" : "SUNDANESE PUNCTUATION BINDU DA SATANGA", "h" : "1CC6" },
{"g" : "\u1CC7", "n" : "SUNDANESE PUNCTUATION BINDU BA SATANGA", "h" : "1CC7" },

{"g" : "\uA930", "n" : "REJANG LETTER KA", "h" : "A930"},
{"g" : "\uA931", "n" : "REJANG LETTER GA", "h" : "A931"},
{"g" : "\uA932", "n" : "REJANG LETTER NGA", "h" : "A932"},
{"g" : "\uA933", "n" : "REJANG LETTER TA", "h" : "A933"},
{"g" : "\uA934", "n" : "REJANG LETTER DA", "h" : "A934"},
{"g" : "\uA935", "n" : "REJANG LETTER NA", "h" : "A935"},
{"g" : "\uA936", "n" : "REJANG LETTER PA", "h" : "A936"},
{"g" : "\uA937", "n" : "REJANG LETTER BA", "h" : "A937"},
{"g" : "\uA938", "n" : "REJANG LETTER MA", "h" : "A938"},
{"g" : "\uA939", "n" : "REJANG LETTER CA", "h" : "A939"},
{"g" : "\uA93A", "n" : "REJANG LETTER JA", "h" : "A93A"},
{"g" : "\uA93B", "n" : "REJANG LETTER NYA", "h" : "A93B"},
{"g" : "\uA93C", "n" : "REJANG LETTER SA", "h" : "A93C"},
{"g" : "\uA93D", "n" : "REJANG LETTER RA", "h" : "A93D"},
{"g" : "\uA93E", "n" : "REJANG LETTER LA", "h" : "A93E"},
{"g" : "\uA93F", "n" : "REJANG LETTER YA", "h" : "A93F"},
{"g" : "\uA940", "n" : "REJANG LETTER WA", "h" : "A940"},
{"g" : "\uA941", "n" : "REJANG LETTER HA", "h" : "A941"},
{"g" : "\uA942", "n" : "REJANG LETTER MBA", "h" : "A942"},
{"g" : "\uA943", "n" : "REJANG LETTER NGGA", "h" : "A943"},
{"g" : "\uA944", "n" : "REJANG LETTER NDA", "h" : "A944"},
{"g" : "\uA945", "n" : "REJANG LETTER NYJA", "h" : "A945"},
{"g" : "\uA946", "n" : "REJANG LETTER A", "h" : "A946"},
{"g" : "\uA947", "n" : "REJANG VOWEL SIGN I", "h" : "A947"},
{"g" : "\uA948", "n" : "REJANG VOWEL SIGN U", "h" : "A948"},
{"g" : "\uA949", "n" : "REJANG VOWEL SIGN E", "h" : "A949"},
{"g" : "\uA94A", "n" : "REJANG VOWEL SIGN AI", "h" : "A94A"},
{"g" : "\uA94B", "n" : "REJANG VOWEL SIGN O", "h" : "A94B"},
{"g" : "\uA94C", "n" : "REJANG VOWEL SIGN AU", "h" : "A94C"},
{"g" : "\uA94D", "n" : "REJANG VOWEL SIGN EU", "h" : "A94D"},
{"g" : "\uA94E", "n" : "REJANG VOWEL SIGN EA", "h" : "A94E"},
{"g" : "\uA94F", "n" : "REJANG CONSONANT SIGN NG", "h" : "A94F"},
{"g" : "\uA950", "n" : "REJANG CONSONANT SIGN N", "h" : "A950"},
{"g" : "\uA951", "n" : "REJANG CONSONANT SIGN R", "h" : "A951"},
{"g" : "\uA952", "n" : "REJANG CONSONANT SIGN H", "h" : "A952"},
{"g" : "\uA953", "n" : "REJANG VIRAMA", "h" : "A953"},
{"g" : "\uA95F", "n" : "REJANG SECTION MARK", "h" : "A95F"},

{"g" : "\uA980", "n" : "JAVANESE SIGN PANYANGGA", "h" : "A980"},
{"g" : "\uA981", "n" : "JAVANESE SIGN CECAK", "h" : "A981"},
{"g" : "\uA982", "n" : "JAVANESE SIGN LAYAR", "h" : "A982"},
{"g" : "\uA983", "n" : "JAVANESE SIGN WIGNYAN", "h" : "A983"},
{"g" : "\uA984", "n" : "JAVANESE LETTER A", "h" : "A984"},
{"g" : "\uA985", "n" : "JAVANESE LETTER I KAWI", "h" : "A985"},
{"g" : "\uA986", "n" : "JAVANESE LETTER I", "h" : "A986"},
{"g" : "\uA987", "n" : "JAVANESE LETTER II", "h" : "A987"},
{"g" : "\uA988", "n" : "JAVANESE LETTER U", "h" : "A988"},
{"g" : "\uA989", "n" : "JAVANESE LETTER PA CEREK", "h" : "A989"},
{"g" : "\uA98A", "n" : "JAVANESE LETTER NGA LELET", "h" : "A98A"},
{"g" : "\uA98B", "n" : "JAVANESE LETTER NGA LELET RASWADI", "h" : "A98B"},
{"g" : "\uA98C", "n" : "JAVANESE LETTER E", "h" : "A98C"},
{"g" : "\uA98D", "n" : "JAVANESE LETTER AI", "h" : "A98D"},
{"g" : "\uA98E", "n" : "JAVANESE LETTER O", "h" : "A98E"},
{"g" : "\uA98F", "n" : "JAVANESE LETTER KA", "h" : "A98F"},
{"g" : "\uA990", "n" : "JAVANESE LETTER KA SASAK", "h" : "A990"},
{"g" : "\uA991", "n" : "JAVANESE LETTER KA MURDA", "h" : "A991"},
{"g" : "\uA992", "n" : "JAVANESE LETTER GA", "h" : "A992"},
{"g" : "\uA993", "n" : "JAVANESE LETTER GA MURDA", "h" : "A993"},
{"g" : "\uA994", "n" : "JAVANESE LETTER NGA", "h" : "A994"},
{"g" : "\uA995", "n" : "JAVANESE LETTER CA", "h" : "A995"},
{"g" : "\uA996", "n" : "JAVANESE LETTER CA MURDA", "h" : "A996"},
{"g" : "\uA997", "n" : "JAVANESE LETTER JA", "h" : "A997"},
{"g" : "\uA998", "n" : "JAVANESE LETTER NYA MURDA", "h" : "A998"},
{"g" : "\uA999", "n" : "JAVANESE LETTER JA MAHAPRANA", "h" : "A999"},
{"g" : "\uA99A", "n" : "JAVANESE LETTER NYA", "h" : "A99A"},
{"g" : "\uA99B", "n" : "JAVANESE LETTER TTA", "h" : "A99B"},
{"g" : "\uA99C", "n" : "JAVANESE LETTER TTA MAHAPRANA", "h" : "A99C"},
{"g" : "\uA99D", "n" : "JAVANESE LETTER DDA", "h" : "A99D"},
{"g" : "\uA99E", "n" : "JAVANESE LETTER DDA MAHAPRANA", "h" : "A99E"},
{"g" : "\uA99F", "n" : "JAVANESE LETTER NA MURDA", "h" : "A99F"},
{"g" : "\uA9A0", "n" : "JAVANESE LETTER TA", "h" : "A9A0"},
{"g" : "\uA9A1", "n" : "JAVANESE LETTER TA MURDA", "h" : "A9A1"},
{"g" : "\uA9A2", "n" : "JAVANESE LETTER DA", "h" : "A9A2"},
{"g" : "\uA9A3", "n" : "JAVANESE LETTER DA MAHAPRANA", "h" : "A9A3"},
{"g" : "\uA9A4", "n" : "JAVANESE LETTER NA", "h" : "A9A4"},
{"g" : "\uA9A5", "n" : "JAVANESE LETTER PA", "h" : "A9A5"},
{"g" : "\uA9A6", "n" : "JAVANESE LETTER PA MURDA", "h" : "A9A6"},
{"g" : "\uA9A7", "n" : "JAVANESE LETTER BA", "h" : "A9A7"},
{"g" : "\uA9A8", "n" : "JAVANESE LETTER BA MURDA", "h" : "A9A8"},
{"g" : "\uA9A9", "n" : "JAVANESE LETTER MA", "h" : "A9A9"},
{"g" : "\uA9AA", "n" : "JAVANESE LETTER YA", "h" : "A9AA"},
{"g" : "\uA9AB", "n" : "JAVANESE LETTER RA", "h" : "A9AB"},
{"g" : "\uA9AC", "n" : "JAVANESE LETTER RA AGUNG", "h" : "A9AC"},
{"g" : "\uA9AD", "n" : "JAVANESE LETTER LA", "h" : "A9AD"},
{"g" : "\uA9AE", "n" : "JAVANESE LETTER WA", "h" : "A9AE"},
{"g" : "\uA9AF", "n" : "JAVANESE LETTER SA MURDA", "h" : "A9AF"},
{"g" : "\uA9B0", "n" : "JAVANESE LETTER SA MAHAPRANA", "h" : "A9B0"},
{"g" : "\uA9B1", "n" : "JAVANESE LETTER SA", "h" : "A9B1"},
{"g" : "\uA9B2", "n" : "JAVANESE LETTER HA", "h" : "A9B2"},
{"g" : "\uA9B3", "n" : "JAVANESE SIGN CECAK TELU", "h" : "A9B3"},
{"g" : "\uA9B4", "n" : "JAVANESE VOWEL SIGN TARUNG", "h" : "A9B4"},
{"g" : "\uA9B5", "n" : "JAVANESE VOWEL SIGN TOLONG", "h" : "A9B5"},
{"g" : "\uA9B6", "n" : "JAVANESE VOWEL SIGN WULU", "h" : "A9B6"},
{"g" : "\uA9B7", "n" : "JAVANESE VOWEL SIGN WULU MELIK", "h" : "A9B7"},
{"g" : "\uA9B8", "n" : "JAVANESE VOWEL SIGN SUKU", "h" : "A9B8"},
{"g" : "\uA9B9", "n" : "JAVANESE VOWEL SIGN SUKU MENDUT", "h" : "A9B9"},
{"g" : "\uA9BA", "n" : "JAVANESE VOWEL SIGN TALING", "h" : "A9BA"},
{"g" : "\uA9BB", "n" : "JAVANESE VOWEL SIGN DIRGA MURE", "h" : "A9BB"},
{"g" : "\uA9BC", "n" : "JAVANESE VOWEL SIGN PEPET", "h" : "A9BC"},
{"g" : "\uA9BD", "n" : "JAVANESE CONSONANT SIGN KERET", "h" : "A9BD"},
{"g" : "\uA9BE", "n" : "JAVANESE CONSONANT SIGN PENGKAL", "h" : "A9BE"},
{"g" : "\uA9BF", "n" : "JAVANESE CONSONANT SIGN CAKRA", "h" : "A9BF"},
{"g" : "\uA9C0", "n" : "JAVANESE PANGKON", "h" : "A9C0"},
{"g" : "\uA9C1", "n" : "JAVANESE LEFT RERENGGAN", "h" : "A9C1"},
{"g" : "\uA9C2", "n" : "JAVANESE RIGHT RERENGGAN", "h" : "A9C2"},
{"g" : "\uA9C3", "n" : "JAVANESE PADA ANDAP", "h" : "A9C3"},
{"g" : "\uA9C4", "n" : "JAVANESE PADA MADYA", "h" : "A9C4"},
{"g" : "\uA9C5", "n" : "JAVANESE PADA LUHUR", "h" : "A9C5"},
{"g" : "\uA9C6", "n" : "JAVANESE PADA WINDU", "h" : "A9C6"},
{"g" : "\uA9C7", "n" : "JAVANESE PADA PANGKAT", "h" : "A9C7"},
{"g" : "\uA9C8", "n" : "JAVANESE PADA LINGSA", "h" : "A9C8"},
{"g" : "\uA9C9", "n" : "JAVANESE PADA LUNGSI", "h" : "A9C9"},
{"g" : "\uA9CA", "n" : "JAVANESE PADA ADEG", "h" : "A9CA"},
{"g" : "\uA9CB", "n" : "JAVANESE PADA ADEG ADEG", "h" : "A9CB"},
{"g" : "\uA9CC", "n" : "JAVANESE PADA PISELEH", "h" : "A9CC"},
{"g" : "\uA9CD", "n" : "JAVANESE TURNED PADA PISELEH", "h" : "A9CD"},
{"g" : "\uA9CF", "n" : "JAVANESE PANGRANGKEP", "h" : "A9CF"},
{"g" : "\uA9D0", "n" : "JAVANESE DIGIT ZERO", "h" : "A9D0"},
{"g" : "\uA9D1", "n" : "JAVANESE DIGIT ONE", "h" : "A9D1"},
{"g" : "\uA9D2", "n" : "JAVANESE DIGIT TWO", "h" : "A9D2"},
{"g" : "\uA9D3", "n" : "JAVANESE DIGIT THREE", "h" : "A9D3"},
{"g" : "\uA9D4", "n" : "JAVANESE DIGIT FOUR", "h" : "A9D4"},
{"g" : "\uA9D5", "n" : "JAVANESE DIGIT FIVE", "h" : "A9D5"},
{"g" : "\uA9D6", "n" : "JAVANESE DIGIT SIX", "h" : "A9D6"},
{"g" : "\uA9D7", "n" : "JAVANESE DIGIT SEVEN", "h" : "A9D7"},
{"g" : "\uA9D8", "n" : "JAVANESE DIGIT EIGHT", "h" : "A9D8"},
{"g" : "\uA9D9", "n" : "JAVANESE DIGIT NINE", "h" : "A9D9"},
{"g" : "\uA9DE", "n" : "JAVANESE PADA TIRTA TUMETES", "h" : "A9DE"},
{"g" : "\uA9DF", "n" : "JAVANESE PADA ISEN-ISEN", "h" : "A9DF"},

{"g" : "\u{11EE0}", "n" : "MAKASAR LETTER KA", "h" : "11EE0"},
{"g" : "\u{11EE1}", "n" : "MAKASAR LETTER GA", "h" : "11EE1"},
{"g" : "\u{11EE2}", "n" : "MAKASAR LETTER NGA", "h" : "11EE2"},
{"g" : "\u{11EE3}", "n" : "MAKASAR LETTER PA", "h" : "11EE3"},
{"g" : "\u{11EE4}", "n" : "MAKASAR LETTER BA", "h" : "11EE4"},
{"g" : "\u{11EE5}", "n" : "MAKASAR LETTER MA", "h" : "11EE5"},
{"g" : "\u{11EE6}", "n" : "MAKASAR LETTER TA", "h" : "11EE6"},
{"g" : "\u{11EE7}", "n" : "MAKASAR LETTER DA", "h" : "11EE7"},
{"g" : "\u{11EE8}", "n" : "MAKASAR LETTER NA", "h" : "11EE8"},
{"g" : "\u{11EE9}", "n" : "MAKASAR LETTER CA", "h" : "11EE9"},
{"g" : "\u{11EEA}", "n" : "MAKASAR LETTER JA", "h" : "11EEA"},
{"g" : "\u{11EEB}", "n" : "MAKASAR LETTER NYA", "h" : "11EEB"},
{"g" : "\u{11EEC}", "n" : "MAKASAR LETTER YA", "h" : "11EEC"},
{"g" : "\u{11EED}", "n" : "MAKASAR LETTER RA", "h" : "11EED"},
{"g" : "\u{11EEE}", "n" : "MAKASAR LETTER LA", "h" : "11EEE"},
{"g" : "\u{11EEF}", "n" : "MAKASAR LETTER VA", "h" : "11EEF"},
{"g" : "\u{11EF0}", "n" : "MAKASAR LETTER SA", "h" : "11EF0"},
{"g" : "\u{11EF1}", "n" : "MAKASAR LETTER A", "h" : "11EF1"},
{"g" : "\u{11EF2}", "n" : "MAKASAR ANGKA", "h" : "11EF2"},
{"g" : "\u{11EF3}", "n" : "MAKASAR VOWEL SIGN I", "h" : "11EF3"},
{"g" : "\u{11EF4}", "n" : "MAKASAR VOWEL SIGN U", "h" : "11EF4"},
{"g" : "\u{11EF5}", "n" : "MAKASAR VOWEL SIGN E", "h" : "11EF5"},
{"g" : "\u{11EF6}", "n" : "MAKASAR VOWEL SIGN O", "h" : "11EF6"},
{"g" : "\u{11EF7}", "n" : "MAKASAR PASSIMBANG", "h" : "11EF7"},
{"g" : "\u{11EF8}", "n" : "MAKASAR END OF SECTION", "h" : "11EF8"}
];
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    	var myPara1 = document.createElement('p');
    	var myPara2 = document.createElement('p');
    	var myPara3 = document.createElement('p');
		  var myPara4 = document.createElement('p');
		  var myPara5 = document.createElement('p');
		  var myPara6 = document.createElement('p');

    	myPara1.textContent = glyph;
    	myPara2.textContent = name;
    	myPara3.textContent = 'U+' + hex;
		  myPara4.textContent = '&#x' + hex + ';';
		  myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
		  myPara6.textContent = '\\' + 'u' + hex;

    	myArticle.appendChild(myPara1);
    	myArticle.appendChild(myPara2);
    	myArticle.appendChild(myPara3);
		  myArticle.appendChild(myPara4);
		  myArticle.appendChild(myPara5);
		  myArticle.appendChild(myPara6);

      section.appendChild(myArticle);
  }
}
