var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u0021", "n" : "EXCLAMATION MARK", "h" : "0021" },
{"g" : "\u0022", "n" : "QUOTATION MARK", "h" : "0022" },
{"g" : "\u0023", "n" : "NUMBER SIGN", "h" : "0023" },
{"g" : "\u0024", "n" : "DOLLAR SIGN", "h" : "0024" },
{"g" : "\u0025", "n" : "PERCENT SIGN", "h" : "0025" },
{"g" : "\u0026", "n" : "AMPERSAND", "h" : "0026" },
{"g" : "\u0027", "n" : "APOSTROPHE", "h" : "0027" },
{"g" : "\u0028", "n" : "LEFT PARENTHESIS", "h" : "0028" },
{"g" : "\u0029", "n" : "RIGHT PARENTHESIS", "h" : "0029" },
{"g" : "\u002A", "n" : "ASTERISK", "h" : "002A" },

{"g" : "\u002C", "n" : "COMMA", "h" : "002C" },
{"g" : "\u002D", "n" : "HYPHEN-MINUS", "h" : "002D" },
{"g" : "\u002E", "n" : "FULL STOP", "h" : "002E" },
{"g" : "\u002F", "n" : "SOLIDUS", "h" : "002F" },
{"g" : "\u003A", "n" : "COLON", "h" : "003A" },
{"g" : "\u003B", "n" : "SEMICOLON", "h" : "003B" },
{"g" : "\u003C", "n" : "LESS-THAN SIGN", "h" : "003C" },
{"g" : "\u003D", "n" : "EQUALS SIGN", "h" : "003D" },
{"g" : "\u003E", "n" : "GREATER-THAN SIGN", "h" : "003E" },
{"g" : "\u003F", "n" : "QUESTION MARK", "h" : "003F" },
{"g" : "\u0040", "n" : "COMMERCIAL AT", "h" : "0040" },
{"g" : "\u005B", "n" : "LEFT SQUARE BRACKET", "h" : "005B" },
{"g" : "\u005C", "n" : "REVERSE SOLIDUS", "h" : "005C" },
{"g" : "\u005D", "n" : "RIGHT SQUARE BRACKET", "h" : "005D" },
{"g" : "\u005E", "n" : "CIRCUMFLEX ACCENT", "h" : "005E" },
{"g" : "\u005F", "n" : "LOW LINE", "h" : "005F" },
{"g" : "\u0060", "n" : "GRAVE ACCENT", "h" : "0060" },
{"g" : "\u007B", "n" : "LEFT CURLY BRACKET", "h" : "007B" },
{"g" : "\u007C", "n" : "VERTICAL LINE", "h" : "007C" },
{"g" : "\u007D", "n" : "RIGHT CURLY BRACKET", "h" : "007D" },
{"g" : "\u007E", "n" : "TILDE", "h" : "007E" },
{"g" : "\u007F", "n" : "DELETE", "h" : "007F" },

{"g" : "\u00A1", "n" : "INVERTED EXCLAMATION MARK", "h" : "00A1" },
{"g" : "\u00A2", "n" : "CENT SIGN", "h" : "00A2" },
{"g" : "\u00A3", "n" : "POUND SIGN", "h" : "00A3" },
{"g" : "\u00A4", "n" : "CURRENCY SIGN", "h" : "00A4" },
{"g" : "\u00A5", "n" : "YEN SIGN", "h" : "00A5" },
{"g" : "\u00A6", "n" : "BROKEN BAR", "h" : "00A6" },
{"g" : "\u00A7", "n" : "SECTION SIGN", "h" : "00A7" },
{"g" : "\u00A8", "n" : "DIAERESIS", "h" : "00A8" },
{"g" : "\u00A9", "n" : "COPYRIGHT SIGN", "h" : "00A9" },
{"g" : "\u00AA", "n" : "FEMININE ORDINAL INDICATOR", "h" : "00AA" },
{"g" : "\u00AB", "n" : "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK", "h" : "00AB" },
{"g" : "\u00AC", "n" : "NOT SIGN", "h" : "00AC" },

{"g" : "\u00AE", "n" : "REGISTERED SIGN", "h" : "00AE" },
{"g" : "\u00AF", "n" : "MACRON", "h" : "00AF" },
{"g" : "\u00B0", "n" : "DEGREE SIGN", "h" : "00B0" },
{"g" : "\u00B1", "n" : "PLUS-MINUS SIGN", "h" : "00B1" },
{"g" : "\u00B2", "n" : "SUPERSCRIPT TWO", "h" : "00B2" },
{"g" : "\u00B3", "n" : "SUPERSCRIPT THREE", "h" : "00B3" },
{"g" : "\u00B4", "n" : "ACUTE ACCENT", "h" : "00B4" },
{"g" : "\u00B5", "n" : "MICRO SIGN", "h" : "00B5" },
{"g" : "\u00B6", "n" : "PILCROW SIGN", "h" : "00B6" },
{"g" : "\u00B7", "n" : "MIDDLE DOT", "h" : "00B7" },
{"g" : "\u00B8", "n" : "CEDILLA", "h" : "00B8" },
{"g" : "\u00B9", "n" : "SUPERSCRIPT ONE", "h" : "00B9" },
{"g" : "\u00BA", "n" : "MASCULINE ORDINAL INDICATOR", "h" : "00BA" },
{"g" : "\u00BB", "n" : "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK", "h" : "00BB" },

{"g" : "\u00BF", "n" : "INVERTED QUESTION MARK", "h" : "00BF" },

{"g" : "\u2010", "n" : "HYPHEN", "h" : "2010" },

{"g" : "\u2012", "n" : "FIGURE DASH", "h" : "2012" },
{"g" : "\u2013", "n" : "EN DASH", "h" : "2013" },
{"g" : "\u2014", "n" : "EM DASH", "h" : "2014" },
{"g" : "\u2015", "n" : "HORIZONTAL BAR", "h" : "2015" },
{"g" : "\u2016", "n" : "DOUBLE VERTICAL LINE", "h" : "2016" },
{"g" : "\u2017", "n" : "DOUBLE LOW LINE", "h" : "2017" },
{"g" : "\u2018", "n" : "LEFT SINGLE QUOTATION MARK", "h" : "2018" },
{"g" : "\u2019", "n" : "RIGHT SINGLE QUOTATION MARK", "h" : "2019" },
{"g" : "\u201A", "n" : "SINGLE LOW-9 QUOTATION MARK", "h" : "201A" },
{"g" : "\u201B", "n" : "SINGLE HIGH-REVERSED-9 QUOTATION MARK", "h" : "201B" },
{"g" : "\u201C", "n" : "LEFT DOUBLE QUOTATION MARK", "h" : "201C" },
{"g" : "\u201D", "n" : "RIGHT DOUBLE QUOTATION MARK", "h" : "201D" },
{"g" : "\u201E", "n" : "DOUBLE LOW-9 QUOTATION MARK", "h" : "201E" },
{"g" : "\u201F", "n" : "DOUBLE HIGH-REVERSED-9 QUOTATION MARK", "h" : "201F" },
{"g" : "\u2020", "n" : "DAGGER", "h" : "2020" },
{"g" : "\u2021", "n" : "DOUBLE DAGGER", "h" : "2021" },
{"g" : "\u2022", "n" : "BULLET", "h" : "2022" },
{"g" : "\u2023", "n" : "TRIANGULAR BULLET", "h" : "2023" },
{"g" : "\u2024", "n" : "ONE DOT LEADER", "h" : "2024" },
{"g" : "\u2025", "n" : "TWO DOT LEADER", "h" : "2025" },
{"g" : "\u2026", "n" : "HORIZONTAL ELLIPSIS", "h" : "2026" },
{"g" : "\u2027", "n" : "HYPHENATION POINT", "h" : "2027" },

{"g" : "\u2030", "n" : "PER MILLE SIGN", "h" : "2030" },
{"g" : "\u2031", "n" : "PER TEN THOUSAND SIGN", "h" : "2031" },
{"g" : "\u2032", "n" : "PRIME", "h" : "2032" },
{"g" : "\u2033", "n" : "DOUBLE PRIME", "h" : "2033" },
{"g" : "\u2034", "n" : "TRIPLE PRIME", "h" : "2034" },
{"g" : "\u2035", "n" : "REVERSED PRIME", "h" : "2035" },
{"g" : "\u2036", "n" : "REVERSED DOUBLE PRIME", "h" : "2036" },
{"g" : "\u2037", "n" : "REVERSED TRIPLE PRIME", "h" : "2037" },
{"g" : "\u2038", "n" : "CARET", "h" : "2038" },
{"g" : "\u2039", "n" : "SINGLE LEFT-POINTING ANGLE QUOTATION MARK", "h" : "2039" },
{"g" : "\u203A", "n" : "SINGLE RIGHT-POINTING ANGLE QUOTATION MARK", "h" : "203A" },
{"g" : "\u203B", "n" : "REFERENCE MARK", "h" : "203B" },
{"g" : "\u203C", "n" : "DOUBLE EXCLAMATION MARK", "h" : "203C" },
{"g" : "\u203D", "n" : "INTERROBANG", "h" : "203D" },
{"g" : "\u203E", "n" : "OVERLINE", "h" : "203E" },
{"g" : "\u203F", "n" : "UNDERTIE", "h" : "203F" },
{"g" : "\u2040", "n" : "CHARACTER TIE", "h" : "2040" },
{"g" : "\u2041", "n" : "CARET INSERTION POINT", "h" : "2041" },
{"g" : "\u2042", "n" : "ASTERISM", "h" : "2042" },
{"g" : "\u2043", "n" : "HYPHEN BULLET", "h" : "2043" },
{"g" : "\u2044", "n" : "FRACTION SLASH", "h" : "2044" },
{"g" : "\u2045", "n" : "LEFT SQUARE BRACKET WITH QUILL", "h" : "2045" },
{"g" : "\u2046", "n" : "RIGHT SQUARE BRACKET WITH QUILL", "h" : "2046" },
{"g" : "\u2047", "n" : "DOUBLE QUESTION MARK", "h" : "2047" },
{"g" : "\u2048", "n" : "QUESTION EXCLAMATION MARK", "h" : "2048" },
{"g" : "\u2049", "n" : "EXCLAMATION QUESTION MARK", "h" : "2049" },
{"g" : "\u204A", "n" : "TIRONIAN SIGN ET", "h" : "204A" },
{"g" : "\u204B", "n" : "REVERSED PILCROW SIGN", "h" : "204B" },
{"g" : "\u204C", "n" : "BLACK LEFTWARDS BULLET", "h" : "204C" },
{"g" : "\u204D", "n" : "BLACK RIGHTWARDS BULLET", "h" : "204D" },
{"g" : "\u204E", "n" : "LOW ASTERISK", "h" : "204E" },
{"g" : "\u204F", "n" : "REVERSED SEMICOLON", "h" : "204F" },
{"g" : "\u2050", "n" : "CLOSE UP", "h" : "2050" },
{"g" : "\u2051", "n" : "TWO ASTERISKS ALIGNED VERTICALLY", "h" : "2051" },
{"g" : "\u2052", "n" : "COMMERCIAL MINUS SIGN", "h" : "2052" },
{"g" : "\u2053", "n" : "SWUNG DASH", "h" : "2053" },
{"g" : "\u2054", "n" : "INVERTED UNDERTIE", "h" : "2054" },
{"g" : "\u2055", "n" : "FLOWER PUNCTUATION MARK", "h" : "2055" },
{"g" : "\u2056", "n" : "THREE DOT PUNCTUATION", "h" : "2056" },
{"g" : "\u2057", "n" : "QUADRUPLE PRIME", "h" : "2057" },
{"g" : "\u2058", "n" : "FOUR DOT PUNCTUATION", "h" : "2058" },
{"g" : "\u2059", "n" : "FIVE DOT PUNCTUATION", "h" : "2059" },
{"g" : "\u205A", "n" : "TWO DOT PUNCTUATION", "h" : "205A" },
{"g" : "\u205B", "n" : "FOUR DOT MARK", "h" : "205B" },
{"g" : "\u205C", "n" : "DOTTED CROSS", "h" : "205C" },
{"g" : "\u205D", "n" : "TRICOLON", "h" : "205D" },
{"g" : "\u205E", "n" : "VERTICAL FOUR DOTS", "h" : "205E" },

{"g" : "\u20A0", "n" : "EURO-CURRENCY SIGN", "h" : "20A0" },
{"g" : "\u20A1", "n" : "COLON SIGN", "h" : "20A1" },
{"g" : "\u20A2", "n" : "CRUZEIRO SIGN", "h" : "20A2" },
{"g" : "\u20A3", "n" : "FRENCH FRANC SIGN", "h" : "20A3" },
{"g" : "\u20A4", "n" : "LIRA SIGN", "h" : "20A4" },
{"g" : "\u20A5", "n" : "MILL SIGN", "h" : "20A5" },
{"g" : "\u20A6", "n" : "NAIRA SIGN", "h" : "20A6" },
{"g" : "\u20A7", "n" : "PESETA SIGN", "h" : "20A7" },
{"g" : "\u20A8", "n" : "RUPEE SIGN", "h" : "20A8" },
{"g" : "\u20A9", "n" : "WON SIGN", "h" : "20A9" },
{"g" : "\u20AA", "n" : "NEW SHEQEL SIGN", "h" : "20AA" },
{"g" : "\u20AB", "n" : "DONG SIGN", "h" : "20AB" },
{"g" : "\u20AC", "n" : "EURO SIGN", "h" : "20AC" },
{"g" : "\u20AD", "n" : "KIP SIGN", "h" : "20AD" },
{"g" : "\u20AE", "n" : "TUGRIK SIGN", "h" : "20AE" },
{"g" : "\u20AF", "n" : "DRACHMA SIGN", "h" : "20AF" },
{"g" : "\u20B0", "n" : "GERMAN PENNY SIGN", "h" : "20B0" },
{"g" : "\u20B1", "n" : "PESO SIGN", "h" : "20B1" },
{"g" : "\u20B2", "n" : "GUARANI SIGN", "h" : "20B2" },
{"g" : "\u20B3", "n" : "AUSTRAL SIGN", "h" : "20B3" },
{"g" : "\u20B4", "n" : "HRYVNIA SIGN", "h" : "20B4" },
{"g" : "\u20B5", "n" : "CEDI SIGN", "h" : "20B5" },
{"g" : "\u20B6", "n" : "LIVRE TOURNOIS SIGN", "h" : "20B6" },
{"g" : "\u20B7", "n" : "SPESMILO SIGN", "h" : "20B7" },
{"g" : "\u20B8", "n" : "TENGE SIGN", "h" : "20B8" },
{"g" : "\u20B9", "n" : "INDIAN RUPEE SIGN", "h" : "20B9" },
{"g" : "\u20BA", "n" : "TURKISH LIRA SIGN", "h" : "20BA" },
{"g" : "\u20BB", "n" : "NORDIC MARK SIGN", "h" : "20BB" },
{"g" : "\u20BC", "n" : "MANAT SIGN", "h" : "20BC" },
{"g" : "\u20BD", "n" : "RUBLE SIGN", "h" : "20BD" },
{"g" : "\u20BE", "n" : "LARI SIGN", "h" : "20BE" },
{"g" : "\u20BF", "n" : "BITCOIN SIGN", "h" : "20BF" },

{"g" : "\u2753", "n" : "BLACK QUESTION MARK ORNAMENT", "h" : "2753" },
{"g" : "\u2754", "n" : "WHITE QUESTION MARK ORNAMENT", "h" : "2754" },
{"g" : "\u2755", "n" : "WHITE EXCLAMATION MARK ORNAMENT", "h" : "2755" },
{"g" : "\u2756", "n" : "BLACK DIAMOND MINUS WHITE X", "h" : "2756" },
{"g" : "\u2757", "n" : "HEAVY EXCLAMATION MARK SYMBOL", "h" : "2757" },
{"g" : "\u2758", "n" : "LIGHT VERTICAL BAR", "h" : "2758" },
{"g" : "\u2759", "n" : "MEDIUM VERTICAL BAR", "h" : "2759" },
{"g" : "\u275A", "n" : "HEAVY VERTICAL BAR", "h" : "275A" },
{"g" : "\u275B", "n" : "HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT", "h" : "275B" },
{"g" : "\u275C", "n" : "HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT", "h" : "275C" },
{"g" : "\u275D", "n" : "HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT", "h" : "275D" },
{"g" : "\u275E", "n" : "HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT", "h" : "275E" },
{"g" : "\u275F", "n" : "HEAVY LOW SINGLE COMMA QUOTATION MARK ORNAMENT", "h" : "275F" },
{"g" : "\u2760", "n" : "HEAVY LOW DOUBLE COMMA QUOTATION MARK ORNAMENT", "h" : "2760" },
{"g" : "\u2761", "n" : "CURVED STEM PARAGRAPH SIGN ORNAMENT", "h" : "2761" },
{"g" : "\u2762", "n" : "HEAVY EXCLAMATION MARK ORNAMENT", "h" : "2762" },
{"g" : "\u2763", "n" : "HEAVY HEART EXCLAMATION MARK ORNAMENT", "h" : "2763" },

{"g" : "\u2765", "n" : "ROTATED HEAVY BLACK HEART BULLET", "h" : "2765" },
{"g" : "\u2766", "n" : "FLORAL HEART", "h" : "2766" },
{"g" : "\u2767", "n" : "ROTATED FLORAL HEART BULLET", "h" : "2767" },
{"g" : "\u2768", "n" : "MEDIUM LEFT PARENTHESIS ORNAMENT", "h" : "2768" },
{"g" : "\u2769", "n" : "MEDIUM RIGHT PARENTHESIS ORNAMENT", "h" : "2769" },
{"g" : "\u276A", "n" : "MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT", "h" : "276A" },
{"g" : "\u276B", "n" : "MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT", "h" : "276B" },
{"g" : "\u276C", "n" : "MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT", "h" : "276C" },
{"g" : "\u276D", "n" : "MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT", "h" : "276D" },
{"g" : "\u276E", "n" : "HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT", "h" : "276E" },
{"g" : "\u276F", "n" : "HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT", "h" : "276F" },
{"g" : "\u2770", "n" : "HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT", "h" : "2770" },
{"g" : "\u2771", "n" : "HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT", "h" : "2771" },
{"g" : "\u2772", "n" : "LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT", "h" : "2772" },
{"g" : "\u2773", "n" : "LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT", "h" : "2773" },
{"g" : "\u2774", "n" : "MEDIUM LEFT CURLY BRACKET ORNAMENT", "h" : "2774" },
{"g" : "\u2775", "n" : "MEDIUM RIGHT CURLY BRACKET ORNAMENT", "h" : "2775" },

{"g" : "\u2E00", "n" : "RIGHT ANGLE SUBSTITUTION MARKER", "h" : "2E00" },
{"g" : "\u2E01", "n" : "RIGHT ANGLE DOTTED SUBSTITUTION MARKER", "h" : "2E01" },
{"g" : "\u2E02", "n" : "LEFT SUBSTITUTION BRACKET", "h" : "2E02" },
{"g" : "\u2E03", "n" : "RIGHT SUBSTITUTION BRACKET", "h" : "2E03" },
{"g" : "\u2E04", "n" : "LEFT DOTTED SUBSTITUTION BRACKET", "h" : "2E04" },
{"g" : "\u2E05", "n" : "RIGHT DOTTED SUBSTITUTION BRACKET", "h" : "2E05" },
{"g" : "\u2E06", "n" : "RAISED INTERPOLATION MARKER", "h" : "2E06" },
{"g" : "\u2E07", "n" : "RAISED DOTTED INTERPOLATION MARKER", "h" : "2E07" },
{"g" : "\u2E08", "n" : "DOTTED TRANSPOSITION MARKER", "h" : "2E08" },
{"g" : "\u2E09", "n" : "LEFT TRANSPOSITION BRACKET", "h" : "2E09" },
{"g" : "\u2E0A", "n" : "RIGHT TRANSPOSITION BRACKET", "h" : "2E0A" },
{"g" : "\u2E0B", "n" : "RAISED SQUARE", "h" : "2E0B" },
{"g" : "\u2E0C", "n" : "LEFT RAISED OMISSION BRACKET", "h" : "2E0C" },
{"g" : "\u2E0D", "n" : "RIGHT RAISED OMISSION BRACKET", "h" : "2E0D" },
{"g" : "\u2E0E", "n" : "EDITORIAL CORONIS", "h" : "2E0E" },
{"g" : "\u2E0F", "n" : "PARAGRAPHOS", "h" : "2E0F" },
{"g" : "\u2E10", "n" : "FORKED PARAGRAPHOS", "h" : "2E10" },
{"g" : "\u2E11", "n" : "REVERSED FORKED PARAGRAPHOS", "h" : "2E11" },
{"g" : "\u2E12", "n" : "HYPODIASTOLE", "h" : "2E12" },
{"g" : "\u2E13", "n" : "DOTTED OBELOS", "h" : "2E13" },
{"g" : "\u2E14", "n" : "DOWNWARDS ANCORA", "h" : "2E14" },
{"g" : "\u2E15", "n" : "UPWARDS ANCORA", "h" : "2E15" },
{"g" : "\u2E16", "n" : "DOTTED RIGHT-POINTING ANGLE", "h" : "2E16" },
{"g" : "\u2E17", "n" : "DOUBLE OBLIQUE HYPHEN", "h" : "2E17" },
{"g" : "\u2E18", "n" : "INVERTED INTERROBANG", "h" : "2E18" },
{"g" : "\u2E19", "n" : "PALM BRANCH", "h" : "2E19" },
{"g" : "\u2E1A", "n" : "HYPHEN WITH DIAERESIS", "h" : "2E1A" },
{"g" : "\u2E1B", "n" : "TILDE WITH RING ABOVE", "h" : "2E1B" },
{"g" : "\u2E1C", "n" : "LEFT LOW PARAPHRASE BRACKET", "h" : "2E1C" },
{"g" : "\u2E1D", "n" : "RIGHT LOW PARAPHRASE BRACKET", "h" : "2E1D" },
{"g" : "\u2E1E", "n" : "TILDE WITH DOT ABOVE", "h" : "2E1E" },
{"g" : "\u2E1F", "n" : "TILDE WITH DOT BELOW", "h" : "2E1F" },
{"g" : "\u2E20", "n" : "LEFT VERTICAL BAR WITH QUILL", "h" : "2E20" },
{"g" : "\u2E21", "n" : "RIGHT VERTICAL BAR WITH QUILL", "h" : "2E21" },
{"g" : "\u2E22", "n" : "TOP LEFT HALF BRACKET", "h" : "2E22" },
{"g" : "\u2E23", "n" : "TOP RIGHT HALF BRACKET", "h" : "2E23" },
{"g" : "\u2E24", "n" : "BOTTOM LEFT HALF BRACKET", "h" : "2E24" },
{"g" : "\u2E25", "n" : "BOTTOM RIGHT HALF BRACKET", "h" : "2E25" },
{"g" : "\u2E26", "n" : "LEFT SIDEWAYS U BRACKET", "h" : "2E26" },
{"g" : "\u2E27", "n" : "RIGHT SIDEWAYS U BRACKET", "h" : "2E27" },
{"g" : "\u2E28", "n" : "LEFT DOUBLE PARENTHESIS", "h" : "2E28" },
{"g" : "\u2E29", "n" : "RIGHT DOUBLE PARENTHESIS", "h" : "2E29" },
{"g" : "\u2E2A", "n" : "TWO DOTS OVER ONE DOT PUNCTUATION", "h" : "2E2A" },
{"g" : "\u2E2B", "n" : "ONE DOT OVER TWO DOTS PUNCTUATION", "h" : "2E2B" },
{"g" : "\u2E2C", "n" : "SQUARED FOUR DOT PUNCTUATION", "h" : "2E2C" },
{"g" : "\u2E2D", "n" : "FIVE DOT MARK", "h" : "2E2D" },
{"g" : "\u2E2E", "n" : "REVERSED QUESTION MARK", "h" : "2E2E" },
{"g" : "\u2E2F", "n" : "VERTICAL TILDE", "h" : "2E2F" },
{"g" : "\u2E30", "n" : "RING POINT", "h" : "2E30" },
{"g" : "\u2E31", "n" : "WORD SEPARATOR MIDDLE DOT", "h" : "2E31" },
{"g" : "\u2E32", "n" : "TURNED COMMA", "h" : "2E32" },
{"g" : "\u2E33", "n" : "RAISED DOT", "h" : "2E33" },
{"g" : "\u2E34", "n" : "RAISED COMMA", "h" : "2E34" },
{"g" : "\u2E35", "n" : "TURNED SEMICOLON", "h" : "2E35" },
{"g" : "\u2E36", "n" : "DAGGER WITH LEFT GUARD", "h" : "2E36" },
{"g" : "\u2E37", "n" : "DAGGER WITH RIGHT GUARD", "h" : "2E37" },
{"g" : "\u2E38", "n" : "TURNED DAGGER", "h" : "2E38" },
{"g" : "\u2E39", "n" : "TOP HALF SECTION SIGN", "h" : "2E39" },
{"g" : "\u2E3A", "n" : "TWO-EM DASH", "h" : "2E3A" },
{"g" : "\u2E3B", "n" : "THREE-EM DASH", "h" : "2E3B" },
{"g" : "\u2E3C", "n" : "STENOGRAPHIC FULL STOP", "h" : "2E3C" },
{"g" : "\u2E3D", "n" : "VERTICAL SIX DOTS", "h" : "2E3D" },
{"g" : "\u2E3E", "n" : "WIGGLY VERTICAL LINE", "h" : "2E3E" },
{"g" : "\u2E3F", "n" : "CAPITULUM", "h" : "2E3F" },
{"g" : "\u2E40", "n" : "DOUBLE HYPHEN", "h" : "2E40" },
{"g" : "\u2E41", "n" : "REVERSED COMMA", "h" : "2E41" },
{"g" : "\u2E42", "n" : "DOUBLE LOW-REVERSED-9 QUOTATION MARK", "h" : "2E42" },
{"g" : "\u2E43", "n" : "DASH WITH LEFT UPTURN", "h" : "2E43" },
{"g" : "\u2E44", "n" : "DOUBLE SUSPENSION MARK", "h" : "2E44" },
{"g" : "\u2E45", "n" : "INVERTED LOW KAVYKA", "h" : "2E45" },
{"g" : "\u2E46", "n" : "INVERTED LOW KAVYKA WITH KAVYKA ABOVE", "h" : "2E46" },
{"g" : "\u2E47", "n" : "LOW KAVYKA", "h" : "2E47" },
{"g" : "\u2E48", "n" : "LOW KAVYKA WITH DOT", "h" : "2E48" },
{"g" : "\u2E49", "n" : "DOUBLE STACKED COMMA", "h" : "2E49" },
{"g" : "\u2E4A", "n" : "DOTTED SOLIDUS", "h" : "2E4A" },
{"g" : "\u2E4B", "n" : "TRIPLE DAGGER", "h" : "2E4B" },
{"g" : "\u2E4C", "n" : "MEDIEVAL COMMA", "h" : "2E4C" },
{"g" : "\u2E4D", "n" : "PARAGRAPHUS MARK", "h" : "2E4D" },
{"g" : "\u2E4E", "n" : "PUNCTUS ELEVATUS MARK", "h" : "2E4E" },
{"g" : "\u2E4F", "n" : "CORNISH VERSE DIVIDER", "h" : "2E4F" },

{"g" : "\u3000", "n" : "IDEOGRAPHIC SPACE", "h" : "3000" },
{"g" : "\u3001", "n" : "IDEOGRAPHIC COMMA", "h" : "3001" },
{"g" : "\u3002", "n" : "IDEOGRAPHIC FULL STOP", "h" : "3002" },
{"g" : "\u3003", "n" : "DITTO MARK", "h" : "3003" },

{"g" : "\u3005", "n" : "IDEOGRAPHIC ITERATION MARK", "h" : "3005" },
{"g" : "\u3006", "n" : "IDEOGRAPHIC CLOSING MARK", "h" : "3006" },
{"g" : "\u3007", "n" : "IDEOGRAPHIC NUMBER ZERO", "h" : "3007" },
{"g" : "\u3008", "n" : "LEFT ANGLE BRACKET", "h" : "3008" },
{"g" : "\u3009", "n" : "RIGHT ANGLE BRACKET", "h" : "3009" },
{"g" : "\u300A", "n" : "LEFT DOUBLE ANGLE BRACKET", "h" : "300A" },
{"g" : "\u300B", "n" : "RIGHT DOUBLE ANGLE BRACKET", "h" : "300B" },
{"g" : "\u300C", "n" : "LEFT CORNER BRACKET", "h" : "300C" },
{"g" : "\u300D", "n" : "RIGHT CORNER BRACKET", "h" : "300D" },
{"g" : "\u300E", "n" : "LEFT WHITE CORNER BRACKET", "h" : "300E" },
{"g" : "\u300F", "n" : "RIGHT WHITE CORNER BRACKET", "h" : "300F" },
{"g" : "\u3010", "n" : "LEFT BLACK LENTICULAR BRACKET", "h" : "3010" },
{"g" : "\u3011", "n" : "RIGHT BLACK LENTICULAR BRACKET", "h" : "3011" },
{"g" : "\u3012", "n" : "POSTAL MARK", "h" : "3012" },
{"g" : "\u3013", "n" : "GETA MARK", "h" : "3013" },
{"g" : "\u3014", "n" : "LEFT TORTOISE SHELL BRACKET", "h" : "3014" },
{"g" : "\u3015", "n" : "RIGHT TORTOISE SHELL BRACKET", "h" : "3015" },
{"g" : "\u3016", "n" : "LEFT WHITE LENTICULAR BRACKET", "h" : "3016" },
{"g" : "\u3017", "n" : "RIGHT WHITE LENTICULAR BRACKET", "h" : "3017" },
{"g" : "\u3018", "n" : "LEFT WHITE TORTOISE SHELL BRACKET", "h" : "3018" },
{"g" : "\u3019", "n" : "RIGHT WHITE TORTOISE SHELL BRACKET", "h" : "3019" },
{"g" : "\u301A", "n" : "LEFT WHITE SQUARE BRACKET", "h" : "301A" },
{"g" : "\u301B", "n" : "RIGHT WHITE SQUARE BRACKET", "h" : "301B" },
{"g" : "\u301C", "n" : "WAVE DASH", "h" : "301C" },
{"g" : "\u301D", "n" : "REVERSED DOUBLE PRIME QUOTATION MARK", "h" : "301D" },
{"g" : "\u301E", "n" : "DOUBLE PRIME QUOTATION MARK", "h" : "301E" },
{"g" : "\u301F", "n" : "LOW DOUBLE PRIME QUOTATION MARK", "h" : "301F" },

{"g" : "\u3030", "n" : "WAVY DASH", "h" : "3030" },
{"g" : "\u3031", "n" : "VERTICAL KANA REPEAT MARK", "h" : "3031" },
{"g" : "\u3032", "n" : "VERTICAL KANA REPEAT WITH VOICED SOUND MARK", "h" : "3032" },
{"g" : "\u3033", "n" : "VERTICAL KANA REPEAT MARK UPPER HALF", "h" : "3033" },
{"g" : "\u3034", "n" : "VERTICAL KANA REPEAT WITH VOICED SOUND MARK UPPER HALF", "h" : "3034" },
{"g" : "\u3035", "n" : "VERTICAL KANA REPEAT MARK LOWER HALF", "h" : "3035" },

{"g" : "\u303B", "n" : "VERTICAL IDEOGRAPHIC ITERATION MARK", "h" : "303B" },
{"g" : "\u303C", "n" : "MASU MARK", "h" : "303C" },
{"g" : "\u303D", "n" : "PART ALTERNATION MARK", "h" : "303D" },

{"g" : "\uA673", "n" : "SLAVONIC ASTERISK", "h" : "A673"},

{"g" : "\uA67E", "n" : "CYRILLIC KAVYKA", "h" : "A67E"},

{"g" : "\uFE10", "n" : "PRESENTATION FORM FOR VERTICAL COMMA", "h" : "FE10"},
{"g" : "\uFE11", "n" : "PRESENTATION FORM FOR VERTICAL IDEOGRAPHIC COMMA", "h" : "FE11"},
{"g" : "\uFE12", "n" : "PRESENTATION FORM FOR VERTICAL IDEOGRAPHIC FULL STOP", "h" : "FE12"},
{"g" : "\uFE13", "n" : "PRESENTATION FORM FOR VERTICAL COLON", "h" : "FE13"},
{"g" : "\uFE14", "n" : "PRESENTATION FORM FOR VERTICAL SEMICOLON", "h" : "FE14"},
{"g" : "\uFE15", "n" : "PRESENTATION FORM FOR VERTICAL EXCLAMATION MARK", "h" : "FE15"},
{"g" : "\uFE16", "n" : "PRESENTATION FORM FOR VERTICAL QUESTION MARK", "h" : "FE16"},
{"g" : "\uFE17", "n" : "PRESENTATION FORM FOR VERTICAL LEFT WHITE LENTICULAR BRACKET", "h" : "FE17"},
{"g" : "\uFE18", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET", "h" : "FE18"},
{"g" : "\uFE19", "n" : "PRESENTATION FORM FOR VERTICAL HORIZONTAL ELLIPSIS", "h" : "FE19"},

{"g" : "\uFE30", "n" : "PRESENTATION FORM FOR VERTICAL TWO DOT LEADER", "h" : "FE30"},
{"g" : "\uFE31", "n" : "PRESENTATION FORM FOR VERTICAL EM DASH", "h" : "FE31"},
{"g" : "\uFE32", "n" : "PRESENTATION FORM FOR VERTICAL EN DASH", "h" : "FE32"},
{"g" : "\uFE33", "n" : "PRESENTATION FORM FOR VERTICAL LOW LINE", "h" : "FE33"},
{"g" : "\uFE34", "n" : "PRESENTATION FORM FOR VERTICAL WAVY LOW LINE", "h" : "FE34"},
{"g" : "\uFE35", "n" : "PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS", "h" : "FE35"},
{"g" : "\uFE36", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS", "h" : "FE36"},
{"g" : "\uFE37", "n" : "PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET", "h" : "FE37"},
{"g" : "\uFE38", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET", "h" : "FE38"},
{"g" : "\uFE39", "n" : "PRESENTATION FORM FOR VERTICAL LEFT TORTOISE SHELL BRACKET", "h" : "FE39"},
{"g" : "\uFE3A", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT TORTOISE SHELL BRACKET", "h" : "FE3A"},
{"g" : "\uFE3B", "n" : "PRESENTATION FORM FOR VERTICAL LEFT BLACK LENTICULAR BRACKET", "h" : "FE3B"},
{"g" : "\uFE3C", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT BLACK LENTICULAR BRACKET", "h" : "FE3C"},
{"g" : "\uFE3D", "n" : "PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET", "h" : "FE3D"},
{"g" : "\uFE3E", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET", "h" : "FE3E"},
{"g" : "\uFE3F", "n" : "PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET", "h" : "FE3F"},
{"g" : "\uFE40", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET", "h" : "FE40"},
{"g" : "\uFE41", "n" : "PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET", "h" : "FE41"},
{"g" : "\uFE42", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT CORNER BRACKET", "h" : "FE42"},
{"g" : "\uFE43", "n" : "PRESENTATION FORM FOR VERTICAL LEFT WHITE CORNER BRACKET", "h" : "FE43"},
{"g" : "\uFE44", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT WHITE CORNER BRACKET", "h" : "FE44"},
{"g" : "\uFE45", "n" : "SESAME DOT", "h" : "FE45"},
{"g" : "\uFE46", "n" : "WHITE SESAME DOT", "h" : "FE46"},
{"g" : "\uFE47", "n" : "PRESENTATION FORM FOR VERTICAL LEFT SQUARE BRACKET", "h" : "FE47"},
{"g" : "\uFE48", "n" : "PRESENTATION FORM FOR VERTICAL RIGHT SQUARE BRACKET", "h" : "FE48"},
{"g" : "\uFE49", "n" : "DASHED OVERLINE", "h" : "FE49"},
{"g" : "\uFE4A", "n" : "CENTRELINE OVERLINE", "h" : "FE4A"},
{"g" : "\uFE4B", "n" : "WAVY OVERLINE", "h" : "FE4B"},
{"g" : "\uFE4C", "n" : "DOUBLE WAVY OVERLINE", "h" : "FE4C"},
{"g" : "\uFE4D", "n" : "DASHED LOW LINE", "h" : "FE4D"},
{"g" : "\uFE4E", "n" : "CENTRELINE LOW LINE", "h" : "FE4E"},
{"g" : "\uFE4F", "n" : "WAVY LOW LINE", "h" : "FE4F"},

{"g" : "\uFE50", "n" : "SMALL COMMA", "h" : "FE50"},
{"g" : "\uFE51", "n" : "SMALL IDEOGRAPHIC COMMA", "h" : "FE51"},
{"g" : "\uFE52", "n" : "SMALL FULL STOP", "h" : "FE52"},

{"g" : "\uFE54", "n" : "SMALL SEMICOLON", "h" : "FE54"},
{"g" : "\uFE55", "n" : "SMALL COLON", "h" : "FE55"},
{"g" : "\uFE56", "n" : "SMALL QUESTION MARK", "h" : "FE56"},
{"g" : "\uFE57", "n" : "SMALL EXCLAMATION MARK", "h" : "FE57"},
{"g" : "\uFE58", "n" : "SMALL EM DASH", "h" : "FE58"},
{"g" : "\uFE59", "n" : "SMALL LEFT PARENTHESIS", "h" : "FE59"},
{"g" : "\uFE5A", "n" : "SMALL RIGHT PARENTHESIS", "h" : "FE5A"},
{"g" : "\uFE5B", "n" : "SMALL LEFT CURLY BRACKET", "h" : "FE5B"},
{"g" : "\uFE5C", "n" : "SMALL RIGHT CURLY BRACKET", "h" : "FE5C"},
{"g" : "\uFE5D", "n" : "SMALL LEFT TORTOISE SHELL BRACKET", "h" : "FE5D"},
{"g" : "\uFE5E", "n" : "SMALL RIGHT TORTOISE SHELL BRACKET", "h" : "FE5E"},
{"g" : "\uFE5F", "n" : "SMALL NUMBER SIGN", "h" : "FE5F"},
{"g" : "\uFE60", "n" : "SMALL AMPERSAND", "h" : "FE60"},
{"g" : "\uFE61", "n" : "SMALL ASTERISK", "h" : "FE61"},
{"g" : "\uFE62", "n" : "SMALL PLUS SIGN", "h" : "FE62"},
{"g" : "\uFE63", "n" : "SMALL HYPHEN-MINUS", "h" : "FE63"},
{"g" : "\uFE64", "n" : "SMALL LESS-THAN SIGN", "h" : "FE64"},
{"g" : "\uFE65", "n" : "SMALL GREATER-THAN SIGN", "h" : "FE65"},
{"g" : "\uFE66", "n" : "SMALL EQUALS SIGN", "h" : "FE66"},

{"g" : "\uFE68", "n" : "SMALL REVERSE SOLIDUS", "h" : "FE68"},
{"g" : "\uFE69", "n" : "SMALL DOLLAR SIGN", "h" : "FE69"},
{"g" : "\uFE6A", "n" : "SMALL PERCENT SIGN", "h" : "FE6A"},
{"g" : "\uFE6B", "n" : "SMALL COMMERCIAL AT", "h" : "FE6B"},

{"g" : "\uFF01", "n" : "FULLWIDTH EXCLAMATION MARK", "h" : "FF01"},
{"g" : "\uFF02", "n" : "FULLWIDTH QUOTATION MARK", "h" : "FF02"},
{"g" : "\uFF03", "n" : "FULLWIDTH NUMBER SIGN", "h" : "FF03"},
{"g" : "\uFF04", "n" : "FULLWIDTH DOLLAR SIGN", "h" : "FF04"},
{"g" : "\uFF05", "n" : "FULLWIDTH PERCENT SIGN", "h" : "FF05"},
{"g" : "\uFF06", "n" : "FULLWIDTH AMPERSAND", "h" : "FF06"},
{"g" : "\uFF07", "n" : "FULLWIDTH APOSTROPHE", "h" : "FF07"},
{"g" : "\uFF08", "n" : "FULLWIDTH LEFT PARENTHESIS", "h" : "FF08"},
{"g" : "\uFF09", "n" : "FULLWIDTH RIGHT PARENTHESIS", "h" : "FF09"},
{"g" : "\uFF0A", "n" : "FULLWIDTH ASTERISK", "h" : "FF0A"},
{"g" : "\uFF0B", "n" : "FULLWIDTH PLUS SIGN", "h" : "FF0B"},
{"g" : "\uFF0C", "n" : "FULLWIDTH COMMA", "h" : "FF0C"},
{"g" : "\uFF0D", "n" : "FULLWIDTH HYPHEN-MINUS", "h" : "FF0D"},
{"g" : "\uFF0E", "n" : "FULLWIDTH FULL STOP", "h" : "FF0E"},
{"g" : "\uFF0F", "n" : "FULLWIDTH SOLIDUS", "h" : "FF0F"},

{"g" : "\uFF1A", "n" : "FULLWIDTH COLON", "h" : "FF1A"},
{"g" : "\uFF1B", "n" : "FULLWIDTH SEMICOLON", "h" : "FF1B"},
{"g" : "\uFF1C", "n" : "FULLWIDTH LESS-THAN SIGN", "h" : "FF1C"},
{"g" : "\uFF1D", "n" : "FULLWIDTH EQUALS SIGN", "h" : "FF1D"},
{"g" : "\uFF1E", "n" : "FULLWIDTH GREATER-THAN SIGN", "h" : "FF1E"},
{"g" : "\uFF1F", "n" : "FULLWIDTH QUESTION MARK", "h" : "FF1F"},
{"g" : "\uFF20", "n" : "FULLWIDTH COMMERCIAL AT", "h" : "FF20"},

{"g" : "\uFF3B", "n" : "FULLWIDTH LEFT SQUARE BRACKET", "h" : "FF3B"},
{"g" : "\uFF3C", "n" : "FULLWIDTH REVERSE SOLIDUS", "h" : "FF3C"},
{"g" : "\uFF3D", "n" : "FULLWIDTH RIGHT SQUARE BRACKET", "h" : "FF3D"},
{"g" : "\uFF3E", "n" : "FULLWIDTH CIRCUMFLEX ACCENT", "h" : "FF3E"},
{"g" : "\uFF3F", "n" : "FULLWIDTH LOW LINE", "h" : "FF3F"},
{"g" : "\uFF40", "n" : "FULLWIDTH GRAVE ACCENT", "h" : "FF40"},

{"g" : "\uFF5B", "n" : "FULLWIDTH LEFT CURLY BRACKET", "h" : "FF5B"},
{"g" : "\uFF5C", "n" : "FULLWIDTH VERTICAL LINE", "h" : "FF5C"},
{"g" : "\uFF5D", "n" : "FULLWIDTH RIGHT CURLY BRACKET", "h" : "FF5D"},
{"g" : "\uFF5E", "n" : "FULLWIDTH TILDE", "h" : "FF5E"},
{"g" : "\uFF5F", "n" : "FULLWIDTH LEFT WHITE PARENTHESIS", "h" : "FF5F"},
{"g" : "\uFF60", "n" : "FULLWIDTH RIGHT WHITE PARENTHESIS", "h" : "FF60"},
{"g" : "\uFF61", "n" : "HALFWIDTH IDEOGRAPHIC FULL STOP", "h" : "FF61"},
{"g" : "\uFF62", "n" : "HALFWIDTH LEFT CORNER BRACKET", "h" : "FF62"},
{"g" : "\uFF63", "n" : "HALFWIDTH RIGHT CORNER BRACKET", "h" : "FF63"},
{"g" : "\uFF64", "n" : "HALFWIDTH IDEOGRAPHIC COMMA", "h" : "FF64"},

{"g" : "\uFFE0", "n" : "FULLWIDTH CENT SIGN", "h" : "FFE0"},
{"g" : "\uFFE1", "n" : "FULLWIDTH POUND SIGN", "h" : "FFE1"},
{"g" : "\uFFE2", "n" : "FULLWIDTH NOT SIGN", "h" : "FFE2"},
{"g" : "\uFFE3", "n" : "FULLWIDTH MACRON", "h" : "FFE3"},
{"g" : "\uFFE4", "n" : "FULLWIDTH BROKEN BAR", "h" : "FFE4"},
{"g" : "\uFFE5", "n" : "FULLWIDTH YEN SIGN", "h" : "FFE5"},
{"g" : "\uFFE6", "n" : "FULLWIDTH WON SIGN", "h" : "FFE6"},

{"g" : "\uFFE8", "n" : "HALFWIDTH FORMS LIGHT VERTICAL", "h" : "FFE8"},

{"g" : "\uFFED", "n" : "HALFWIDTH BLACK SQUARE", "h" : "FFED"},
{"g" : "\uFFEE", "n" : "HALFWIDTH WHITE CIRCLE", "h" : "FFEE"},

{"g" : "\u{10B3A}", "n" : "TINY TWO DOTS OVER ONE DOT PUNCTUATION", "h" : "10B3A"},
{"g" : "\u{10B3B}", "n" : "SMALL TWO DOTS OVER ONE DOT PUNCTUATION", "h" : "10B3B"},
{"g" : "\u{10B3C}", "n" : "LARGE TWO DOTS OVER ONE DOT PUNCTUATION", "h" : "10B3C"},
{"g" : "\u{10B3D}", "n" : "LARGE ONE DOT OVER TWO DOTS PUNCTUATION", "h" : "10B3D"},
{"g" : "\u{10B3E}", "n" : "LARGE TWO RINGS OVER ONE RING PUNCTUATION", "h" : "10B3E"},
{"g" : "\u{10B3F}", "n" : "LARGE ONE RING OVER TWO RINGS PUNCTUATION", "h" : "10B3F"},

{"g" : "\u{16FE0}", "n" : "TANGUT ITERATION MARK", "h" : "16FE0"},
{"g" : "\u{16FE1}", "n" : "NUSHU ITERATION MARK", "h" : "16FE1"},
{"g" : "\u{16FE2}", "n" : "OLD CHINESE HOOK MARK", "h" : "16FE2"},
{"g" : "\u{16FE3}", "n" : "OLD CHINESE ITERATION MARK", "h" : "16FE3"},

{"g" : "\u{1F670}", "n" : "SCRIPT LIGATURE ET ORNAMENT", "h" : "1F670"},
{"g" : "\u{1F671}", "n" : "HEAVY SCRIPT LIGATURE ET ORNAMENT", "h" : "1F671"},
{"g" : "\u{1F672}", "n" : "LIGATURE OPEN ET ORNAMENT", "h" : "1F672"},
{"g" : "\u{1F673}", "n" : "HEAVY LIGATURE OPEN ET ORNAMENT", "h" : "1F673"},
{"g" : "\u{1F674}", "n" : "HEAVY AMPERSAND ORNAMENT", "h" : "1F674"},
{"g" : "\u{1F675}", "n" : "SWASH AMPERSAND ORNAMENT", "h" : "1F675"},
{"g" : "\u{1F676}", "n" : "SANS-SERIF HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT", "h" : "1F676"},
{"g" : "\u{1F677}", "n" : "SANS-SERIF HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT", "h" : "1F677"},
{"g" : "\u{1F678}", "n" : "SANS-SERIF HEAVY LOW DOUBLE COMMA QUOTATION MARK ORNAMENT", "h" : "1F678"},
{"g" : "\u{1F679}", "n" : "HEAVY INTERROBANG ORNAMENT", "h" : "1F679"},
{"g" : "\u{1F67A}", "n" : "SANS-SERIF INTERROBANG ORNAMENT", "h" : "1F67A"},
{"g" : "\u{1F67B}", "n" : "HEAVY SANS-SERIF INTERROBANG ORNAMENT", "h" : "1F67B"},
{"g" : "\u{1F67C}", "n" : "VERY HEAVY SOLIDUS", "h" : "1F67C"},
{"g" : "\u{1F67D}", "n" : "VERY HEAVY REVERSE SOLIDUS", "h" : "1F67D"},
];
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    	var myPara1 = document.createElement('p');
    	var myPara2 = document.createElement('p');
    	var myPara3 = document.createElement('p');
		  var myPara4 = document.createElement('p');
		  var myPara5 = document.createElement('p');
		  var myPara6 = document.createElement('p');

    	myPara1.textContent = glyph;
    	myPara2.textContent = name;
    	myPara3.textContent = 'U+' + hex;
		  myPara4.textContent = '&#x' + hex + ';';
		  myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
		  myPara6.textContent = '\\' + 'u' + hex;

    	myArticle.appendChild(myPara1);
    	myArticle.appendChild(myPara2);
    	myArticle.appendChild(myPara3);
		  myArticle.appendChild(myPara4);
		  myArticle.appendChild(myPara5);
		  myArticle.appendChild(myPara6);

    section.appendChild(myArticle);
  }
}
