var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u0E01", "n" : "THAI CHARACTER KO KAI", "h" : "0E01" },
{"g" : "\u0E02", "n" : "THAI CHARACTER KHO KHAI", "h" : "0E02" },
{"g" : "\u0E03", "n" : "THAI CHARACTER KHO KHUAT", "h" : "0E03" },
{"g" : "\u0E04", "n" : "THAI CHARACTER KHO KHWAI", "h" : "0E04" },
{"g" : "\u0E05", "n" : "THAI CHARACTER KHO KHON", "h" : "0E05" },
{"g" : "\u0E06", "n" : "THAI CHARACTER KHO RAKHANG", "h" : "0E06" },
{"g" : "\u0E07", "n" : "THAI CHARACTER NGO NGU", "h" : "0E07" },
{"g" : "\u0E08", "n" : "THAI CHARACTER CHO CHAN", "h" : "0E08" },
{"g" : "\u0E09", "n" : "THAI CHARACTER CHO CHING", "h" : "0E09" },
{"g" : "\u0E0A", "n" : "THAI CHARACTER CHO CHANG", "h" : "0E0A" },
{"g" : "\u0E0B", "n" : "THAI CHARACTER SO SO", "h" : "0E0B" },
{"g" : "\u0E0C", "n" : "THAI CHARACTER CHO CHOE", "h" : "0E0C" },
{"g" : "\u0E0D", "n" : "THAI CHARACTER YO YING", "h" : "0E0D" },
{"g" : "\u0E0E", "n" : "THAI CHARACTER DO CHADA", "h" : "0E0E" },
{"g" : "\u0E0F", "n" : "THAI CHARACTER TO PATAK", "h" : "0E0F" },
{"g" : "\u0E10", "n" : "THAI CHARACTER THO THAN", "h" : "0E10" },
{"g" : "\u0E11", "n" : "THAI CHARACTER THO NANGMONTHO", "h" : "0E11" },
{"g" : "\u0E12", "n" : "THAI CHARACTER THO PHUTHAO", "h" : "0E12" },
{"g" : "\u0E13", "n" : "THAI CHARACTER NO NEN", "h" : "0E13" },
{"g" : "\u0E14", "n" : "THAI CHARACTER DO DEK", "h" : "0E14" },
{"g" : "\u0E15", "n" : "THAI CHARACTER TO TAO", "h" : "0E15" },
{"g" : "\u0E16", "n" : "THAI CHARACTER THO THUNG", "h" : "0E16" },
{"g" : "\u0E17", "n" : "THAI CHARACTER THO THAHAN", "h" : "0E17" },
{"g" : "\u0E18", "n" : "THAI CHARACTER THO THONG", "h" : "0E18" },
{"g" : "\u0E19", "n" : "THAI CHARACTER NO NU", "h" : "0E19" },
{"g" : "\u0E1A", "n" : "THAI CHARACTER BO BAIMAI", "h" : "0E1A" },
{"g" : "\u0E1B", "n" : "THAI CHARACTER PO PLA", "h" : "0E1B" },
{"g" : "\u0E1C", "n" : "THAI CHARACTER PHO PHUNG", "h" : "0E1C" },
{"g" : "\u0E1D", "n" : "THAI CHARACTER FO FA", "h" : "0E1D" },
{"g" : "\u0E1E", "n" : "THAI CHARACTER PHO PHAN", "h" : "0E1E" },
{"g" : "\u0E1F", "n" : "THAI CHARACTER FO FAN", "h" : "0E1F" },
{"g" : "\u0E20", "n" : "THAI CHARACTER PHO SAMPHAO", "h" : "0E20" },
{"g" : "\u0E21", "n" : "THAI CHARACTER MO MA", "h" : "0E21" },
{"g" : "\u0E22", "n" : "THAI CHARACTER YO YAK", "h" : "0E22" },
{"g" : "\u0E23", "n" : "THAI CHARACTER RO RUA", "h" : "0E23" },
{"g" : "\u0E24", "n" : "THAI CHARACTER RU", "h" : "0E24" },
{"g" : "\u0E25", "n" : "THAI CHARACTER LO LING", "h" : "0E25" },
{"g" : "\u0E26", "n" : "THAI CHARACTER LU", "h" : "0E26" },
{"g" : "\u0E27", "n" : "THAI CHARACTER WO WAEN", "h" : "0E27" },
{"g" : "\u0E28", "n" : "THAI CHARACTER SO SALA", "h" : "0E28" },
{"g" : "\u0E29", "n" : "THAI CHARACTER SO RUSI", "h" : "0E29" },
{"g" : "\u0E2A", "n" : "THAI CHARACTER SO SUA", "h" : "0E2A" },
{"g" : "\u0E2B", "n" : "THAI CHARACTER HO HIP", "h" : "0E2B" },
{"g" : "\u0E2C", "n" : "THAI CHARACTER LO CHULA", "h" : "0E2C" },
{"g" : "\u0E2D", "n" : "THAI CHARACTER O ANG", "h" : "0E2D" },
{"g" : "\u0E2E", "n" : "THAI CHARACTER HO NOKHUK", "h" : "0E2E" },
{"g" : "\u0E2F", "n" : "THAI CHARACTER PAIYANNOI", "h" : "0E2F" },
{"g" : "\u0E30", "n" : "THAI CHARACTER SARA A", "h" : "0E30" },
{"g" : "\u0E31", "n" : "THAI CHARACTER MAI HAN-AKAT", "h" : "0E31" },
{"g" : "\u0E32", "n" : "THAI CHARACTER SARA AA", "h" : "0E32" },
{"g" : "\u0E33", "n" : "THAI CHARACTER SARA AM", "h" : "0E33" },
{"g" : "\u0E34", "n" : "THAI CHARACTER SARA I", "h" : "0E34" },
{"g" : "\u0E35", "n" : "THAI CHARACTER SARA II", "h" : "0E35" },
{"g" : "\u0E36", "n" : "THAI CHARACTER SARA UE", "h" : "0E36" },
{"g" : "\u0E37", "n" : "THAI CHARACTER SARA UEE", "h" : "0E37" },
{"g" : "\u0E38", "n" : "THAI CHARACTER SARA U", "h" : "0E38" },
{"g" : "\u0E39", "n" : "THAI CHARACTER SARA UU", "h" : "0E39" },
{"g" : "\u0E3A", "n" : "THAI CHARACTER PHINTHU", "h" : "0E3A" },

{"g" : "\u0E3F", "n" : "THAI CURRENCY SYMBOL BAHT", "h" : "0E3F" },
{"g" : "\u0E40", "n" : "THAI CHARACTER SARA E", "h" : "0E40" },
{"g" : "\u0E41", "n" : "THAI CHARACTER SARA AE", "h" : "0E41" },
{"g" : "\u0E42", "n" : "THAI CHARACTER SARA O", "h" : "0E42" },
{"g" : "\u0E43", "n" : "THAI CHARACTER SARA AI MAIMUAN", "h" : "0E43" },
{"g" : "\u0E44", "n" : "THAI CHARACTER SARA AI MAIMALAI", "h" : "0E44" },
{"g" : "\u0E45", "n" : "THAI CHARACTER LAKKHANGYAO", "h" : "0E45" },
{"g" : "\u0E46", "n" : "THAI CHARACTER MAIYAMOK", "h" : "0E46" },
{"g" : "\u0E47", "n" : "THAI CHARACTER MAITAIKHU", "h" : "0E47" },
{"g" : "\u0E48", "n" : "THAI CHARACTER MAI EK", "h" : "0E48" },
{"g" : "\u0E49", "n" : "THAI CHARACTER MAI THO", "h" : "0E49" },
{"g" : "\u0E4A", "n" : "THAI CHARACTER MAI TRI", "h" : "0E4A" },
{"g" : "\u0E4B", "n" : "THAI CHARACTER MAI CHATTAWA", "h" : "0E4B" },
{"g" : "\u0E4C", "n" : "THAI CHARACTER THANTHAKHAT", "h" : "0E4C" },
{"g" : "\u0E4D", "n" : "THAI CHARACTER NIKHAHIT", "h" : "0E4D" },
{"g" : "\u0E4E", "n" : "THAI CHARACTER YAMAKKAN", "h" : "0E4E" },
{"g" : "\u0E4F", "n" : "THAI CHARACTER FONGMAN", "h" : "0E4F" },
{"g" : "\u0E50", "n" : "THAI DIGIT ZERO", "h" : "0E50" },
{"g" : "\u0E51", "n" : "THAI DIGIT ONE", "h" : "0E51" },
{"g" : "\u0E52", "n" : "THAI DIGIT TWO", "h" : "0E52" },
{"g" : "\u0E53", "n" : "THAI DIGIT THREE", "h" : "0E53" },
{"g" : "\u0E54", "n" : "THAI DIGIT FOUR", "h" : "0E54" },
{"g" : "\u0E55", "n" : "THAI DIGIT FIVE", "h" : "0E55" },
{"g" : "\u0E56", "n" : "THAI DIGIT SIX", "h" : "0E56" },
{"g" : "\u0E57", "n" : "THAI DIGIT SEVEN", "h" : "0E57" },
{"g" : "\u0E58", "n" : "THAI DIGIT EIGHT", "h" : "0E58" },
{"g" : "\u0E59", "n" : "THAI DIGIT NINE", "h" : "0E59" },
{"g" : "\u0E5A", "n" : "THAI CHARACTER ANGKHANKHU", "h" : "0E5A" },
{"g" : "\u0E5B", "n" : "THAI CHARACTER KHOMUT", "h" : "0E5B" },

{"g" : "\u0E81", "n" : "LAO LETTER KO", "h" : "0E81" },
{"g" : "\u0E82", "n" : "LAO LETTER KHO SUNG", "h" : "0E82" },

{"g" : "\u0E84", "n" : "LAO LETTER KHO TAM", "h" : "0E84" },

{"g" : "\u0E86", "n" : "LAO LETTER PALI GHA", "h" : "0E86" },
{"g" : "\u0E87", "n" : "LAO LETTER NGO", "h" : "0E87" },
{"g" : "\u0E88", "n" : "LAO LETTER CO", "h" : "0E88" },
{"g" : "\u0E89", "n" : "LAO LETTER PALI CHA", "h" : "0E89" },
{"g" : "\u0E8A", "n" : "LAO LETTER SO TAM", "h" : "0E8A" },

{"g" : "\u0E8C", "n" : "LAO LETTER PALI JHA", "h" : "0E8C" },
{"g" : "\u0E8D", "n" : "LAO LETTER NYO", "h" : "0E8D" },
{"g" : "\u0E8E", "n" : "LAO LETTER PALI NYA", "h" : "0E8E" },
{"g" : "\u0E8F", "n" : "LAO LETTER PALI TTA", "h" : "0E8F" },
{"g" : "\u0E90", "n" : "LAO LETTER PALI TTHA", "h" : "0E90" },
{"g" : "\u0E91", "n" : "LAO LETTER PALI DDA", "h" : "0E91" },
{"g" : "\u0E92", "n" : "LAO LETTER PALI DDHA", "h" : "0E92" },
{"g" : "\u0E93", "n" : "LAO LETTER PALI NNA", "h" : "0E93" },
{"g" : "\u0E94", "n" : "LAO LETTER DO", "h" : "0E94" },
{"g" : "\u0E95", "n" : "LAO LETTER TO", "h" : "0E95" },
{"g" : "\u0E96", "n" : "LAO LETTER THO SUNG", "h" : "0E96" },
{"g" : "\u0E97", "n" : "LAO LETTER THO TAM", "h" : "0E97" },
{"g" : "\u0E98", "n" : "LAO LETTER PALI DHA", "h" : "0E98" },
{"g" : "\u0E99", "n" : "LAO LETTER NO", "h" : "0E99" },
{"g" : "\u0E9A", "n" : "LAO LETTER BO", "h" : "0E9A" },
{"g" : "\u0E9B", "n" : "LAO LETTER PO", "h" : "0E9B" },
{"g" : "\u0E9C", "n" : "LAO LETTER PHO SUNG", "h" : "0E9C" },
{"g" : "\u0E9D", "n" : "LAO LETTER FO TAM", "h" : "0E9D" },
{"g" : "\u0E9E", "n" : "LAO LETTER PHO TAM", "h" : "0E9E" },
{"g" : "\u0E9F", "n" : "LAO LETTER FO SUNG", "h" : "0E9F" },
{"g" : "\u0EA0", "n" : "LAO LETTER PALI BHA", "h" : "0EA0" },
{"g" : "\u0EA1", "n" : "LAO LETTER MO", "h" : "0EA1" },
{"g" : "\u0EA2", "n" : "LAO LETTER YO", "h" : "0EA2" },
{"g" : "\u0EA3", "n" : "LAO LETTER LO LING", "h" : "0EA3" },

{"g" : "\u0EA5", "n" : "LAO LETTER LO LOOT", "h" : "0EA5" },

{"g" : "\u0EA7", "n" : "LAO LETTER WO", "h" : "0EA7" },
{"g" : "\u0EA8", "n" : "LAO LETTER SANSKRIT SHA", "h" : "0EA8" },
{"g" : "\u0EA9", "n" : "LAO LETTER SANSKRIT SSA", "h" : "0EA9" },
{"g" : "\u0EAA", "n" : "LAO LETTER SO SUNG", "h" : "0EAA" },
{"g" : "\u0EAB", "n" : "LAO LETTER HO SUNG", "h" : "0EAB" },
{"g" : "\u0EAC", "n" : "LAO LETTER PALI LLA", "h" : "0EAC" },
{"g" : "\u0EAD", "n" : "LAO LETTER O", "h" : "0EAD" },
{"g" : "\u0EAE", "n" : "LAO LETTER HO TAM", "h" : "0EAE" },
{"g" : "\u0EAF", "n" : "LAO ELLIPSIS", "h" : "0EAF" },
{"g" : "\u0EB0", "n" : "LAO VOWEL SIGN A", "h" : "0EB0" },
{"g" : "\u0EB1", "n" : "LAO VOWEL SIGN MAI KAN", "h" : "0EB1" },
{"g" : "\u0EB2", "n" : "LAO VOWEL SIGN AA", "h" : "0EB2" },
{"g" : "\u0EB3", "n" : "LAO VOWEL SIGN AM", "h" : "0EB3" },
{"g" : "\u0EB4", "n" : "LAO VOWEL SIGN I", "h" : "0EB4" },
{"g" : "\u0EB5", "n" : "LAO VOWEL SIGN II", "h" : "0EB5" },
{"g" : "\u0EB6", "n" : "LAO VOWEL SIGN Y", "h" : "0EB6" },
{"g" : "\u0EB7", "n" : "LAO VOWEL SIGN YY", "h" : "0EB7" },
{"g" : "\u0EB8", "n" : "LAO VOWEL SIGN U", "h" : "0EB8" },
{"g" : "\u0EB9", "n" : "LAO VOWEL SIGN UU", "h" : "0EB9" },
{"g" : "\u0EBA", "n" : "LAO SIGN PALI VIRAMA", "h" : "0EBA" },
{"g" : "\u0EBB", "n" : "LAO VOWEL SIGN MAI KON", "h" : "0EBB" },
{"g" : "\u0EBC", "n" : "LAO SEMIVOWEL SIGN LO", "h" : "0EBC" },
{"g" : "\u0EBD", "n" : "LAO SEMIVOWEL SIGN NYO", "h" : "0EBD" },

{"g" : "\u0EC0", "n" : "LAO VOWEL SIGN E", "h" : "0EC0" },
{"g" : "\u0EC1", "n" : "LAO VOWEL SIGN EI", "h" : "0EC1" },
{"g" : "\u0EC2", "n" : "LAO VOWEL SIGN O", "h" : "0EC2" },
{"g" : "\u0EC3", "n" : "LAO VOWEL SIGN AY", "h" : "0EC3" },
{"g" : "\u0EC4", "n" : "LAO VOWEL SIGN AI", "h" : "0EC4" },

{"g" : "\u0EC6", "n" : "LAO KO LA", "h" : "0EC6" },

{"g" : "\u0EC8", "n" : "LAO TONE MAI EK", "h" : "0EC8" },
{"g" : "\u0EC9", "n" : "LAO TONE MAI THO", "h" : "0EC9" },
{"g" : "\u0ECA", "n" : "LAO TONE MAI TI", "h" : "0ECA" },
{"g" : "\u0ECB", "n" : "LAO TONE MAI CATAWA", "h" : "0ECB" },
{"g" : "\u0ECC", "n" : "LAO CANCELLATION MARK", "h" : "0ECC" },
{"g" : "\u0ECD", "n" : "LAO NIGGAHITA", "h" : "0ECD" },

{"g" : "\u0ED0", "n" : "LAO DIGIT ZERO", "h" : "0ED0" },
{"g" : "\u0ED1", "n" : "LAO DIGIT ONE", "h" : "0ED1" },
{"g" : "\u0ED2", "n" : "LAO DIGIT TWO", "h" : "0ED2" },
{"g" : "\u0ED3", "n" : "LAO DIGIT THREE", "h" : "0ED3" },
{"g" : "\u0ED4", "n" : "LAO DIGIT FOUR", "h" : "0ED4" },
{"g" : "\u0ED5", "n" : "LAO DIGIT FIVE", "h" : "0ED5" },
{"g" : "\u0ED6", "n" : "LAO DIGIT SIX", "h" : "0ED6" },
{"g" : "\u0ED7", "n" : "LAO DIGIT SEVEN", "h" : "0ED7" },
{"g" : "\u0ED8", "n" : "LAO DIGIT EIGHT", "h" : "0ED8" },
{"g" : "\u0ED9", "n" : "LAO DIGIT NINE", "h" : "0ED9" },

{"g" : "\u0EDC", "n" : "LAO HO NO", "h" : "0EDC" },
{"g" : "\u0EDD", "n" : "LAO HO MO", "h" : "0EDD" },
{"g" : "\u0EDE", "n" : "LAO LETTER KHMU GO", "h" : "0EDE" },
{"g" : "\u0EDF", "n" : "LAO LETTER KHMU NYO", "h" : "0EDF" },

{"g" : "\u1000", "n" : "MYANMAR LETTER KA", "h" : "1000" },
{"g" : "\u1001", "n" : "MYANMAR LETTER KHA", "h" : "1001" },
{"g" : "\u1002", "n" : "MYANMAR LETTER GA", "h" : "1002" },
{"g" : "\u1003", "n" : "MYANMAR LETTER GHA", "h" : "1003" },
{"g" : "\u1004", "n" : "MYANMAR LETTER NGA", "h" : "1004" },
{"g" : "\u1005", "n" : "MYANMAR LETTER CA", "h" : "1005" },
{"g" : "\u1006", "n" : "MYANMAR LETTER CHA", "h" : "1006" },
{"g" : "\u1007", "n" : "MYANMAR LETTER JA", "h" : "1007" },
{"g" : "\u1008", "n" : "MYANMAR LETTER JHA", "h" : "1008" },
{"g" : "\u1009", "n" : "MYANMAR LETTER NYA", "h" : "1009" },
{"g" : "\u100A", "n" : "MYANMAR LETTER NNYA", "h" : "100A" },
{"g" : "\u100B", "n" : "MYANMAR LETTER TTA", "h" : "100B" },
{"g" : "\u100C", "n" : "MYANMAR LETTER TTHA", "h" : "100C" },
{"g" : "\u100D", "n" : "MYANMAR LETTER DDA", "h" : "100D" },
{"g" : "\u100E", "n" : "MYANMAR LETTER DDHA", "h" : "100E" },
{"g" : "\u100F", "n" : "MYANMAR LETTER NNA", "h" : "100F" },
{"g" : "\u1010", "n" : "MYANMAR LETTER TA", "h" : "1010" },
{"g" : "\u1011", "n" : "MYANMAR LETTER THA", "h" : "1011" },
{"g" : "\u1012", "n" : "MYANMAR LETTER DA", "h" : "1012" },
{"g" : "\u1013", "n" : "MYANMAR LETTER DHA", "h" : "1013" },
{"g" : "\u1014", "n" : "MYANMAR LETTER NA", "h" : "1014" },
{"g" : "\u1015", "n" : "MYANMAR LETTER PA", "h" : "1015" },
{"g" : "\u1016", "n" : "MYANMAR LETTER PHA", "h" : "1016" },
{"g" : "\u1017", "n" : "MYANMAR LETTER BA", "h" : "1017" },
{"g" : "\u1018", "n" : "MYANMAR LETTER BHA", "h" : "1018" },
{"g" : "\u1019", "n" : "MYANMAR LETTER MA", "h" : "1019" },
{"g" : "\u101A", "n" : "MYANMAR LETTER YA", "h" : "101A" },
{"g" : "\u101B", "n" : "MYANMAR LETTER RA", "h" : "101B" },
{"g" : "\u101C", "n" : "MYANMAR LETTER LA", "h" : "101C" },
{"g" : "\u101D", "n" : "MYANMAR LETTER WA", "h" : "101D" },
{"g" : "\u101E", "n" : "MYANMAR LETTER SA", "h" : "101E" },
{"g" : "\u101F", "n" : "MYANMAR LETTER HA", "h" : "101F" },
{"g" : "\u1020", "n" : "MYANMAR LETTER LLA", "h" : "1020" },
{"g" : "\u1021", "n" : "MYANMAR LETTER A", "h" : "1021" },
{"g" : "\u1022", "n" : "MYANMAR LETTER SHAN A", "h" : "1022" },
{"g" : "\u1023", "n" : "MYANMAR LETTER I", "h" : "1023" },
{"g" : "\u1024", "n" : "MYANMAR LETTER II", "h" : "1024" },
{"g" : "\u1025", "n" : "MYANMAR LETTER U", "h" : "1025" },
{"g" : "\u1026", "n" : "MYANMAR LETTER UU", "h" : "1026" },
{"g" : "\u1027", "n" : "MYANMAR LETTER E", "h" : "1027" },
{"g" : "\u1028", "n" : "MYANMAR LETTER MON E", "h" : "1028" },
{"g" : "\u1029", "n" : "MYANMAR LETTER O", "h" : "1029" },
{"g" : "\u102A", "n" : "MYANMAR LETTER AU", "h" : "102A" },
{"g" : "\u102B", "n" : "MYANMAR VOWEL SIGN TALL AA", "h" : "102B" },
{"g" : "\u102C", "n" : "MYANMAR VOWEL SIGN AA", "h" : "102C" },
{"g" : "\u102D", "n" : "MYANMAR VOWEL SIGN I", "h" : "102D" },
{"g" : "\u102E", "n" : "MYANMAR VOWEL SIGN II", "h" : "102E" },
{"g" : "\u102F", "n" : "MYANMAR VOWEL SIGN U", "h" : "102F" },
{"g" : "\u1030", "n" : "MYANMAR VOWEL SIGN UU", "h" : "1030" },
{"g" : "\u1031", "n" : "MYANMAR VOWEL SIGN E", "h" : "1031" },
{"g" : "\u1032", "n" : "MYANMAR VOWEL SIGN AI", "h" : "1032" },
{"g" : "\u1033", "n" : "MYANMAR VOWEL SIGN MON II", "h" : "1033" },
{"g" : "\u1034", "n" : "MYANMAR VOWEL SIGN MON O", "h" : "1034" },
{"g" : "\u1035", "n" : "MYANMAR VOWEL SIGN E ABOVE", "h" : "1035" },
{"g" : "\u1036", "n" : "MYANMAR SIGN ANUSVARA", "h" : "1036" },
{"g" : "\u1037", "n" : "MYANMAR SIGN DOT BELOW", "h" : "1037" },
{"g" : "\u1038", "n" : "MYANMAR SIGN VISARGA", "h" : "1038" },
{"g" : "\u1039", "n" : "MYANMAR SIGN VIRAMA", "h" : "1039" },
{"g" : "\u103A", "n" : "MYANMAR SIGN ASAT", "h" : "103A" },
{"g" : "\u103B", "n" : "MYANMAR CONSONANT SIGN MEDIAL YA", "h" : "103B" },
{"g" : "\u103C", "n" : "MYANMAR CONSONANT SIGN MEDIAL RA", "h" : "103C" },
{"g" : "\u103D", "n" : "MYANMAR CONSONANT SIGN MEDIAL WA", "h" : "103D" },
{"g" : "\u103E", "n" : "MYANMAR CONSONANT SIGN MEDIAL HA", "h" : "103E" },
{"g" : "\u103F", "n" : "MYANMAR LETTER GREAT SA", "h" : "103F" },
{"g" : "\u1040", "n" : "MYANMAR DIGIT ZERO", "h" : "1040" },
{"g" : "\u1041", "n" : "MYANMAR DIGIT ONE", "h" : "1041" },
{"g" : "\u1042", "n" : "MYANMAR DIGIT TWO", "h" : "1042" },
{"g" : "\u1043", "n" : "MYANMAR DIGIT THREE", "h" : "1043" },
{"g" : "\u1044", "n" : "MYANMAR DIGIT FOUR", "h" : "1044" },
{"g" : "\u1045", "n" : "MYANMAR DIGIT FIVE", "h" : "1045" },
{"g" : "\u1046", "n" : "MYANMAR DIGIT SIX", "h" : "1046" },
{"g" : "\u1047", "n" : "MYANMAR DIGIT SEVEN", "h" : "1047" },
{"g" : "\u1048", "n" : "MYANMAR DIGIT EIGHT", "h" : "1048" },
{"g" : "\u1049", "n" : "MYANMAR DIGIT NINE", "h" : "1049" },
{"g" : "\u104A", "n" : "MYANMAR SIGN LITTLE SECTION", "h" : "104A" },
{"g" : "\u104B", "n" : "MYANMAR SIGN SECTION", "h" : "104B" },
{"g" : "\u104C", "n" : "MYANMAR SYMBOL LOCATIVE", "h" : "104C" },
{"g" : "\u104D", "n" : "MYANMAR SYMBOL COMPLETED", "h" : "104D" },
{"g" : "\u104E", "n" : "MYANMAR SYMBOL AFOREMENTIONED", "h" : "104E" },
{"g" : "\u104F", "n" : "MYANMAR SYMBOL GENITIVE", "h" : "104F" },
{"g" : "\u1050", "n" : "MYANMAR LETTER SHA", "h" : "1050" },
{"g" : "\u1051", "n" : "MYANMAR LETTER SSA", "h" : "1051" },
{"g" : "\u1052", "n" : "MYANMAR LETTER VOCALIC R", "h" : "1052" },
{"g" : "\u1053", "n" : "MYANMAR LETTER VOCALIC RR", "h" : "1053" },
{"g" : "\u1054", "n" : "MYANMAR LETTER VOCALIC L", "h" : "1054" },
{"g" : "\u1055", "n" : "MYANMAR LETTER VOCALIC LL", "h" : "1055" },
{"g" : "\u1056", "n" : "MYANMAR VOWEL SIGN VOCALIC R", "h" : "1056" },
{"g" : "\u1057", "n" : "MYANMAR VOWEL SIGN VOCALIC RR", "h" : "1057" },
{"g" : "\u1058", "n" : "MYANMAR VOWEL SIGN VOCALIC L", "h" : "1058" },
{"g" : "\u1059", "n" : "MYANMAR VOWEL SIGN VOCALIC LL", "h" : "1059" },
{"g" : "\u105A", "n" : "MYANMAR LETTER MON NGA", "h" : "105A" },
{"g" : "\u105B", "n" : "MYANMAR LETTER MON JHA", "h" : "105B" },
{"g" : "\u105C", "n" : "MYANMAR LETTER MON BBA", "h" : "105C" },
{"g" : "\u105D", "n" : "MYANMAR LETTER MON BBE", "h" : "105D" },
{"g" : "\u105E", "n" : "MYANMAR CONSONANT SIGN MON MEDIAL NA", "h" : "105E" },
{"g" : "\u105F", "n" : "MYANMAR CONSONANT SIGN MON MEDIAL MA", "h" : "105F" },
{"g" : "\u1060", "n" : "MYANMAR CONSONANT SIGN MON MEDIAL LA", "h" : "1060" },
{"g" : "\u1061", "n" : "MYANMAR LETTER SGAW KAREN SHA", "h" : "1061" },
{"g" : "\u1062", "n" : "MYANMAR VOWEL SIGN SGAW KAREN EU", "h" : "1062" },
{"g" : "\u1063", "n" : "MYANMAR TONE MARK SGAW KAREN HATHI", "h" : "1063" },
{"g" : "\u1064", "n" : "MYANMAR TONE MARK SGAW KAREN KE PHO", "h" : "1064" },
{"g" : "\u1065", "n" : "MYANMAR LETTER WESTERN PWO KAREN THA", "h" : "1065" },
{"g" : "\u1066", "n" : "MYANMAR LETTER WESTERN PWO KAREN PWA", "h" : "1066" },
{"g" : "\u1067", "n" : "MYANMAR VOWEL SIGN WESTERN PWO KAREN EU", "h" : "1067" },
{"g" : "\u1068", "n" : "MYANMAR VOWEL SIGN WESTERN PWO KAREN UE", "h" : "1068" },
{"g" : "\u1069", "n" : "MYANMAR SIGN WESTERN PWO KAREN TONE-1", "h" : "1069" },
{"g" : "\u106A", "n" : "MYANMAR SIGN WESTERN PWO KAREN TONE-2", "h" : "106A" },
{"g" : "\u106B", "n" : "MYANMAR SIGN WESTERN PWO KAREN TONE-3", "h" : "106B" },
{"g" : "\u106C", "n" : "MYANMAR SIGN WESTERN PWO KAREN TONE-4", "h" : "106C" },
{"g" : "\u106D", "n" : "MYANMAR SIGN WESTERN PWO KAREN TONE-5", "h" : "106D" },
{"g" : "\u106E", "n" : "MYANMAR LETTER EASTERN PWO KAREN NNA", "h" : "106E" },
{"g" : "\u106F", "n" : "MYANMAR LETTER EASTERN PWO KAREN YWA", "h" : "106F" },
{"g" : "\u1070", "n" : "MYANMAR LETTER EASTERN PWO KAREN GHWA", "h" : "1070" },
{"g" : "\u1071", "n" : "MYANMAR VOWEL SIGN GEBA KAREN I", "h" : "1071" },
{"g" : "\u1072", "n" : "MYANMAR VOWEL SIGN KAYAH OE", "h" : "1072" },
{"g" : "\u1073", "n" : "MYANMAR VOWEL SIGN KAYAH U", "h" : "1073" },
{"g" : "\u1074", "n" : "MYANMAR VOWEL SIGN KAYAH EE", "h" : "1074" },
{"g" : "\u1075", "n" : "MYANMAR LETTER SHAN KA", "h" : "1075" },
{"g" : "\u1076", "n" : "MYANMAR LETTER SHAN KHA", "h" : "1076" },
{"g" : "\u1077", "n" : "MYANMAR LETTER SHAN GA", "h" : "1077" },
{"g" : "\u1078", "n" : "MYANMAR LETTER SHAN CA", "h" : "1078" },
{"g" : "\u1079", "n" : "MYANMAR LETTER SHAN ZA", "h" : "1079" },
{"g" : "\u107A", "n" : "MYANMAR LETTER SHAN NYA", "h" : "107A" },
{"g" : "\u107B", "n" : "MYANMAR LETTER SHAN DA", "h" : "107B" },
{"g" : "\u107C", "n" : "MYANMAR LETTER SHAN NA", "h" : "107C" },
{"g" : "\u107D", "n" : "MYANMAR LETTER SHAN PHA", "h" : "107D" },
{"g" : "\u107E", "n" : "MYANMAR LETTER SHAN FA", "h" : "107E" },
{"g" : "\u107F", "n" : "MYANMAR LETTER SHAN BA", "h" : "107F" },
{"g" : "\u1080", "n" : "MYANMAR LETTER SHAN THA", "h" : "1080" },
{"g" : "\u1081", "n" : "MYANMAR LETTER SHAN HA", "h" : "1081" },
{"g" : "\u1082", "n" : "MYANMAR CONSONANT SIGN SHAN MEDIAL WA", "h" : "1082" },
{"g" : "\u1083", "n" : "MYANMAR VOWEL SIGN SHAN AA", "h" : "1083" },
{"g" : "\u1084", "n" : "MYANMAR VOWEL SIGN SHAN E", "h" : "1084" },
{"g" : "\u1085", "n" : "MYANMAR VOWEL SIGN SHAN E ABOVE", "h" : "1085" },
{"g" : "\u1086", "n" : "MYANMAR VOWEL SIGN SHAN FINAL Y", "h" : "1086" },
{"g" : "\u1087", "n" : "MYANMAR SIGN SHAN TONE-2", "h" : "1087" },
{"g" : "\u1088", "n" : "MYANMAR SIGN SHAN TONE-3", "h" : "1088" },
{"g" : "\u1089", "n" : "MYANMAR SIGN SHAN TONE-5", "h" : "1089" },
{"g" : "\u108A", "n" : "MYANMAR SIGN SHAN TONE-6", "h" : "108A" },
{"g" : "\u108B", "n" : "MYANMAR SIGN SHAN COUNCIL TONE-2", "h" : "108B" },
{"g" : "\u108C", "n" : "MYANMAR SIGN SHAN COUNCIL TONE-3", "h" : "108C" },
{"g" : "\u108D", "n" : "MYANMAR SIGN SHAN COUNCIL EMPHATIC TONE", "h" : "108D" },
{"g" : "\u108E", "n" : "MYANMAR LETTER RUMAI PALAUNG FA", "h" : "108E" },
{"g" : "\u108F", "n" : "MYANMAR SIGN RUMAI PALAUNG TONE-5", "h" : "108F" },
{"g" : "\u1090", "n" : "MYANMAR SHAN DIGIT ZERO", "h" : "1090" },
{"g" : "\u1091", "n" : "MYANMAR SHAN DIGIT ONE", "h" : "1091" },
{"g" : "\u1092", "n" : "MYANMAR SHAN DIGIT TWO", "h" : "1092" },
{"g" : "\u1093", "n" : "MYANMAR SHAN DIGIT THREE", "h" : "1093" },
{"g" : "\u1094", "n" : "MYANMAR SHAN DIGIT FOUR", "h" : "1094" },
{"g" : "\u1095", "n" : "MYANMAR SHAN DIGIT FIVE", "h" : "1095" },
{"g" : "\u1096", "n" : "MYANMAR SHAN DIGIT SIX", "h" : "1096" },
{"g" : "\u1097", "n" : "MYANMAR SHAN DIGIT SEVEN", "h" : "1097" },
{"g" : "\u1098", "n" : "MYANMAR SHAN DIGIT EIGHT", "h" : "1098" },
{"g" : "\u1099", "n" : "MYANMAR SHAN DIGIT NINE", "h" : "1099" },
{"g" : "\u109A", "n" : "MYANMAR SIGN KHAMTI TONE-1", "h" : "109A" },
{"g" : "\u109B", "n" : "MYANMAR SIGN KHAMTI TONE-3", "h" : "109B" },
{"g" : "\u109C", "n" : "MYANMAR VOWEL SIGN AITON A", "h" : "109C" },
{"g" : "\u109D", "n" : "MYANMAR VOWEL SIGN AITON AI", "h" : "109D" },
{"g" : "\u109E", "n" : "MYANMAR SYMBOL SHAN ONE", "h" : "109E" },
{"g" : "\u109F", "n" : "MYANMAR SYMBOL SHAN EXCLAMATION", "h" : "109F" },

{"g" : "\u1780", "n" : "KHMER LETTER KA", "h" : "1780" },
{"g" : "\u1781", "n" : "KHMER LETTER KHA", "h" : "1781" },
{"g" : "\u1782", "n" : "KHMER LETTER KO", "h" : "1782" },
{"g" : "\u1783", "n" : "KHMER LETTER KHO", "h" : "1783" },
{"g" : "\u1784", "n" : "KHMER LETTER NGO", "h" : "1784" },
{"g" : "\u1785", "n" : "KHMER LETTER CA", "h" : "1785" },
{"g" : "\u1786", "n" : "KHMER LETTER CHA", "h" : "1786" },
{"g" : "\u1787", "n" : "KHMER LETTER CO", "h" : "1787" },
{"g" : "\u1788", "n" : "KHMER LETTER CHO", "h" : "1788" },
{"g" : "\u1789", "n" : "KHMER LETTER NYO", "h" : "1789" },
{"g" : "\u178A", "n" : "KHMER LETTER DA", "h" : "178A" },
{"g" : "\u178B", "n" : "KHMER LETTER TTHA", "h" : "178B" },
{"g" : "\u178C", "n" : "KHMER LETTER DO", "h" : "178C" },
{"g" : "\u178D", "n" : "KHMER LETTER TTHO", "h" : "178D" },
{"g" : "\u178E", "n" : "KHMER LETTER NNO", "h" : "178E" },
{"g" : "\u178F", "n" : "KHMER LETTER TA", "h" : "178F" },
{"g" : "\u1790", "n" : "KHMER LETTER THA", "h" : "1790" },
{"g" : "\u1791", "n" : "KHMER LETTER TO", "h" : "1791" },
{"g" : "\u1792", "n" : "KHMER LETTER THO", "h" : "1792" },
{"g" : "\u1793", "n" : "KHMER LETTER NO", "h" : "1793" },
{"g" : "\u1794", "n" : "KHMER LETTER BA", "h" : "1794" },
{"g" : "\u1795", "n" : "KHMER LETTER PHA", "h" : "1795" },
{"g" : "\u1796", "n" : "KHMER LETTER PO", "h" : "1796" },
{"g" : "\u1797", "n" : "KHMER LETTER PHO", "h" : "1797" },
{"g" : "\u1798", "n" : "KHMER LETTER MO", "h" : "1798" },
{"g" : "\u1799", "n" : "KHMER LETTER YO", "h" : "1799" },
{"g" : "\u179A", "n" : "KHMER LETTER RO", "h" : "179A" },
{"g" : "\u179B", "n" : "KHMER LETTER LO", "h" : "179B" },
{"g" : "\u179C", "n" : "KHMER LETTER VO", "h" : "179C" },
{"g" : "\u179D", "n" : "KHMER LETTER SHA", "h" : "179D" },
{"g" : "\u179E", "n" : "KHMER LETTER SSO", "h" : "179E" },
{"g" : "\u179F", "n" : "KHMER LETTER SA", "h" : "179F" },
{"g" : "\u17A0", "n" : "KHMER LETTER HA", "h" : "17A0" },
{"g" : "\u17A1", "n" : "KHMER LETTER LA", "h" : "17A1" },
{"g" : "\u17A2", "n" : "KHMER LETTER QA", "h" : "17A2" },
{"g" : "\u17A3", "n" : "KHMER INDEPENDENT VOWEL QAQ", "h" : "17A3" },
{"g" : "\u17A4", "n" : "KHMER INDEPENDENT VOWEL QAA", "h" : "17A4" },
{"g" : "\u17A5", "n" : "KHMER INDEPENDENT VOWEL QI", "h" : "17A5" },
{"g" : "\u17A6", "n" : "KHMER INDEPENDENT VOWEL QII", "h" : "17A6" },
{"g" : "\u17A7", "n" : "KHMER INDEPENDENT VOWEL QU", "h" : "17A7" },
{"g" : "\u17A8", "n" : "KHMER INDEPENDENT VOWEL QUK", "h" : "17A8" },
{"g" : "\u17A9", "n" : "KHMER INDEPENDENT VOWEL QUU", "h" : "17A9" },
{"g" : "\u17AA", "n" : "KHMER INDEPENDENT VOWEL QUUV", "h" : "17AA" },
{"g" : "\u17AB", "n" : "KHMER INDEPENDENT VOWEL RY", "h" : "17AB" },
{"g" : "\u17AC", "n" : "KHMER INDEPENDENT VOWEL RYY", "h" : "17AC" },
{"g" : "\u17AD", "n" : "KHMER INDEPENDENT VOWEL LY", "h" : "17AD" },
{"g" : "\u17AE", "n" : "KHMER INDEPENDENT VOWEL LYY", "h" : "17AE" },
{"g" : "\u17AF", "n" : "KHMER INDEPENDENT VOWEL QE", "h" : "17AF" },
{"g" : "\u17B0", "n" : "KHMER INDEPENDENT VOWEL QAI", "h" : "17B0" },
{"g" : "\u17B1", "n" : "KHMER INDEPENDENT VOWEL QOO TYPE ONE", "h" : "17B1" },
{"g" : "\u17B2", "n" : "KHMER INDEPENDENT VOWEL QOO TYPE TWO", "h" : "17B2" },
{"g" : "\u17B3", "n" : "KHMER INDEPENDENT VOWEL QAU", "h" : "17B3" },
{"g" : "\u17B4", "n" : "KHMER VOWEL INHERENT AQ", "h" : "17B4" },
{"g" : "\u17B5", "n" : "KHMER VOWEL INHERENT AA", "h" : "17B5" },
{"g" : "\u17B6", "n" : "KHMER VOWEL SIGN AA", "h" : "17B6" },
{"g" : "\u17B7", "n" : "KHMER VOWEL SIGN I", "h" : "17B7" },
{"g" : "\u17B8", "n" : "KHMER VOWEL SIGN II", "h" : "17B8" },
{"g" : "\u17B9", "n" : "KHMER VOWEL SIGN Y", "h" : "17B9" },
{"g" : "\u17BA", "n" : "KHMER VOWEL SIGN YY", "h" : "17BA" },
{"g" : "\u17BB", "n" : "KHMER VOWEL SIGN U", "h" : "17BB" },
{"g" : "\u17BC", "n" : "KHMER VOWEL SIGN UU", "h" : "17BC" },
{"g" : "\u17BD", "n" : "KHMER VOWEL SIGN UA", "h" : "17BD" },
{"g" : "\u17BE", "n" : "KHMER VOWEL SIGN OE", "h" : "17BE" },
{"g" : "\u17BF", "n" : "KHMER VOWEL SIGN YA", "h" : "17BF" },
{"g" : "\u17C0", "n" : "KHMER VOWEL SIGN IE", "h" : "17C0" },
{"g" : "\u17C1", "n" : "KHMER VOWEL SIGN E", "h" : "17C1" },
{"g" : "\u17C2", "n" : "KHMER VOWEL SIGN AE", "h" : "17C2" },
{"g" : "\u17C3", "n" : "KHMER VOWEL SIGN AI", "h" : "17C3" },
{"g" : "\u17C4", "n" : "KHMER VOWEL SIGN OO", "h" : "17C4" },
{"g" : "\u17C5", "n" : "KHMER VOWEL SIGN AU", "h" : "17C5" },
{"g" : "\u17C6", "n" : "KHMER SIGN NIKAHIT", "h" : "17C6" },
{"g" : "\u17C7", "n" : "KHMER SIGN REAHMUK", "h" : "17C7" },
{"g" : "\u17C8", "n" : "KHMER SIGN YUUKALEAPINTU", "h" : "17C8" },
{"g" : "\u17C9", "n" : "KHMER SIGN MUUSIKATOAN", "h" : "17C9" },
{"g" : "\u17CA", "n" : "KHMER SIGN TRIISAP", "h" : "17CA" },
{"g" : "\u17CB", "n" : "KHMER SIGN BANTOC", "h" : "17CB" },
{"g" : "\u17CC", "n" : "KHMER SIGN ROBAT", "h" : "17CC" },
{"g" : "\u17CD", "n" : "KHMER SIGN TOANDAKHIAT", "h" : "17CD" },
{"g" : "\u17CE", "n" : "KHMER SIGN KAKABAT", "h" : "17CE" },
{"g" : "\u17CF", "n" : "KHMER SIGN AHSDA", "h" : "17CF" },
{"g" : "\u17D0", "n" : "KHMER SIGN SAMYOK SANNYA", "h" : "17D0" },
{"g" : "\u17D1", "n" : "KHMER SIGN VIRIAM", "h" : "17D1" },
{"g" : "\u17D2", "n" : "KHMER SIGN COENG", "h" : "17D2" },
{"g" : "\u17D3", "n" : "KHMER SIGN BATHAMASAT", "h" : "17D3" },
{"g" : "\u17D4", "n" : "KHMER SIGN KHAN", "h" : "17D4" },
{"g" : "\u17D5", "n" : "KHMER SIGN BARIYOOSAN", "h" : "17D5" },
{"g" : "\u17D6", "n" : "KHMER SIGN CAMNUC PII KUUH", "h" : "17D6" },
{"g" : "\u17D7", "n" : "KHMER SIGN LEK TOO", "h" : "17D7" },
{"g" : "\u17D8", "n" : "KHMER SIGN BEYYAL", "h" : "17D8" },
{"g" : "\u17D9", "n" : "KHMER SIGN PHNAEK MUAN", "h" : "17D9" },
{"g" : "\u17DA", "n" : "KHMER SIGN KOOMUUT", "h" : "17DA" },
{"g" : "\u17DB", "n" : "KHMER CURRENCY SYMBOL RIEL", "h" : "17DB" },
{"g" : "\u17DC", "n" : "KHMER SIGN AVAKRAHASANYA", "h" : "17DC" },
{"g" : "\u17DD", "n" : "KHMER SIGN ATTHACAN", "h" : "17DD" },

{"g" : "\u17E0", "n" : "KHMER DIGIT ZERO", "h" : "17E0" },
{"g" : "\u17E1", "n" : "KHMER DIGIT ONE", "h" : "17E1" },
{"g" : "\u17E2", "n" : "KHMER DIGIT TWO", "h" : "17E2" },
{"g" : "\u17E3", "n" : "KHMER DIGIT THREE", "h" : "17E3" },
{"g" : "\u17E4", "n" : "KHMER DIGIT FOUR", "h" : "17E4" },
{"g" : "\u17E5", "n" : "KHMER DIGIT FIVE", "h" : "17E5" },
{"g" : "\u17E6", "n" : "KHMER DIGIT SIX", "h" : "17E6" },
{"g" : "\u17E7", "n" : "KHMER DIGIT SEVEN", "h" : "17E7" },
{"g" : "\u17E8", "n" : "KHMER DIGIT EIGHT", "h" : "17E8" },
{"g" : "\u17E9", "n" : "KHMER DIGIT NINE", "h" : "17E9" },

{"g" : "\u17F0", "n" : "KHMER SYMBOL LEK ATTAK SON", "h" : "17F0" },
{"g" : "\u17F1", "n" : "KHMER SYMBOL LEK ATTAK MUOY", "h" : "17F1" },
{"g" : "\u17F2", "n" : "KHMER SYMBOL LEK ATTAK PII", "h" : "17F2" },
{"g" : "\u17F3", "n" : "KHMER SYMBOL LEK ATTAK BEI", "h" : "17F3" },
{"g" : "\u17F4", "n" : "KHMER SYMBOL LEK ATTAK BUON", "h" : "17F4" },
{"g" : "\u17F5", "n" : "KHMER SYMBOL LEK ATTAK PRAM", "h" : "17F5" },
{"g" : "\u17F6", "n" : "KHMER SYMBOL LEK ATTAK PRAM-MUOY", "h" : "17F6" },
{"g" : "\u17F7", "n" : "KHMER SYMBOL LEK ATTAK PRAM-PII", "h" : "17F7" },
{"g" : "\u17F8", "n" : "KHMER SYMBOL LEK ATTAK PRAM-BEI", "h" : "17F8" },
{"g" : "\u17F9", "n" : "KHMER SYMBOL LEK ATTAK PRAM-BUON", "h" : "17F9" },

{"g" : "\u1950", "n" : "TAI LE LETTER KA", "h" : "1950" },
{"g" : "\u1951", "n" : "TAI LE LETTER XA", "h" : "1951" },
{"g" : "\u1952", "n" : "TAI LE LETTER NGA", "h" : "1952" },
{"g" : "\u1953", "n" : "TAI LE LETTER TSA", "h" : "1953" },
{"g" : "\u1954", "n" : "TAI LE LETTER SA", "h" : "1954" },
{"g" : "\u1955", "n" : "TAI LE LETTER YA", "h" : "1955" },
{"g" : "\u1956", "n" : "TAI LE LETTER TA", "h" : "1956" },
{"g" : "\u1957", "n" : "TAI LE LETTER THA", "h" : "1957" },
{"g" : "\u1958", "n" : "TAI LE LETTER LA", "h" : "1958" },
{"g" : "\u1959", "n" : "TAI LE LETTER PA", "h" : "1959" },
{"g" : "\u195A", "n" : "TAI LE LETTER PHA", "h" : "195A" },
{"g" : "\u195B", "n" : "TAI LE LETTER MA", "h" : "195B" },
{"g" : "\u195C", "n" : "TAI LE LETTER FA", "h" : "195C" },
{"g" : "\u195D", "n" : "TAI LE LETTER VA", "h" : "195D" },
{"g" : "\u195E", "n" : "TAI LE LETTER HA", "h" : "195E" },
{"g" : "\u195F", "n" : "TAI LE LETTER QA", "h" : "195F" },
{"g" : "\u1960", "n" : "TAI LE LETTER KHA", "h" : "1960" },
{"g" : "\u1961", "n" : "TAI LE LETTER TSHA", "h" : "1961" },
{"g" : "\u1962", "n" : "TAI LE LETTER NA", "h" : "1962" },
{"g" : "\u1963", "n" : "TAI LE LETTER A", "h" : "1963" },
{"g" : "\u1964", "n" : "TAI LE LETTER I", "h" : "1964" },
{"g" : "\u1965", "n" : "TAI LE LETTER EE", "h" : "1965" },
{"g" : "\u1966", "n" : "TAI LE LETTER EH", "h" : "1966" },
{"g" : "\u1967", "n" : "TAI LE LETTER U", "h" : "1967" },
{"g" : "\u1968", "n" : "TAI LE LETTER OO", "h" : "1968" },
{"g" : "\u1969", "n" : "TAI LE LETTER O", "h" : "1969" },
{"g" : "\u196A", "n" : "TAI LE LETTER UE", "h" : "196A" },
{"g" : "\u196B", "n" : "TAI LE LETTER E", "h" : "196B" },
{"g" : "\u196C", "n" : "TAI LE LETTER AUE", "h" : "196C" },
{"g" : "\u196D", "n" : "TAI LE LETTER AI", "h" : "196D" },

{"g" : "\u1970", "n" : "TAI LE LETTER TONE-2", "h" : "1970" },
{"g" : "\u1971", "n" : "TAI LE LETTER TONE-3", "h" : "1971" },
{"g" : "\u1972", "n" : "TAI LE LETTER TONE-4", "h" : "1972" },
{"g" : "\u1973", "n" : "TAI LE LETTER TONE-5", "h" : "1973" },
{"g" : "\u1974", "n" : "TAI LE LETTER TONE-6", "h" : "1974" },

{"g" : "\u1980", "n" : "NEW TAI LUE LETTER HIGH QA", "h" : "1980" },
{"g" : "\u1981", "n" : "NEW TAI LUE LETTER LOW QA", "h" : "1981" },
{"g" : "\u1982", "n" : "NEW TAI LUE LETTER HIGH KA", "h" : "1982" },
{"g" : "\u1983", "n" : "NEW TAI LUE LETTER HIGH XA", "h" : "1983" },
{"g" : "\u1984", "n" : "NEW TAI LUE LETTER HIGH NGA", "h" : "1984" },
{"g" : "\u1985", "n" : "NEW TAI LUE LETTER LOW KA", "h" : "1985" },
{"g" : "\u1986", "n" : "NEW TAI LUE LETTER LOW XA", "h" : "1986" },
{"g" : "\u1987", "n" : "NEW TAI LUE LETTER LOW NGA", "h" : "1987" },
{"g" : "\u1988", "n" : "NEW TAI LUE LETTER HIGH TSA", "h" : "1988" },
{"g" : "\u1989", "n" : "NEW TAI LUE LETTER HIGH SA", "h" : "1989" },
{"g" : "\u198A", "n" : "NEW TAI LUE LETTER HIGH YA", "h" : "198A" },
{"g" : "\u198B", "n" : "NEW TAI LUE LETTER LOW TSA", "h" : "198B" },
{"g" : "\u198C", "n" : "NEW TAI LUE LETTER LOW SA", "h" : "198C" },
{"g" : "\u198D", "n" : "NEW TAI LUE LETTER LOW YA", "h" : "198D" },
{"g" : "\u198E", "n" : "NEW TAI LUE LETTER HIGH TA", "h" : "198E" },
{"g" : "\u198F", "n" : "NEW TAI LUE LETTER HIGH THA", "h" : "198F" },
{"g" : "\u1990", "n" : "NEW TAI LUE LETTER HIGH NA", "h" : "1990" },
{"g" : "\u1991", "n" : "NEW TAI LUE LETTER LOW TA", "h" : "1991" },
{"g" : "\u1992", "n" : "NEW TAI LUE LETTER LOW THA", "h" : "1992" },
{"g" : "\u1993", "n" : "NEW TAI LUE LETTER LOW NA", "h" : "1993" },
{"g" : "\u1994", "n" : "NEW TAI LUE LETTER HIGH PA", "h" : "1994" },
{"g" : "\u1995", "n" : "NEW TAI LUE LETTER HIGH PHA", "h" : "1995" },
{"g" : "\u1996", "n" : "NEW TAI LUE LETTER HIGH MA", "h" : "1996" },
{"g" : "\u1997", "n" : "NEW TAI LUE LETTER LOW PA", "h" : "1997" },
{"g" : "\u1998", "n" : "NEW TAI LUE LETTER LOW PHA", "h" : "1998" },
{"g" : "\u1999", "n" : "NEW TAI LUE LETTER LOW MA", "h" : "1999" },
{"g" : "\u199A", "n" : "NEW TAI LUE LETTER HIGH FA", "h" : "199A" },
{"g" : "\u199B", "n" : "NEW TAI LUE LETTER HIGH VA", "h" : "199B" },
{"g" : "\u199C", "n" : "NEW TAI LUE LETTER HIGH LA", "h" : "199C" },
{"g" : "\u199D", "n" : "NEW TAI LUE LETTER LOW FA", "h" : "199D" },
{"g" : "\u199E", "n" : "NEW TAI LUE LETTER LOW VA", "h" : "199E" },
{"g" : "\u199F", "n" : "NEW TAI LUE LETTER LOW LA", "h" : "199F" },
{"g" : "\u19A0", "n" : "NEW TAI LUE LETTER HIGH HA", "h" : "19A0" },
{"g" : "\u19A1", "n" : "NEW TAI LUE LETTER HIGH DA", "h" : "19A1" },
{"g" : "\u19A2", "n" : "NEW TAI LUE LETTER HIGH BA", "h" : "19A2" },
{"g" : "\u19A3", "n" : "NEW TAI LUE LETTER LOW HA", "h" : "19A3" },
{"g" : "\u19A4", "n" : "NEW TAI LUE LETTER LOW DA", "h" : "19A4" },
{"g" : "\u19A5", "n" : "NEW TAI LUE LETTER LOW BA", "h" : "19A5" },
{"g" : "\u19A6", "n" : "NEW TAI LUE LETTER HIGH KVA", "h" : "19A6" },
{"g" : "\u19A7", "n" : "NEW TAI LUE LETTER HIGH XVA", "h" : "19A7" },
{"g" : "\u19A8", "n" : "NEW TAI LUE LETTER LOW KVA", "h" : "19A8" },
{"g" : "\u19A9", "n" : "NEW TAI LUE LETTER LOW XVA", "h" : "19A9" },
{"g" : "\u19AA", "n" : "NEW TAI LUE LETTER HIGH SUA", "h" : "19AA" },
{"g" : "\u19AB", "n" : "NEW TAI LUE LETTER LOW SUA", "h" : "19AB" },

{"g" : "\u19B0", "n" : "NEW TAI LUE VOWEL SIGN VOWEL SHORTENER", "h" : "19B0" },
{"g" : "\u19B1", "n" : "NEW TAI LUE VOWEL SIGN AA", "h" : "19B1" },
{"g" : "\u19B2", "n" : "NEW TAI LUE VOWEL SIGN II", "h" : "19B2" },
{"g" : "\u19B3", "n" : "NEW TAI LUE VOWEL SIGN U", "h" : "19B3" },
{"g" : "\u19B4", "n" : "NEW TAI LUE VOWEL SIGN UU", "h" : "19B4" },
{"g" : "\u19B5", "n" : "NEW TAI LUE VOWEL SIGN E", "h" : "19B5" },
{"g" : "\u19B6", "n" : "NEW TAI LUE VOWEL SIGN AE", "h" : "19B6" },
{"g" : "\u19B7", "n" : "NEW TAI LUE VOWEL SIGN O", "h" : "19B7" },
{"g" : "\u19B8", "n" : "NEW TAI LUE VOWEL SIGN OA", "h" : "19B8" },
{"g" : "\u19B9", "n" : "NEW TAI LUE VOWEL SIGN UE", "h" : "19B9" },
{"g" : "\u19BA", "n" : "NEW TAI LUE VOWEL SIGN AY", "h" : "19BA" },
{"g" : "\u19BB", "n" : "NEW TAI LUE VOWEL SIGN AAY", "h" : "19BB" },
{"g" : "\u19BC", "n" : "NEW TAI LUE VOWEL SIGN UY", "h" : "19BC" },
{"g" : "\u19BD", "n" : "NEW TAI LUE VOWEL SIGN OY", "h" : "19BD" },
{"g" : "\u19BE", "n" : "NEW TAI LUE VOWEL SIGN OAY", "h" : "19BE" },
{"g" : "\u19BF", "n" : "NEW TAI LUE VOWEL SIGN UEY", "h" : "19BF" },
{"g" : "\u19C0", "n" : "NEW TAI LUE VOWEL SIGN IY", "h" : "19C0" },
{"g" : "\u19C1", "n" : "NEW TAI LUE LETTER FINAL V", "h" : "19C1" },
{"g" : "\u19C2", "n" : "NEW TAI LUE LETTER FINAL NG", "h" : "19C2" },
{"g" : "\u19C3", "n" : "NEW TAI LUE LETTER FINAL N", "h" : "19C3" },
{"g" : "\u19C4", "n" : "NEW TAI LUE LETTER FINAL M", "h" : "19C4" },
{"g" : "\u19C5", "n" : "NEW TAI LUE LETTER FINAL K", "h" : "19C5" },
{"g" : "\u19C6", "n" : "NEW TAI LUE LETTER FINAL D", "h" : "19C6" },
{"g" : "\u19C7", "n" : "NEW TAI LUE LETTER FINAL B", "h" : "19C7" },
{"g" : "\u19C8", "n" : "NEW TAI LUE TONE MARK-1", "h" : "19C8" },
{"g" : "\u19C9", "n" : "NEW TAI LUE TONE MARK-2", "h" : "19C9" },

{"g" : "\u19D0", "n" : "NEW TAI LUE DIGIT ZERO", "h" : "19D0" },
{"g" : "\u19D1", "n" : "NEW TAI LUE DIGIT ONE", "h" : "19D1" },
{"g" : "\u19D2", "n" : "NEW TAI LUE DIGIT TWO", "h" : "19D2" },
{"g" : "\u19D3", "n" : "NEW TAI LUE DIGIT THREE", "h" : "19D3" },
{"g" : "\u19D4", "n" : "NEW TAI LUE DIGIT FOUR", "h" : "19D4" },
{"g" : "\u19D5", "n" : "NEW TAI LUE DIGIT FIVE", "h" : "19D5" },
{"g" : "\u19D6", "n" : "NEW TAI LUE DIGIT SIX", "h" : "19D6" },
{"g" : "\u19D7", "n" : "NEW TAI LUE DIGIT SEVEN", "h" : "19D7" },
{"g" : "\u19D8", "n" : "NEW TAI LUE DIGIT EIGHT", "h" : "19D8" },
{"g" : "\u19D9", "n" : "NEW TAI LUE DIGIT NINE", "h" : "19D9" },
{"g" : "\u19DA", "n" : "NEW TAI LUE THAM DIGIT ONE", "h" : "19DA" },

{"g" : "\u19DE", "n" : "NEW TAI LUE SIGN LAE", "h" : "19DE" },
{"g" : "\u19DF", "n" : "NEW TAI LUE SIGN LAEV", "h" : "19DF" },

{"g" : "\u19E0", "n" : "KHMER SYMBOL PATHAMASAT", "h" : "19E0" },
{"g" : "\u19E1", "n" : "KHMER SYMBOL MUOY KOET", "h" : "19E1" },
{"g" : "\u19E2", "n" : "KHMER SYMBOL PII KOET", "h" : "19E2" },
{"g" : "\u19E3", "n" : "KHMER SYMBOL BEI KOET", "h" : "19E3" },
{"g" : "\u19E4", "n" : "KHMER SYMBOL BUON KOET", "h" : "19E4" },
{"g" : "\u19E5", "n" : "KHMER SYMBOL PRAM KOET", "h" : "19E5" },
{"g" : "\u19E6", "n" : "KHMER SYMBOL PRAM-MUOY KOET", "h" : "19E6" },
{"g" : "\u19E7", "n" : "KHMER SYMBOL PRAM-PII KOET", "h" : "19E7" },
{"g" : "\u19E8", "n" : "KHMER SYMBOL PRAM-BEI KOET", "h" : "19E8" },
{"g" : "\u19E9", "n" : "KHMER SYMBOL PRAM-BUON KOET", "h" : "19E9" },
{"g" : "\u19EA", "n" : "KHMER SYMBOL DAP KOET", "h" : "19EA" },
{"g" : "\u19EB", "n" : "KHMER SYMBOL DAP-MUOY KOET", "h" : "19EB" },
{"g" : "\u19EC", "n" : "KHMER SYMBOL DAP-PII KOET", "h" : "19EC" },
{"g" : "\u19ED", "n" : "KHMER SYMBOL DAP-BEI KOET", "h" : "19ED" },
{"g" : "\u19EE", "n" : "KHMER SYMBOL DAP-BUON KOET", "h" : "19EE" },
{"g" : "\u19EF", "n" : "KHMER SYMBOL DAP-PRAM KOET", "h" : "19EF" },
{"g" : "\u19F0", "n" : "KHMER SYMBOL TUTEYASAT", "h" : "19F0" },
{"g" : "\u19F1", "n" : "KHMER SYMBOL MUOY ROC", "h" : "19F1" },
{"g" : "\u19F2", "n" : "KHMER SYMBOL PII ROC", "h" : "19F2" },
{"g" : "\u19F3", "n" : "KHMER SYMBOL BEI ROC", "h" : "19F3" },
{"g" : "\u19F4", "n" : "KHMER SYMBOL BUON ROC", "h" : "19F4" },
{"g" : "\u19F5", "n" : "KHMER SYMBOL PRAM ROC", "h" : "19F5" },
{"g" : "\u19F6", "n" : "KHMER SYMBOL PRAM-MUOY ROC", "h" : "19F6" },
{"g" : "\u19F7", "n" : "KHMER SYMBOL PRAM-PII ROC", "h" : "19F7" },
{"g" : "\u19F8", "n" : "KHMER SYMBOL PRAM-BEI ROC", "h" : "19F8" },
{"g" : "\u19F9", "n" : "KHMER SYMBOL PRAM-BUON ROC", "h" : "19F9" },
{"g" : "\u19FA", "n" : "KHMER SYMBOL DAP ROC", "h" : "19FA" },
{"g" : "\u19FB", "n" : "KHMER SYMBOL DAP-MUOY ROC", "h" : "19FB" },
{"g" : "\u19FC", "n" : "KHMER SYMBOL DAP-PII ROC", "h" : "19FC" },
{"g" : "\u19FD", "n" : "KHMER SYMBOL DAP-BEI ROC", "h" : "19FD" },
{"g" : "\u19FE", "n" : "KHMER SYMBOL DAP-BUON ROC", "h" : "19FE" },
{"g" : "\u19FF", "n" : "KHMER SYMBOL DAP-PRAM ROC", "h" : "19FF" },

{"g" : "\u1A20", "n" : "TAI THAM LETTER HIGH KA", "h" : "1A20" },
{"g" : "\u1A21", "n" : "TAI THAM LETTER HIGH KHA", "h" : "1A21" },
{"g" : "\u1A22", "n" : "TAI THAM LETTER HIGH KXA", "h" : "1A22" },
{"g" : "\u1A23", "n" : "TAI THAM LETTER LOW KA", "h" : "1A23" },
{"g" : "\u1A24", "n" : "TAI THAM LETTER LOW KXA", "h" : "1A24" },
{"g" : "\u1A25", "n" : "TAI THAM LETTER LOW KHA", "h" : "1A25" },
{"g" : "\u1A26", "n" : "TAI THAM LETTER NGA", "h" : "1A26" },
{"g" : "\u1A27", "n" : "TAI THAM LETTER HIGH CA", "h" : "1A27" },
{"g" : "\u1A28", "n" : "TAI THAM LETTER HIGH CHA", "h" : "1A28" },
{"g" : "\u1A29", "n" : "TAI THAM LETTER LOW CA", "h" : "1A29" },
{"g" : "\u1A2A", "n" : "TAI THAM LETTER LOW SA", "h" : "1A2A" },
{"g" : "\u1A2B", "n" : "TAI THAM LETTER LOW CHA", "h" : "1A2B" },
{"g" : "\u1A2C", "n" : "TAI THAM LETTER NYA", "h" : "1A2C" },
{"g" : "\u1A2D", "n" : "TAI THAM LETTER RATA", "h" : "1A2D" },
{"g" : "\u1A2E", "n" : "TAI THAM LETTER HIGH RATHA", "h" : "1A2E" },
{"g" : "\u1A2F", "n" : "TAI THAM LETTER DA", "h" : "1A2F" },
{"g" : "\u1A30", "n" : "TAI THAM LETTER LOW RATHA", "h" : "1A30" },
{"g" : "\u1A31", "n" : "TAI THAM LETTER RANA", "h" : "1A31" },
{"g" : "\u1A32", "n" : "TAI THAM LETTER HIGH TA", "h" : "1A32" },
{"g" : "\u1A33", "n" : "TAI THAM LETTER HIGH THA", "h" : "1A33" },
{"g" : "\u1A34", "n" : "TAI THAM LETTER LOW TA", "h" : "1A34" },
{"g" : "\u1A35", "n" : "TAI THAM LETTER LOW THA", "h" : "1A35" },
{"g" : "\u1A36", "n" : "TAI THAM LETTER NA", "h" : "1A36" },
{"g" : "\u1A37", "n" : "TAI THAM LETTER BA", "h" : "1A37" },
{"g" : "\u1A38", "n" : "TAI THAM LETTER HIGH PA", "h" : "1A38" },
{"g" : "\u1A39", "n" : "TAI THAM LETTER HIGH PHA", "h" : "1A39" },
{"g" : "\u1A3A", "n" : "TAI THAM LETTER HIGH FA", "h" : "1A3A" },
{"g" : "\u1A3B", "n" : "TAI THAM LETTER LOW PA", "h" : "1A3B" },
{"g" : "\u1A3C", "n" : "TAI THAM LETTER LOW FA", "h" : "1A3C" },
{"g" : "\u1A3D", "n" : "TAI THAM LETTER LOW PHA", "h" : "1A3D" },
{"g" : "\u1A3E", "n" : "TAI THAM LETTER MA", "h" : "1A3E" },
{"g" : "\u1A3F", "n" : "TAI THAM LETTER LOW YA", "h" : "1A3F" },
{"g" : "\u1A40", "n" : "TAI THAM LETTER HIGH YA", "h" : "1A40" },
{"g" : "\u1A41", "n" : "TAI THAM LETTER RA", "h" : "1A41" },
{"g" : "\u1A42", "n" : "TAI THAM LETTER RUE", "h" : "1A42" },
{"g" : "\u1A43", "n" : "TAI THAM LETTER LA", "h" : "1A43" },
{"g" : "\u1A44", "n" : "TAI THAM LETTER LUE", "h" : "1A44" },
{"g" : "\u1A45", "n" : "TAI THAM LETTER WA", "h" : "1A45" },
{"g" : "\u1A46", "n" : "TAI THAM LETTER HIGH SHA", "h" : "1A46" },
{"g" : "\u1A47", "n" : "TAI THAM LETTER HIGH SSA", "h" : "1A47" },
{"g" : "\u1A48", "n" : "TAI THAM LETTER HIGH SA", "h" : "1A48" },
{"g" : "\u1A49", "n" : "TAI THAM LETTER HIGH HA", "h" : "1A49" },
{"g" : "\u1A4A", "n" : "TAI THAM LETTER LLA", "h" : "1A4A" },
{"g" : "\u1A4B", "n" : "TAI THAM LETTER A", "h" : "1A4B" },
{"g" : "\u1A4C", "n" : "TAI THAM LETTER LOW HA", "h" : "1A4C" },
{"g" : "\u1A4D", "n" : "TAI THAM LETTER I", "h" : "1A4D" },
{"g" : "\u1A4E", "n" : "TAI THAM LETTER II", "h" : "1A4E" },
{"g" : "\u1A4F", "n" : "TAI THAM LETTER U", "h" : "1A4F" },
{"g" : "\u1A50", "n" : "TAI THAM LETTER UU", "h" : "1A50" },
{"g" : "\u1A51", "n" : "TAI THAM LETTER EE", "h" : "1A51" },
{"g" : "\u1A52", "n" : "TAI THAM LETTER OO", "h" : "1A52" },
{"g" : "\u1A53", "n" : "TAI THAM LETTER LAE", "h" : "1A53" },
{"g" : "\u1A54", "n" : "TAI THAM LETTER GREAT SA", "h" : "1A54" },
{"g" : "\u1A55", "n" : "TAI THAM CONSONANT SIGN MEDIAL RA", "h" : "1A55" },
{"g" : "\u1A56", "n" : "TAI THAM CONSONANT SIGN MEDIAL LA", "h" : "1A56" },
{"g" : "\u1A57", "n" : "TAI THAM CONSONANT SIGN LA TANG LAI", "h" : "1A57" },
{"g" : "\u1A58", "n" : "TAI THAM SIGN MAI KANG LAI", "h" : "1A58" },
{"g" : "\u1A59", "n" : "TAI THAM CONSONANT SIGN FINAL NGA", "h" : "1A59" },
{"g" : "\u1A5A", "n" : "TAI THAM CONSONANT SIGN LOW PA", "h" : "1A5A" },
{"g" : "\u1A5B", "n" : "TAI THAM CONSONANT SIGN HIGH RATHA OR LOW PA", "h" : "1A5B" },
{"g" : "\u1A5C", "n" : "TAI THAM CONSONANT SIGN MA", "h" : "1A5C" },
{"g" : "\u1A5D", "n" : "TAI THAM CONSONANT SIGN BA", "h" : "1A5D" },
{"g" : "\u1A5E", "n" : "TAI THAM CONSONANT SIGN SA", "h" : "1A5E" },

{"g" : "\u1A60", "n" : "TAI THAM SIGN SAKOT", "h" : "1A60" },
{"g" : "\u1A61", "n" : "TAI THAM VOWEL SIGN A", "h" : "1A61" },
{"g" : "\u1A62", "n" : "TAI THAM VOWEL SIGN MAI SAT", "h" : "1A62" },
{"g" : "\u1A63", "n" : "TAI THAM VOWEL SIGN AA", "h" : "1A63" },
{"g" : "\u1A64", "n" : "TAI THAM VOWEL SIGN TALL AA", "h" : "1A64" },
{"g" : "\u1A65", "n" : "TAI THAM VOWEL SIGN I", "h" : "1A65" },
{"g" : "\u1A66", "n" : "TAI THAM VOWEL SIGN II", "h" : "1A66" },
{"g" : "\u1A67", "n" : "TAI THAM VOWEL SIGN UE", "h" : "1A67" },
{"g" : "\u1A68", "n" : "TAI THAM VOWEL SIGN UUE", "h" : "1A68" },
{"g" : "\u1A69", "n" : "TAI THAM VOWEL SIGN U", "h" : "1A69" },
{"g" : "\u1A6A", "n" : "TAI THAM VOWEL SIGN UU", "h" : "1A6A" },
{"g" : "\u1A6B", "n" : "TAI THAM VOWEL SIGN O", "h" : "1A6B" },
{"g" : "\u1A6C", "n" : "TAI THAM VOWEL SIGN OA BELOW", "h" : "1A6C" },
{"g" : "\u1A6D", "n" : "TAI THAM VOWEL SIGN OY", "h" : "1A6D" },
{"g" : "\u1A6E", "n" : "TAI THAM VOWEL SIGN E", "h" : "1A6E" },
{"g" : "\u1A6F", "n" : "TAI THAM VOWEL SIGN AE", "h" : "1A6F" },
{"g" : "\u1A70", "n" : "TAI THAM VOWEL SIGN OO", "h" : "1A70" },
{"g" : "\u1A71", "n" : "TAI THAM VOWEL SIGN AI", "h" : "1A71" },
{"g" : "\u1A72", "n" : "TAI THAM VOWEL SIGN THAM AI", "h" : "1A72" },
{"g" : "\u1A73", "n" : "TAI THAM VOWEL SIGN OA ABOVE", "h" : "1A73" },
{"g" : "\u1A74", "n" : "TAI THAM SIGN MAI KANG", "h" : "1A74" },
{"g" : "\u1A75", "n" : "TAI THAM SIGN TONE-1", "h" : "1A75" },
{"g" : "\u1A76", "n" : "TAI THAM SIGN TONE-2", "h" : "1A76" },
{"g" : "\u1A77", "n" : "TAI THAM SIGN KHUEN TONE-3", "h" : "1A77" },
{"g" : "\u1A78", "n" : "TAI THAM SIGN KHUEN TONE-4", "h" : "1A78" },
{"g" : "\u1A79", "n" : "TAI THAM SIGN KHUEN TONE-5", "h" : "1A79" },
{"g" : "\u1A7A", "n" : "TAI THAM SIGN RA HAAM", "h" : "1A7A" },
{"g" : "\u1A7B", "n" : "TAI THAM SIGN MAI SAM", "h" : "1A7B" },
{"g" : "\u1A7C", "n" : "TAI THAM SIGN KHUEN-LUE KARAN", "h" : "1A7C" },

{"g" : "\u1A7F", "n" : "TAI THAM COMBINING CRYPTOGRAMMIC DOT", "h" : "1A7F" },
{"g" : "\u1A80", "n" : "TAI THAM HORA DIGIT ZERO", "h" : "1A80" },
{"g" : "\u1A81", "n" : "TAI THAM HORA DIGIT ONE", "h" : "1A81" },
{"g" : "\u1A82", "n" : "TAI THAM HORA DIGIT TWO", "h" : "1A82" },
{"g" : "\u1A83", "n" : "TAI THAM HORA DIGIT THREE", "h" : "1A83" },
{"g" : "\u1A84", "n" : "TAI THAM HORA DIGIT FOUR", "h" : "1A84" },
{"g" : "\u1A85", "n" : "TAI THAM HORA DIGIT FIVE", "h" : "1A85" },
{"g" : "\u1A86", "n" : "TAI THAM HORA DIGIT SIX", "h" : "1A86" },
{"g" : "\u1A87", "n" : "TAI THAM HORA DIGIT SEVEN", "h" : "1A87" },
{"g" : "\u1A88", "n" : "TAI THAM HORA DIGIT EIGHT", "h" : "1A88" },
{"g" : "\u1A89", "n" : "TAI THAM HORA DIGIT NINE", "h" : "1A89" },

{"g" : "\u1A90", "n" : "TAI THAM THAM DIGIT ZERO", "h" : "1A90" },
{"g" : "\u1A91", "n" : "TAI THAM THAM DIGIT ONE", "h" : "1A91" },
{"g" : "\u1A92", "n" : "TAI THAM THAM DIGIT TWO", "h" : "1A92" },
{"g" : "\u1A93", "n" : "TAI THAM THAM DIGIT THREE", "h" : "1A93" },
{"g" : "\u1A94", "n" : "TAI THAM THAM DIGIT FOUR", "h" : "1A94" },
{"g" : "\u1A95", "n" : "TAI THAM THAM DIGIT FIVE", "h" : "1A95" },
{"g" : "\u1A96", "n" : "TAI THAM THAM DIGIT SIX", "h" : "1A96" },
{"g" : "\u1A97", "n" : "TAI THAM THAM DIGIT SEVEN", "h" : "1A97" },
{"g" : "\u1A98", "n" : "TAI THAM THAM DIGIT EIGHT", "h" : "1A98" },
{"g" : "\u1A99", "n" : "TAI THAM THAM DIGIT NINE", "h" : "1A99" },

{"g" : "\u1AA0", "n" : "TAI THAM SIGN WIANG", "h" : "1AA0" },
{"g" : "\u1AA1", "n" : "TAI THAM SIGN WIANGWAAK", "h" : "1AA1" },
{"g" : "\u1AA2", "n" : "TAI THAM SIGN SAWAN", "h" : "1AA2" },
{"g" : "\u1AA3", "n" : "TAI THAM SIGN KEOW", "h" : "1AA3" },
{"g" : "\u1AA4", "n" : "TAI THAM SIGN HOY", "h" : "1AA4" },
{"g" : "\u1AA5", "n" : "TAI THAM SIGN DOKMAI", "h" : "1AA5" },
{"g" : "\u1AA6", "n" : "TAI THAM SIGN REVERSED ROTATED RANA", "h" : "1AA6" },
{"g" : "\u1AA7", "n" : "TAI THAM SIGN MAI YAMOK", "h" : "1AA7" },
{"g" : "\u1AA8", "n" : "TAI THAM SIGN KAAN", "h" : "1AA8" },
{"g" : "\u1AA9", "n" : "TAI THAM SIGN KAANKUU", "h" : "1AA9" },
{"g" : "\u1AAA", "n" : "TAI THAM SIGN SATKAAN", "h" : "1AAA" },
{"g" : "\u1AAB", "n" : "TAI THAM SIGN SATKAANKUU", "h" : "1AAB" },
{"g" : "\u1AAC", "n" : "TAI THAM SIGN HANG", "h" : "1AAC" },
{"g" : "\u1AAD", "n" : "TAI THAM SIGN CAANG", "h" : "1AAD" },

{"g" : "\uA900", "n" : "KAYAH LI DIGIT ZERO", "h" : "A900"},
{"g" : "\uA901", "n" : "KAYAH LI DIGIT ONE", "h" : "A901"},
{"g" : "\uA902", "n" : "KAYAH LI DIGIT TWO", "h" : "A902"},
{"g" : "\uA903", "n" : "KAYAH LI DIGIT THREE", "h" : "A903"},
{"g" : "\uA904", "n" : "KAYAH LI DIGIT FOUR", "h" : "A904"},
{"g" : "\uA905", "n" : "KAYAH LI DIGIT FIVE", "h" : "A905"},
{"g" : "\uA906", "n" : "KAYAH LI DIGIT SIX", "h" : "A906"},
{"g" : "\uA907", "n" : "KAYAH LI DIGIT SEVEN", "h" : "A907"},
{"g" : "\uA908", "n" : "KAYAH LI DIGIT EIGHT", "h" : "A908"},
{"g" : "\uA909", "n" : "KAYAH LI DIGIT NINE", "h" : "A909"},
{"g" : "\uA90A", "n" : "KAYAH LI LETTER KA", "h" : "A90A"},
{"g" : "\uA90B", "n" : "KAYAH LI LETTER KHA", "h" : "A90B"},
{"g" : "\uA90C", "n" : "KAYAH LI LETTER GA", "h" : "A90C"},
{"g" : "\uA90D", "n" : "KAYAH LI LETTER NGA", "h" : "A90D"},
{"g" : "\uA90E", "n" : "KAYAH LI LETTER SA", "h" : "A90E"},
{"g" : "\uA90F", "n" : "KAYAH LI LETTER SHA", "h" : "A90F"},
{"g" : "\uA910", "n" : "KAYAH LI LETTER ZA", "h" : "A910"},
{"g" : "\uA911", "n" : "KAYAH LI LETTER NYA", "h" : "A911"},
{"g" : "\uA912", "n" : "KAYAH LI LETTER TA", "h" : "A912"},
{"g" : "\uA913", "n" : "KAYAH LI LETTER HTA", "h" : "A913"},
{"g" : "\uA914", "n" : "KAYAH LI LETTER NA", "h" : "A914"},
{"g" : "\uA915", "n" : "KAYAH LI LETTER PA", "h" : "A915"},
{"g" : "\uA916", "n" : "KAYAH LI LETTER PHA", "h" : "A916"},
{"g" : "\uA917", "n" : "KAYAH LI LETTER MA", "h" : "A917"},
{"g" : "\uA918", "n" : "KAYAH LI LETTER DA", "h" : "A918"},
{"g" : "\uA919", "n" : "KAYAH LI LETTER BA", "h" : "A919"},
{"g" : "\uA91A", "n" : "KAYAH LI LETTER RA", "h" : "A91A"},
{"g" : "\uA91B", "n" : "KAYAH LI LETTER YA", "h" : "A91B"},
{"g" : "\uA91C", "n" : "KAYAH LI LETTER LA", "h" : "A91C"},
{"g" : "\uA91D", "n" : "KAYAH LI LETTER WA", "h" : "A91D"},
{"g" : "\uA91E", "n" : "KAYAH LI LETTER THA", "h" : "A91E"},
{"g" : "\uA91F", "n" : "KAYAH LI LETTER HA", "h" : "A91F"},
{"g" : "\uA920", "n" : "KAYAH LI LETTER VA", "h" : "A920"},
{"g" : "\uA921", "n" : "KAYAH LI LETTER CA", "h" : "A921"},
{"g" : "\uA922", "n" : "KAYAH LI LETTER A", "h" : "A922"},
{"g" : "\uA923", "n" : "KAYAH LI LETTER OE", "h" : "A923"},
{"g" : "\uA924", "n" : "KAYAH LI LETTER I", "h" : "A924"},
{"g" : "\uA925", "n" : "KAYAH LI LETTER OO", "h" : "A925"},
{"g" : "\uA926", "n" : "KAYAH LI VOWEL UE", "h" : "A926"},
{"g" : "\uA927", "n" : "KAYAH LI VOWEL E", "h" : "A927"},
{"g" : "\uA928", "n" : "KAYAH LI VOWEL U", "h" : "A928"},
{"g" : "\uA929", "n" : "KAYAH LI VOWEL EE", "h" : "A929"},
{"g" : "\uA92A", "n" : "KAYAH LI VOWEL O", "h" : "A92A"},
{"g" : "\uA92B", "n" : "KAYAH LI TONE PLOPHU", "h" : "A92B"},
{"g" : "\uA92C", "n" : "KAYAH LI TONE CALYA", "h" : "A92C"},
{"g" : "\uA92D", "n" : "KAYAH LI TONE CALYA PLOPHU", "h" : "A92D"},
{"g" : "\uA92E", "n" : "KAYAH LI SIGN CWI", "h" : "A92E"},
{"g" : "\uA92F", "n" : "KAYAH LI SIGN SHYA", "h" : "A92F"},

{"g" : "\uA9E0", "n" : "MYANMAR LETTER SHAN GHA", "h" : "A9E0"},
{"g" : "\uA9E1", "n" : "MYANMAR LETTER SHAN CHA", "h" : "A9E1"},
{"g" : "\uA9E2", "n" : "MYANMAR LETTER SHAN JHA", "h" : "A9E2"},
{"g" : "\uA9E3", "n" : "MYANMAR LETTER SHAN NNA", "h" : "A9E3"},
{"g" : "\uA9E4", "n" : "MYANMAR LETTER SHAN BHA", "h" : "A9E4"},
{"g" : "\uA9E5", "n" : "MYANMAR SIGN SHAN SAW", "h" : "A9E5"},
{"g" : "\uA9E6", "n" : "MYANMAR MODIFIER LETTER SHAN REDUPLICATION", "h" : "A9E6"},
{"g" : "\uA9E7", "n" : "MYANMAR LETTER TAI LAING NYA", "h" : "A9E7"},
{"g" : "\uA9E8", "n" : "MYANMAR LETTER TAI LAING FA", "h" : "A9E8"},
{"g" : "\uA9E9", "n" : "MYANMAR LETTER TAI LAING GA", "h" : "A9E9"},
{"g" : "\uA9EA", "n" : "MYANMAR LETTER TAI LAING GHA", "h" : "A9EA"},
{"g" : "\uA9EB", "n" : "MYANMAR LETTER TAI LAING JA", "h" : "A9EB"},
{"g" : "\uA9EC", "n" : "MYANMAR LETTER TAI LAING JHA", "h" : "A9EC"},
{"g" : "\uA9ED", "n" : "MYANMAR LETTER TAI LAING DDA", "h" : "A9ED"},
{"g" : "\uA9EE", "n" : "MYANMAR LETTER TAI LAING DDHA", "h" : "A9EE"},
{"g" : "\uA9EF", "n" : "MYANMAR LETTER TAI LAING NNA", "h" : "A9EF"},
{"g" : "\uA9F0", "n" : "MYANMAR TAI LAING DIGIT ZERO", "h" : "A9F0"},
{"g" : "\uA9F1", "n" : "MYANMAR TAI LAING DIGIT ONE", "h" : "A9F1"},
{"g" : "\uA9F2", "n" : "MYANMAR TAI LAING DIGIT TWO", "h" : "A9F2"},
{"g" : "\uA9F3", "n" : "MYANMAR TAI LAING DIGIT THREE", "h" : "A9F3"},
{"g" : "\uA9F4", "n" : "MYANMAR TAI LAING DIGIT FOUR", "h" : "A9F4"},
{"g" : "\uA9F5", "n" : "MYANMAR TAI LAING DIGIT FIVE", "h" : "A9F5"},
{"g" : "\uA9F6", "n" : "MYANMAR TAI LAING DIGIT SIX", "h" : "A9F6"},
{"g" : "\uA9F7", "n" : "MYANMAR TAI LAING DIGIT SEVEN", "h" : "A9F7"},
{"g" : "\uA9F8", "n" : "MYANMAR TAI LAING DIGIT EIGHT", "h" : "A9F8"},
{"g" : "\uA9F9", "n" : "MYANMAR TAI LAING DIGIT NINE", "h" : "A9F9"},
{"g" : "\uA9FA", "n" : "MYANMAR LETTER TAI LAING LLA", "h" : "A9FA"},
{"g" : "\uA9FB", "n" : "MYANMAR LETTER TAI LAING DA", "h" : "A9FB"},
{"g" : "\uA9FC", "n" : "MYANMAR LETTER TAI LAING DHA", "h" : "A9FC"},
{"g" : "\uA9FD", "n" : "MYANMAR LETTER TAI LAING BA", "h" : "A9FD"},
{"g" : "\uA9FE", "n" : "MYANMAR LETTER TAI LAING BHA", "h" : "A9FE"},

{"g" : "\uAA00", "n" : "CHAM LETTER A", "h" : "AA00"},
{"g" : "\uAA01", "n" : "CHAM LETTER I", "h" : "AA01"},
{"g" : "\uAA02", "n" : "CHAM LETTER U", "h" : "AA02"},
{"g" : "\uAA03", "n" : "CHAM LETTER E", "h" : "AA03"},
{"g" : "\uAA04", "n" : "CHAM LETTER AI", "h" : "AA04"},
{"g" : "\uAA05", "n" : "CHAM LETTER O", "h" : "AA05"},
{"g" : "\uAA06", "n" : "CHAM LETTER KA", "h" : "AA06"},
{"g" : "\uAA07", "n" : "CHAM LETTER KHA", "h" : "AA07"},
{"g" : "\uAA08", "n" : "CHAM LETTER GA", "h" : "AA08"},
{"g" : "\uAA09", "n" : "CHAM LETTER GHA", "h" : "AA09"},
{"g" : "\uAA0A", "n" : "CHAM LETTER NGUE", "h" : "AA0A"},
{"g" : "\uAA0B", "n" : "CHAM LETTER NGA", "h" : "AA0B"},
{"g" : "\uAA0C", "n" : "CHAM LETTER CHA", "h" : "AA0C"},
{"g" : "\uAA0D", "n" : "CHAM LETTER CHHA", "h" : "AA0D"},
{"g" : "\uAA0E", "n" : "CHAM LETTER JA", "h" : "AA0E"},
{"g" : "\uAA0F", "n" : "CHAM LETTER JHA", "h" : "AA0F"},
{"g" : "\uAA10", "n" : "CHAM LETTER NHUE", "h" : "AA10"},
{"g" : "\uAA11", "n" : "CHAM LETTER NHA", "h" : "AA11"},
{"g" : "\uAA12", "n" : "CHAM LETTER NHJA", "h" : "AA12"},
{"g" : "\uAA13", "n" : "CHAM LETTER TA", "h" : "AA13"},
{"g" : "\uAA14", "n" : "CHAM LETTER THA", "h" : "AA14"},
{"g" : "\uAA15", "n" : "CHAM LETTER DA", "h" : "AA15"},
{"g" : "\uAA16", "n" : "CHAM LETTER DHA", "h" : "AA16"},
{"g" : "\uAA17", "n" : "CHAM LETTER NUE", "h" : "AA17"},
{"g" : "\uAA18", "n" : "CHAM LETTER NA", "h" : "AA18"},
{"g" : "\uAA19", "n" : "CHAM LETTER DDA", "h" : "AA19"},
{"g" : "\uAA1A", "n" : "CHAM LETTER PA", "h" : "AA1A"},
{"g" : "\uAA1B", "n" : "CHAM LETTER PPA", "h" : "AA1B"},
{"g" : "\uAA1C", "n" : "CHAM LETTER PHA", "h" : "AA1C"},
{"g" : "\uAA1D", "n" : "CHAM LETTER BA", "h" : "AA1D"},
{"g" : "\uAA1E", "n" : "CHAM LETTER BHA", "h" : "AA1E"},
{"g" : "\uAA1F", "n" : "CHAM LETTER MUE", "h" : "AA1F"},
{"g" : "\uAA20", "n" : "CHAM LETTER MA", "h" : "AA20"},
{"g" : "\uAA21", "n" : "CHAM LETTER BBA", "h" : "AA21"},
{"g" : "\uAA22", "n" : "CHAM LETTER YA", "h" : "AA22"},
{"g" : "\uAA23", "n" : "CHAM LETTER RA", "h" : "AA23"},
{"g" : "\uAA24", "n" : "CHAM LETTER LA", "h" : "AA24"},
{"g" : "\uAA25", "n" : "CHAM LETTER VA", "h" : "AA25"},
{"g" : "\uAA26", "n" : "CHAM LETTER SSA", "h" : "AA26"},
{"g" : "\uAA27", "n" : "CHAM LETTER SA", "h" : "AA27"},
{"g" : "\uAA28", "n" : "CHAM LETTER HA", "h" : "AA28"},
{"g" : "\uAA29", "n" : "CHAM VOWEL SIGN AA", "h" : "AA29"},
{"g" : "\uAA2A", "n" : "CHAM VOWEL SIGN I", "h" : "AA2A"},
{"g" : "\uAA2B", "n" : "CHAM VOWEL SIGN II", "h" : "AA2B"},
{"g" : "\uAA2C", "n" : "CHAM VOWEL SIGN EI", "h" : "AA2C"},
{"g" : "\uAA2D", "n" : "CHAM VOWEL SIGN U", "h" : "AA2D"},
{"g" : "\uAA2E", "n" : "CHAM VOWEL SIGN OE", "h" : "AA2E"},
{"g" : "\uAA2F", "n" : "CHAM VOWEL SIGN O", "h" : "AA2F"},
{"g" : "\uAA30", "n" : "CHAM VOWEL SIGN AI", "h" : "AA30"},
{"g" : "\uAA31", "n" : "CHAM VOWEL SIGN AU", "h" : "AA31"},
{"g" : "\uAA32", "n" : "CHAM VOWEL SIGN UE", "h" : "AA32"},
{"g" : "\uAA33", "n" : "CHAM CONSONANT SIGN YA", "h" : "AA33"},
{"g" : "\uAA34", "n" : "CHAM CONSONANT SIGN RA", "h" : "AA34"},
{"g" : "\uAA35", "n" : "CHAM CONSONANT SIGN LA", "h" : "AA35"},
{"g" : "\uAA36", "n" : "CHAM CONSONANT SIGN WA", "h" : "AA36"},
{"g" : "\uAA40", "n" : "CHAM LETTER FINAL K", "h" : "AA40"},
{"g" : "\uAA41", "n" : "CHAM LETTER FINAL G", "h" : "AA41"},
{"g" : "\uAA42", "n" : "CHAM LETTER FINAL NG", "h" : "AA42"},
{"g" : "\uAA43", "n" : "CHAM CONSONANT SIGN FINAL NG", "h" : "AA43"},
{"g" : "\uAA44", "n" : "CHAM LETTER FINAL CH", "h" : "AA44"},
{"g" : "\uAA45", "n" : "CHAM LETTER FINAL T", "h" : "AA45"},
{"g" : "\uAA46", "n" : "CHAM LETTER FINAL N", "h" : "AA46"},
{"g" : "\uAA47", "n" : "CHAM LETTER FINAL P", "h" : "AA47"},
{"g" : "\uAA48", "n" : "CHAM LETTER FINAL Y", "h" : "AA48"},
{"g" : "\uAA49", "n" : "CHAM LETTER FINAL R", "h" : "AA49"},
{"g" : "\uAA4A", "n" : "CHAM LETTER FINAL L", "h" : "AA4A"},
{"g" : "\uAA4B", "n" : "CHAM LETTER FINAL SS", "h" : "AA4B"},
{"g" : "\uAA4C", "n" : "CHAM CONSONANT SIGN FINAL M", "h" : "AA4C"},
{"g" : "\uAA4D", "n" : "CHAM CONSONANT SIGN FINAL H", "h" : "AA4D"},
{"g" : "\uAA50", "n" : "CHAM DIGIT ZERO", "h" : "AA50"},
{"g" : "\uAA51", "n" : "CHAM DIGIT ONE", "h" : "AA51"},
{"g" : "\uAA52", "n" : "CHAM DIGIT TWO", "h" : "AA52"},
{"g" : "\uAA53", "n" : "CHAM DIGIT THREE", "h" : "AA53"},
{"g" : "\uAA54", "n" : "CHAM DIGIT FOUR", "h" : "AA54"},
{"g" : "\uAA55", "n" : "CHAM DIGIT FIVE", "h" : "AA55"},
{"g" : "\uAA56", "n" : "CHAM DIGIT SIX", "h" : "AA56"},
{"g" : "\uAA57", "n" : "CHAM DIGIT SEVEN", "h" : "AA57"},
{"g" : "\uAA58", "n" : "CHAM DIGIT EIGHT", "h" : "AA58"},
{"g" : "\uAA59", "n" : "CHAM DIGIT NINE", "h" : "AA59"},
{"g" : "\uAA5C", "n" : "CHAM PUNCTUATION SPIRAL", "h" : "AA5C"},
{"g" : "\uAA5D", "n" : "CHAM PUNCTUATION DANDA", "h" : "AA5D"},
{"g" : "\uAA5E", "n" : "CHAM PUNCTUATION DOUBLE DANDA", "h" : "AA5E"},
{"g" : "\uAA5F", "n" : "CHAM PUNCTUATION TRIPLE DANDA", "h" : "AA5F"},

{"g" : "\uAA60", "n" : "MYANMAR LETTER KHAMTI GA", "h" : "AA60"},
{"g" : "\uAA61", "n" : "MYANMAR LETTER KHAMTI CA", "h" : "AA61"},
{"g" : "\uAA62", "n" : "MYANMAR LETTER KHAMTI CHA", "h" : "AA62"},
{"g" : "\uAA63", "n" : "MYANMAR LETTER KHAMTI JA", "h" : "AA63"},
{"g" : "\uAA64", "n" : "MYANMAR LETTER KHAMTI JHA", "h" : "AA64"},
{"g" : "\uAA65", "n" : "MYANMAR LETTER KHAMTI NYA", "h" : "AA65"},
{"g" : "\uAA66", "n" : "MYANMAR LETTER KHAMTI TTA", "h" : "AA66"},
{"g" : "\uAA67", "n" : "MYANMAR LETTER KHAMTI TTHA", "h" : "AA67"},
{"g" : "\uAA68", "n" : "MYANMAR LETTER KHAMTI DDA", "h" : "AA68"},
{"g" : "\uAA69", "n" : "MYANMAR LETTER KHAMTI DDHA", "h" : "AA69"},
{"g" : "\uAA6A", "n" : "MYANMAR LETTER KHAMTI DHA", "h" : "AA6A"},
{"g" : "\uAA6B", "n" : "MYANMAR LETTER KHAMTI NA", "h" : "AA6B"},
{"g" : "\uAA6C", "n" : "MYANMAR LETTER KHAMTI SA", "h" : "AA6C"},
{"g" : "\uAA6D", "n" : "MYANMAR LETTER KHAMTI HA", "h" : "AA6D"},
{"g" : "\uAA6E", "n" : "MYANMAR LETTER KHAMTI HHA", "h" : "AA6E"},
{"g" : "\uAA6F", "n" : "MYANMAR LETTER KHAMTI FA", "h" : "AA6F"},
{"g" : "\uAA70", "n" : "MYANMAR MODIFIER LETTER KHAMTI REDUPLICATION", "h" : "AA70"},
{"g" : "\uAA71", "n" : "MYANMAR LETTER KHAMTI XA", "h" : "AA71"},
{"g" : "\uAA72", "n" : "MYANMAR LETTER KHAMTI ZA", "h" : "AA72"},
{"g" : "\uAA73", "n" : "MYANMAR LETTER KHAMTI RA", "h" : "AA73"},
{"g" : "\uAA74", "n" : "MYANMAR LOGOGRAM KHAMTI OAY", "h" : "AA74"},
{"g" : "\uAA75", "n" : "MYANMAR LOGOGRAM KHAMTI QN", "h" : "AA75"},
{"g" : "\uAA76", "n" : "MYANMAR LOGOGRAM KHAMTI HM", "h" : "AA76"},
{"g" : "\uAA77", "n" : "MYANMAR SYMBOL AITON EXCLAMATION", "h" : "AA77"},
{"g" : "\uAA78", "n" : "MYANMAR SYMBOL AITON ONE", "h" : "AA78"},
{"g" : "\uAA79", "n" : "MYANMAR SYMBOL AITON TWO", "h" : "AA79"},
{"g" : "\uAA7A", "n" : "MYANMAR LETTER AITON RA", "h" : "AA7A"},
{"g" : "\uAA7B", "n" : "MYANMAR SIGN PAO KAREN TONE", "h" : "AA7B"},
{"g" : "\uAA7C", "n" : "MYANMAR SIGN TAI LAING TONE-2", "h" : "AA7C"},
{"g" : "\uAA7D", "n" : "MYANMAR SIGN TAI LAING TONE-5", "h" : "AA7D"},
{"g" : "\uAA7E", "n" : "MYANMAR LETTER SHWE PALAUNG CHA", "h" : "AA7E"},
{"g" : "\uAA7F", "n" : "MYANMAR LETTER SHWE PALAUNG SHA", "h" : "AA7F"},

{"g" : "\uAA80", "n" : "TAI VIET LETTER LOW KO", "h" : "AA80"},
{"g" : "\uAA81", "n" : "TAI VIET LETTER HIGH KO", "h" : "AA81"},
{"g" : "\uAA82", "n" : "TAI VIET LETTER LOW KHO", "h" : "AA82"},
{"g" : "\uAA83", "n" : "TAI VIET LETTER HIGH KHO", "h" : "AA83"},
{"g" : "\uAA84", "n" : "TAI VIET LETTER LOW KHHO", "h" : "AA84"},
{"g" : "\uAA85", "n" : "TAI VIET LETTER HIGH KHHO", "h" : "AA85"},
{"g" : "\uAA86", "n" : "TAI VIET LETTER LOW GO", "h" : "AA86"},
{"g" : "\uAA87", "n" : "TAI VIET LETTER HIGH GO", "h" : "AA87"},
{"g" : "\uAA88", "n" : "TAI VIET LETTER LOW NGO", "h" : "AA88"},
{"g" : "\uAA89", "n" : "TAI VIET LETTER HIGH NGO", "h" : "AA89"},
{"g" : "\uAA8A", "n" : "TAI VIET LETTER LOW CO", "h" : "AA8A"},
{"g" : "\uAA8B", "n" : "TAI VIET LETTER HIGH CO", "h" : "AA8B"},
{"g" : "\uAA8C", "n" : "TAI VIET LETTER LOW CHO", "h" : "AA8C"},
{"g" : "\uAA8D", "n" : "TAI VIET LETTER HIGH CHO", "h" : "AA8D"},
{"g" : "\uAA8E", "n" : "TAI VIET LETTER LOW SO", "h" : "AA8E"},
{"g" : "\uAA8F", "n" : "TAI VIET LETTER HIGH SO", "h" : "AA8F"},
{"g" : "\uAA90", "n" : "TAI VIET LETTER LOW NYO", "h" : "AA90"},
{"g" : "\uAA91", "n" : "TAI VIET LETTER HIGH NYO", "h" : "AA91"},
{"g" : "\uAA92", "n" : "TAI VIET LETTER LOW DO", "h" : "AA92"},
{"g" : "\uAA93", "n" : "TAI VIET LETTER HIGH DO", "h" : "AA93"},
{"g" : "\uAA94", "n" : "TAI VIET LETTER LOW TO", "h" : "AA94"},
{"g" : "\uAA95", "n" : "TAI VIET LETTER HIGH TO", "h" : "AA95"},
{"g" : "\uAA96", "n" : "TAI VIET LETTER LOW THO", "h" : "AA96"},
{"g" : "\uAA97", "n" : "TAI VIET LETTER HIGH THO", "h" : "AA97"},
{"g" : "\uAA98", "n" : "TAI VIET LETTER LOW NO", "h" : "AA98"},
{"g" : "\uAA99", "n" : "TAI VIET LETTER HIGH NO", "h" : "AA99"},
{"g" : "\uAA9A", "n" : "TAI VIET LETTER LOW BO", "h" : "AA9A"},
{"g" : "\uAA9B", "n" : "TAI VIET LETTER HIGH BO", "h" : "AA9B"},
{"g" : "\uAA9C", "n" : "TAI VIET LETTER LOW PO", "h" : "AA9C"},
{"g" : "\uAA9D", "n" : "TAI VIET LETTER HIGH PO", "h" : "AA9D"},
{"g" : "\uAA9E", "n" : "TAI VIET LETTER LOW PHO", "h" : "AA9E"},
{"g" : "\uAA9F", "n" : "TAI VIET LETTER HIGH PHO", "h" : "AA9F"},
{"g" : "\uAAA0", "n" : "TAI VIET LETTER LOW FO", "h" : "AAA0"},
{"g" : "\uAAA1", "n" : "TAI VIET LETTER HIGH FO", "h" : "AAA1"},
{"g" : "\uAAA2", "n" : "TAI VIET LETTER LOW MO", "h" : "AAA2"},
{"g" : "\uAAA3", "n" : "TAI VIET LETTER HIGH MO", "h" : "AAA3"},
{"g" : "\uAAA4", "n" : "TAI VIET LETTER LOW YO", "h" : "AAA4"},
{"g" : "\uAAA5", "n" : "TAI VIET LETTER HIGH YO", "h" : "AAA5"},
{"g" : "\uAAA6", "n" : "TAI VIET LETTER LOW RO", "h" : "AAA6"},
{"g" : "\uAAA7", "n" : "TAI VIET LETTER HIGH RO", "h" : "AAA7"},
{"g" : "\uAAA8", "n" : "TAI VIET LETTER LOW LO", "h" : "AAA8"},
{"g" : "\uAAA9", "n" : "TAI VIET LETTER HIGH LO", "h" : "AAA9"},
{"g" : "\uAAAA", "n" : "TAI VIET LETTER LOW VO", "h" : "AAAA"},
{"g" : "\uAAAB", "n" : "TAI VIET LETTER HIGH VO", "h" : "AAAB"},
{"g" : "\uAAAC", "n" : "TAI VIET LETTER LOW HO", "h" : "AAAC"},
{"g" : "\uAAAD", "n" : "TAI VIET LETTER HIGH HO", "h" : "AAAD"},
{"g" : "\uAAAE", "n" : "TAI VIET LETTER LOW O", "h" : "AAAE"},
{"g" : "\uAAAF", "n" : "TAI VIET LETTER HIGH O", "h" : "AAAF"},
{"g" : "\uAAB0", "n" : "TAI VIET MAI KANG", "h" : "AAB0"},
{"g" : "\uAAB1", "n" : "TAI VIET VOWEL AA", "h" : "AAB1"},
{"g" : "\uAAB2", "n" : "TAI VIET VOWEL I", "h" : "AAB2"},
{"g" : "\uAAB3", "n" : "TAI VIET VOWEL UE", "h" : "AAB3"},
{"g" : "\uAAB4", "n" : "TAI VIET VOWEL U", "h" : "AAB4"},
{"g" : "\uAAB5", "n" : "TAI VIET VOWEL E", "h" : "AAB5"},
{"g" : "\uAAB6", "n" : "TAI VIET VOWEL O", "h" : "AAB6"},
{"g" : "\uAAB7", "n" : "TAI VIET MAI KHIT", "h" : "AAB7"},
{"g" : "\uAAB8", "n" : "TAI VIET VOWEL IA", "h" : "AAB8"},
{"g" : "\uAAB9", "n" : "TAI VIET VOWEL UEA", "h" : "AAB9"},
{"g" : "\uAABA", "n" : "TAI VIET VOWEL UA", "h" : "AABA"},
{"g" : "\uAABB", "n" : "TAI VIET VOWEL AUE", "h" : "AABB"},
{"g" : "\uAABC", "n" : "TAI VIET VOWEL AY", "h" : "AABC"},
{"g" : "\uAABD", "n" : "TAI VIET VOWEL AN", "h" : "AABD"},
{"g" : "\uAABE", "n" : "TAI VIET VOWEL AM", "h" : "AABE"},
{"g" : "\uAABF", "n" : "TAI VIET TONE MAI EK", "h" : "AABF"},
{"g" : "\uAAC0", "n" : "TAI VIET TONE MAI NUENG", "h" : "AAC0"},
{"g" : "\uAAC1", "n" : "TAI VIET TONE MAI THO", "h" : "AAC1"},
{"g" : "\uAAC2", "n" : "TAI VIET TONE MAI SONG", "h" : "AAC2"},
{"g" : "\uAADB", "n" : "TAI VIET SYMBOL KON", "h" : "AADB"},
{"g" : "\uAADC", "n" : "TAI VIET SYMBOL NUENG", "h" : "AADC"},
{"g" : "\uAADD", "n" : "TAI VIET SYMBOL SAM", "h" : "AADD"},
{"g" : "\uAADE", "n" : "TAI VIET SYMBOL HO HOI", "h" : "AADE"},
{"g" : "\uAADF", "n" : "TAI VIET SYMBOL KOI KOI", "h" : "AADF"},

{"g" : "\u{10D00}", "n" : "HANIFI ROHINGYA LETTER A", "h" : "10D00"},
{"g" : "\u{10D01}", "n" : "HANIFI ROHINGYA LETTER BA", "h" : "10D01"},
{"g" : "\u{10D02}", "n" : "HANIFI ROHINGYA LETTER PA", "h" : "10D02"},
{"g" : "\u{10D03}", "n" : "HANIFI ROHINGYA LETTER TA", "h" : "10D03"},
{"g" : "\u{10D04}", "n" : "HANIFI ROHINGYA LETTER TTA", "h" : "10D04"},
{"g" : "\u{10D05}", "n" : "HANIFI ROHINGYA LETTER JA", "h" : "10D05"},
{"g" : "\u{10D06}", "n" : "HANIFI ROHINGYA LETTER CA", "h" : "10D06"},
{"g" : "\u{10D07}", "n" : "HANIFI ROHINGYA LETTER HA", "h" : "10D07"},
{"g" : "\u{10D08}", "n" : "HANIFI ROHINGYA LETTER KHA", "h" : "10D08"},
{"g" : "\u{10D09}", "n" : "HANIFI ROHINGYA LETTER FA", "h" : "10D09"},
{"g" : "\u{10D0A}", "n" : "HANIFI ROHINGYA LETTER DA", "h" : "10D0A"},
{"g" : "\u{10D0B}", "n" : "HANIFI ROHINGYA LETTER DDA", "h" : "10D0B"},
{"g" : "\u{10D0C}", "n" : "HANIFI ROHINGYA LETTER RA", "h" : "10D0C"},
{"g" : "\u{10D0D}", "n" : "HANIFI ROHINGYA LETTER RRA", "h" : "10D0D"},
{"g" : "\u{10D0E}", "n" : "HANIFI ROHINGYA LETTER ZA", "h" : "10D0E"},
{"g" : "\u{10D0F}", "n" : "HANIFI ROHINGYA LETTER SA", "h" : "10D0F"},
{"g" : "\u{10D10}", "n" : "HANIFI ROHINGYA LETTER SHA", "h" : "10D10"},
{"g" : "\u{10D11}", "n" : "HANIFI ROHINGYA LETTER KA", "h" : "10D11"},
{"g" : "\u{10D12}", "n" : "HANIFI ROHINGYA LETTER GA", "h" : "10D12"},
{"g" : "\u{10D13}", "n" : "HANIFI ROHINGYA LETTER LA", "h" : "10D13"},
{"g" : "\u{10D14}", "n" : "HANIFI ROHINGYA LETTER MA", "h" : "10D14"},
{"g" : "\u{10D15}", "n" : "HANIFI ROHINGYA LETTER NA", "h" : "10D15"},
{"g" : "\u{10D16}", "n" : "HANIFI ROHINGYA LETTER WA", "h" : "10D16"},
{"g" : "\u{10D17}", "n" : "HANIFI ROHINGYA LETTER KINNA WA", "h" : "10D17"},
{"g" : "\u{10D18}", "n" : "HANIFI ROHINGYA LETTER YA", "h" : "10D18"},
{"g" : "\u{10D19}", "n" : "HANIFI ROHINGYA LETTER KINNA YA", "h" : "10D19"},
{"g" : "\u{10D1A}", "n" : "HANIFI ROHINGYA LETTER NGA", "h" : "10D1A"},
{"g" : "\u{10D1B}", "n" : "HANIFI ROHINGYA LETTER NYA", "h" : "10D1B"},
{"g" : "\u{10D1C}", "n" : "HANIFI ROHINGYA LETTER VA", "h" : "10D1C"},
{"g" : "\u{10D1D}", "n" : "HANIFI ROHINGYA VOWEL A", "h" : "10D1D"},
{"g" : "\u{10D1E}", "n" : "HANIFI ROHINGYA VOWEL I", "h" : "10D1E"},
{"g" : "\u{10D1F}", "n" : "HANIFI ROHINGYA VOWEL U", "h" : "10D1F"},
{"g" : "\u{10D20}", "n" : "HANIFI ROHINGYA VOWEL E", "h" : "10D20"},
{"g" : "\u{10D21}", "n" : "HANIFI ROHINGYA VOWEL O", "h" : "10D21"},
{"g" : "\u{10D22}", "n" : "HANIFI ROHINGYA MARK SAKIN", "h" : "10D22"},
{"g" : "\u{10D23}", "n" : "HANIFI ROHINGYA MARK NA KHONNA", "h" : "10D23"},
{"g" : "\u{10D24}", "n" : "HANIFI ROHINGYA SIGN HARBAHAY", "h" : "10D24"},
{"g" : "\u{10D25}", "n" : "HANIFI ROHINGYA SIGN TAHALA", "h" : "10D25"},
{"g" : "\u{10D26}", "n" : "HANIFI ROHINGYA SIGN TANA", "h" : "10D26"},
{"g" : "\u{10D27}", "n" : "HANIFI ROHINGYA SIGN TASSI", "h" : "10D27"},

{"g" : "\u{10D30}", "n" : "HANIFI ROHINGYA DIGIT ZERO", "h" : "10D30"},
{"g" : "\u{10D31}", "n" : "HANIFI ROHINGYA DIGIT ONE", "h" : "10D31"},
{"g" : "\u{10D32}", "n" : "HANIFI ROHINGYA DIGIT TWO", "h" : "10D32"},
{"g" : "\u{10D33}", "n" : "HANIFI ROHINGYA DIGIT THREE", "h" : "10D33"},
{"g" : "\u{10D34}", "n" : "HANIFI ROHINGYA DIGIT FOUR", "h" : "10D34"},
{"g" : "\u{10D35}", "n" : "HANIFI ROHINGYA DIGIT FIVE", "h" : "10D35"},
{"g" : "\u{10D36}", "n" : "HANIFI ROHINGYA DIGIT SIX", "h" : "10D36"},
{"g" : "\u{10D37}", "n" : "HANIFI ROHINGYA DIGIT SEVEN", "h" : "10D37"},
{"g" : "\u{10D38}", "n" : "HANIFI ROHINGYA DIGIT EIGHT", "h" : "10D38"},
{"g" : "\u{10D39}", "n" : "HANIFI ROHINGYA DIGIT NINE", "h" : "10D39"},

{"g" : "\u{11AC0}", "n" : "PAU CIN HAU LETTER PA", "h" : "11AC0"},
{"g" : "\u{11AC1}", "n" : "PAU CIN HAU LETTER KA", "h" : "11AC1"},
{"g" : "\u{11AC2}", "n" : "PAU CIN HAU LETTER LA", "h" : "11AC2"},
{"g" : "\u{11AC3}", "n" : "PAU CIN HAU LETTER MA", "h" : "11AC3"},
{"g" : "\u{11AC4}", "n" : "PAU CIN HAU LETTER DA", "h" : "11AC4"},
{"g" : "\u{11AC5}", "n" : "PAU CIN HAU LETTER ZA", "h" : "11AC5"},
{"g" : "\u{11AC6}", "n" : "PAU CIN HAU LETTER VA", "h" : "11AC6"},
{"g" : "\u{11AC7}", "n" : "PAU CIN HAU LETTER NGA", "h" : "11AC7"},
{"g" : "\u{11AC8}", "n" : "PAU CIN HAU LETTER HA", "h" : "11AC8"},
{"g" : "\u{11AC9}", "n" : "PAU CIN HAU LETTER GA", "h" : "11AC9"},
{"g" : "\u{11ACA}", "n" : "PAU CIN HAU LETTER KHA", "h" : "11ACA"},
{"g" : "\u{11ACB}", "n" : "PAU CIN HAU LETTER SA", "h" : "11ACB"},
{"g" : "\u{11ACC}", "n" : "PAU CIN HAU LETTER BA", "h" : "11ACC"},
{"g" : "\u{11ACD}", "n" : "PAU CIN HAU LETTER CA", "h" : "11ACD"},
{"g" : "\u{11ACE}", "n" : "PAU CIN HAU LETTER TA", "h" : "11ACE"},
{"g" : "\u{11ACF}", "n" : "PAU CIN HAU LETTER THA", "h" : "11ACF"},
{"g" : "\u{11AD0}", "n" : "PAU CIN HAU LETTER NA", "h" : "11AD0"},
{"g" : "\u{11AD1}", "n" : "PAU CIN HAU LETTER PHA", "h" : "11AD1"},
{"g" : "\u{11AD2}", "n" : "PAU CIN HAU LETTER RA", "h" : "11AD2"},
{"g" : "\u{11AD3}", "n" : "PAU CIN HAU LETTER FA", "h" : "11AD3"},
{"g" : "\u{11AD4}", "n" : "PAU CIN HAU LETTER CHA", "h" : "11AD4"},
{"g" : "\u{11AD5}", "n" : "PAU CIN HAU LETTER A", "h" : "11AD5"},
{"g" : "\u{11AD6}", "n" : "PAU CIN HAU LETTER E", "h" : "11AD6"},
{"g" : "\u{11AD7}", "n" : "PAU CIN HAU LETTER I", "h" : "11AD7"},
{"g" : "\u{11AD8}", "n" : "PAU CIN HAU LETTER O", "h" : "11AD8"},
{"g" : "\u{11AD9}", "n" : "PAU CIN HAU LETTER U", "h" : "11AD9"},
{"g" : "\u{11ADA}", "n" : "PAU CIN HAU LETTER UA", "h" : "11ADA"},
{"g" : "\u{11ADB}", "n" : "PAU CIN HAU LETTER IA", "h" : "11ADB"},
{"g" : "\u{11ADC}", "n" : "PAU CIN HAU LETTER FINAL P", "h" : "11ADC"},
{"g" : "\u{11ADD}", "n" : "PAU CIN HAU LETTER FINAL K", "h" : "11ADD"},
{"g" : "\u{11ADE}", "n" : "PAU CIN HAU LETTER FINAL T", "h" : "11ADE"},
{"g" : "\u{11ADF}", "n" : "PAU CIN HAU LETTER FINAL M", "h" : "11ADF"},
{"g" : "\u{11AE0}", "n" : "PAU CIN HAU LETTER FINAL N", "h" : "11AE0"},
{"g" : "\u{11AE1}", "n" : "PAU CIN HAU LETTER FINAL L", "h" : "11AE1"},
{"g" : "\u{11AE2}", "n" : "PAU CIN HAU LETTER FINAL W", "h" : "11AE2"},
{"g" : "\u{11AE3}", "n" : "PAU CIN HAU LETTER FINAL NG", "h" : "11AE3"},
{"g" : "\u{11AE4}", "n" : "PAU CIN HAU LETTER FINAL Y", "h" : "11AE4"},
{"g" : "\u{11AE5}", "n" : "PAU CIN HAU RISING TONE LONG", "h" : "11AE5"},
{"g" : "\u{11AE6}", "n" : "PAU CIN HAU RISING TONE", "h" : "11AE6"},
{"g" : "\u{11AE7}", "n" : "PAU CIN HAU SANDHI GLOTTAL STOP", "h" : "11AE7"},
{"g" : "\u{11AE8}", "n" : "PAU CIN HAU RISING TONE LONG FINAL", "h" : "11AE8"},
{"g" : "\u{11AE9}", "n" : "PAU CIN HAU RISING TONE FINAL", "h" : "11AE9"},
{"g" : "\u{11AEA}", "n" : "PAU CIN HAU SANDHI GLOTTAL STOP FINAL", "h" : "11AEA"},
{"g" : "\u{11AEB}", "n" : "PAU CIN HAU SANDHI TONE LONG", "h" : "11AEB"},
{"g" : "\u{11AEC}", "n" : "PAU CIN HAU SANDHI TONE", "h" : "11AEC"},
{"g" : "\u{11AED}", "n" : "PAU CIN HAU SANDHI TONE LONG FINAL", "h" : "11AED"},
{"g" : "\u{11AEE}", "n" : "PAU CIN HAU SANDHI TONE FINAL", "h" : "11AEE"},
{"g" : "\u{11AEF}", "n" : "PAU CIN HAU MID-LEVEL TONE", "h" : "11AEF"},
{"g" : "\u{11AF0}", "n" : "PAU CIN HAU GLOTTAL STOP VARIANT", "h" : "11AF0"},
{"g" : "\u{11AF1}", "n" : "PAU CIN HAU MID-LEVEL TONE LONG FINAL", "h" : "11AF1"},
{"g" : "\u{11AF2}", "n" : "PAU CIN HAU MID-LEVEL TONE FINAL", "h" : "11AF2"},
{"g" : "\u{11AF3}", "n" : "PAU CIN HAU LOW-FALLING TONE LONG", "h" : "11AF3"},
{"g" : "\u{11AF4}", "n" : "PAU CIN HAU LOW-FALLING TONE", "h" : "11AF4"},
{"g" : "\u{11AF5}", "n" : "PAU CIN HAU GLOTTAL STOP", "h" : "11AF5"},
{"g" : "\u{11AF6}", "n" : "PAU CIN HAU LOW-FALLING TONE LONG FINAL", "h" : "11AF6"},
{"g" : "\u{11AF7}", "n" : "PAU CIN HAU LOW-FALLING TONE FINAL", "h" : "11AF7"},
{"g" : "\u{11AF8}", "n" : "PAU CIN HAU GLOTTAL STOP FINAL", "h" : "11AF8"},

{"g" : "\u{16B00}", "n" : "PAHAWH HMONG VOWEL KEEB", "h" : "16B00"},
{"g" : "\u{16B01}", "n" : "PAHAWH HMONG VOWEL KEEV", "h" : "16B01"},
{"g" : "\u{16B02}", "n" : "PAHAWH HMONG VOWEL KIB", "h" : "16B02"},
{"g" : "\u{16B03}", "n" : "PAHAWH HMONG VOWEL KIV", "h" : "16B03"},
{"g" : "\u{16B04}", "n" : "PAHAWH HMONG VOWEL KAUB", "h" : "16B04"},
{"g" : "\u{16B05}", "n" : "PAHAWH HMONG VOWEL KAUV", "h" : "16B05"},
{"g" : "\u{16B06}", "n" : "PAHAWH HMONG VOWEL KUB", "h" : "16B06"},
{"g" : "\u{16B07}", "n" : "PAHAWH HMONG VOWEL KUV", "h" : "16B07"},
{"g" : "\u{16B08}", "n" : "PAHAWH HMONG VOWEL KEB", "h" : "16B08"},
{"g" : "\u{16B09}", "n" : "PAHAWH HMONG VOWEL KEV", "h" : "16B09"},
{"g" : "\u{16B0A}", "n" : "PAHAWH HMONG VOWEL KAIB", "h" : "16B0A"},
{"g" : "\u{16B0B}", "n" : "PAHAWH HMONG VOWEL KAIV", "h" : "16B0B"},
{"g" : "\u{16B0C}", "n" : "PAHAWH HMONG VOWEL KOOB", "h" : "16B0C"},
{"g" : "\u{16B0D}", "n" : "PAHAWH HMONG VOWEL KOOV", "h" : "16B0D"},
{"g" : "\u{16B0E}", "n" : "PAHAWH HMONG VOWEL KAWB", "h" : "16B0E"},
{"g" : "\u{16B0F}", "n" : "PAHAWH HMONG VOWEL KAWV", "h" : "16B0F"},
{"g" : "\u{16B10}", "n" : "PAHAWH HMONG VOWEL KUAB", "h" : "16B10"},
{"g" : "\u{16B11}", "n" : "PAHAWH HMONG VOWEL KUAV", "h" : "16B11"},
{"g" : "\u{16B12}", "n" : "PAHAWH HMONG VOWEL KOB", "h" : "16B12"},
{"g" : "\u{16B13}", "n" : "PAHAWH HMONG VOWEL KOV", "h" : "16B13"},
{"g" : "\u{16B14}", "n" : "PAHAWH HMONG VOWEL KIAB", "h" : "16B14"},
{"g" : "\u{16B15}", "n" : "PAHAWH HMONG VOWEL KIAV", "h" : "16B15"},
{"g" : "\u{16B16}", "n" : "PAHAWH HMONG VOWEL KAB", "h" : "16B16"},
{"g" : "\u{16B17}", "n" : "PAHAWH HMONG VOWEL KAV", "h" : "16B17"},
{"g" : "\u{16B18}", "n" : "PAHAWH HMONG VOWEL KWB", "h" : "16B18"},
{"g" : "\u{16B19}", "n" : "PAHAWH HMONG VOWEL KWV", "h" : "16B19"},
{"g" : "\u{16B1A}", "n" : "PAHAWH HMONG VOWEL KAAB", "h" : "16B1A"},
{"g" : "\u{16B1B}", "n" : "PAHAWH HMONG VOWEL KAAV", "h" : "16B1B"},
{"g" : "\u{16B1C}", "n" : "PAHAWH HMONG CONSONANT VAU", "h" : "16B1C"},
{"g" : "\u{16B1D}", "n" : "PAHAWH HMONG CONSONANT NTSAU", "h" : "16B1D"},
{"g" : "\u{16B1E}", "n" : "PAHAWH HMONG CONSONANT LAU", "h" : "16B1E"},
{"g" : "\u{16B1F}", "n" : "PAHAWH HMONG CONSONANT HAU", "h" : "16B1F"},
{"g" : "\u{16B20}", "n" : "PAHAWH HMONG CONSONANT NLAU", "h" : "16B20"},
{"g" : "\u{16B21}", "n" : "PAHAWH HMONG CONSONANT RAU", "h" : "16B21"},
{"g" : "\u{16B22}", "n" : "PAHAWH HMONG CONSONANT NKAU", "h" : "16B22"},
{"g" : "\u{16B23}", "n" : "PAHAWH HMONG CONSONANT QHAU", "h" : "16B23"},
{"g" : "\u{16B24}", "n" : "PAHAWH HMONG CONSONANT YAU", "h" : "16B24"},
{"g" : "\u{16B25}", "n" : "PAHAWH HMONG CONSONANT HLAU", "h" : "16B25"},
{"g" : "\u{16B26}", "n" : "PAHAWH HMONG CONSONANT MAU", "h" : "16B26"},
{"g" : "\u{16B27}", "n" : "PAHAWH HMONG CONSONANT CHAU", "h" : "16B27"},
{"g" : "\u{16B28}", "n" : "PAHAWH HMONG CONSONANT NCHAU", "h" : "16B28"},
{"g" : "\u{16B29}", "n" : "PAHAWH HMONG CONSONANT HNAU", "h" : "16B29"},
{"g" : "\u{16B2A}", "n" : "PAHAWH HMONG CONSONANT PLHAU", "h" : "16B2A"},
{"g" : "\u{16B2B}", "n" : "PAHAWH HMONG CONSONANT NTHAU", "h" : "16B2B"},
{"g" : "\u{16B2C}", "n" : "PAHAWH HMONG CONSONANT NAU", "h" : "16B2C"},
{"g" : "\u{16B2D}", "n" : "PAHAWH HMONG CONSONANT AU", "h" : "16B2D"},
{"g" : "\u{16B2E}", "n" : "PAHAWH HMONG CONSONANT XAU", "h" : "16B2E"},
{"g" : "\u{16B2F}", "n" : "PAHAWH HMONG CONSONANT CAU", "h" : "16B2F"},
{"g" : "\u{16B30}", "n" : "PAHAWH HMONG MARK CIM TUB", "h" : "16B30"},
{"g" : "\u{16B31}", "n" : "PAHAWH HMONG MARK CIM SO", "h" : "16B31"},
{"g" : "\u{16B32}", "n" : "PAHAWH HMONG MARK CIM KES", "h" : "16B32"},
{"g" : "\u{16B33}", "n" : "PAHAWH HMONG MARK CIM KHAV", "h" : "16B33"},
{"g" : "\u{16B34}", "n" : "PAHAWH HMONG MARK CIM SUAM", "h" : "16B34"},
{"g" : "\u{16B35}", "n" : "PAHAWH HMONG MARK CIM HOM", "h" : "16B35"},
{"g" : "\u{16B36}", "n" : "PAHAWH HMONG MARK CIM TAUM", "h" : "16B36"},
{"g" : "\u{16B37}", "n" : "PAHAWH HMONG SIGN VOS THOM", "h" : "16B37"},
{"g" : "\u{16B38}", "n" : "PAHAWH HMONG SIGN VOS TSHAB CEEB", "h" : "16B38"},
{"g" : "\u{16B39}", "n" : "PAHAWH HMONG SIGN CIM CHEEM", "h" : "16B39"},
{"g" : "\u{16B3A}", "n" : "PAHAWH HMONG SIGN VOS THIAB", "h" : "16B3A"},
{"g" : "\u{16B3B}", "n" : "PAHAWH HMONG SIGN VOS FEEM", "h" : "16B3B"},
{"g" : "\u{16B3C}", "n" : "PAHAWH HMONG SIGN XYEEM NTXIV", "h" : "16B3C"},
{"g" : "\u{16B3D}", "n" : "PAHAWH HMONG SIGN XYEEM RHO", "h" : "16B3D"},
{"g" : "\u{16B3E}", "n" : "PAHAWH HMONG SIGN XYEEM TOV", "h" : "16B3E"},
{"g" : "\u{16B3F}", "n" : "PAHAWH HMONG SIGN XYEEM FAIB", "h" : "16B3F"},
{"g" : "\u{16B40}", "n" : "PAHAWH HMONG SIGN VOS SEEV", "h" : "16B40"},
{"g" : "\u{16B41}", "n" : "PAHAWH HMONG SIGN MEEJ SUAB", "h" : "16B41"},
{"g" : "\u{16B42}", "n" : "PAHAWH HMONG SIGN VOS NRUA", "h" : "16B42"},
{"g" : "\u{16B43}", "n" : "PAHAWH HMONG SIGN IB YAM", "h" : "16B43"},
{"g" : "\u{16B44}", "n" : "PAHAWH HMONG SIGN XAUS", "h" : "16B44"},
{"g" : "\u{16B45}", "n" : "PAHAWH HMONG SIGN CIM TSOV ROG", "h" : "16B45"},

{"g" : "\u{16B50}", "n" : "PAHAWH HMONG DIGIT ZERO", "h" : "16B50"},
{"g" : "\u{16B51}", "n" : "PAHAWH HMONG DIGIT ONE", "h" : "16B51"},
{"g" : "\u{16B52}", "n" : "PAHAWH HMONG DIGIT TWO", "h" : "16B52"},
{"g" : "\u{16B53}", "n" : "PAHAWH HMONG DIGIT THREE", "h" : "16B53"},
{"g" : "\u{16B54}", "n" : "PAHAWH HMONG DIGIT FOUR", "h" : "16B54"},
{"g" : "\u{16B55}", "n" : "PAHAWH HMONG DIGIT FIVE", "h" : "16B55"},
{"g" : "\u{16B56}", "n" : "PAHAWH HMONG DIGIT SIX", "h" : "16B56"},
{"g" : "\u{16B57}", "n" : "PAHAWH HMONG DIGIT SEVEN", "h" : "16B57"},
{"g" : "\u{16B58}", "n" : "PAHAWH HMONG DIGIT EIGHT", "h" : "16B58"},
{"g" : "\u{16B59}", "n" : "PAHAWH HMONG DIGIT NINE", "h" : "16B59"},

{"g" : "\u{16B5B}", "n" : "PAHAWH HMONG NUMBER TENS", "h" : "16B5B"},
{"g" : "\u{16B5C}", "n" : "PAHAWH HMONG NUMBER HUNDREDS", "h" : "16B5C"},
{"g" : "\u{16B5D}", "n" : "PAHAWH HMONG NUMBER TEN THOUSANDS", "h" : "16B5D"},
{"g" : "\u{16B5E}", "n" : "PAHAWH HMONG NUMBER MILLIONS", "h" : "16B5E"},
{"g" : "\u{16B5F}", "n" : "PAHAWH HMONG NUMBER HUNDRED MILLIONS", "h" : "16B5F"},
{"g" : "\u{16B60}", "n" : "PAHAWH HMONG NUMBER TEN BILLIONS", "h" : "16B60"},
{"g" : "\u{16B61}", "n" : "PAHAWH HMONG NUMBER TRILLIONS", "h" : "16B61"},

{"g" : "\u{16B63}", "n" : "PAHAWH HMONG SIGN VOS LUB", "h" : "16B63"},
{"g" : "\u{16B64}", "n" : "PAHAWH HMONG SIGN XYOO", "h" : "16B64"},
{"g" : "\u{16B65}", "n" : "PAHAWH HMONG SIGN HLI", "h" : "16B65"},
{"g" : "\u{16B66}", "n" : "PAHAWH HMONG SIGN THIRD-STAGE HLI", "h" : "16B66"},
{"g" : "\u{16B67}", "n" : "PAHAWH HMONG SIGN ZWJ THAJ", "h" : "16B67"},
{"g" : "\u{16B68}", "n" : "PAHAWH HMONG SIGN HNUB", "h" : "16B68"},
{"g" : "\u{16B69}", "n" : "PAHAWH HMONG SIGN NQIG", "h" : "16B69"},
{"g" : "\u{16B6A}", "n" : "PAHAWH HMONG SIGN XIAB", "h" : "16B6A"},
{"g" : "\u{16B6B}", "n" : "PAHAWH HMONG SIGN NTUJ", "h" : "16B6B"},
{"g" : "\u{16B6C}", "n" : "PAHAWH HMONG SIGN AV", "h" : "16B6C"},
{"g" : "\u{16B6D}", "n" : "PAHAWH HMONG SIGN TXHEEJ CEEV", "h" : "16B6D"},
{"g" : "\u{16B6E}", "n" : "PAHAWH HMONG SIGN MEEJ TSEEB", "h" : "16B6E"},
{"g" : "\u{16B6F}", "n" : "PAHAWH HMONG SIGN TAU", "h" : "16B6F"},
{"g" : "\u{16B70}", "n" : "PAHAWH HMONG SIGN LOS", "h" : "16B70"},
{"g" : "\u{16B71}", "n" : "PAHAWH HMONG SIGN MUS", "h" : "16B71"},
{"g" : "\u{16B72}", "n" : "PAHAWH HMONG SIGN CIM HAIS LUS NTOG NTOG", "h" : "16B72"},
{"g" : "\u{16B73}", "n" : "PAHAWH HMONG SIGN CIM CUAM TSHOOJ", "h" : "16B73"},
{"g" : "\u{16B74}", "n" : "PAHAWH HMONG SIGN CIM TXWV", "h" : "16B74"},
{"g" : "\u{16B75}", "n" : "PAHAWH HMONG SIGN CIM TXWV CHWV", "h" : "16B75"},
{"g" : "\u{16B76}", "n" : "PAHAWH HMONG SIGN CIM PUB DAWB", "h" : "16B76"},
{"g" : "\u{16B77}", "n" : "PAHAWH HMONG SIGN CIM NRES TOS", "h" : "16B77"},

{"g" : "\u{16B7D}", "n" : "PAHAWH HMONG CLAN SIGN TSHEEJ", "h" : "16B7D"},
{"g" : "\u{16B7E}", "n" : "PAHAWH HMONG CLAN SIGN YEEG", "h" : "16B7E"},
{"g" : "\u{16B7F}", "n" : "PAHAWH HMONG CLAN SIGN LIS", "h" : "16B7F"},
{"g" : "\u{16B80}", "n" : "PAHAWH HMONG CLAN SIGN LAUJ", "h" : "16B80"},
{"g" : "\u{16B81}", "n" : "PAHAWH HMONG CLAN SIGN XYOOJ", "h" : "16B81"},
{"g" : "\u{16B82}", "n" : "PAHAWH HMONG CLAN SIGN KOO", "h" : "16B82"},
{"g" : "\u{16B83}", "n" : "PAHAWH HMONG CLAN SIGN HAWJ", "h" : "16B83"},
{"g" : "\u{16B84}", "n" : "PAHAWH HMONG CLAN SIGN MUAS", "h" : "16B84"},
{"g" : "\u{16B85}", "n" : "PAHAWH HMONG CLAN SIGN THOJ", "h" : "16B85"},
{"g" : "\u{16B86}", "n" : "PAHAWH HMONG CLAN SIGN TSAB", "h" : "16B86"},
{"g" : "\u{16B87}", "n" : "PAHAWH HMONG CLAN SIGN PHAB", "h" : "16B87"},
{"g" : "\u{16B88}", "n" : "PAHAWH HMONG CLAN SIGN KHAB", "h" : "16B88"},
{"g" : "\u{16B89}", "n" : "PAHAWH HMONG CLAN SIGN HAM", "h" : "16B89"},
{"g" : "\u{16B8A}", "n" : "PAHAWH HMONG CLAN SIGN VAJ", "h" : "16B8A"},
{"g" : "\u{16B8B}", "n" : "PAHAWH HMONG CLAN SIGN FAJ", "h" : "16B8B"},
{"g" : "\u{16B8C}", "n" : "PAHAWH HMONG CLAN SIGN YAJ", "h" : "16B8C"},
{"g" : "\u{16B8D}", "n" : "PAHAWH HMONG CLAN SIGN TSWB", "h" : "16B8D"},
{"g" : "\u{16B8E}", "n" : "PAHAWH HMONG CLAN SIGN KWM", "h" : "16B8E"},
{"g" : "\u{16B8F}", "n" : "PAHAWH HMONG CLAN SIGN VWJ", "h" : "16B8F"},

{"g" : "\u{1E100}", "n" : "NYIAKENG PUACHUE HMONG LETTER MA", "h" : "1E100"},
{"g" : "\u{1E101}", "n" : "NYIAKENG PUACHUE HMONG LETTER TSA", "h" : "1E101"},
{"g" : "\u{1E102}", "n" : "NYIAKENG PUACHUE HMONG LETTER NTA", "h" : "1E102"},
{"g" : "\u{1E103}", "n" : "NYIAKENG PUACHUE HMONG LETTER TA", "h" : "1E103"},
{"g" : "\u{1E104}", "n" : "NYIAKENG PUACHUE HMONG LETTER HA", "h" : "1E104"},
{"g" : "\u{1E105}", "n" : "NYIAKENG PUACHUE HMONG LETTER NA", "h" : "1E105"},
{"g" : "\u{1E106}", "n" : "NYIAKENG PUACHUE HMONG LETTER XA", "h" : "1E106"},
{"g" : "\u{1E107}", "n" : "NYIAKENG PUACHUE HMONG LETTER NKA", "h" : "1E107"},
{"g" : "\u{1E108}", "n" : "NYIAKENG PUACHUE HMONG LETTER CA", "h" : "1E108"},
{"g" : "\u{1E109}", "n" : "NYIAKENG PUACHUE HMONG LETTER LA", "h" : "1E109"},
{"g" : "\u{1E10A}", "n" : "NYIAKENG PUACHUE HMONG LETTER SA", "h" : "1E10A"},
{"g" : "\u{1E10B}", "n" : "NYIAKENG PUACHUE HMONG LETTER ZA", "h" : "1E10B"},
{"g" : "\u{1E10C}", "n" : "NYIAKENG PUACHUE HMONG LETTER NCA", "h" : "1E10C"},
{"g" : "\u{1E10D}", "n" : "NYIAKENG PUACHUE HMONG LETTER NTSA", "h" : "1E10D"},
{"g" : "\u{1E10E}", "n" : "NYIAKENG PUACHUE HMONG LETTER KA", "h" : "1E10E"},
{"g" : "\u{1E10F}", "n" : "NYIAKENG PUACHUE HMONG LETTER DA", "h" : "1E10F"},
{"g" : "\u{1E110}", "n" : "NYIAKENG PUACHUE HMONG LETTER NYA", "h" : "1E110"},
{"g" : "\u{1E111}", "n" : "NYIAKENG PUACHUE HMONG LETTER NRA", "h" : "1E111"},
{"g" : "\u{1E112}", "n" : "NYIAKENG PUACHUE HMONG LETTER VA", "h" : "1E112"},
{"g" : "\u{1E113}", "n" : "NYIAKENG PUACHUE HMONG LETTER NTXA", "h" : "1E113"},
{"g" : "\u{1E114}", "n" : "NYIAKENG PUACHUE HMONG LETTER TXA", "h" : "1E114"},
{"g" : "\u{1E115}", "n" : "NYIAKENG PUACHUE HMONG LETTER FA", "h" : "1E115"},
{"g" : "\u{1E116}", "n" : "NYIAKENG PUACHUE HMONG LETTER RA", "h" : "1E116"},
{"g" : "\u{1E117}", "n" : "NYIAKENG PUACHUE HMONG LETTER QA", "h" : "1E117"},
{"g" : "\u{1E118}", "n" : "NYIAKENG PUACHUE HMONG LETTER YA", "h" : "1E118"},
{"g" : "\u{1E119}", "n" : "NYIAKENG PUACHUE HMONG LETTER NQA", "h" : "1E119"},
{"g" : "\u{1E11A}", "n" : "NYIAKENG PUACHUE HMONG LETTER PA", "h" : "1E11A"},
{"g" : "\u{1E11B}", "n" : "NYIAKENG PUACHUE HMONG LETTER XYA", "h" : "1E11B"},
{"g" : "\u{1E11C}", "n" : "NYIAKENG PUACHUE HMONG LETTER NPA", "h" : "1E11C"},
{"g" : "\u{1E11D}", "n" : "NYIAKENG PUACHUE HMONG LETTER DLA", "h" : "1E11D"},
{"g" : "\u{1E11E}", "n" : "NYIAKENG PUACHUE HMONG LETTER NPLA", "h" : "1E11E"},
{"g" : "\u{1E11F}", "n" : "NYIAKENG PUACHUE HMONG LETTER HAH", "h" : "1E11F"},
{"g" : "\u{1E120}", "n" : "NYIAKENG PUACHUE HMONG LETTER MLA", "h" : "1E120"},
{"g" : "\u{1E121}", "n" : "NYIAKENG PUACHUE HMONG LETTER PLA", "h" : "1E121"},
{"g" : "\u{1E122}", "n" : "NYIAKENG PUACHUE HMONG LETTER GA", "h" : "1E122"},
{"g" : "\u{1E123}", "n" : "NYIAKENG PUACHUE HMONG LETTER RRA", "h" : "1E123"},
{"g" : "\u{1E124}", "n" : "NYIAKENG PUACHUE HMONG LETTER A", "h" : "1E124"},
{"g" : "\u{1E125}", "n" : "NYIAKENG PUACHUE HMONG LETTER AA", "h" : "1E125"},
{"g" : "\u{1E126}", "n" : "NYIAKENG PUACHUE HMONG LETTER I", "h" : "1E126"},
{"g" : "\u{1E127}", "n" : "NYIAKENG PUACHUE HMONG LETTER U", "h" : "1E127"},
{"g" : "\u{1E128}", "n" : "NYIAKENG PUACHUE HMONG LETTER O", "h" : "1E128"},
{"g" : "\u{1E129}", "n" : "NYIAKENG PUACHUE HMONG LETTER OO", "h" : "1E129"},
{"g" : "\u{1E12A}", "n" : "NYIAKENG PUACHUE HMONG LETTER E", "h" : "1E12A"},
{"g" : "\u{1E12B}", "n" : "NYIAKENG PUACHUE HMONG LETTER EE", "h" : "1E12B"},
{"g" : "\u{1E12C}", "n" : "NYIAKENG PUACHUE HMONG LETTER W", "h" : "1E12C"},

{"g" : "\u{1E130}", "n" : "NYIAKENG PUACHUE HMONG TONE-B", "h" : "1E130"},
{"g" : "\u{1E131}", "n" : "NYIAKENG PUACHUE HMONG TONE-M", "h" : "1E131"},
{"g" : "\u{1E132}", "n" : "NYIAKENG PUACHUE HMONG TONE-J", "h" : "1E132"},
{"g" : "\u{1E133}", "n" : "NYIAKENG PUACHUE HMONG TONE-V", "h" : "1E133"},
{"g" : "\u{1E134}", "n" : "NYIAKENG PUACHUE HMONG TONE-S", "h" : "1E134"},
{"g" : "\u{1E135}", "n" : "NYIAKENG PUACHUE HMONG TONE-G", "h" : "1E135"},
{"g" : "\u{1E136}", "n" : "NYIAKENG PUACHUE HMONG TONE-D", "h" : "1E136"},
{"g" : "\u{1E137}", "n" : "NYIAKENG PUACHUE HMONG SIGN FOR PERSON", "h" : "1E137"},
{"g" : "\u{1E138}", "n" : "NYIAKENG PUACHUE HMONG SIGN FOR THING", "h" : "1E138"},
{"g" : "\u{1E139}", "n" : "NYIAKENG PUACHUE HMONG SIGN FOR LOCATION", "h" : "1E139"},
{"g" : "\u{1E13A}", "n" : "NYIAKENG PUACHUE HMONG SIGN FOR ANIMAL", "h" : "1E13A"},
{"g" : "\u{1E13B}", "n" : "NYIAKENG PUACHUE HMONG SIGN FOR INVERTEBRATE", "h" : "1E13B"},
{"g" : "\u{1E13C}", "n" : "NYIAKENG PUACHUE HMONG SIGN XW XW", "h" : "1E13C"},
{"g" : "\u{1E13D}", "n" : "NYIAKENG PUACHUE HMONG SYLLABLE LENGTHENER", "h" : "1E13D"},

{"g" : "\u{1E140}", "n" : "NYIAKENG PUACHUE HMONG DIGIT ZERO", "h" : "1E140"},
{"g" : "\u{1E141}", "n" : "NYIAKENG PUACHUE HMONG DIGIT ONE", "h" : "1E141"},
{"g" : "\u{1E142}", "n" : "NYIAKENG PUACHUE HMONG DIGIT TWO", "h" : "1E142"},
{"g" : "\u{1E143}", "n" : "NYIAKENG PUACHUE HMONG DIGIT THREE", "h" : "1E143"},
{"g" : "\u{1E144}", "n" : "NYIAKENG PUACHUE HMONG DIGIT FOUR", "h" : "1E144"},
{"g" : "\u{1E145}", "n" : "NYIAKENG PUACHUE HMONG DIGIT FIVE", "h" : "1E145"},
{"g" : "\u{1E146}", "n" : "NYIAKENG PUACHUE HMONG DIGIT SIX", "h" : "1E146"},
{"g" : "\u{1E147}", "n" : "NYIAKENG PUACHUE HMONG DIGIT SEVEN", "h" : "1E147"},
{"g" : "\u{1E148}", "n" : "NYIAKENG PUACHUE HMONG DIGIT EIGHT", "h" : "1E148"},
{"g" : "\u{1E149}", "n" : "NYIAKENG PUACHUE HMONG DIGIT NINE", "h" : "1E149"},

{"g" : "\u{1E14E}", "n" : "NYIAKENG PUACHUE HMONG LOGOGRAM NYAJ", "h" : "1E14E"},
{"g" : "\u{1E14F}", "n" : "NYIAKENG PUACHUE HMONG CIRCLED CA", "h" : "1E14F"}
];
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    		var myPara1 = document.createElement('p');
    		var myPara2 = document.createElement('p');
    		var myPara3 = document.createElement('p');
		var myPara4 = document.createElement('p');
		var myPara5 = document.createElement('p');
		var myPara6 = document.createElement('p');

    		myPara1.textContent = glyph;
    		myPara2.textContent = name;
    		myPara3.textContent = 'U+' + hex;
		myPara4.textContent = '&#x' + hex + ';';
		myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
		myPara6.textContent = '\\' + 'u' + hex;

    		myArticle.appendChild(myPara1);
    		myArticle.appendChild(myPara2);
    		myArticle.appendChild(myPara3);
		myArticle.appendChild(myPara4);
		myArticle.appendChild(myPara5);
		myArticle.appendChild(myPara6);

    		section.appendChild(myArticle);
  }
}
