var section = document.querySelector('section');
window.addEventListener('DOMContentLoaded', (event) => {
    showCodepoints(Array);
});

function showCodepoints(arrayObj) {
var codepoints = [
{"g" : "\u0000", "n" : "NULL", "h" : "0000" },
{"g" : "\u0001", "n" : "START OF HEADING", "h" : "0001" },
{"g" : "\u0002", "n" : "START OF TEXT", "h" : "0002" },
{"g" : "\u0003", "n" : "END OF TEXT", "h" : "0003" },
{"g" : "\u0004", "n" : "END OF TRANSMISSION", "h" : "0004" },
{"g" : "\u0005", "n" : "ENQUIRY", "h" : "0005" },
{"g" : "\u0006", "n" : "ACKNOWLEDGE", "h" : "0006" },
{"g" : "\u0007", "n" : "BELL", "h" : "0007" },
{"g" : "\u0008", "n" : "BACKSPACE", "h" : "0008" },
{"g" : "\u0009", "n" : "CHARACTER TABULATION", "h" : "0009" },
{"g" : "\u000A", "n" : "LINE FEED (LF)", "h" : "000A" },
{"g" : "\u000B", "n" : "LINE TABULATION", "h" : "000B" },
{"g" : "\u000C", "n" : "FORM FEED (FF)", "h" : "000C" },
{"g" : "\u000D", "n" : "CARRIAGE RETURN (CR)", "h" : "000D" },
{"g" : "\u000E", "n" : "SHIFT OUT", "h" : "000E" },
{"g" : "\u000F", "n" : "SHIFT IN", "h" : "000F" },
{"g" : "\u0010", "n" : "DATA LINK ESCAPE", "h" : "0010" },
{"g" : "\u0011", "n" : "DEVICE CONTROL ONE", "h" : "0011" },
{"g" : "\u0012", "n" : "DEVICE CONTROL TWO", "h" : "0012" },
{"g" : "\u0013", "n" : "DEVICE CONTROL THREE", "h" : "0013" },
{"g" : "\u0014", "n" : "DEVICE CONTROL FOUR", "h" : "0014" },
{"g" : "\u0015", "n" : "NEGATIVE ACKNOWLEDGE", "h" : "0015" },
{"g" : "\u0016", "n" : "SYNCHRONOUS IDLE", "h" : "0016" },
{"g" : "\u0017", "n" : "END OF TRANSMISSION BLOCK", "h" : "0017" },
{"g" : "\u0018", "n" : "CANCEL", "h" : "0018" },
{"g" : "\u0019", "n" : "END OF MEDIUM", "h" : "0019" },
{"g" : "\u001A", "n" : "SUBSTITUTE", "h" : "001A" },
{"g" : "\u001B", "n" : "ESCAPE", "h" : "001B" },
{"g" : "\u001C", "n" : "INFORMATION SEPARATOR FOUR", "h" : "001C" },
{"g" : "\u001D", "n" : "INFORMATION SEPARATOR THREE", "h" : "001D" },
{"g" : "\u001E", "n" : "INFORMATION SEPARATOR TWO", "h" : "001E" },
{"g" : "\u001F", "n" : "INFORMATION SEPARATOR ONE", "h" : "001F" },
{"g" : "\u0020", "n" : "SPACE", "h" : "0020" },

{"g" : "\u0080", "n" : "<control>", "h" : "0080" },
{"g" : "\u0081", "n" : "<control>", "h" : "0081" },
{"g" : "\u0082", "n" : "BREAK PERMITTED HERE", "h" : "0082" },
{"g" : "\u0083", "n" : "NO BREAK HERE", "h" : "0083" },
{"g" : "\u0084", "n" : "<control>", "h" : "0084" },
{"g" : "\u0085", "n" : "NEXT LINE (NEL)", "h" : "0085" },
{"g" : "\u0086", "n" : "START OF SELECTED AREA", "h" : "0086" },
{"g" : "\u0087", "n" : "END OF SELECTED AREA", "h" : "0087" },
{"g" : "\u0088", "n" : "CHARACTER TABULATION SET", "h" : "0088" },
{"g" : "\u0089", "n" : "CHARACTER TABULATION WITH JUSTIFICATION", "h" : "0089" },
{"g" : "\u008A", "n" : "LINE TABULATION SET", "h" : "008A" },
{"g" : "\u008B", "n" : "PARTIAL LINE FORWARD", "h" : "008B" },
{"g" : "\u008C", "n" : "PARTIAL LINE BACKWARD", "h" : "008C" },
{"g" : "\u008D", "n" : "REVERSE LINE FEED", "h" : "008D" },
{"g" : "\u008E", "n" : "SINGLE SHIFT TWO", "h" : "008E" },
{"g" : "\u008F", "n" : "SINGLE SHIFT THREE", "h" : "008F" },
{"g" : "\u0090", "n" : "DEVICE CONTROL STRING", "h" : "0090" },
{"g" : "\u0091", "n" : "PRIVATE USE ONE", "h" : "0091" },
{"g" : "\u0092", "n" : "PRIVATE USE TWO", "h" : "0092" },
{"g" : "\u0093", "n" : "SET TRANSMIT STATE", "h" : "0093" },
{"g" : "\u0094", "n" : "CANCEL CHARACTER", "h" : "0094" },
{"g" : "\u0095", "n" : "MESSAGE WAITING", "h" : "0095" },
{"g" : "\u0096", "n" : "START OF GUARDED AREA", "h" : "0096" },
{"g" : "\u0097", "n" : "END OF GUARDED AREA", "h" : "0097" },
{"g" : "\u0098", "n" : "START OF STRING", "h" : "0098" },
{"g" : "\u0099", "n" : "<control>", "h" : "0099" },
{"g" : "\u009A", "n" : "SINGLE CHARACTER INTRODUCER", "h" : "009A" },
{"g" : "\u009B", "n" : "CONTROL SEQUENCE INTRODUCER", "h" : "009B" },
{"g" : "\u009C", "n" : "STRING TERMINATOR", "h" : "009C" },
{"g" : "\u009D", "n" : "OPERATING SYSTEM COMMAND", "h" : "009D" },
{"g" : "\u009E", "n" : "PRIVACY MESSAGE", "h" : "009E" },
{"g" : "\u009F", "n" : "APPLICATION PROGRAM COMMAND", "h" : "009F" },
{"g" : "\u00A0", "n" : "NO-BREAK SPACE", "h" : "00A0" },
	
{"g" : "\u00AD", "n" : "SOFT HYPHEN", "h" : "00AD" },

{"g" : "\u2000", "n" : "EN QUAD", "h" : "2000" },
{"g" : "\u2001", "n" : "EM QUAD", "h" : "2001" },
{"g" : "\u2002", "n" : "EN SPACE", "h" : "2002" },
{"g" : "\u2003", "n" : "EM SPACE", "h" : "2003" },
{"g" : "\u2004", "n" : "THREE-PER-EM SPACE", "h" : "2004" },
{"g" : "\u2005", "n" : "FOUR-PER-EM SPACE", "h" : "2005" },
{"g" : "\u2006", "n" : "SIX-PER-EM SPACE", "h" : "2006" },
{"g" : "\u2007", "n" : "FIGURE SPACE", "h" : "2007" },
{"g" : "\u2008", "n" : "PUNCTUATION SPACE", "h" : "2008" },
{"g" : "\u2009", "n" : "THIN SPACE", "h" : "2009" },
{"g" : "\u200A", "n" : "HAIR SPACE", "h" : "200A" },
{"g" : "\u200B", "n" : "ZERO WIDTH SPACE", "h" : "200B" },
{"g" : "\u200C", "n" : "ZERO WIDTH NON-JOINER", "h" : "200C" },
{"g" : "\u200D", "n" : "ZERO WIDTH JOINER", "h" : "200D" },
{"g" : "\u200E", "n" : "LEFT-TO-RIGHT MARK", "h" : "200E" },
{"g" : "\u200F", "n" : "RIGHT-TO-LEFT MARK", "h" : "200F" },

{"g" : "\u2011", "n" : "NON-BREAKING HYPHEN", "h" : "2011" },

{"g" : "\u2028", "n" : "LINE SEPARATOR", "h" : "2028" },
{"g" : "\u2029", "n" : "PARAGRAPH SEPARATOR", "h" : "2029" },
{"g" : "\u202A", "n" : "LEFT-TO-RIGHT EMBEDDING", "h" : "202A" },
{"g" : "\u202B", "n" : "RIGHT-TO-LEFT EMBEDDING", "h" : "202B" },
{"g" : "\u202C", "n" : "POP DIRECTIONAL FORMATTING", "h" : "202C" },
{"g" : "\u202D", "n" : "LEFT-TO-RIGHT OVERRIDE", "h" : "202D" },
{"g" : "\u202E", "n" : "RIGHT-TO-LEFT OVERRIDE", "h" : "202E" },
{"g" : "\u202F", "n" : "NARROW NO-BREAK SPACE", "h" : "202F" },

{"g" : "\u205F", "n" : "MEDIUM MATHEMATICAL SPACE", "h" : "205F" },
{"g" : "\u2060", "n" : "WORD JOINER", "h" : "2060" },

{"g" : "\u2061", "n" : "FUNCTION APPLICATION", "h" : "2061" },
{"g" : "\u2062", "n" : "INVISIBLE TIMES", "h" : "2062" },
{"g" : "\u2063", "n" : "INVISIBLE SEPARATOR", "h" : "2063" },
{"g" : "\u2064", "n" : "INVISIBLE PLUS", "h" : "2064" },

{"g" : "\u2066", "n" : "LEFT-TO-RIGHT ISOLATE", "h" : "2066" },
{"g" : "\u2067", "n" : "RIGHT-TO-LEFT ISOLATE", "h" : "2067" },
{"g" : "\u2068", "n" : "FIRST STRONG ISOLATE", "h" : "2068" },
{"g" : "\u2069", "n" : "POP DIRECTIONAL ISOLATE", "h" : "2069" },
{"g" : "\u206A", "n" : "INHIBIT SYMMETRIC SWAPPING", "h" : "206A" },
{"g" : "\u206B", "n" : "ACTIVATE SYMMETRIC SWAPPING", "h" : "206B" },
{"g" : "\u206C", "n" : "INHIBIT ARABIC FORM SHAPING", "h" : "206C" },
{"g" : "\u206D", "n" : "ACTIVATE ARABIC FORM SHAPING", "h" : "206D" },
{"g" : "\u206E", "n" : "NATIONAL DIGIT SHAPES", "h" : "206E" },
{"g" : "\u206F", "n" : "NOMINAL DIGIT SHAPES", "h" : "206F" },

{"g" : "\u2300", "n" : "DIAMETER SIGN", "h" : "2300" },
{"g" : "\u2301", "n" : "ELECTRIC ARROW", "h" : "2301" },
{"g" : "\u2302", "n" : "HOUSE", "h" : "2302" },
{"g" : "\u2303", "n" : "UP ARROWHEAD", "h" : "2303" },
{"g" : "\u2304", "n" : "DOWN ARROWHEAD", "h" : "2304" },
{"g" : "\u2305", "n" : "PROJECTIVE", "h" : "2305" },
{"g" : "\u2306", "n" : "PERSPECTIVE", "h" : "2306" },
{"g" : "\u2307", "n" : "WAVY LINE", "h" : "2307" },

{"g" : "\u230C", "n" : "BOTTOM RIGHT CROP", "h" : "230C" },
{"g" : "\u230D", "n" : "BOTTOM LEFT CROP", "h" : "230D" },
{"g" : "\u230E", "n" : "TOP RIGHT CROP", "h" : "230E" },
{"g" : "\u230F", "n" : "TOP LEFT CROP", "h" : "230F" },
{"g" : "\u2310", "n" : "REVERSED NOT SIGN", "h" : "2310" },
{"g" : "\u2311", "n" : "SQUARE LOZENGE", "h" : "2311" },
{"g" : "\u2312", "n" : "ARC", "h" : "2312" },
{"g" : "\u2313", "n" : "SEGMENT", "h" : "2313" },
{"g" : "\u2314", "n" : "SECTOR", "h" : "2314" },
{"g" : "\u2315", "n" : "TELEPHONE RECORDER", "h" : "2315" },
{"g" : "\u2316", "n" : "POSITION INDICATOR", "h" : "2316" },
{"g" : "\u2317", "n" : "VIEWDATA SQUARE", "h" : "2317" },
{"g" : "\u2318", "n" : "PLACE OF INTEREST SIGN", "h" : "2318" },
{"g" : "\u2319", "n" : "TURNED NOT SIGN", "h" : "2319" },
{"g" : "\u231A", "n" : "WATCH", "h" : "231A" },
{"g" : "\u231B", "n" : "HOURGLASS", "h" : "231B" },
{"g" : "\u231C", "n" : "TOP LEFT CORNER", "h" : "231C" },
{"g" : "\u231D", "n" : "TOP RIGHT CORNER", "h" : "231D" },
{"g" : "\u231E", "n" : "BOTTOM LEFT CORNER", "h" : "231E" },
{"g" : "\u231F", "n" : "BOTTOM RIGHT CORNER", "h" : "231F" },
{"g" : "\u2320", "n" : "TOP HALF INTEGRAL", "h" : "2320" },
{"g" : "\u2321", "n" : "BOTTOM HALF INTEGRAL", "h" : "2321" },
{"g" : "\u2322", "n" : "FROWN", "h" : "2322" },
{"g" : "\u2323", "n" : "SMILE", "h" : "2323" },
{"g" : "\u2324", "n" : "UP ARROWHEAD BETWEEN TWO HORIZONTAL BARS", "h" : "2324" },
{"g" : "\u2325", "n" : "OPTION KEY", "h" : "2325" },
{"g" : "\u2326", "n" : "ERASE TO THE RIGHT", "h" : "2326" },
{"g" : "\u2327", "n" : "X IN A RECTANGLE BOX", "h" : "2327" },
{"g" : "\u2328", "n" : "KEYBOARD", "h" : "2328" },
{"g" : "\u2329", "n" : "LEFT-POINTING ANGLE BRACKET", "h" : "2329" },
{"g" : "\u232A", "n" : "RIGHT-POINTING ANGLE BRACKET", "h" : "232A" },
{"g" : "\u232B", "n" : "ERASE TO THE LEFT", "h" : "232B" },
{"g" : "\u232C", "n" : "BENZENE RING", "h" : "232C" },
{"g" : "\u232D", "n" : "CYLINDRICITY", "h" : "232D" },
{"g" : "\u232E", "n" : "ALL AROUND-PROFILE", "h" : "232E" },
{"g" : "\u232F", "n" : "SYMMETRY", "h" : "232F" },
{"g" : "\u2330", "n" : "TOTAL RUNOUT", "h" : "2330" },
{"g" : "\u2331", "n" : "DIMENSION ORIGIN", "h" : "2331" },
{"g" : "\u2332", "n" : "CONICAL TAPER", "h" : "2332" },
{"g" : "\u2333", "n" : "SLOPE", "h" : "2333" },
{"g" : "\u2334", "n" : "COUNTERBORE", "h" : "2334" },
{"g" : "\u2335", "n" : "COUNTERSINK", "h" : "2335" },
{"g" : "\u2336", "n" : "APL FUNCTIONAL SYMBOL I-BEAM", "h" : "2336" },
{"g" : "\u2337", "n" : "APL FUNCTIONAL SYMBOL SQUISH QUAD", "h" : "2337" },
{"g" : "\u2338", "n" : "APL FUNCTIONAL SYMBOL QUAD EQUAL", "h" : "2338" },
{"g" : "\u2339", "n" : "APL FUNCTIONAL SYMBOL QUAD DIVIDE", "h" : "2339" },
{"g" : "\u233A", "n" : "APL FUNCTIONAL SYMBOL QUAD DIAMOND", "h" : "233A" },
{"g" : "\u233B", "n" : "APL FUNCTIONAL SYMBOL QUAD JOT", "h" : "233B" },
{"g" : "\u233C", "n" : "APL FUNCTIONAL SYMBOL QUAD CIRCLE", "h" : "233C" },
{"g" : "\u233D", "n" : "APL FUNCTIONAL SYMBOL CIRCLE STILE", "h" : "233D" },
{"g" : "\u233E", "n" : "APL FUNCTIONAL SYMBOL CIRCLE JOT", "h" : "233E" },
{"g" : "\u233F", "n" : "APL FUNCTIONAL SYMBOL SLASH BAR", "h" : "233F" },
{"g" : "\u2340", "n" : "APL FUNCTIONAL SYMBOL BACKSLASH BAR", "h" : "2340" },
{"g" : "\u2341", "n" : "APL FUNCTIONAL SYMBOL QUAD SLASH", "h" : "2341" },
{"g" : "\u2342", "n" : "APL FUNCTIONAL SYMBOL QUAD BACKSLASH", "h" : "2342" },
{"g" : "\u2343", "n" : "APL FUNCTIONAL SYMBOL QUAD LESS-THAN", "h" : "2343" },
{"g" : "\u2344", "n" : "APL FUNCTIONAL SYMBOL QUAD GREATER-THAN", "h" : "2344" },
{"g" : "\u2345", "n" : "APL FUNCTIONAL SYMBOL LEFTWARDS VANE", "h" : "2345" },
{"g" : "\u2346", "n" : "APL FUNCTIONAL SYMBOL RIGHTWARDS VANE", "h" : "2346" },
{"g" : "\u2347", "n" : "APL FUNCTIONAL SYMBOL QUAD LEFTWARDS ARROW", "h" : "2347" },
{"g" : "\u2348", "n" : "APL FUNCTIONAL SYMBOL QUAD RIGHTWARDS ARROW", "h" : "2348" },
{"g" : "\u2349", "n" : "APL FUNCTIONAL SYMBOL CIRCLE BACKSLASH", "h" : "2349" },
{"g" : "\u234A", "n" : "APL FUNCTIONAL SYMBOL DOWN TACK UNDERBAR", "h" : "234A" },
{"g" : "\u234B", "n" : "APL FUNCTIONAL SYMBOL DELTA STILE", "h" : "234B" },
{"g" : "\u234C", "n" : "APL FUNCTIONAL SYMBOL QUAD DOWN CARET", "h" : "234C" },
{"g" : "\u234D", "n" : "APL FUNCTIONAL SYMBOL QUAD DELTA", "h" : "234D" },
{"g" : "\u234E", "n" : "APL FUNCTIONAL SYMBOL DOWN TACK JOT", "h" : "234E" },
{"g" : "\u234F", "n" : "APL FUNCTIONAL SYMBOL UPWARDS VANE", "h" : "234F" },
{"g" : "\u2350", "n" : "APL FUNCTIONAL SYMBOL QUAD UPWARDS ARROW", "h" : "2350" },
{"g" : "\u2351", "n" : "APL FUNCTIONAL SYMBOL UP TACK OVERBAR", "h" : "2351" },
{"g" : "\u2352", "n" : "APL FUNCTIONAL SYMBOL DEL STILE", "h" : "2352" },
{"g" : "\u2353", "n" : "APL FUNCTIONAL SYMBOL QUAD UP CARET", "h" : "2353" },
{"g" : "\u2354", "n" : "APL FUNCTIONAL SYMBOL QUAD DEL", "h" : "2354" },
{"g" : "\u2355", "n" : "APL FUNCTIONAL SYMBOL UP TACK JOT", "h" : "2355" },
{"g" : "\u2356", "n" : "APL FUNCTIONAL SYMBOL DOWNWARDS VANE", "h" : "2356" },
{"g" : "\u2357", "n" : "APL FUNCTIONAL SYMBOL QUAD DOWNWARDS ARROW", "h" : "2357" },
{"g" : "\u2358", "n" : "APL FUNCTIONAL SYMBOL QUOTE UNDERBAR", "h" : "2358" },
{"g" : "\u2359", "n" : "APL FUNCTIONAL SYMBOL DELTA UNDERBAR", "h" : "2359" },
{"g" : "\u235A", "n" : "APL FUNCTIONAL SYMBOL DIAMOND UNDERBAR", "h" : "235A" },
{"g" : "\u235B", "n" : "APL FUNCTIONAL SYMBOL JOT UNDERBAR", "h" : "235B" },
{"g" : "\u235C", "n" : "APL FUNCTIONAL SYMBOL CIRCLE UNDERBAR", "h" : "235C" },
{"g" : "\u235D", "n" : "APL FUNCTIONAL SYMBOL UP SHOE JOT", "h" : "235D" },
{"g" : "\u235E", "n" : "APL FUNCTIONAL SYMBOL QUOTE QUAD", "h" : "235E" },
{"g" : "\u235F", "n" : "APL FUNCTIONAL SYMBOL CIRCLE STAR", "h" : "235F" },
{"g" : "\u2360", "n" : "APL FUNCTIONAL SYMBOL QUAD COLON", "h" : "2360" },
{"g" : "\u2361", "n" : "APL FUNCTIONAL SYMBOL UP TACK DIAERESIS", "h" : "2361" },
{"g" : "\u2362", "n" : "APL FUNCTIONAL SYMBOL DEL DIAERESIS", "h" : "2362" },
{"g" : "\u2363", "n" : "APL FUNCTIONAL SYMBOL STAR DIAERESIS", "h" : "2363" },
{"g" : "\u2364", "n" : "APL FUNCTIONAL SYMBOL JOT DIAERESIS", "h" : "2364" },
{"g" : "\u2365", "n" : "APL FUNCTIONAL SYMBOL CIRCLE DIAERESIS", "h" : "2365" },
{"g" : "\u2366", "n" : "APL FUNCTIONAL SYMBOL DOWN SHOE STILE", "h" : "2366" },
{"g" : "\u2367", "n" : "APL FUNCTIONAL SYMBOL LEFT SHOE STILE", "h" : "2367" },
{"g" : "\u2368", "n" : "APL FUNCTIONAL SYMBOL TILDE DIAERESIS", "h" : "2368" },
{"g" : "\u2369", "n" : "APL FUNCTIONAL SYMBOL GREATER-THAN DIAERESIS", "h" : "2369" },
{"g" : "\u236A", "n" : "APL FUNCTIONAL SYMBOL COMMA BAR", "h" : "236A" },
{"g" : "\u236B", "n" : "APL FUNCTIONAL SYMBOL DEL TILDE", "h" : "236B" },
{"g" : "\u236C", "n" : "APL FUNCTIONAL SYMBOL ZILDE", "h" : "236C" },
{"g" : "\u236D", "n" : "APL FUNCTIONAL SYMBOL STILE TILDE", "h" : "236D" },
{"g" : "\u236E", "n" : "APL FUNCTIONAL SYMBOL SEMICOLON UNDERBAR", "h" : "236E" },
{"g" : "\u236F", "n" : "APL FUNCTIONAL SYMBOL QUAD NOT EQUAL", "h" : "236F" },
{"g" : "\u2370", "n" : "APL FUNCTIONAL SYMBOL QUAD QUESTION", "h" : "2370" },
{"g" : "\u2371", "n" : "APL FUNCTIONAL SYMBOL DOWN CARET TILDE", "h" : "2371" },
{"g" : "\u2372", "n" : "APL FUNCTIONAL SYMBOL UP CARET TILDE", "h" : "2372" },
{"g" : "\u2373", "n" : "APL FUNCTIONAL SYMBOL IOTA", "h" : "2373" },
{"g" : "\u2374", "n" : "APL FUNCTIONAL SYMBOL RHO", "h" : "2374" },
{"g" : "\u2375", "n" : "APL FUNCTIONAL SYMBOL OMEGA", "h" : "2375" },
{"g" : "\u2376", "n" : "APL FUNCTIONAL SYMBOL ALPHA UNDERBAR", "h" : "2376" },
{"g" : "\u2377", "n" : "APL FUNCTIONAL SYMBOL EPSILON UNDERBAR", "h" : "2377" },
{"g" : "\u2378", "n" : "APL FUNCTIONAL SYMBOL IOTA UNDERBAR", "h" : "2378" },
{"g" : "\u2379", "n" : "APL FUNCTIONAL SYMBOL OMEGA UNDERBAR", "h" : "2379" },
{"g" : "\u237A", "n" : "APL FUNCTIONAL SYMBOL ALPHA", "h" : "237A" },
{"g" : "\u237B", "n" : "NOT CHECK MARK", "h" : "237B" },
{"g" : "\u237C", "n" : "RIGHT ANGLE WITH DOWNWARDS ZIGZAG ARROW", "h" : "237C" },
{"g" : "\u237D", "n" : "SHOULDERED OPEN BOX", "h" : "237D" },
{"g" : "\u237E", "n" : "BELL SYMBOL", "h" : "237E" },
{"g" : "\u237F", "n" : "VERTICAL LINE WITH MIDDLE DOT", "h" : "237F" },
{"g" : "\u2380", "n" : "INSERTION SYMBOL", "h" : "2380" },
{"g" : "\u2381", "n" : "CONTINUOUS UNDERLINE SYMBOL", "h" : "2381" },
{"g" : "\u2382", "n" : "DISCONTINUOUS UNDERLINE SYMBOL", "h" : "2382" },
{"g" : "\u2383", "n" : "EMPHASIS SYMBOL", "h" : "2383" },
{"g" : "\u2384", "n" : "COMPOSITION SYMBOL", "h" : "2384" },
{"g" : "\u2385", "n" : "WHITE SQUARE WITH CENTRE VERTICAL LINE", "h" : "2385" },
{"g" : "\u2386", "n" : "ENTER SYMBOL", "h" : "2386" },
{"g" : "\u2387", "n" : "ALTERNATIVE KEY SYMBOL", "h" : "2387" },
{"g" : "\u2388", "n" : "HELM SYMBOL", "h" : "2388" },
{"g" : "\u2389", "n" : "CIRCLED HORIZONTAL BAR WITH NOTCH", "h" : "2389" },
{"g" : "\u238A", "n" : "CIRCLED TRIANGLE DOWN", "h" : "238A" },
{"g" : "\u238B", "n" : "BROKEN CIRCLE WITH NORTHWEST ARROW", "h" : "238B" },
{"g" : "\u238C", "n" : "UNDO SYMBOL", "h" : "238C" },
{"g" : "\u238D", "n" : "MONOSTABLE SYMBOL", "h" : "238D" },
{"g" : "\u238E", "n" : "HYSTERESIS SYMBOL", "h" : "238E" },
{"g" : "\u238F", "n" : "OPEN-CIRCUIT-OUTPUT H-TYPE SYMBOL", "h" : "238F" },
{"g" : "\u2390", "n" : "OPEN-CIRCUIT-OUTPUT L-TYPE SYMBOL", "h" : "2390" },
{"g" : "\u2391", "n" : "PASSIVE-PULL-DOWN-OUTPUT SYMBOL", "h" : "2391" },
{"g" : "\u2392", "n" : "PASSIVE-PULL-UP-OUTPUT SYMBOL", "h" : "2392" },
{"g" : "\u2393", "n" : "DIRECT CURRENT SYMBOL FORM TWO", "h" : "2393" },
{"g" : "\u2394", "n" : "SOFTWARE-FUNCTION SYMBOL", "h" : "2394" },
{"g" : "\u2395", "n" : "APL FUNCTIONAL SYMBOL QUAD", "h" : "2395" },
{"g" : "\u2396", "n" : "DECIMAL SEPARATOR KEY SYMBOL", "h" : "2396" },
{"g" : "\u2397", "n" : "PREVIOUS PAGE", "h" : "2397" },
{"g" : "\u2398", "n" : "NEXT PAGE", "h" : "2398" },
{"g" : "\u2399", "n" : "PRINT SCREEN SYMBOL", "h" : "2399" },
{"g" : "\u239A", "n" : "CLEAR SCREEN SYMBOL", "h" : "239A" },
{"g" : "\u239B", "n" : "LEFT PARENTHESIS UPPER HOOK", "h" : "239B" },
{"g" : "\u239C", "n" : "LEFT PARENTHESIS EXTENSION", "h" : "239C" },
{"g" : "\u239D", "n" : "LEFT PARENTHESIS LOWER HOOK", "h" : "239D" },
{"g" : "\u239E", "n" : "RIGHT PARENTHESIS UPPER HOOK", "h" : "239E" },
{"g" : "\u239F", "n" : "RIGHT PARENTHESIS EXTENSION", "h" : "239F" },
{"g" : "\u23A0", "n" : "RIGHT PARENTHESIS LOWER HOOK", "h" : "23A0" },
{"g" : "\u23A1", "n" : "LEFT SQUARE BRACKET UPPER CORNER", "h" : "23A1" },
{"g" : "\u23A2", "n" : "LEFT SQUARE BRACKET EXTENSION", "h" : "23A2" },
{"g" : "\u23A3", "n" : "LEFT SQUARE BRACKET LOWER CORNER", "h" : "23A3" },
{"g" : "\u23A4", "n" : "RIGHT SQUARE BRACKET UPPER CORNER", "h" : "23A4" },
{"g" : "\u23A5", "n" : "RIGHT SQUARE BRACKET EXTENSION", "h" : "23A5" },
{"g" : "\u23A6", "n" : "RIGHT SQUARE BRACKET LOWER CORNER", "h" : "23A6" },
{"g" : "\u23A7", "n" : "LEFT CURLY BRACKET UPPER HOOK", "h" : "23A7" },
{"g" : "\u23A8", "n" : "LEFT CURLY BRACKET MIDDLE PIECE", "h" : "23A8" },
{"g" : "\u23A9", "n" : "LEFT CURLY BRACKET LOWER HOOK", "h" : "23A9" },
{"g" : "\u23AA", "n" : "CURLY BRACKET EXTENSION", "h" : "23AA" },
{"g" : "\u23AB", "n" : "RIGHT CURLY BRACKET UPPER HOOK", "h" : "23AB" },
{"g" : "\u23AC", "n" : "RIGHT CURLY BRACKET MIDDLE PIECE", "h" : "23AC" },
{"g" : "\u23AD", "n" : "RIGHT CURLY BRACKET LOWER HOOK", "h" : "23AD" },
{"g" : "\u23AE", "n" : "INTEGRAL EXTENSION", "h" : "23AE" },
{"g" : "\u23AF", "n" : "HORIZONTAL LINE EXTENSION", "h" : "23AF" },
{"g" : "\u23B0", "n" : "UPPER LEFT OR LOWER RIGHT CURLY BRACKET SECTION", "h" : "23B0" },
{"g" : "\u23B1", "n" : "UPPER RIGHT OR LOWER LEFT CURLY BRACKET SECTION", "h" : "23B1" },
{"g" : "\u23B2", "n" : "SUMMATION TOP", "h" : "23B2" },
{"g" : "\u23B3", "n" : "SUMMATION BOTTOM", "h" : "23B3" },
{"g" : "\u23B4", "n" : "TOP SQUARE BRACKET", "h" : "23B4" },
{"g" : "\u23B5", "n" : "BOTTOM SQUARE BRACKET", "h" : "23B5" },
{"g" : "\u23B6", "n" : "BOTTOM SQUARE BRACKET OVER TOP SQUARE BRACKET", "h" : "23B6" },
{"g" : "\u23B7", "n" : "RADICAL SYMBOL BOTTOM", "h" : "23B7" },
{"g" : "\u23B8", "n" : "LEFT VERTICAL BOX LINE", "h" : "23B8" },
{"g" : "\u23B9", "n" : "RIGHT VERTICAL BOX LINE", "h" : "23B9" },
{"g" : "\u23BA", "n" : "HORIZONTAL SCAN LINE-1", "h" : "23BA" },
{"g" : "\u23BB", "n" : "HORIZONTAL SCAN LINE-3", "h" : "23BB" },
{"g" : "\u23BC", "n" : "HORIZONTAL SCAN LINE-7", "h" : "23BC" },
{"g" : "\u23BD", "n" : "HORIZONTAL SCAN LINE-9", "h" : "23BD" },
{"g" : "\u23BE", "n" : "DENTISTRY SYMBOL LIGHT VERTICAL AND TOP RIGHT", "h" : "23BE" },
{"g" : "\u23BF", "n" : "DENTISTRY SYMBOL LIGHT VERTICAL AND BOTTOM RIGHT", "h" : "23BF" },
{"g" : "\u23C0", "n" : "DENTISTRY SYMBOL LIGHT VERTICAL WITH CIRCLE", "h" : "23C0" },
{"g" : "\u23C1", "n" : "DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH CIRCLE", "h" : "23C1" },
{"g" : "\u23C2", "n" : "DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH CIRCLE", "h" : "23C2" },
{"g" : "\u23C3", "n" : "DENTISTRY SYMBOL LIGHT VERTICAL WITH TRIANGLE", "h" : "23C3" },
{"g" : "\u23C4", "n" : "DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH TRIANGLE", "h" : "23C4" },
{"g" : "\u23C5", "n" : "DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH TRIANGLE", "h" : "23C5" },
{"g" : "\u23C6", "n" : "DENTISTRY SYMBOL LIGHT VERTICAL AND WAVE", "h" : "23C6" },
{"g" : "\u23C7", "n" : "DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH WAVE", "h" : "23C7" },
{"g" : "\u23C8", "n" : "DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH WAVE", "h" : "23C8" },
{"g" : "\u23C9", "n" : "DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL", "h" : "23C9" },
{"g" : "\u23CA", "n" : "DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL", "h" : "23CA" },
{"g" : "\u23CB", "n" : "DENTISTRY SYMBOL LIGHT VERTICAL AND TOP LEFT", "h" : "23CB" },
{"g" : "\u23CC", "n" : "DENTISTRY SYMBOL LIGHT VERTICAL AND BOTTOM LEFT", "h" : "23CC" },
{"g" : "\u23CD", "n" : "SQUARE FOOT", "h" : "23CD" },
{"g" : "\u23CE", "n" : "RETURN SYMBOL", "h" : "23CE" },
{"g" : "\u23CF", "n" : "EJECT SYMBOL", "h" : "23CF" },
{"g" : "\u23D0", "n" : "VERTICAL LINE EXTENSION", "h" : "23D0" },
{"g" : "\u23D1", "n" : "METRICAL BREVE", "h" : "23D1" },
{"g" : "\u23D2", "n" : "METRICAL LONG OVER SHORT", "h" : "23D2" },
{"g" : "\u23D3", "n" : "METRICAL SHORT OVER LONG", "h" : "23D3" },
{"g" : "\u23D4", "n" : "METRICAL LONG OVER TWO SHORTS", "h" : "23D4" },
{"g" : "\u23D5", "n" : "METRICAL TWO SHORTS OVER LONG", "h" : "23D5" },
{"g" : "\u23D6", "n" : "METRICAL TWO SHORTS JOINED", "h" : "23D6" },
{"g" : "\u23D7", "n" : "METRICAL TRISEME", "h" : "23D7" },
{"g" : "\u23D8", "n" : "METRICAL TETRASEME", "h" : "23D8" },
{"g" : "\u23D9", "n" : "METRICAL PENTASEME", "h" : "23D9" },
{"g" : "\u23DA", "n" : "EARTH GROUND", "h" : "23DA" },
{"g" : "\u23DB", "n" : "FUSE", "h" : "23DB" },
{"g" : "\u23DC", "n" : "TOP PARENTHESIS", "h" : "23DC" },
{"g" : "\u23DD", "n" : "BOTTOM PARENTHESIS", "h" : "23DD" },
{"g" : "\u23DE", "n" : "TOP CURLY BRACKET", "h" : "23DE" },
{"g" : "\u23DF", "n" : "BOTTOM CURLY BRACKET", "h" : "23DF" },
{"g" : "\u23E0", "n" : "TOP TORTOISE SHELL BRACKET", "h" : "23E0" },
{"g" : "\u23E1", "n" : "BOTTOM TORTOISE SHELL BRACKET", "h" : "23E1" },
{"g" : "\u23E2", "n" : "WHITE TRAPEZIUM", "h" : "23E2" },
{"g" : "\u23E3", "n" : "BENZENE RING WITH CIRCLE", "h" : "23E3" },
{"g" : "\u23E4", "n" : "STRAIGHTNESS", "h" : "23E4" },
{"g" : "\u23E5", "n" : "FLATNESS", "h" : "23E5" },
{"g" : "\u23E6", "n" : "AC CURRENT", "h" : "23E6" },
{"g" : "\u23E7", "n" : "ELECTRICAL INTERSECTION", "h" : "23E7" },
{"g" : "\u23E8", "n" : "DECIMAL EXPONENT SYMBOL", "h" : "23E8" },
{"g" : "\u23E9", "n" : "BLACK RIGHT-POINTING DOUBLE TRIANGLE", "h" : "23E9" },
{"g" : "\u23EA", "n" : "BLACK LEFT-POINTING DOUBLE TRIANGLE", "h" : "23EA" },
{"g" : "\u23EB", "n" : "BLACK UP-POINTING DOUBLE TRIANGLE", "h" : "23EB" },
{"g" : "\u23EC", "n" : "BLACK DOWN-POINTING DOUBLE TRIANGLE", "h" : "23EC" },
{"g" : "\u23ED", "n" : "BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR", "h" : "23ED" },
{"g" : "\u23EE", "n" : "BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR", "h" : "23EE" },
{"g" : "\u23EF", "n" : "BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR", "h" : "23EF" },
{"g" : "\u23F0", "n" : "ALARM CLOCK", "h" : "23F0" },
{"g" : "\u23F1", "n" : "STOPWATCH", "h" : "23F1" },
{"g" : "\u23F2", "n" : "TIMER CLOCK", "h" : "23F2" },
{"g" : "\u23F3", "n" : "HOURGLASS WITH FLOWING SAND", "h" : "23F3" },
{"g" : "\u23F4", "n" : "BLACK MEDIUM LEFT-POINTING TRIANGLE", "h" : "23F4" },
{"g" : "\u23F5", "n" : "BLACK MEDIUM RIGHT-POINTING TRIANGLE", "h" : "23F5" },
{"g" : "\u23F6", "n" : "BLACK MEDIUM UP-POINTING TRIANGLE", "h" : "23F6" },
{"g" : "\u23F7", "n" : "BLACK MEDIUM DOWN-POINTING TRIANGLE", "h" : "23F7" },
{"g" : "\u23F8", "n" : "DOUBLE VERTICAL BAR", "h" : "23F8" },
{"g" : "\u23F9", "n" : "BLACK SQUARE FOR STOP", "h" : "23F9" },
{"g" : "\u23FA", "n" : "BLACK CIRCLE FOR RECORD", "h" : "23FA" },
{"g" : "\u23FB", "n" : "POWER SYMBOL", "h" : "23FB" },
{"g" : "\u23FC", "n" : "POWER ON-OFF SYMBOL", "h" : "23FC" },
{"g" : "\u23FD", "n" : "POWER ON SYMBOL", "h" : "23FD" },
{"g" : "\u23FE", "n" : "POWER SLEEP SYMBOL", "h" : "23FE" },
{"g" : "\u23FF", "n" : "OBSERVER EYE SYMBOL", "h" : "23FF" },

{"g" : "\u2400", "n" : "SYMBOL FOR NULL", "h" : "2400" },
{"g" : "\u2401", "n" : "SYMBOL FOR START OF HEADING", "h" : "2401" },
{"g" : "\u2402", "n" : "SYMBOL FOR START OF TEXT", "h" : "2402" },
{"g" : "\u2403", "n" : "SYMBOL FOR END OF TEXT", "h" : "2403" },
{"g" : "\u2404", "n" : "SYMBOL FOR END OF TRANSMISSION", "h" : "2404" },
{"g" : "\u2405", "n" : "SYMBOL FOR ENQUIRY", "h" : "2405" },
{"g" : "\u2406", "n" : "SYMBOL FOR ACKNOWLEDGE", "h" : "2406" },
{"g" : "\u2407", "n" : "SYMBOL FOR BELL", "h" : "2407" },
{"g" : "\u2408", "n" : "SYMBOL FOR BACKSPACE", "h" : "2408" },
{"g" : "\u2409", "n" : "SYMBOL FOR HORIZONTAL TABULATION", "h" : "2409" },
{"g" : "\u240A", "n" : "SYMBOL FOR LINE FEED", "h" : "240A" },
{"g" : "\u240B", "n" : "SYMBOL FOR VERTICAL TABULATION", "h" : "240B" },
{"g" : "\u240C", "n" : "SYMBOL FOR FORM FEED", "h" : "240C" },
{"g" : "\u240D", "n" : "SYMBOL FOR CARRIAGE RETURN", "h" : "240D" },
{"g" : "\u240E", "n" : "SYMBOL FOR SHIFT OUT", "h" : "240E" },
{"g" : "\u240F", "n" : "SYMBOL FOR SHIFT IN", "h" : "240F" },
{"g" : "\u2410", "n" : "SYMBOL FOR DATA LINK ESCAPE", "h" : "2410" },
{"g" : "\u2411", "n" : "SYMBOL FOR DEVICE CONTROL ONE", "h" : "2411" },
{"g" : "\u2412", "n" : "SYMBOL FOR DEVICE CONTROL TWO", "h" : "2412" },
{"g" : "\u2413", "n" : "SYMBOL FOR DEVICE CONTROL THREE", "h" : "2413" },
{"g" : "\u2414", "n" : "SYMBOL FOR DEVICE CONTROL FOUR", "h" : "2414" },
{"g" : "\u2415", "n" : "SYMBOL FOR NEGATIVE ACKNOWLEDGE", "h" : "2415" },
{"g" : "\u2416", "n" : "SYMBOL FOR SYNCHRONOUS IDLE", "h" : "2416" },
{"g" : "\u2417", "n" : "SYMBOL FOR END OF TRANSMISSION BLOCK", "h" : "2417" },
{"g" : "\u2418", "n" : "SYMBOL FOR CANCEL", "h" : "2418" },
{"g" : "\u2419", "n" : "SYMBOL FOR END OF MEDIUM", "h" : "2419" },
{"g" : "\u241A", "n" : "SYMBOL FOR SUBSTITUTE", "h" : "241A" },
{"g" : "\u241B", "n" : "SYMBOL FOR ESCAPE", "h" : "241B" },
{"g" : "\u241C", "n" : "SYMBOL FOR FILE SEPARATOR", "h" : "241C" },
{"g" : "\u241D", "n" : "SYMBOL FOR GROUP SEPARATOR", "h" : "241D" },
{"g" : "\u241E", "n" : "SYMBOL FOR RECORD SEPARATOR", "h" : "241E" },
{"g" : "\u241F", "n" : "SYMBOL FOR UNIT SEPARATOR", "h" : "241F" },
{"g" : "\u2420", "n" : "SYMBOL FOR SPACE", "h" : "2420" },
{"g" : "\u2421", "n" : "SYMBOL FOR DELETE", "h" : "2421" },
{"g" : "\u2422", "n" : "BLANK SYMBOL", "h" : "2422" },
{"g" : "\u2423", "n" : "OPEN BOX", "h" : "2423" },
{"g" : "\u2424", "n" : "SYMBOL FOR NEWLINE", "h" : "2424" },
{"g" : "\u2425", "n" : "SYMBOL FOR DELETE FORM TWO", "h" : "2425" },
{"g" : "\u2426", "n" : "SYMBOL FOR SUBSTITUTE FORM TWO", "h" : "2426" },

{"g" : "\u2440", "n" : "OCR HOOK", "h" : "2440" },
{"g" : "\u2441", "n" : "OCR CHAIR", "h" : "2441" },
{"g" : "\u2442", "n" : "OCR FORK", "h" : "2442" },
{"g" : "\u2443", "n" : "OCR INVERTED FORK", "h" : "2443" },
{"g" : "\u2444", "n" : "OCR BELT BUCKLE", "h" : "2444" },
{"g" : "\u2445", "n" : "OCR BOW TIE", "h" : "2445" },
{"g" : "\u2446", "n" : "OCR BRANCH BANK IDENTIFICATION", "h" : "2446" },
{"g" : "\u2447", "n" : "OCR AMOUNT OF CHECK", "h" : "2447" },
{"g" : "\u2448", "n" : "OCR DASH", "h" : "2448" },
{"g" : "\u2449", "n" : "OCR CUSTOMER ACCOUNT NUMBER", "h" : "2449" },
{"g" : "\u244A", "n" : "OCR DOUBLE BACKSLASH", "h" : "244A" },
	
{"g" : "\u2B7E", "n" : "HORIZONTAL TAB KEY", "h" : "2B7E" },
{"g" : "\u2B7F", "n" : "VERTICAL TAB KEY", "h" : "2B7F" },

{"g" : "\u2B90", "n" : "RETURN LEFT", "h" : "2B90" },
{"g" : "\u2B91", "n" : "RETURN RIGHT", "h" : "2B91" },
{"g" : "\u2B92", "n" : "NEWLINE LEFT", "h" : "2B92" },
{"g" : "\u2B93", "n" : "NEWLINE RIGHT", "h" : "2B93" },

{"g" : "\u2BB8", "n" : "UPWARDS WHITE ARROW FROM BAR WITH HORIZONTAL BAR", "h" : "2BB8" },
{"g" : "\u2BB9", "n" : "UP ARROWHEAD IN A RECTANGLE BOX", "h" : "2BB9" },

{"g" : "\u2BFF", "n" : "HELLSCHREIBER PAUSE SYMBOL", "h" : "2BFF" },

{"g" : "\uFEFF", "n" : "ZERO WIDTH NO-BREAK SPACE", "h" : "FEFF"},

{"g" : "\uFFF9", "n" : "INTERLINEAR ANNOTATION ANCHOR", "h" : "FFF9"},
{"g" : "\uFFFA", "n" : "INTERLINEAR ANNOTATION SEPARATOR", "h" : "FFFA"},
{"g" : "\uFFFB", "n" : "INTERLINEAR ANNOTATION TERMINATOR", "h" : "FFFB"},
{"g" : "\uFFFC", "n" : "OBJECT REPLACEMENT CHARACTER", "h" : "FFFC"},
{"g" : "\uFFFD", "n" : "REPLACEMENT CHARACTER", "h" : "FFFD"},

{"g" : "\u{16FE4}", "n" : "KHITAN SMALL SCRIPT FILLER", "h" : "16FE4"},

{"g" : "\u{1FB00}", "n" : "BLOCK SEXTANT-1", "h" : "1FB00"},
{"g" : "\u{1FB01}", "n" : "BLOCK SEXTANT-2", "h" : "1FB01"},
{"g" : "\u{1FB02}", "n" : "BLOCK SEXTANT-12", "h" : "1FB02"},
{"g" : "\u{1FB03}", "n" : "BLOCK SEXTANT-3", "h" : "1FB03"},
{"g" : "\u{1FB04}", "n" : "BLOCK SEXTANT-13", "h" : "1FB04"},
{"g" : "\u{1FB05}", "n" : "BLOCK SEXTANT-23", "h" : "1FB05"},
{"g" : "\u{1FB06}", "n" : "BLOCK SEXTANT-123", "h" : "1FB06"},
{"g" : "\u{1FB07}", "n" : "BLOCK SEXTANT-4", "h" : "1FB07"},
{"g" : "\u{1FB08}", "n" : "BLOCK SEXTANT-14", "h" : "1FB08"},
{"g" : "\u{1FB09}", "n" : "BLOCK SEXTANT-24", "h" : "1FB09"},
{"g" : "\u{1FB0A}", "n" : "BLOCK SEXTANT-124", "h" : "1FB0A"},
{"g" : "\u{1FB0B}", "n" : "BLOCK SEXTANT-34", "h" : "1FB0B"},
{"g" : "\u{1FB0C}", "n" : "BLOCK SEXTANT-134", "h" : "1FB0C"},
{"g" : "\u{1FB0D}", "n" : "BLOCK SEXTANT-234", "h" : "1FB0D"},
{"g" : "\u{1FB0E}", "n" : "BLOCK SEXTANT-1234", "h" : "1FB0E"},
{"g" : "\u{1FB0F}", "n" : "BLOCK SEXTANT-5", "h" : "1FB0F"},
{"g" : "\u{1FB10}", "n" : "BLOCK SEXTANT-15", "h" : "1FB10"},
{"g" : "\u{1FB11}", "n" : "BLOCK SEXTANT-25", "h" : "1FB11"},
{"g" : "\u{1FB12}", "n" : "BLOCK SEXTANT-125", "h" : "1FB12"},
{"g" : "\u{1FB13}", "n" : "BLOCK SEXTANT-35", "h" : "1FB13"},
{"g" : "\u{1FB14}", "n" : "BLOCK SEXTANT-235", "h" : "1FB14"},
{"g" : "\u{1FB15}", "n" : "BLOCK SEXTANT-1235", "h" : "1FB15"},
{"g" : "\u{1FB16}", "n" : "BLOCK SEXTANT-45", "h" : "1FB16"},
{"g" : "\u{1FB17}", "n" : "BLOCK SEXTANT-145", "h" : "1FB17"},
{"g" : "\u{1FB18}", "n" : "BLOCK SEXTANT-245", "h" : "1FB18"},
{"g" : "\u{1FB19}", "n" : "BLOCK SEXTANT-1245", "h" : "1FB19"},
{"g" : "\u{1FB1A}", "n" : "BLOCK SEXTANT-345", "h" : "1FB1A"},
{"g" : "\u{1FB1B}", "n" : "BLOCK SEXTANT-1345", "h" : "1FB1B"},
{"g" : "\u{1FB1C}", "n" : "BLOCK SEXTANT-2345", "h" : "1FB1C"},
{"g" : "\u{1FB1D}", "n" : "BLOCK SEXTANT-12345", "h" : "1FB1D"},
{"g" : "\u{1FB1E}", "n" : "BLOCK SEXTANT-6", "h" : "1FB1E"},
{"g" : "\u{1FB1F}", "n" : "BLOCK SEXTANT-16", "h" : "1FB1F"},
{"g" : "\u{1FB20}", "n" : "BLOCK SEXTANT-26", "h" : "1FB20"},
{"g" : "\u{1FB21}", "n" : "BLOCK SEXTANT-126", "h" : "1FB21"},
{"g" : "\u{1FB22}", "n" : "BLOCK SEXTANT-36", "h" : "1FB22"},
{"g" : "\u{1FB23}", "n" : "BLOCK SEXTANT-136", "h" : "1FB23"},
{"g" : "\u{1FB24}", "n" : "BLOCK SEXTANT-236", "h" : "1FB24"},
{"g" : "\u{1FB25}", "n" : "BLOCK SEXTANT-1236", "h" : "1FB25"},
{"g" : "\u{1FB26}", "n" : "BLOCK SEXTANT-46", "h" : "1FB26"},
{"g" : "\u{1FB27}", "n" : "BLOCK SEXTANT-146", "h" : "1FB27"},
{"g" : "\u{1FB28}", "n" : "BLOCK SEXTANT-1246", "h" : "1FB28"},
{"g" : "\u{1FB29}", "n" : "BLOCK SEXTANT-346", "h" : "1FB29"},
{"g" : "\u{1FB2A}", "n" : "BLOCK SEXTANT-1346", "h" : "1FB2A"},
{"g" : "\u{1FB2B}", "n" : "BLOCK SEXTANT-2346", "h" : "1FB2B"},
{"g" : "\u{1FB2C}", "n" : "BLOCK SEXTANT-12346", "h" : "1FB2C"},
{"g" : "\u{1FB2D}", "n" : "BLOCK SEXTANT-56", "h" : "1FB2D"},
{"g" : "\u{1FB2E}", "n" : "BLOCK SEXTANT-156", "h" : "1FB2E"},
{"g" : "\u{1FB2F}", "n" : "BLOCK SEXTANT-256", "h" : "1FB2F"},
{"g" : "\u{1FB30}", "n" : "BLOCK SEXTANT-1256", "h" : "1FB30"},
{"g" : "\u{1FB31}", "n" : "BLOCK SEXTANT-356", "h" : "1FB31"},
{"g" : "\u{1FB32}", "n" : "BLOCK SEXTANT-1356", "h" : "1FB32"},
{"g" : "\u{1FB33}", "n" : "BLOCK SEXTANT-2356", "h" : "1FB33"},
{"g" : "\u{1FB34}", "n" : "BLOCK SEXTANT-12356", "h" : "1FB34"},
{"g" : "\u{1FB35}", "n" : "BLOCK SEXTANT-456", "h" : "1FB35"},
{"g" : "\u{1FB36}", "n" : "BLOCK SEXTANT-1456", "h" : "1FB36"},
{"g" : "\u{1FB37}", "n" : "BLOCK SEXTANT-2456", "h" : "1FB37"},
{"g" : "\u{1FB38}", "n" : "BLOCK SEXTANT-12456", "h" : "1FB38"},
{"g" : "\u{1FB39}", "n" : "BLOCK SEXTANT-3456", "h" : "1FB39"},
{"g" : "\u{1FB3A}", "n" : "BLOCK SEXTANT-13456", "h" : "1FB3A"},
{"g" : "\u{1FB3B}", "n" : "BLOCK SEXTANT-23456", "h" : "1FB3B"},
{"g" : "\u{1FB3C}", "n" : "LOWER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER CENTRE", "h" : "1FB3C"},
{"g" : "\u{1FB3D}", "n" : "LOWER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER RIGHT", "h" : "1FB3D"},
{"g" : "\u{1FB3E}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER CENTRE", "h" : "1FB3E"},
{"g" : "\u{1FB3F}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER RIGHT", "h" : "1FB3F"},
{"g" : "\u{1FB40}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO LOWER CENTRE", "h" : "1FB40"},
{"g" : "\u{1FB41}", "n" : "LOWER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER CENTRE", "h" : "1FB41"},
{"g" : "\u{1FB42}", "n" : "LOWER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER RIGHT", "h" : "1FB42"},
{"g" : "\u{1FB43}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER CENTRE", "h" : "1FB43"},
{"g" : "\u{1FB44}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER RIGHT", "h" : "1FB44"},
{"g" : "\u{1FB45}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO UPPER CENTRE", "h" : "1FB45"},
{"g" : "\u{1FB46}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER MIDDLE RIGHT", "h" : "1FB46"},
{"g" : "\u{1FB47}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO LOWER MIDDLE RIGHT", "h" : "1FB47"},
{"g" : "\u{1FB48}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO LOWER MIDDLE RIGHT", "h" : "1FB48"},
{"g" : "\u{1FB49}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO UPPER MIDDLE RIGHT", "h" : "1FB49"},
{"g" : "\u{1FB4A}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO UPPER MIDDLE RIGHT", "h" : "1FB4A"},
{"g" : "\u{1FB4B}", "n" : "LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO UPPER RIGHT", "h" : "1FB4B"},
{"g" : "\u{1FB4C}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO UPPER MIDDLE RIGHT", "h" : "1FB4C"},
{"g" : "\u{1FB4D}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO UPPER MIDDLE RIGHT", "h" : "1FB4D"},
{"g" : "\u{1FB4E}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO LOWER MIDDLE RIGHT", "h" : "1FB4E"},
{"g" : "\u{1FB4F}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO LOWER MIDDLE RIGHT", "h" : "1FB4F"},
{"g" : "\u{1FB50}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO LOWER RIGHT", "h" : "1FB50"},
{"g" : "\u{1FB51}", "n" : "LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER MIDDLE RIGHT", "h" : "1FB51"},
{"g" : "\u{1FB52}", "n" : "UPPER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER CENTRE", "h" : "1FB52"},
{"g" : "\u{1FB53}", "n" : "UPPER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER RIGHT", "h" : "1FB53"},
{"g" : "\u{1FB54}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER CENTRE", "h" : "1FB54"},
{"g" : "\u{1FB55}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER RIGHT", "h" : "1FB55"},
{"g" : "\u{1FB56}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO LOWER CENTRE", "h" : "1FB56"},
{"g" : "\u{1FB57}", "n" : "UPPER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER CENTRE", "h" : "1FB57"},
{"g" : "\u{1FB58}", "n" : "UPPER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER RIGHT", "h" : "1FB58"},
{"g" : "\u{1FB59}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER CENTRE", "h" : "1FB59"},
{"g" : "\u{1FB5A}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER RIGHT", "h" : "1FB5A"},
{"g" : "\u{1FB5B}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO UPPER CENTRE", "h" : "1FB5B"},
{"g" : "\u{1FB5C}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER MIDDLE RIGHT", "h" : "1FB5C"},
{"g" : "\u{1FB5D}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO LOWER MIDDLE RIGHT", "h" : "1FB5D"},
{"g" : "\u{1FB5E}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO LOWER MIDDLE RIGHT", "h" : "1FB5E"},
{"g" : "\u{1FB5F}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO UPPER MIDDLE RIGHT", "h" : "1FB5F"},
{"g" : "\u{1FB60}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO UPPER MIDDLE RIGHT", "h" : "1FB60"},
{"g" : "\u{1FB61}", "n" : "UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO UPPER RIGHT", "h" : "1FB61"},
{"g" : "\u{1FB62}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO UPPER MIDDLE RIGHT", "h" : "1FB62"},
{"g" : "\u{1FB63}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO UPPER MIDDLE RIGHT", "h" : "1FB63"},
{"g" : "\u{1FB64}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO LOWER MIDDLE RIGHT", "h" : "1FB64"},
{"g" : "\u{1FB65}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO LOWER MIDDLE RIGHT", "h" : "1FB65"},
{"g" : "\u{1FB66}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO LOWER RIGHT", "h" : "1FB66"},
{"g" : "\u{1FB67}", "n" : "UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER MIDDLE RIGHT", "h" : "1FB67"},
{"g" : "\u{1FB68}", "n" : "UPPER AND RIGHT AND LOWER TRIANGULAR THREE QUARTERS BLOCK", "h" : "1FB68"},
{"g" : "\u{1FB69}", "n" : "LEFT AND LOWER AND RIGHT TRIANGULAR THREE QUARTERS BLOCK", "h" : "1FB69"},
{"g" : "\u{1FB6A}", "n" : "UPPER AND LEFT AND LOWER TRIANGULAR THREE QUARTERS BLOCK", "h" : "1FB6A"},
{"g" : "\u{1FB6B}", "n" : "LEFT AND UPPER AND RIGHT TRIANGULAR THREE QUARTERS BLOCK", "h" : "1FB6B"},
{"g" : "\u{1FB6C}", "n" : "LEFT TRIANGULAR ONE QUARTER BLOCK", "h" : "1FB6C"},
{"g" : "\u{1FB6D}", "n" : "UPPER TRIANGULAR ONE QUARTER BLOCK", "h" : "1FB6D"},
{"g" : "\u{1FB6E}", "n" : "RIGHT TRIANGULAR ONE QUARTER BLOCK", "h" : "1FB6E"},
{"g" : "\u{1FB6F}", "n" : "LOWER TRIANGULAR ONE QUARTER BLOCK", "h" : "1FB6F"},
{"g" : "\u{1FB70}", "n" : "VERTICAL ONE EIGHTH BLOCK-2", "h" : "1FB70"},
{"g" : "\u{1FB71}", "n" : "VERTICAL ONE EIGHTH BLOCK-3", "h" : "1FB71"},
{"g" : "\u{1FB72}", "n" : "VERTICAL ONE EIGHTH BLOCK-4", "h" : "1FB72"},
{"g" : "\u{1FB73}", "n" : "VERTICAL ONE EIGHTH BLOCK-5", "h" : "1FB73"},
{"g" : "\u{1FB74}", "n" : "VERTICAL ONE EIGHTH BLOCK-6", "h" : "1FB74"},
{"g" : "\u{1FB75}", "n" : "VERTICAL ONE EIGHTH BLOCK-7", "h" : "1FB75"},
{"g" : "\u{1FB76}", "n" : "HORIZONTAL ONE EIGHTH BLOCK-2", "h" : "1FB76"},
{"g" : "\u{1FB77}", "n" : "HORIZONTAL ONE EIGHTH BLOCK-3", "h" : "1FB77"},
{"g" : "\u{1FB78}", "n" : "HORIZONTAL ONE EIGHTH BLOCK-4", "h" : "1FB78"},
{"g" : "\u{1FB79}", "n" : "HORIZONTAL ONE EIGHTH BLOCK-5", "h" : "1FB79"},
{"g" : "\u{1FB7A}", "n" : "HORIZONTAL ONE EIGHTH BLOCK-6", "h" : "1FB7A"},
{"g" : "\u{1FB7B}", "n" : "HORIZONTAL ONE EIGHTH BLOCK-7", "h" : "1FB7B"},
{"g" : "\u{1FB7C}", "n" : "LEFT AND LOWER ONE EIGHTH BLOCK", "h" : "1FB7C"},
{"g" : "\u{1FB7D}", "n" : "LEFT AND UPPER ONE EIGHTH BLOCK", "h" : "1FB7D"},
{"g" : "\u{1FB7E}", "n" : "RIGHT AND UPPER ONE EIGHTH BLOCK", "h" : "1FB7E"},
{"g" : "\u{1FB7F}", "n" : "RIGHT AND LOWER ONE EIGHTH BLOCK", "h" : "1FB7F"},
{"g" : "\u{1FB80}", "n" : "UPPER AND LOWER ONE EIGHTH BLOCK", "h" : "1FB80"},
{"g" : "\u{1FB81}", "n" : "HORIZONTAL ONE EIGHTH BLOCK-1358", "h" : "1FB81"},
{"g" : "\u{1FB82}", "n" : "UPPER ONE QUARTER BLOCK", "h" : "1FB82"},
{"g" : "\u{1FB83}", "n" : "UPPER THREE EIGHTHS BLOCK", "h" : "1FB83"},
{"g" : "\u{1FB84}", "n" : "UPPER FIVE EIGHTHS BLOCK", "h" : "1FB84"},
{"g" : "\u{1FB85}", "n" : "UPPER THREE QUARTERS BLOCK", "h" : "1FB85"},
{"g" : "\u{1FB86}", "n" : "UPPER SEVEN EIGHTHS BLOCK", "h" : "1FB86"},
{"g" : "\u{1FB87}", "n" : "RIGHT ONE QUARTER BLOCK", "h" : "1FB87"},
{"g" : "\u{1FB88}", "n" : "RIGHT THREE EIGHTHS BLOCK", "h" : "1FB88"},
{"g" : "\u{1FB89}", "n" : "RIGHT FIVE EIGHTHS BLOCK", "h" : "1FB89"},
{"g" : "\u{1FB8A}", "n" : "RIGHT THREE QUARTERS BLOCK", "h" : "1FB8A"},
{"g" : "\u{1FB8B}", "n" : "RIGHT SEVEN EIGHTHS BLOCK", "h" : "1FB8B"},
{"g" : "\u{1FB8C}", "n" : "LEFT HALF MEDIUM SHADE", "h" : "1FB8C"},
{"g" : "\u{1FB8D}", "n" : "RIGHT HALF MEDIUM SHADE", "h" : "1FB8D"},
{"g" : "\u{1FB8E}", "n" : "UPPER HALF MEDIUM SHADE", "h" : "1FB8E"},
{"g" : "\u{1FB8F}", "n" : "LOWER HALF MEDIUM SHADE", "h" : "1FB8F"},
{"g" : "\u{1FB90}", "n" : "INVERSE MEDIUM SHADE", "h" : "1FB90"},
{"g" : "\u{1FB91}", "n" : "UPPER HALF BLOCK AND LOWER HALF INVERSE MEDIUM SHADE", "h" : "1FB91"},
{"g" : "\u{1FB92}", "n" : "UPPER HALF INVERSE MEDIUM SHADE AND LOWER HALF BLOCK", "h" : "1FB92"},

{"g" : "\u{1FB94}", "n" : "LEFT HALF INVERSE MEDIUM SHADE AND RIGHT HALF BLOCK", "h" : "1FB94"},
{"g" : "\u{1FB95}", "n" : "CHECKER BOARD FILL", "h" : "1FB95"},
{"g" : "\u{1FB96}", "n" : "INVERSE CHECKER BOARD FILL", "h" : "1FB96"},
{"g" : "\u{1FB97}", "n" : "HEAVY HORIZONTAL FILL", "h" : "1FB97"},
{"g" : "\u{1FB98}", "n" : "UPPER LEFT TO LOWER RIGHT FILL", "h" : "1FB98"},
{"g" : "\u{1FB99}", "n" : "UPPER RIGHT TO LOWER LEFT FILL", "h" : "1FB99"},
{"g" : "\u{1FB9A}", "n" : "UPPER AND LOWER TRIANGULAR HALF BLOCK", "h" : "1FB9A"},
{"g" : "\u{1FB9B}", "n" : "LEFT AND RIGHT TRIANGULAR HALF BLOCK", "h" : "1FB9B"},
{"g" : "\u{1FB9C}", "n" : "UPPER LEFT TRIANGULAR MEDIUM SHADE", "h" : "1FB9C"},
{"g" : "\u{1FB9D}", "n" : "UPPER RIGHT TRIANGULAR MEDIUM SHADE", "h" : "1FB9D"},
{"g" : "\u{1FB9E}", "n" : "LOWER RIGHT TRIANGULAR MEDIUM SHADE", "h" : "1FB9E"},
{"g" : "\u{1FB9F}", "n" : "LOWER LEFT TRIANGULAR MEDIUM SHADE", "h" : "1FB9F"},

{"g" : "\u{1FBA0}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT", "h" : "1FBA0"},
{"g" : "\u{1FBA1}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT", "h" : "1FBA1"},
{"g" : "\u{1FBA2}", "n" : "BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER CENTRE", "h" : "1FBA2"},
{"g" : "\u{1FBA3}", "n" : "BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO LOWER CENTRE", "h" : "1FBA3"},
{"g" : "\u{1FBA4}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE", "h" : "1FBA4"},
{"g" : "\u{1FBA5}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE", "h" : "1FBA5"},
{"g" : "\u{1FBA6}", "n" : "BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER CENTRE TO MIDDLE RIGHT", "h" : "1FBA6"},
{"g" : "\u{1FBA7}", "n" : "BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO UPPER CENTRE TO MIDDLE RIGHT", "h" : "1FBA7"},
{"g" : "\u{1FBA8}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT AND MIDDLE RIGHT TO LOWER CENTRE", "h" : "1FBA8"},
{"g" : "\u{1FBA9}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT AND MIDDLE LEFT TO LOWER CENTRE", "h" : "1FBA9"},
{"g" : "\u{1FBAA}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE TO MIDDLE LEFT", "h" : "1FBAA"},
{"g" : "\u{1FBAB}", "n" : "BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE TO MIDDLE RIGHT", "h" : "1FBAB"},
{"g" : "\u{1FBAC}", "n" : "BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE", "h" : "1FBAC"},
{"g" : "\u{1FBAD}", "n" : "BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE", "h" : "1FBAD"},
{"g" : "\u{1FBAE}", "n" : "BOX DRAWINGS LIGHT DIAGONAL DIAMOND", "h" : "1FBAE"},
{"g" : "\u{1FBAF}", "n" : "BOX DRAWINGS LIGHT HORIZONTAL WITH VERTICAL STROKE", "h" : "1FBAF"},

{"g" : "\u{1FBB0}", "n" : "ARROWHEAD-SHAPED POINTER", "h" : "1FBB0"},
{"g" : "\u{1FBB1}", "n" : "INVERSE CHECK MARK", "h" : "1FBB1"},
{"g" : "\u{1FBB2}", "n" : "LEFT HALF RUNNING MAN", "h" : "1FBB2"},
{"g" : "\u{1FBB3}", "n" : "RIGHT HALF RUNNING MAN", "h" : "1FBB3"},
{"g" : "\u{1FBB4}", "n" : "INVERSE DOWNWARDS ARROW WITH TIP LEFTWARDS", "h" : "1FBB4"},
{"g" : "\u{1FBB5}", "n" : "LEFTWARDS ARROW AND UPPER AND LOWER ONE EIGHTH BLOCK", "h" : "1FBB5"},
{"g" : "\u{1FBB6}", "n" : "RIGHTWARDS ARROW AND UPPER AND LOWER ONE EIGHTH BLOCK", "h" : "1FBB6"},
{"g" : "\u{1FBB7}", "n" : "DOWNWARDS ARROW AND RIGHT ONE EIGHTH BLOCK", "h" : "1FBB7"},
{"g" : "\u{1FBB8}", "n" : "UPWARDS ARROW AND RIGHT ONE EIGHTH BLOCK", "h" : "1FBB8"},
{"g" : "\u{1FBB9}", "n" : "LEFT HALF FOLDER", "h" : "1FBB9"},
{"g" : "\u{1FBBA}", "n" : "RIGHT HALF FOLDER", "h" : "1FBBA"},
{"g" : "\u{1FBBB}", "n" : "VOIDED GREEK CROSS", "h" : "1FBBB"},
{"g" : "\u{1FBBC}", "n" : "RIGHT OPEN SQUARED DOT", "h" : "1FBBC"},
{"g" : "\u{1FBBD}", "n" : "NEGATIVE DIAGONAL CROSS", "h" : "1FBBD"},
{"g" : "\u{1FBBE}", "n" : "NEGATIVE DIAGONAL MIDDLE RIGHT TO LOWER CENTRE", "h" : "1FBBE"},
{"g" : "\u{1FBBF}", "n" : "NEGATIVE DIAGONAL DIAMOND", "h" : "1FBBF"},

{"g" : "\u{1FBC}", "n" : "", "h" : "1FBC"}
];
	
/* 
 */
      
  for (var i = 0; i < codepoints.length; i++) {
	var myArticle = document.createElement('article');
	var glyph = codepoints[i].g;
	var name = codepoints[i].n;
	var hex = codepoints[i].h;
    	var myPara1 = document.createElement('p');
    	var myPara2 = document.createElement('p');
    	var myPara3 = document.createElement('p');
	var myPara4 = document.createElement('p');
	var myPara5 = document.createElement('p');
	var myPara6 = document.createElement('p');

    	myPara1.textContent = glyph;
    	myPara2.textContent = name;
    	myPara3.textContent = 'U+' + hex;
	myPara4.textContent = '&#x' + hex + ';';
	myPara5.textContent = '&#' + parseInt(hex, 16) + ';';
	myPara6.textContent = '\\' + 'u' + hex;

    	myArticle.appendChild(myPara1);
    	myArticle.appendChild(myPara2);
    	myArticle.appendChild(myPara3);
	myArticle.appendChild(myPara4);
	myArticle.appendChild(myPara5);
	myArticle.appendChild(myPara6);

    section.appendChild(myArticle);
  }
}
